### ISSUE TITLE
ITMS-91065: Missing signature

### ISSUE THREAD

**Issue by Devh-cv** [daltoniam/Starscream#1019]
### Question
Hello, Guys 
im facing issue submit my app to appstore:

We noticed one or more issues with a recent submission for App Store review for the following app:

MyApp
Version 1.4
Build 1
Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91065: Missing signature - Your app includes “Frameworks/Starscream.framework/Starscream”, which includes Starscream, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

Apple Developer Relations
### Environment:
- OS/Version: IOS
- Starscream Version 
- Xcode Version 15.3 (15E204a)

**Comment by vanxet** [comment]
Hi @Devh-cv 
Do you resolve it?
I have same issue, can you share way to fix it!
Thanks!

**Comment by Devh-cv** [comment]
hello friend, yes i manage to fix..
contact me on whatsapp:

+1 (719) 430‑9434

vanxet ***@***.***> escreveu (segunda, 9/09/2024 à(s) 07:40):

**Comment by vanxet** [comment]
hi bro,
I don't have whatsapp, can you share way to fix it in mail
many thanks!

Vào Th 2, 9 thg 9, 2024 vào lúc 23:15 Dude Dev ***@***.***>
đã viết:
