### ISSUE TITLE
Bug in WebSocket.swift :: processRawMessage()

### ISSUE THREAD

**Issue by bdpdx** [daltoniam/Starscream#103]
Hi,

I would issue a pull request as I've fixed this in my fork, but I'm ahead by a few commits you may not want, so...

You have a bug in `processRawMessage()` where if a payload is split across multiple packets you may not process it correctly.

The block of code immediately following the setting of the `dataLength` variable currently reads:

```swift
            if bufferLen < offset {
                fragBuffer = NSData(bytes: buffer, length: bufferLen)
                return
            }
```
It should be changed to:

```swift
            if bufferLen < offset || UInt64(bufferLen - offset) < dataLength {
                fragBuffer = NSData(bytes: buffer, length: bufferLen)
                return
            }
```

**Comment by acmacalister** [comment]
Thanks for reporting this, good catch. I will add this for both master and the swift-2.0 branch.
