### ISSUE TITLE
Race condition for isConnected property?

### ISSUE THREAD

**Issue by moodsushi** [daltoniam/Starscream#109]
The private `connected` var is set on a background thread:
```
line 305: connected = processHTTP(buffer, bufferLen: length)
```
but the public `isConnected` var should (I assume) only be accessed on the main thread. This leads to the case where `isConnected` is true (when read from the main thread), but although the block that calls the delegate method `websocketDidConnect()` (line 356) has been dispatched to the main queue, it is yet to be run.

For some reason this was only noticed on upgrading to Xcode7b6 / iOS9.

**Comment by daltoniam** [comment]
I see what you mean, that could result in some undesirable behavior in certain cases. I don't think it will be a problem for most people but I agree it should be fixed. I will investigate a fix, don't think it should be to difficult. Thanks for pointing it out.

**Comment by moodsushi** [comment]
Yeah, it's not a massive issue, it was just odd that as soon as I upgraded it kept getting triggered. No idea why!

**Comment by daltoniam** [comment]
Weird. Oh well, I think it should be fixed now :smile:
