### ISSUE TITLE
.join() renamed to .joinWithSeparator()

### ISSUE THREAD

**Issue by kenl97216** [daltoniam/Starscream#111]
With Xcode 7 beta 6, .join() has been removed (so much for deprecation...), line #177 of WebSocket.swift in createHTTPRequest (Swift 2.0 branch) goes from:

	self.addHeader(urlRequest, key: headerWSProtocolName, val: ",".joinWithSeparator(protocols))
	
	to:
	
	self.addHeader(urlRequest, key: headerWSProtocolName, val: protocols.joinWithSeparator(","))

**Comment by daltoniam** [comment]
Pull Request #108 brought support for this. If you take a look at the current Swift-2.0 branch, it should already be that way. (Who needs deprecation anyway :smile:).

https://github.com/daltoniam/Starscream/blob/Swift-2.0/WebSocket.swift#L177
