### ISSUE TITLE
Intermittent Invalid HTTP upgrade with Meteor server hosted at xxx.meteor.com

### ISSUE THREAD

**Issue by siegesmund** [daltoniam/Starscream#112]
I'm getting an Invalid HTTP Upgrade error trying to connect to a Meteor server at swiftddp.meteor.com. About a third of the time it works well, and I can send DDP messages over the socket, and it functions perfectly. The rest of the time it refuses to connect.

The problem appears to be that I'm getting a 200 response status code instead of 101 on line 377, but only a part of the time?

**Comment by daltoniam** [comment]
I don't know enough about how meteor works to say what is happen. I did just check in a few fixes that might have helped, might want to try the latest version.
