### ISSUE TITLE
socket.connect() only works when a new Websocket object is instantiated

### ISSUE THREAD

**Issue by SamDecrock** [daltoniam/Starscream#113]
Hi,

I'm building a service that tries to reconnect every 5 seconds until the websocket server is up.
However, just doing ```socket.connect()``` doesn't work (anymore, it worked using the pre-Swift-1.2-version).

I have to reinstantiate the whole WebSocket object, set the delegate and do ```socket.connect()``` again. That doesn't seem right, does it?

**Comment by daltoniam** [comment]
No that doesn't sound right at all :smile:. 

Just to make sure I am testing and understand the issue properly, the websocket server is down, and a call to `connect` is done every 5 seconds? At some point the websocket server comes up and the client should connect once on the next 5 second interval? Do you never get a `websocketDidDisconnect:` call from the delegate? 

I am not getting the same results in my test with https://github.com/daltoniam/Starscream/tree/master/examples/SimpleTest. I tried not having the websocket server running and attempted to connect multiple times and got `websocketDidDisconnect:` calls. I then started the websocket server and it connected as expected.

**Comment by SamDecrock** [comment]
Ok,

I tested it using your SimpleTest-example project and I got some weird results. Probably not related to your library, but I'm not sure.

in ```websocketDidDisconnect:``` I'm doing this to reconnect:
```swift
let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(5 * Double(NSEC_PER_SEC)))
dispatch_after(delayTime, dispatch_get_main_queue()) {
    println("reconnecting \(self.reconnectingCounter)...")
    self.textfield.text = "reconnecting \(self.reconnectingCounter)..."
    self.socket.connect()
    self.reconnectingCounter++
}
```

This works on iOS, but 'hangs' on OS X. I prints out ```reconnecting``` and shows ```reconnecting``` in the textfield, but the socket is not reconnecting. However, if I remove the textfield code, it works!

**Comment by SamDecrock** [comment]
Ok,

I retried it using ```NSTimer``` instead of ```dispatch_after```, but I'm still getting the same results. After connecting like 7 times, it just stops connecting.

I tracked it down to something that might be "your fault".

I added some debugging code to your ```connect()``` function like this:
```swift
///Connect to the websocket server on a background thread
public func connect() {
    if isCreated {
        println("AAAAAAAAAAAAAAAAAAAA")
        return
    }
    dispatch_async(queue,{ [weak self] in
        println("BBBBBBBBBBBBBBBBBBBB")
        self?.didDisconnect = false
    })
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), { [weak self] in
        println("CCCCCCCCCCCCCCCCCCCC")
        self?.isCreated = true
        self?.createHTTPRequest()
        self?.isCreated = false
    })
}
```

And this is what comes out of the console. Mind the ```BBBBBBBBBBBBBBBBBBBB``` and the ```CCCCCCCCCCCCCCCCCCCC``` being switch just before it stops reconnecting ;-)


```
> websocket: setting delegate
> websocket: connecting 1...
CCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBBBBBBBBBB
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 2...
BBBBBBBBBBBBBBBBCBCBCBCBC
CCCCCCCCCCCCCCC
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 3...
BBBBBBBBBBBBBBBBBBCBCBC
CCCCCCCCCCCCCCCCC
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 4...
BBBBBBBBBBBBBBBBCBCBCBCBC
CCCCCCCCCCCCCCC
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 5...
BBBBBBBBBBBBBBBBCBCBCBCBC
CCCCCCCCCCCCCCC
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 6...
BBBBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCB
CCCC
Optional("The operation couldn’t be completed. Connection refused")

> websocket: connecting 7...
CCCCCCCCCCCCCCCCCCCC
BBBBBBBBBBBBBBBBBBBB
```

And then it stops reconnecting

**Comment by SamDecrock** [comment]
Now it seemed to to work,

But after 72 tries, it stopped again:

```
> websocket: connecting 68...
BBBBBBBBBBBBBBBBBBBB
doDisconnect
Optional("The operation couldn’t be completed. Connection refused")
CCCCCCCCCCCCCCCCCCCC

> websocket: connecting 69...
BBBBBBBBBBBBBBBBBBBB
doDisconnect
Optional("The operation couldn’t be completed. Connection refused")
CCCCCCCCCCCCCCCCCCCC

> websocket: connecting 70...
BBBBBBBBBBBBBBBBBBBB
doDisconnect
Optional("The operation couldn’t be completed. Connection refused")
CCCCCCCCCCCCCCCCCCCC

> websocket: connecting 71...
BBBBBBBBBBBBBBBBBBBB
doDisconnect
Optional("The operation couldn’t be completed. Connection refused")
CCCCCCCCCCCCCCCCCCCC
doDisconnect

> websocket: connecting 72...
BBBBBBBBBBBBBBBBBBBB
```


I added ```println("doDisconnect")``` to your ```doDisconnect()``` function like this:

```swift
///used to preform the disconnect delegate
private func doDisconnect(error: NSError?) {
    println("doDisconnect")
    if !self.didDisconnect {
        dispatch_async(queue,{ [weak self] in
            self?.didDisconnect = true
            if let disconnect = self?.onDisconnect {
                disconnect(error)
            }
            if let s = self {
                s.delegate?.websocketDidDisconnect(s, error: error)
            }
        })
    }
}
```

It seems like a timing problem

**Comment by daltoniam** [comment]
72 tries, that is persistence :smile:. The doDisconnect I think we would be triggering is this one:

https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L294

Which makes me guess that we might be falling into some kind of issue where:

https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L281

`waitUntilAllOperationsAreFinished` is waiting forever and doDisconnect is never called at that point. Maybe put a `println` after and before the `waitUntilAllOperationsAreFinished` and see if that is what is causing the hang up? I will try to setup the same test you are running as soon as possible.

**Comment by shaneneuerburg** [comment]
This is one of those useless comments where I tell you that I'm having the exact same issue, but I don't have anything to bring to the table to help. I'm seeing interesting results with the latest version. Sometimes, the WebSocket will call onConnect, but then quickly disconnect. I'll then try to reconnect after a couple of seconds. Sometimes it works, sometimes it hangs on the connecting state without calling onDisconnect.

**Comment by SamDecrock** [comment]
Hi,

I uploaded a sample project for you to test out: https://github.com/SamDecrock/Starscream-Websocket-OSX-Test

It fails after 3 connects when the textview gets filled with lorum ipsum text ;-)

**Comment by daltoniam** [comment]
@shaneneuerburg amazing comment, made my morning :smile:. 
@SamDecrock thanks for the project, that helped a lot! I think I figured out what it was. I believe it was an issue with the `didDisconnect` bool not getting updated and thus the delegate not being called because of the way the dispatch_async queue where setup, it would only happen if the second queue executed before the first one. 

Please let me know if the latest code fixes it for you guys.

**Comment by SamDecrock** [comment]
On the test project, it now works.

Unfortunately, on my main project, it still fails sometimes. I did some debugging and it seems to wait forever on ```waitUntilAllOperationsAreFinished``` in the ```disconnectStream``` function...

**Comment by SamDecrock** [comment]
Ok, that was a different issue.

I was writing to the socket even when it was not connected.

I fixed it by adding ```if !isConnected { return }``` to the ```dequeueWrite```-function, like this:

```swift
///used to write things to the stream
private func dequeueWrite(data: NSData, code: OpCode) {
    if !isConnected { return }
    ...
```

**Comment by daltoniam** [comment]
ok that behavior makes sense. I added logic a long time ago that wait for the socket to be connected for up to 5 seconds before giving up on writing to it. I am divided on that now. It can be handy when on connect you write something before the socket is connected, but can produce weird behavior as we have seen now.

**Comment by daltoniam** [comment]
I am going to think on and test it, but I think I am leaning towards removing that wait logic as you probably shouldn't be trying to write to a socket that isn't connected yet anyway. It can lead to unexpected behavior as we are seeing now. It makes more sense for the user of the library to handle these cases.

**Comment by SamDecrock** [comment]
It seems to hang much longer than 5 seconds though. ```waitUntilAllOperationsAreFinished``` seems to wait forever as the write queue never gets emptied.

**Comment by daltoniam** [comment]
I change the code to no longer do the wait. I also am cutting `master` over to be the Swift 2.0 branch since it will be out very soon. I move the Swift-1.2 code to here: https://github.com/daltoniam/Starscream/tree/swift-1.2 and made a `0.9.7` tag (for the package managers). Thanks again for helping track down this issue.
