### ISSUE TITLE
Security class should be renamed

### ISSUE THREAD

**Issue by artman** [daltoniam/Starscream#115]
When not integrating via CocoaPods, but directly including Starscream source files in a framework (like we do with jetstream), the Security-class's name collides with the Security module. Maybe rename Security to SSLSecurity?

**Comment by daltoniam** [comment]
Ah good point, didn't even think of that. SSLSecurity seems straight forward enough to me :smile:. Thanks! I will change that shortly.

**Comment by artman** [comment]
Awesome, thanks mate!

**Comment by daltoniam** [comment]
Done. Thanks again.
