### ISSUE TITLE
Sending Video Data on LAN?

### ISSUE THREAD

**Issue by ZENUAV** [daltoniam/Starscream#116]
Could this library be used to send a video stream of live video over a LAN/wifi hub from say an iPad to other iPads or PC clients??

**Comment by acmacalister** [comment]
WebSockets, _might_ be an acceptable protocol to do this over, but that depends on what you are doing. Most application would probably use something more optimized for video streaming. I would take a look at Apple's Live Streaming tech for streaming video data if it was me.

https://developer.apple.com/streaming/
