### ISSUE TITLE
Needs delay between socket creation and connect operation

### ISSUE THREAD

**Issue by erez-rabih** [daltoniam/Starscream#120]
Hi,

I just started using Starscream and had some weird issue:

When I tried to follow your example with an object that performs:
```
var socket = WebSocket(url: NSURL(scheme: "ws", host: "localhost:8080", path: "/")!)
socket.delegate = self
socket.connect()
```
The connection never happened.
It didn't arrive the server nor did it fire the delegate method I've set.

What I had to do is to separate the socket creation and connect() method to two different functions which are called one after another:
```
func create() {
  self.socket = WebSocket(url: NSURL(scheme: "ws", host: "localhost:8080", path: "/")!)
  socket.delegate = self
}
func connect(){
  socket.connect()
}
```

This way everything worked fine, the connection succeeded and I the delegate method got fired as expected.

From what I can conclude there has to be some time interval between the socket creation and connection.

I am using XCode 7 and swift 2
I integrated Starscream vie cocoapods with the following line in the Podfile:
  pod 'Starscream', '~> 1.0.0'

Did anyone else get that weird issue? Am I misunderstanding something very basic here?

Thanks for the help in advance!

**Comment by daltoniam** [comment]
This is expected behavior. The example in the README just demonstrate the basics of the API. You need to keep a reference to the socket object or it will get deallocated. If you just do `var socket` in `viewDidLoad` or something like that it is a local variable and gets deallocated almost immediately and consequently doesn't do anything. See the SimpleTest project in the examples folder on basic setup/usage.

**Comment by erez-rabih** [comment]
@daltoniam Thanks for the explanation.
I got two more questions regarding this:
1. How could I know that the socket will get deallocated if there's no reference to it? It is written or documented somewhere?
2. Do you think it is worth mentioning in the README somewhere or at least in the specific example which actually does not work in reality?

Thanks for the help again,
I really appreciate it.

**Comment by nuclearace** [comment]
@erez-rabih It's in the Swift language. If there's no reference to an object it will be deallocated. https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html#//apple_ref/doc/uid/TP40014097-CH20-ID48

**Comment by daltoniam** [comment]
@erez-rabih. Yeah @nuclearace summed it up nicely and found the docs. I could mention that in the README, but I feel it should be implied on how Swift works. Kinda of a "how far the rabbit hole do you want to go" for an example. We also have the example projects, so I think that should clear up any remaining ambiguity.
