### ISSUE TITLE
401 response is generalized when connecting

### ISSUE THREAD

**Issue by doug-l-mitchell** [daltoniam/Starscream#121]
My websocket on the server requires authentication which returns 401 http status code when authentication fails. I've found that this failure results in 'Invalid Http Upgrade' on the client but no details about why. Can the http status code be included in the websocketDidDisconnect error?

**Comment by acmacalister** [comment]
I think that should be easy enough to do. I will try to get that in there today.

**Comment by daltoniam** [comment]
This has been added and a new release created `1.0.1` (the error code will be the status code of the HTTP response).
