### ISSUE TITLE
Compilation error in Xcode 7

### ISSUE THREAD

**Issue by sk3749614** [daltoniam/Starscream#122]
When I install version 1.0.0 using CocoaPods, I get the following errors. Any pointers on how to fix them other than changing code?

/Pods/Starscream/SSLSecurity.swift:124:22: Cannot invoke 'SecPolicyCreateSSL' with an argument list of type '(Bool, String?)'

/Pods/Starscream/WebSocket.swift:178:67: 'Array<String>' does not have a member named 'joinWithSeparator'

/Pods/Starscream/WebSocket.swift:375:77: Cannot invoke 'takeRetainedValue' with no arguments

**Comment by acmacalister** [comment]
Version 1.0.0 is using Xcode 7, Swift 2. If you need Swift 1.2, use this branch

https://github.com/daltoniam/Starscream/tree/swift-1.2

**Comment by sk3749614** [comment]
Apologies. I assumed I was running with Swift 2.0.
