### ISSUE TITLE
self is nil on iPhone

### ISSUE THREAD

**Issue by SamDecrock** [daltoniam/Starscream#130]
Hi,

I'm trying out Starscream 0.9.7 (Swift 1.2) for iOS using Cocoa Pods.

When connecting right after initialising the websocket object, the ```self?``` inside the ```connect()```-function is ```nil``` and so ```createHTTPRequest()``` doesn't get called so no websocket connecting is made.

```Swift
var socket: WebSocket!

override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view, typically from a nib.
    
    socket = WebSocket(url: NSURL(scheme: "ws", host: "10.100.11.50:3001", path: "/")!)
    socket.delegate = self
    socket.connect()
}
```

However, when connecting some time after the websocket object is created, ```self?``` is not ```nil``` and the socket connects. 

```Swift
var socket: WebSocket!

override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view, typically from a nib.
    
    socket = WebSocket(url: NSURL(scheme: "ws", host: "10.100.11.50:3001", path: "/")!)
    socket.delegate = self
}

@IBAction func buttonConnect_touchUp(sender: AnyObject) {
    socket.connect()
}
```

Also, when adding a ```println(self)``` to the ```connect()```-function, the problem is solved:

```Swift
public func connect() {
    if isCreated {
        return
    }
    dispatch_async(queue,{ [weak self] in
        self?.didDisconnect = false
        println(self)
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), { [weak self] in
            self?.isCreated = true
            self?.createHTTPRequest()
            self?.isCreated = false
        })
    })
}
```

Could this be another timing issue?

Grtz,
Sam

**Comment by daltoniam** [comment]
Yeah I think that might have been an issue. Looking at the latest code we change the connect method:
https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L127

Might want to try changing it to that and see if that resolves the issue.

**Comment by SamDecrock** [comment]
Jup, that fixes it!

Thanks

**Comment by daltoniam** [comment]
Cool. Great to hear.
