### ISSUE TITLE
Is there a timeout I can set?

### ISSUE THREAD

**Issue by SamDecrock** [daltoniam/Starscream#134]
Hi, it seems to take like forever ( a minute or so ) for the 'websocketDidDisconnect()' to occur. Is there a timeout I can set?

I'm using the latest cocoaPod ```pod 'Starscream', '~> 1.0.0'```

**Comment by daltoniam** [comment]
No, there isn't a timeout currently. NSStream doesn't provide a way to add a timeout (we might be able to add our own, just haven't looked into it). I believe the most common way to address this would be to use the Reachability APIs to check if the server is up before attempting a connection. Hopefully NSStream adds a timeout option in the future.

**Comment by SamDecrock** [comment]
Ok, I'll try the Reachability API.

Thanks!
