### ISSUE TITLE
Starscream library can be used as websocket server in my Obj-C application.?

### ISSUE THREAD

**Issue by Kushi171987** [daltoniam/Starscream#136]
I am working on a cordova iPhone (Objective-C) application, which uses websocket server. Right now I am using the CoreWebSocket library for websocket server & am loading my site into the app with url. In my site I am trying to connect to the server with websocket client with the url 'ws://localhost:<port>'. All seems to be working fine. But I moved my site to production server which is 'https', So the websocket communication is failed connect. 

  Can I use ur Starscream library to implement websocket server on native side, And communicate from the browser client as "wss://localhost:<port>".?

**Comment by acmacalister** [comment]
No. Starscream only implements the client side of the RFC spec. Maybe down the road we will look into supporting server side functionality, but it isn't anything we currently have scoped.

**Comment by acmacalister** [comment]
You might look at using PocketSocket. It implements the server spec and has TLS support.

https://github.com/zwopple/PocketSocket

**Comment by Kushi171987** [comment]
oh ok. Thanks you very much for suggest about the PocketSocket. Will check
with that.

Thanks.


Regards,
Kushal Kumar.G,
*Vensi, Inc*.
*750 W. LakeCook Rd, #490*
*Buffalo Grove, IL 60089*
Phone: +1(847) 603-4675
Fax: +1(847) 821-0843
Email: kushal@vensi.com
http://www.vensi.com/
