### ISSUE TITLE
sending lots of bytes with writeData() crashes on iOS 9.1

### ISSUE THREAD

**Issue by SamDecrock** [daltoniam/Starscream#137]
Hi,

I'm having this annoying issue were writeData() crashes my app when sending more than 5000 bytes. However, this only happens when the app is build for release. It doesn't happen when debugging.

Code to make the app crash:
```Swift
var arr = [UInt]()
for var i=0 ; i < 800000; i++ {
    arr.append(255)
}
let data = NSData(bytes: arr, length: arr.count * sizeof(UInt))
self.socket.writeData(data)
```
If you're wondering, I was using this to send an image to the server.

Update: sometimes it happens and sometimes it doesn't. It must be something of a memory issue I think.

**Comment by daltoniam** [comment]
Yeah, that sounds like a memory issue. What does the crash occur? Does it say something about a malloc error?

**Comment by SamDecrock** [comment]
I'm sorry. It was on someone else's iPhone 5 with iOS 9. On my iPhone 4S with iOS 8 that problem didn't occur.

**Comment by daltoniam** [comment]
All good. Without a crash or a consistent way to reproduce the issue I'm not sure what to do to further track down the issue. Only shots in the dark or suggestions I could make is maybe trying buffering/streaming the image to ensure against a memory issue.
