### ISSUE TITLE
Websocket host address

### ISSUE THREAD

**Issue by sadanro100** [daltoniam/Starscream#139]
Hello is there any other way to know the address of a connected Websocket instance rather than making

private var url: NSURL

public?

I need to compare objects in order to add/remove them from an array.

Thanks

**Comment by daltoniam** [comment]
hmmm, yeah currently there won't be a way to compare them. I don't think I every thought there would be a need for that, but in your use case I can see how that might be problematic. I think the best course of action would be to add a read only/computed property that returned the url so it couldn't be modified.

**Comment by daltoniam** [comment]
Added a new property, `currentURL`
