### ISSUE TITLE
Starscream with Objective-C

### ISSUE THREAD

**Issue by ricardopereira** [daltoniam/Starscream#142]
I wanted to use Starscream with Objective-C but the delegate misses the `@objc` attribute.

> The @objc attribute makes your Swift API available in Objective-C and the Objective-C runtime. In other words, you can use the @objc attribute before a Swift method, property, subscript, initializer, class, protocol, or enumeration to use it from Objective-C code. [Exposing Swift Interfaces in Objective-C](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html)

**Comment by ricardopereira** [comment]
So I made the test and it works using:

```
@objc
public protocol WebSocketDelegate: class
```

I noticed that `WebSocketPongDelegate` could be part of `WebSocketDelegate` with the `optional` attribute like `optional func websocketDidReceivePong(socket: WebSocket)` but it will break old code.

**Comment by ricardopereira** [comment]
About b29059a, optional values of non-Objective-C types aren't bridged into Objective-C.
https://github.com/daltoniam/Starscream/blob/d5f690123fd4510ce2f9ea6765c3c78ab8e2415d/WebSocket.swift#L160

**Comment by daltoniam** [comment]
Might a proposing using jetfire for the an objective-c app? 

https://github.com/acmacalister/jetfire

jetfire should have all the same features as Starscream and lets us keep Starscream as a "pure" Swift implementation.

**Comment by ricardopereira** [comment]
@daltoniam Does Jetfire have all the fixes from Starscream?

**Comment by daltoniam** [comment]
Yes it should be fairly even at this point. It gets updated in waves as I have time to port.
