### ISSUE TITLE
isConnected is true in the webSocketDidDisconnect delegate mess

### ISSUE THREAD

**Issue by mlilek-june** [daltoniam/Starscream#147]
WebSocket's `isConnected` property is still `true` when the webSocketDidDisconnect delegate message is received by the client. This is kind of weird since the name implies the disconnection already happened.

It looks like 4c4495da changed it so the internal `connected` property wasn't set to false until after the delegate message was sent, and only refers to `doDisconnect`. But `HEAD`'s implementation doesn't seem to reference that at all.

Just wondering if there's any design considerations I'm missing here or if it seems reasonable to set that property to false before calling the delegate. I'll send a PR if there are no objections.

**Comment by daltoniam** [comment]
Apologized on the delayed response, was on vacation. I have had a lot of back and forth with this, but I agree you are right, it should be set to false when `didDisconnect` is called and true when `didConnect` is called. Only thing to mention is the delegate is called from a different thread then the connected property, so a possible race condition has to be handled. PR is welcomed. Thanks!

**Comment by daltoniam** [comment]
The `1.1.0` release should resolve this. Let us know if you have any issues.
