### ISSUE TITLE
Starscream not work with Xcode 7.1/7.2

### ISSUE THREAD

**Issue by enricosecondulfo** [daltoniam/Starscream#148]
After builded framework (with Carthage) and following the installation procedure, the framework is correctly recognized but after called connect method, the tcp stream is not created. 

Thanks for your help

**Comment by daltoniam** [comment]
Can you provide any code or further details? I can confirm Starscream works fine in the latest xCode version.

**Comment by enricosecondulfo** [comment]
Hello,
after analyzing the situation better, i noticed that the websocketDidConnect method is not fired. Contrary to what occurs in debug. I enclose the project. 
I thank you in advance...
[InettyWebsocket.zip](https://github.com/daltoniam/Starscream/files/70080/InettyWebsocket.zip)

**Comment by daltoniam** [comment]
you need to change:

```swift
let websocket:WebSocket = WebSocket(url: NSURL(string: "ws://192.168.0.4:8080/starter/hello")!, protocols: ["chat", "superchat"])
```

to

```swift
let socket = WebSocket(url: NSURL(string: "ws://192.168.0.4:8080/starter/hello")!, protocols: ["chat", "superchat"])
    
override func viewDidLoad() {
     super.viewDidLoad()
     self.socket.delegate = self
     self.socket.connect()
}
```

you need to make sure your variables don't fall out of scope. See the Simple example app for more info.

**Comment by enricosecondulfo** [comment]
Thanks a lot for your help and for your work
