### ISSUE TITLE
Add support for the Swift Package Manager

### ISSUE THREAD

**Issue by nuclearace** [daltoniam/Starscream#149]
Although the manager is in infancy, I find it much easier to use than CocoaPods or Carthage.

To add support simply create a directory named `Source` and move all needed swift files to it. Then create a Package.swift at the top level.

**Comment by nuclearace** [comment]
The Package.swift might look like

```swift
import PackageDescription

let package = Package(
    name: "Starscream"
)
```

**Comment by daltoniam** [comment]
Sweet. I will do that. Thanks for the info.

**Comment by hamchapman** [comment]
I'm not sure it will work with `Source`. Make it `Sources`and that should work.

See here http://blog.krzyzanowskim.com/2015/12/04/swift-package-manager-and-linux-compatible/

**Comment by nuclearace** [comment]
I think it can be either. It works with Source for me.

**Comment by daltoniam** [comment]
Now you guys are going to make me have to decide :smile:. I think normally `source` would be the more common expression, but either way, just need to get it supported. Thanks for the links and input.

**Comment by daltoniam** [comment]
For reference (at least I think it is):
https://github.com/apple/swift-package-manager/blob/28f5027f025cd0ea9353d42c6286b4452ce68975/Sources/dep/Manifest%2BconfigureTargets.swift#L55
