### ISSUE TITLE
Remove var from parameters and pattern matching

### ISSUE THREAD

**Issue by nuclearace** [daltoniam/Starscream#150]
This is a long term issue that will be implemented in Swift 3, but it might be a good idea to get it out of the way now.

https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters-patterns.md

**Comment by daltoniam** [comment]
agreed

**Comment by daltoniam** [comment]
The `1.1.0` release should resolve this. Let us know if you have any issues.
