### ISSUE TITLE
Origin header should be optional and settable

### ISSUE THREAD

**Issue by steven851007** [daltoniam/Starscream#151]
According to the [RFC](https://tools.ietf.org/html/rfc6455):

> The request MUST include a header field with the name |Origin|
> [RFC6454] if the request is coming from a browser client.  If
> the connection is from a non-browser client, the request MAY 
> include this header field if the semantics of that client match
> the use-case described here for browser clients.  The value of
> this header field is the ASCII serialization of origin of the
> context in which the code establishing the connection is running.

**Comment by daltoniam** [comment]
This is a good point and thanks for linking to the RFC. I agree it should be settable, just want to be careful we don't break any currently working clients by removing the origin header that is sent now. I think we should test some common web socket servers with this change to ensure everything is good before we merge #151.

**Comment by steven851007** [comment]
Good point. Although testing is always important maybe we can also set the previous hardcoded value as the default value for the new optional variable to keep the backward compatibility. What you think?

**Comment by acmacalister** [comment]
I like that idea of the default value. You want to add it your PR and we can merge it?

**Comment by steven851007** [comment]
Done
