### ISSUE TITLE
Starscream hangs when trying to connect with multiple sockets

### ISSUE THREAD

**Issue by rvera** [daltoniam/Starscream#153]
I need to create multiple simultaneous sockets and starscream consistently hangs if I try to create over 64 of them.

So this code fails, the connected callback never gets triggered.
```swift
# Class var
var websockets = [WebSocket]()

# In a method
for index in 1...64 {
    if let newWebSocket = WebSocket(url: YOUR_WS_URL) as WebSocket? {
        newWebSocket.onConnect = {
            print("\(index) Connected")
        }
        newWebSocket.onDisconnect = { (error) -> Void in
            print("\(index) Discconnected")
        }
        print("\(index) Connecting")
        newWebSocket.connect()
        self.websockets.append(newWebSocket)
    }
}
```

Seems to be related to this issue http://stackoverflow.com/questions/15150308/workaround-on-the-threads-limit-in-grand-central-dispatch and the way starscream always dispatches on the background https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L144

Maybe move this into a static private operation queue?

**Comment by acmacalister** [comment]
This is similar to a suggestion opened up on Jetfire (Objective-C equivalent)

https://github.com/acmacalister/jetfire/issues/15

We have looked into a singleton thread and using a stream based APIs to fix this issue, but it requires a rather large refactor we haven't had time to finish yet. If you would like to take a stab at it, PR is welcomed.

**Comment by daltoniam** [comment]
The `1.1.0` release should resolve this. Let us know if you have any issues.
