### ISSUE TITLE
Should CloseCode be a public enum?

### ISSUE THREAD

**Issue by akozlik** [daltoniam/Starscream#155]
We are using Starscream as a CocoaPod but we're unable to check an error code's code value against WebSocket's CloseCode enum. We'd like to do something like 

    public func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        if (error.code == WebSocket.CloseCode.Normal) {
           // Do something
        }
    }

Without that enum being public we are unable to use it in our application, which would force us to hardcode the result as

        if (error.code == 1000)

Gross. If this is acceptable please let me know and I'll issue a PR. Thanks!

**Comment by acmacalister** [comment]
#138 already did this actually. Just need to bump the podspec for Cocoapods. We will do that shortly.

**Comment by akozlik** [comment]
Oh excellent, thanks and sorry I didn't see that referenced in #138 before I posted. I just checked the open tickets. We'll pull the latest pod version once it's updated. Thanks again!
