### ISSUE TITLE
tvOS target needs bit code enabled

### ISSUE THREAD

**Issue by calebd** [daltoniam/Starscream#159]
Also can the scheme be renamed to something better than `StarscreamTv`?

**Comment by daltoniam** [comment]
Ah ok. Hadn't been able to test it on anything but the simulator yet, easy enough fix. What do you propose we rename it to?

**Comment by calebd** [comment]
`carthage build --no-skip-current` will run the same build process as someone integrating the framework.

Other protects are doing <ProjectName> <PlatformName>.

So in this case we would have "Starscream iOS", "Starscream tvOS", and "Starscream Mac".

**Comment by daltoniam** [comment]
I haven't used carthage, but that is good to know, Thanks. That naming convention make sense. I like the consistency. I will update the names when I update the bit code setting.

**Comment by daltoniam** [comment]
I am not seeing a bit code setting for the tvOS project, only iOS. Might be a carthage thing. I renamed the  schemes with the latest check in.

**Comment by calebd** [comment]
I guess this isn't really an issue. I didn't have a tvOS simulator configured which naturally means the build should fail. Looks like it is working now.
