### ISSUE TITLE
Hangs on 401 response

### ISSUE THREAD

**Issue by mlilback** [daltoniam/Starscream#161]
I had a typo in an authentication header and the server was returning a 401 status. The loop at the end of initStreamsWithData() became infinite. Besides handling the 401, there really should be a timeout on that loop. Or it should check the streamStatus of outpStream, which in my case was Closed.

For some reason stream() is never called. The only thing I can think of is that there is a race condition of some kind since it works occasionally when there are pauses from breakpoints.

**Comment by daltoniam** [comment]
Thanks for the report, I think I know what it is. I am working through some other conditions right now with #158 and I think this problematic behavior might be related. I will be sure to check on this as work for the fixes on the issue progress.

**Comment by LamourBt** [comment]
Hey guys do you know where the instruction file for this ... :( @daltoniam ... I didn't use this framework yet but I have the feeling this will change my life

**Comment by acmacalister** [comment]
@LamourBt instruction file for what? For the hanging on a 401 response? Guess we are not sure what you need help with.

**Comment by LamourBt** [comment]
I was trying to add this pod into my project however in the readme it's say see the instruction file but i could not find it, therefore I was hoping that someone could help me. @acmacalister

**Comment by acmacalister** [comment]
Ok, that is completely different then the issue above. To answer your question, you just need to add Starscream as a pod to your Podfile like so:

```ruby
pod 'Starscream', '~> 1.1.1'
```

then do do a `pod install`

**Comment by LamourBt** [comment]
Ok Thanks Another question: Do you know if i could use parse as server host.. did some research could not find any.. or can you recommend one  @acmacalister

**Comment by daltoniam** [comment]
I just checked in a fix into master. Let me know if that seems to resolve it and I will do another release.

**Comment by daltoniam** [comment]
`1.1.2` released!
