### ISSUE TITLE
Starscream hangs when NSStream closes due to connectivity issues

### ISSUE THREAD

**Issue by dkharrat** [daltoniam/Starscream#164]
I was testing the case when my websocket server is down, and noticed that Starscream hangs when it receives the `NSStreamEvent.ErrorOccurred` code after initialization in `initStreamsWithData`.

Specifically, it hangs on the following line in `disconnectStream()`:

    writeQueue.waitUntilAllOperationsAreFinished()

I tracked it down, and it seems that it's due to the following operation:

```swift
    writeQueue.addOperationWithBlock {
        while !outStream.hasSpaceAvailable {
            usleep(100) //wait until the socket is ready
        }
        outStream.write(bytes, maxLength: data.length)
    }
```

Essentially, there's an infinite loop in the while loop waiting for the stream to be available, as `outStream.hasSpaceAvailable` is never true. This causes a deadlock in the disconnect waiting for `writeQueue` to be empty. I was able to resolve it as follows:

```swift
    writeQueue.addOperationWithBlock {
        while outStream.streamError == nil && !outStream.hasSpaceAvailable {
            usleep(100) //wait until the socket is ready
        }
        outStream.write(bytes, maxLength: data.length)
    }
```

Is this the right fix? If so, I can open a pull request with the fix.

**Comment by nuclearace** [comment]
I noticed this when debugging #158

**Comment by daltoniam** [comment]
This is probably related to #161. I have a fix I am testing for both #158 and #161 (and subsequently this one), this is similar to the fix I have. Hopefully can get that pushed up later tonight, just haven't had a free moment yet :disappointed:

**Comment by daltoniam** [comment]
I just checked in a fix into master. Let me know if that seems to resolve it and I will do another release.

**Comment by dkharrat** [comment]
Unfortunately, the change does not fix it. The change now actually introduces a deadlock and it ends up still hanging in the same place. The reason is, on timeout `self.disconnectStream(error)` is called within the queue operation block, but `disconnectStream()` also waits for the operations to finish before proceeding, which will never happen since the operation is also waiting on `disconnectStream()` to return.

Do you need to call `disconnectStream()` within the operation block on timeout/error? `NSStream` would be calling the `NSStreamDelegate` anyways with the error code, and the delegate implementation will call the `disconnectStream()` upon an error code. This is essentially what my fix above does.

**Comment by daltoniam** [comment]
Ah, good point totally overlooked that. You are correct the delegate will call it, I also overlooked that. I check in another fix that I believe should handle it now. Thank you for the feedback.

**Comment by dkharrat** [comment]
Thanks @daltoniam for working on it. Also, I suggest not adding the timeout, as that delays the disconnection and notification unnecessarily. From my testing, the fix I proposed in my first post has worked well. In other words, add the error check to the wait loop.

**Comment by Tramvai** [comment]
Had the same issue and lost quite a bit of time debugging. Works fine after applying your latest fixes. Cheers!

**Comment by daltoniam** [comment]
`1.1.2` released!
