### ISSUE TITLE
pongDelegate seems to require ping before usage

### ISSUE THREAD

**Issue by 11nc** [daltoniam/Starscream#166]
Hi, I recently started using Starscream, thanks for writing it!

I recently added the pongDelegate, just to capture some logging about the round trip time for our pings.

I immediately noticed some strange behavior.  As soon as I added pongDelegate I started to see the following errors and basically the websocket became unusable:

`websocketDidDisconnect(_:error:) error: Optional("masked and rsv data is not currently supported")`

`websocketDidDisconnect(_:error:) error: Optional("Invalid HTTP upgrade")`

After digging around, I discovered that the only way to prevent this from happening while I'm using pongDelegate, is to make sure the first request I send on the websocket is a ping.

If I send an initial ping, everything appears to work correctly.

Is this intended behavior or expected for some reason I'm not aware of?

Thanks!

**Comment by daltoniam** [comment]
hmm, not sure how that would happen. The pongDelegate doesn't change the processing and the latest version passes all the autobahn tests. I tested implementing the pongDelegate in the simple test project and it also worked fine. You only see this issue when implementing the pongDelegate? What kind of WebSocket server do you use?

**Comment by vjkaruna** [comment]
Hi Dalton - thanks for making Starscream awesome :)

I work with Lincoln and we use a Tornado server with Tornado's websocket handler, permessage-deflate turned off by default, tcp_nodelay enabled:

        # don't wait to send out messages on websocket.  
        # we only send complete message payloads.
        self.set_nodelay(True)

We also use Nginx 1.9.3 and Amazon's Elastic Load Balancer. The first request is to wss://domainname , which returns a 101 Switching Protocols response with the Upgrade: websocket header. Immediately after the connection is made, we don't send a ping, but a frame with ~180 bytes JSON UTF-8 encoded data.

**Comment by daltoniam** [comment]
ok that sounds fairly standard. Autobahn uses Tornado too, so we can rule that. What kind of frame is the JSON? Is that frame included in the 101 Switching protocols response?

**Comment by peterzchu** [comment]
We are using a websocket text frame to send back the JSON string.  It is not included in the 101 switching protocol response.

In tornado, we are calling write_message: message is a str and ws_handler is a tornado.websocket.WebSocketHandler subclass

    ws_handler.write_message(message, binary=False)

**Comment by daltoniam** [comment]
Interesting. Not sure what could be happening, it all sounds fairly standard. Is there anymore info that can be provided? This only happens with the pongDelegate is set and enabled? I wasn't able to reproduce it with my tests so trying to narrow down what is happening.

**Comment by daltoniam** [comment]
Following up, any other details to help troubleshoot this?

**Comment by 11nc** [comment]
Not really, sorry.  We were only using the pongDelegate for some logging so
we just stopped using it.

**Comment by daltoniam** [comment]
All good. I wasn't able to reproduce the issue in my own testing, so still not sure what was causing it :confused:. I will close the issue for now and if we run into it again we can track it down.
