### ISSUE TITLE
Compression Support

### ISSUE THREAD

**Issue by mrkd** [daltoniam/Starscream#169]
Is compression something you plan to support in the future?

https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28

**Comment by daltoniam** [comment]
We have talked about adding it, but ideally I would like to add a way to allow negotiation of any kind of extension (a plugin system). This way it won't bloat the core library and would allow any extension desired. I guess the short answer is yes, but we haven't scoped the design or functionally yet.

**Comment by nuclearace** [comment]
:+1: It's definitely worth looking into

**Comment by rvera** [comment]
+1 to this, I think compression is so widely accepted that it should be part of the core lib.

**Comment by jmbene** [comment]
Is there any news about this?

**Comment by acmacalister** [comment]
@jmbene no news. Neither @daltoniam or have had a chance to look at this. It is fair amount of work to do well. I personally haven't been really interested in compression support as I have been doing work with binary protocols, which benefit less from compression then text based ones. That being said, I totally see the usefulness in adding compression support and would be happy to discuss some elegant solution (or PRs 😄).
