### ISSUE TITLE
Unconditionally adding port to Host header

### ISSUE THREAD

**Issue by lucacorti** [daltoniam/Starscream#172]
At https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L226 the port number is unconditionally appended to the hostname in the `Host` header. Is there any good reason for doing that?

This seems redundant and breaks at least my load balancer.

**Comment by daltoniam** [comment]
According to [RFC 2616](https://tools.ietf.org/html/rfc2616#section-3.2.2) it will assume port 80 which isn't ideal in all cases. I could see the issue with a load balancer though, so we could change it to where it doesn't append the port if it is in fact port 80. In the mean time, you can just override the header if you want:

https://github.com/daltoniam/Starscream#custom-headers

**Comment by lucacorti** [comment]
Yes, that would be great. I'd also omit the port if it's 443.
