### ISSUE TITLE
error in __connection_block_invoke_2: Connection interrupted on device

### ISSUE THREAD

**Issue by AdamMak** [daltoniam/Starscream#173]
Hi

I am working on a project that will be reading from a device using sockets. This device continuously sends JSON data and I will be reading from the device about 5-10 times a second. I have got this working on the simulator and it works great, data comes through consistently and I can quickly parse the data without any issues. However when I try to run this on a real device, it just comes up with this error

error in __connection_block_invoke_2: Connection interrupted

Has anyone else had this issue? Is it to do with trying to read data this many times a second? Or is there another reason which explains this

Thanks

Edit

After doing more research, it seems I am unable to even find the port from my device, so it is not even getting to connect first. Any ideas on why I can't find the port from my device, but works fine on simulator?

**Comment by AdamMak** [comment]
Can close this issue, made silly mistake, got it working!

**Comment by damtsnkff** [comment]
Hey, @AdamMak just wondering, what kind of error was it ? There are a few question around StackOverflow, but none of them are solved. (Except one specific case). 
Thanks in advance !

**Comment by mohamedlotfyemara** [comment]
please tell me what's this mistake ?
