### ISSUE TITLE
Crash when the server frame size is too large

### ISSUE THREAD

**Issue by ayking** [daltoniam/Starscream#182]
We encounter a problem that when the server set the frame size to 1MB and send a single large message (20MB) to the mobile client then it will crash due to use up all the memory (Instruments show it consumed 2.8GB). but when after increase the BUFFER_MAX (from 4096 to 16384) in WebSocket the memory issues seems solved. Can you help verify this problem?

**Comment by daltoniam** [comment]
Ok. Thanks for the information. Is there a test project you could provide that I can reproduce this with?

**Comment by ayking** [comment]
Please try to connect this testing server with latest version Starscream.

https://github.com/ayking/Starscream-memory-issue-test-server

**Comment by daltoniam** [comment]
Thank you much. I will try and debug this ASAP.

**Comment by daltoniam** [comment]
Finally got a moment to look at this. I just checked in a fix to the master branch that I think may help with big payloads like this. Please let me know if the latest in master fixes the issue. Thanks!

**Comment by acmacalister** [comment]
Closing for now. If the issue is still occurring with the fixes in master we can reopen this.
