### ISSUE TITLE
Wifi connectivity issues

### ISSUE THREAD

**Issue by kalvish21** [daltoniam/Starscream#183]
I'm connecting a Mac OS X application to another device (android). Periodically the Android device is offline (out of range, wifi off, etc.) and when it is the Starscream socket takes a long time to notice this. Is there a way to speed this up? I even call the writePing method and I get no failure for a very long time.

What is the correct way to know when the device is unreachable? The isConnected method always says connected when it is not.

**Comment by daltoniam** [comment]
I'm not totally certain what exactly is happening as there are a lot of variables in a network based setup like this, but I would think this is normal. If the Android device is acting as a WebSocket server and has a long default ping time, it might take a while for Starscream to "notice" a disconnected state. The isConnected would still show connected as the socket hasn't be disconnected. It is just waiting for some kind of event to come in. I would recommend using Apple's Reachability APIs to detect when the Android device is no longer available. See this for more details on the Reachability APIs.

https://developer.apple.com/library/ios/samplecode/Reachability/Introduction/Intro.html#//apple_ref/doc/uid/DTS40007324-Intro-DontLinkElementID_2
