### ISSUE TITLE
Greater than UInt16 message length

### ISSUE THREAD

**Issue by AndrewGene** [daltoniam/Starscream#184]
If I encode some JSON to send through the socket that is 65537 or greater (UInt16 + 2 bytes) in size, then the socket closes.  I get "connection reset by peer".  This only happens when working off of a device.  The simulator seems to be fine.  My device is an iPhone 6S+.

**Comment by PerishableDave** [comment]
+1

**Comment by daltoniam** [comment]
Interesting. I haven't see that behavior in my fuzzing server tests. It might be related to the same issue as  #182. Might want to try the BUFFER_MAX fix in that issue see if they are the caused by the same problem. Let me know if that fixes it and I will merge the two issues. I hope to do some debugging on #182 soon.

**Comment by AndrewGene** [comment]
I actually saw that issue and made that change.  It did not rectify my situation.  I'm actually compressing an image from the phone, base64 encoding it, and sending it down the socket as a string.  After discovery of this issue though, I implemented a while loop that keeps compressing the image until it gets below the 65537 bytes that crash the socket.  Still, I believe this should be left open since the problem was simply worked around instead of me finding a fix.

**Comment by daltoniam** [comment]
Ok, thanks for the info. Yeah sounds like a different issue. Seems strange it would crash on sending a large payload, it already chucks the content on write. I'll try reproducing it when time permits.

**Comment by daltoniam** [comment]
Finally got a moment to look at this. I just checked in a fix to the master branch that I think may help with big payloads like this. Please let me know if the latest in master fixes the issue. Thanks!

**Comment by acmacalister** [comment]
Closing for now. If the issue is still occurring with the fixes in master we can reopen this.
