### ISSUE TITLE
There is no connectionTimeOut interval

### ISSUE THREAD

**Issue by yakushevichsv** [daltoniam/Starscream#185]
The library doesn't have possibility to define connectionTimeOut.

Socket Rocket can utilise NSURLRequest , which has time out interval. 
Please add an opportunity to set connection time out interval.

**Comment by daltoniam** [comment]
Yeah, this is the same as #134. NSStream doesn't support adding a timeout, but we could probably add something custom. Normally using the reachability APIs and the standard disconnect behavior of NSStream works around the need for a timeout. I would try the reachability APIs and see if that works and if that doesn't then we can investigate adding a timeout option.

**Comment by yakushevichsv** [comment]
Thx for the answer, I would rather add some connection time out timer inside the library. Reachability that is the choice, but having dependency on some other library inside original one that's not a best choice :)

**Comment by pvllnspk** [comment]
idle timeout also would be useful

**Comment by chenfisher** [comment]
why hard code timeout to 5 seconds? why not having a parameter to the connect function or something that would allow to set the timeout externally?

https://github.com/daltoniam/Starscream/commit/b159d03640bf3b8336ff1b5b0d03b8bdf013a7c4#diff-b9ab27dc605d36ce558013387d2ba2d5R115

**Comment by daltoniam** [comment]
The timeout is now a property can be changed as needed (in master right now):
https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L134

**Comment by yabee5566** [comment]
The link is 404 not found now.
https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L134
