### ISSUE TITLE
Starscream's socket.isConnected is always returning false

### ISSUE THREAD

**Issue by serLeon** [daltoniam/Starscream#186]
I'm developing an iOS application using Swift that connects to an Android device via sockets. I've implemented Starscream and was able to connect to the other device. My issue is that when I print something on the websocketDidConnect delegate method, it does not print. Also when I print socket.isConnected, it prints false. Kindly help me. Also, thanks for creating this library.

`import Starscream
    class SettingsViewController: UIViewController, UITextFieldDelegate, WebSocketDelegate{

    override func viewDidLoad() {
            super.viewDidLoad()

        let socket = WebSocket(url: NSURL(string: "ws://\(ipAddressTextField.text!):4000/")!)
        socket.connect()

        print("socket.isConnected \(socket.isConnected)") //this one is false

        socket.onConnect = {
            print("Connected...") // does not print
        }

        socket.onDisconnect = { (error: NSError?) in
            print("websocket is disconnected: \(error?.localizedDescription)") // this one prints when I turn the wifi off
        }

        socket.onData = { (data: NSData) in
            print("got some data: \(data.length)")

        }

    }

func websocketDidConnect(ws: WebSocket) {
    print("websocket is connected")
}

func websocketDidDisconnect(ws: WebSocket, error: NSError?) {
    if let e = error {
        print("websocket is disconnected: \(e.localizedDescription)")
    } else {
        print("websocket disconnected")
    }
}

func websocketDidReceiveMessage(ws: WebSocket, text: String) {
    print("Received text: \(text)")
}

func websocketDidReceiveData(ws: WebSocket, data: NSData) {
    print("Received data: \(data.length)")
}

}`

**Comment by nuclearace** [comment]
That socket is always going to be released at the end of viewDidLoad it needs to be a property

**Comment by nuclearace** [comment]
I also never see where you're setting the websocket delegate.

**Comment by daltoniam** [comment]
@nuclearace thanks for responding to this. @nuclearace is correct, you need to make the socket variable a property so it won't get released. See this example application for more information:

https://github.com/daltoniam/Starscream/blob/master/examples/SimpleTest/SimpleTest/ViewController.swift

**Comment by sreejithsn** [comment]
same issue , i set socket as a property but always i am getting socket.isConnected is always returning false
