### ISSUE TITLE
websocketDidDisconnect is fired when connect() failed

### ISSUE THREAD

**Issue by bsuvorov** [daltoniam/Starscream#187]
It'd be nice to differentiate between websocketDidDisconnect and webSocketDidFailToConnect (doesn't exist yet).

**Comment by pmellati** [comment]
Actually, for me, `onDisconnect` (I'm using closures rather than delegates) is never called if `connect()` fails (It _is_ called though if the disconnect happens sometime after `connect()` succeeds).

So, as of now, I have no way of knowing my connect has failed.

**Comment by pmellati** [comment]
Here is a test to prove my point:

```
import XCTest
import Starscream

class StarscreamTest: XCTestCase {
    func testOnDisconnect() {
        let expectation = expectationWithDescription("whatevs")
        
        let socket = WebSocket(url: NSURL(string: "http://totallynotawebsocket.com")!)
        
        socket.onDisconnect = {_ in
            print("socket.onDisconnect")
            expectation.fulfill()
        }
        
        socket.onConnect = {
            print("socket.onConnect")
            expectation.fulfill()
        }
        
        socket.connect()
        waitForExpectationsWithTimeout(10) {error in
            XCTAssertNil(error, "Network timeout")
        }
    }
}
```

**Comment by daltoniam** [comment]
@bsuvorov I can see the value in having the 2 methods, but it adds one more function that has to be implemented in the delegate. Couldn't you check if if the socket had already connected from the didConnect method and then once didDisconnect is called, know the difference?

@pmellati I am not seeing this issue. I implemented your test case in an a test app and it works properly (calls the disconnect method almost instantly).
