### ISSUE TITLE
inputStream crash

### ISSUE THREAD

**Issue by nirlachman-liveperson** [daltoniam/Starscream#188]
Hey,
I'm experiencing a crash in the library in inputStreamCallbackFunc.
Please find the attached screenshot of the stack trance and additional crash log file.
Thanks!
![screen shot 2016-05-10 at 4 56 54 pm](https://cloud.githubusercontent.com/assets/17472006/15148915/407055ee-16d0-11e6-95c9-071df6b59e7e.png)
[crash117.txt](https://github.com/daltoniam/Starscream/files/257327/crash117.txt)

**Comment by acmacalister** [comment]
Like the other backtraces, we appreciate the report, but without any additional context it is impossible debug. There are a number of things that could cause the stream to crash. If you have a test case, example project, etc that would be helpful.
