### ISSUE TITLE
Calling `connect()` without network connectivity makes the socket indefinitely unusable.

### ISSUE THREAD

**Issue by pmellati** [daltoniam/Starscream#191]
If you call `connect` on a socket when there is no internet/network connectivity, it will forever put the socket in an incorrect state, such that even after network connectivity is re-established, further calls to `connect` will never do anything. Moreover, the original call to `connect` (that was made when there was no network) does not eventually succeed either.

**Comment by daltoniam** [comment]
I can't reproduce this behavior with the latest code, it is able to reconnect after a failed attempt fine. Perhaps you are using an old version of Starscream?
