### ISSUE TITLE
Using self-signed SSL certs

### ISSUE THREAD

**Issue by astoeckley** [daltoniam/Starscream#193]
Does the flag for self-signed certificate use in this library merely instruct the library to use an existing cert that is installed, or will the library handle the self-signing process itself (i.e. generating a cert on startup or similar)?

If the former, any advice on how to actually handle the self-signed setup?

**Comment by daltoniam** [comment]
The self-signed property simply tells the library to not do the strict SSL validation it normally does. The property should probably have a better name, but we will save that for a breaking version change like Swift 3. I would use SSL pinning to do a proper self signed cert.

https://github.com/daltoniam/Starscream#ssl-pinning

That uses the SSL cert provided to validate the connection.
