### ISSUE TITLE
absence of WebSocketPingDelegate ?

### ISSUE THREAD

**Issue by Duraiamuthan** [daltoniam/Starscream#194]
Consider having something like

```
 func websocketDidReceivePing(socket: WebSocket){

    }
```

so that client can decide whether to send back the pong or not ?

**Comment by acmacalister** [comment]
Why would the client need to know if it received a ping? If you look at the RFC section on ping: 

https://tools.ietf.org/html/rfc6455#section-5.5.2

> Upon receipt of a Ping frame, an endpoint MUST send a Pong frame in response, unless it already received a Close frame.

The client is should always send back a pong when it receives a ping, so that delegate wouldn't be terribly useful. What are you trying to get the WebSocket connection to do?

**Comment by Duraiamuthan** [comment]
When the app goes to background , websocket connection gets closed i.e client does not send pong for the ping it received from server.. basically my thought was to keep the websocket connection alive by responding to the ping it received from server eventhough if app is in background.

**Comment by acmacalister** [comment]
Sounds like you would need to set the `voipEnabled` property to true. As noted in the README:

```swift
//set this if you are planning on using the socket in a VOIP background setting (using the background VOIP service).
socket.voipEnabled = true
```

That should keep the socket alive when you go in the background. Starscream automatically handles responding to ping messages with pong. This is how most WebSocket clients work, as it is needed to keep the connection alive. I don't think adding a delegate for receiving ping would make sense.

**Comment by sadeghrz** [comment]
some times connection is not really stable and it broke silently without calling onDisconnect.
my solution is i save last ping that send from server to my client and if client didn't receive ping for a while i call reconnect method.
so how can i implement didPingRecieve in my client?

**Comment by thbaja** [comment]
This should be closed.
