### ISSUE TITLE
Shouldn't the test project just work!?

### ISSUE THREAD

**Issue by mowali** [daltoniam/Starscream#195]
I think the project runs short on detail steps on how can I get it to work right away!?
I opened the SimpleTest project. I see that it already has the Starscream project in it and showing up in its link library, so that is ready.
I ran the compiler of Xcode 7 and the simulator show up but an error generated: 
websocket is disconnected: The operation couldn’t be completed. Connection refused

and that's it! I'm still experiencing with the project, shouldn't just work? Please explain what should I do.

I'm running ios9.

**Comment by acmacalister** [comment]
The README of the test project examples how to run the test WebSocket server.

https://github.com/daltoniam/Starscream/blob/master/examples/SimpleTest/README.md

**Comment by mowali** [comment]
thanks fro the swifty response! While I try to figure out how to get the write permission to install em-websocket, would that install add something to the project, so when deploying to Apple, the iOS Apps will just have it!?

**Comment by acmacalister** [comment]
I'm confusing on what you mean? The install of what? The `em-websocket`? That is just a WebSocket server to test Starscream the WebSocket client. When you deploy to Apple Starscream is a framework that will be linked into your project.

**Comment by mowali** [comment]
you're talking to an iOS beginner :) but that answered it, thank you!
I'll close the issue, since it was just a pilot issue

**Comment by acmacalister** [comment]
Sounds good. Glad it answered the question. Good luck!
