### ISSUE TITLE
Secure connection with auth params

### ISSUE THREAD

**Issue by yarmolyuknikita** [daltoniam/Starscream#196]
Please answer how to authenticate user if server requires user and password? Tried to add params to headers but does not work, I'm connecting to server but getting 401 error (not authenticated)

**Comment by acmacalister** [comment]
It depends on what type of auth you are trying to do. I would assume from you saying `you added params to the headers`, you are trying to use basic auth?

**Comment by yarmolyuknikita** [comment]
yes, like
        socket.headers["user"] = "test"
        socket.headers["password"] = "test"

**Comment by acmacalister** [comment]
That isn't basic auth... I wouldn't think your server would just take two params of the `user` and `password` as header. If you are using Basic Auth it would need to be more like:

`socket.headers["Authorization"] = "Basic QWxhZGRpbjpPcGVuU2VzYW1l"`

with the string being a Base64 encoding of the `user` and `password`

https://en.wikipedia.org/wiki/Basic_access_authentication

If you are trying to just add the params like a regular HTTP request you would have to add those to the actual connection URL, but that would be rather no standard, as the web server is going to upgrade the connection and could just end up ignoring those params altogether.

**Comment by yarmolyuknikita** [comment]
I didn't know that, and it works. Thank you very much!

**Comment by acmacalister** [comment]
your welcome. Glad it works!
