### ISSUE TITLE
Where did those messages come form!?

### ISSUE THREAD

**Issue by mowali** [daltoniam/Starscream#197]
Where did those messages come from when i run the simpleTest!? They are getting printed out in: websocketDidReceiveMessage
Seem to be coming from: 
let data = response.buffer! //local copy so it is perverse for writing

Can you elaborate more about them please?

Sample of prints:
Received text: Use the wireless AI hard drive, then you can override the virtual application!
Received text: We need to transmit the redundant AI card!
Received text: We need to hack the primary SMTP monitor!

**Comment by acmacalister** [comment]
Those messages are generated from the Ruby WebSocket server (`ws-server.rb`) using the gem `faker`

https://github.com/stympy/faker

**Comment by mowali** [comment]
Another bam swifty helpful response! Thanks
