### ISSUE TITLE
Can't call an external pc server from the web socket

### ISSUE THREAD

**Issue by mowali** [daltoniam/Starscream#198]
I have implemented the Starscream in my iMac along with its SimpleTest client. I'm trying now to connect it to a remote pc server. I created a webSocket using c# there and tried to make the SimpleTest client and server sending/listening through that port. 
I know that my pc server resolves correctly. From my other swift project, I connect to the DB that is housed in that server all the time. 
Is there something else beside just plugging the url I need to do to connect to that remote pc server from the Starscream client!?
Thanks!

**Comment by acmacalister** [comment]
Assuming you followed the example in the README or test project, you entered the connect WebSocket URL, setup the delegate and called the `connect()` method that should be all there is to it. If that isn't working I would start doing some basic networking troubleshooting to see what is going on between the client/server connection.
