### ISSUE TITLE
Missing let keyword in README.md

### ISSUE THREAD

**Issue by dirk68-fu** [daltoniam/Starscream#200]
The documentation in README.md, which is also displayed on the GitHub page, is missing a let keyword in two examples:

`let socket = WebSocket(url: NSURL(string: "ws://localhost:8080/")!)`

**Comment by daltoniam** [comment]
Thanks for the comment, but this is actually by design (it use to have the let keyword). I had to many people copying the example out of the README and then opening issues that the socket didn't work because they hadn't retained the local variable.

**Comment by dirk68-fu** [comment]
The problem is: Without 'let' if you copy it into your source, you get the following compiler error which is more confusing than helpful as to the cause of the error:

>Cannot assign to immutable expression of type '(Int32, Int32, Int32) -> Int32'
