### ISSUE TITLE
Not Connecting to local server and no delegate methods called.

### ISSUE THREAD

**Issue by Dwijen-purohit** [daltoniam/Starscream#203]
Hi,

I have been trying to connect to a local server without success. My Code is as follows - 

    class SocketManager: NSObject, WebSocketDelegate {
        var socket: WebSocket!
    
    override init() {
        super.init()
        
        self.socket = WebSocket(url: NSURL(string: "ws://localhost:9292/")!)
        self.socket.delegate = self
        print("TRYING TO CONNECT")
        self.socket.connect()
        print("DONE TRYING")
    }
    
    func websocketDidConnect(ws: WebSocket) {
        print("websocket is connected")
    }
    
    func websocketDidDisconnect(ws: WebSocket, error: NSError?) {
        print("websocket is disconnected: \(error?.localizedDescription)")
    }
    
    func websocketDidReceiveMessage(ws: WebSocket, text: String) {
        print("Received text: \(text)")
    }
    
    func websocketDidReceiveData(ws: WebSocket, data: NSData) {
        print("Received data: \(data.length)")
    }
    
    func websocketDidReceivePong(socket: WebSocket) {
        print("Got pong!")
    }

Both the Print statements "TRYING TO CONNECT" and "DONE TRYING" are present in the log, but none of the delegate methods seem to be called. 

I am not sure what could be wrong here.

Any help is appreciated. 
Thanks

**Comment by acmacalister** [comment]
Your code seems correct. Is the instance of your `SocketManager` a property on whatever class that is implementing it, so it doesn't fall out of scope? That would be my first guess from what you pasted above.

**Comment by Dwijen-purohit** [comment]
Yeah that was the issue, although why does the scope of the object of class `SocketManager` matter?
I understand why it would be a problem for the `WebSocket` class.
