### ISSUE TITLE
Unfortunately: Does not work with Swift 3 even after converting ;-(

### ISSUE THREAD

**Issue by dirk68-fu** [daltoniam/Starscream#206]
When converting to Swift 3 Syntax using xCodes built-in converter this does not compile any more.

Unfortunately I was not able to correct the problems by myself.

**Comment by ShinCurry** [comment]
I'm trying to convert syntax to swift 3.0, it can run but dosen't work , always return
``` 
{
  "id" : null,
  "error" : {
    "message" : "Parse error.",
    "code" : -32700
  },
  "jsonrpc" : "2.0"
}
```
https://github.com/ShinCurry/Starscream/tree/swift3

Can someone help me ？

**Comment by daltoniam** [comment]
Swift 3 branch here:
https://github.com/daltoniam/Starscream/tree/swift3

**Comment by dirk68-fu** [comment]
Great works, thanks!
