### ISSUE TITLE
Why I didn't get any message?

### ISSUE THREAD

**Issue by VictorWang** [daltoniam/Starscream#208]
Hello

Could you give me some suggestion, thanks.
My code:

class ViewController: UIViewController, WebSocketDelegate {

    @IBOutlet weak var textView: UITextView!
    
override func viewDidLoad() {
        super.viewDidLoad()
        // Setup WebSocket

        let uuid = UIDevice.currentDevice().identifierForVendor!.UUIDString;
        let socketHost = "wss://xwww.italki.com:4433/api/message/ws-poll/007/\(uuid)/websocket"
        let socket = WebSocket(url: NSURL(string: socketHost)!)        
       socket.headers["type"] = "auth"
       socket.headers["token"] = "TVRJek1qRTF8MTQ2NjUwODY1Nnw4NTVjMjI5OGQ4MjY4OGY4ZWMyMTQ1MjFmNjkxMTAwMzI1YTZjNjdj"
        socket.delegate = self
        socket.connect()

        if (socket.isConnected == true) {
            print("Connection is successful");
        } else {
            print("Connection is failure")
        }  
    }

func websocketDidConnect(socket: WebSocket) {
        print("web socket is connected")
    }
    
    func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        if let e = error {
            print("Web socket is disconnect: \(error!.localizedDescription)")
        }
//        print("Web socket is disconnect: \(error!.localizedDescription)")
    }
    
    func websocketDidReceiveData(socket: WebSocket, data: NSData) {
        
        print("got some data: \(data.length)")
    }
    
    func websocketDidReceiveMessage(socket: WebSocket, text: String) {
        print("got some text: \(text)")
        let json :NSDictionary
        do {
            try json = NSJSONSerialization.JSONObjectWithData(text.dataUsingEncoding(NSUTF8StringEncoding)!, options: NSJSONReadingOptions.MutableContainers) as! NSDictionary
            if (json["content"] != nil) {
                textView.text = (json["Content"] as! String) + "\n\n" + textView.text
            }
            
        }
        catch {
            print("Could not parse json message")
        }
        
        print("Receive text: \(text)")
        
    }
    
}

My questions is:

1, Why I always get  print("Connection is failure")
2, Could you give me a demo about auth of starscream

Thanks

**Comment by acmacalister** [comment]
1. This is a common design problem. You have to retain the socket as a property in your class if you don't want it to follow out of scope. See the SimpleTest example.

2. I'm not sure what you mean by "demo about auth of starscream". Are you talking about doing basic auth with HTTP headers?

**Comment by VictorWang** [comment]
Some feedback:
This is a common design problem. You have to retain the socket as a property in your class if you don't want it to follow out of scope. See the SimpleTest example.
--- Yes, I did, it works. thanks

I'm not sure what you mean by "demo about auth of starscream". Are you talking about doing basic auth with HTTP headers?
--- After connection is successful, I need send auth message to server, it means server know Who I am

func websocketDidReceiveMessage(socket: WebSocket, text: String) {
        print("Receive text: \(text)")
        
        if (socket.isConnected) {
           
            let json : JSON = ["token":"TVRJek1qRTF8MTQ2NzY4NTA4OHw2NmEwMDU0NTdiZDFlOTczZTU3ZjUwYzRiMTIxNzEzYWNmMzliZWJi",
                               "type": "auth"]
            socket.writeString(json.rawString()!)
            print(json)
            
        }       
    }

However I didn't get any message from server

**Comment by VictorWang** [comment]
By the way , I am using SwiftyJSON.

**Comment by VictorWang** [comment]
I resolved this issue. I used this string with special format, it looks like:
let sendString = ["{\"type\":\"auth\",\"token\":\"TVRJek1qRTF8MTQ2NzY4NTA4OHw2NmEwMDU0NTdiZDFlOTczZTU3ZjUwYzRiMTIxNzEzYWNmMzliZWJi\"}"]
        
        if (socket.isConnected && text == "o") {
            
            socket.writeString(JSON(sendString).rawString()!)
}

Now I have connected with websocket server (sockJS) and gotten this response data from websocket

Thanks
