### ISSUE TITLE
Library not found error

### ISSUE THREAD

**Issue by qadirsuh** [daltoniam/Starscream#21]
Hello,

The library is working fine in simulator but in iPad it gives an error.

"dyld: Library not loaded: @rpath/Starscream.framework/Starscream
  Referenced from: /private/var/mobile/Containers/Bundle/Application/425E8195-885B-4935-8E5B-016BD0B9BDEA/Home Automation Sys Swift.app/Home Automation Sys Swift
  Reason: image not found"

We have already tried the solutions in the following URL.
http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib

Please help?

**Comment by JoeFerrucci** [comment]
1. created new project in Xcode 9, using a new "command-line-tool" project. 
2. ran `pod init`.
3. added `pod 'Starscream'`
4. ran `pod install`.
5. reopened Xcode using `.xcworkspace` instead.
6. followed instructions in this issue ticket. also followed the instructions specified in the readme. 

still getting error `dyld: Library not loaded: @rpath/Starscream.framework/Versions/A/Starscream` and `Reason: image not found`
