### ISSUE TITLE
How to parse the complex string? thanks in advance

### ISSUE THREAD

**Issue by VictorWang** [daltoniam/Starscream#215]
Hello

I have connected to websocket and gotten some return string. However I found this string is not JSON format, could you tell me how to parse it? thanks a lot!

["[{\"chrome_content\":\"Jae H. Kim1233 sent you a new session 

message.\",\"chrome_icon\":\"http://14e9c4e69ca35cfb6c4c-

aaf3b05f5033b13883b8f6e21438352c.r88.cf1.rackcdn.com/T010671456_Avatar_3.jpg\",\"chrome_link

\":\"https://xwww.italki.com/lesson/session/2734345666\",\"type\":\"1998\",\"v\":\"10\"}]"]

**Comment by daltoniam** [comment]
You are going to need to use a JSON parser. Starscream doesn't do anything with JSON directly, it only returns strings or binary as defined by the RFC. There are a plethora of open source Swift JSON parsers as well as the builtin NSJSONSerialization class. I would pick your favorite and parse away!
