### ISSUE TITLE
Any API for reconnect handling automatically?

### ISSUE THREAD

**Issue by haducloc** [daltoniam/Starscream#220]
Thank you for sharing an awesome Websocket lib!
Question: Does the lib support any reconnect handling? Thanks!

**Comment by daltoniam** [comment]
Welcome 😄. It does not do any auto reconnecting, but in the didDisconnect closure or delegate you can call `connect` again which will attempt a reconnection. This allows maximum flexibility to pick when is an appropriate time to reconnect.

**Comment by haducloc** [comment]
So what I need to do is call connect again in didDisconnect method! This means I can reuse WebSocket instance. Is that right? Or I have to create another WebSocket instance in didDisconnect  method and then connect?

Thank you!

**Comment by daltoniam** [comment]
correct, the same instance can be used.

```swift
func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
//other logic to see if you want to reconnect
socket.connect()
}
```
