### ISSUE TITLE
Wrong status code on HTTP invalid upgrade

### ISSUE THREAD

**Issue by chenfisher** [daltoniam/Starscream#223]
Version 1.1.3

When connecting to a server that returns http status code 401 (thus causing invalid http upgrade), the status code returned in the 'error' on didDisconnect is 200

Old version (1.0.2) works; status code returned is 401

Any idea?

**Comment by chenfisher** [comment]
@daltoniam ?

**Comment by daltoniam** [comment]
My only guess is that the disconnect method getting called isn't trigger by the status code a more generic error (maybe it changed)?

https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L514

It appears we still have the code to check and return the status code if it isn't a 101, so might want to check if it is getting trigger by a different `doDisconnect` call?

**Comment by vytk** [comment]
Seeing the same issue:

```
2016/07/30 17:29:26:703  websocketDidDisconnect: Optional(Error Domain=WebSocket Code=200 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})
2016/07/30 17:29:26:703  Disconnected from WebSocketMessageChannel: <WebSocketMessageChannel: 0x13ce9b080>; error: Optional(Error Domain=WebSocket Code=200 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})
2016/07/30 17:29:29:992  Connecting WebSocketMessageChannel
2016/07/30 17:29:30:661  websocketDidDisconnect: Optional(Error Domain=WebSocket Code=200 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})
2016/07/30 17:29:30:662  Disconnected from WebSocketMessageChannel: <WebSocketMessageChannel: 0x13ce9b080>;
```

**Comment by daltoniam** [comment]
A new 1.1.4 for swift 2.3 and 2.0.0 for swift 3 was released. I'm going to close this issue out and if those new version don't seem to resolve the issue, then feel free to open a new one.
