### ISSUE TITLE
Inconsistent Crash (pthread)

### ISSUE THREAD

**Issue by GuyKahlon** [daltoniam/Starscream#224]
I have inconsistent crashes.
Please see my Crashlytices screenshot.

Any idea how to solve this crash?

![image](https://cloud.githubusercontent.com/assets/3619880/17140438/2f67f42e-5351-11e6-84dd-041cbd8a1aeb.png)

# Organization: x
# Platform: ios
# Application: x
# Version: 1.0.901 (10)
# Bundle Identifier: com.x.x
# Issue: 130
# Session: 48511788674247bb867d21786405c248
# Date: 2016-07-19T10:36:11Z
# OS Version: 9.3.2 (13F69)
# Device: iPhone 6
# RAM Free: 10.7%
# Disk Free: 11.2%

#9. Crashed: com.vluxe.starscream.websocket
0  libobjc.A.dylib                0x180d05b90 objc_msgSend + 16
1  CoreFoundation                 0x18163625c <redacted> + 56
2  CoreFoundation                 0x1815ddbc0 <redacted> + 192
3  CoreFoundation                 0x1816520a4 <redacted> + 24
4  libdispatch.dylib              0x1810d94bc <redacted> + 24
5  libdispatch.dylib              0x1810d947c <redacted> + 16
6  libdispatch.dylib              0x1810e54c0 <redacted> + 864
7  libdispatch.dylib              0x1810dcf80 <redacted> + 464
8  libdispatch.dylib              0x1810e7390 <redacted> + 728
9  libdispatch.dylib              0x1810e70b0 <redacted> + 112
10 libsystem_pthread.dylib        0x1812f1470 _pthread_wqthread + 1092
11 libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

--

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x18120cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18120ce54 mach_msg + 72
2  CoreFoundation                 0x181644c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181642964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x18156cc50 CFRunLoopRunSpecific + 384
5  GraphicsServices               0x182e54088 GSEventRunModal + 180
6  UIKit                          0x186856088 UIApplicationMain + 204
7  x-AppStore               0x1002b44ec main (AppDelegate.swift:15)
8  libdispatch.dylib              0x18110a8b8 (Missing)

#1. com.apple.libdispatch-manager
0  libsystem_kernel.dylib         0x1812294d8 kevent_qos + 8
1  libdispatch.dylib              0x1810ec7d8 _dispatch_mgr_invoke + 232
2  libdispatch.dylib              0x1810db648 _dispatch_source_invoke + 50

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  x-AppStore               0x1003247c8 CLSProcessRecordAllThreads + 4298098632
1  x-AppStore               0x1003247c8 CLSProcessRecordAllThreads + 4298098632
2  x-AppStore               0x100324be8 CLSProcessRecordAllThreads + 4298099688
3  x-AppStore               0x10031589c CLSHandler + 4298037404
4  x-AppStore               0x100310bdc CLSMachExceptionServer + 4298017756
5  libsystem_pthread.dylib        0x1812f3b28 _pthread_body + 156
6  libsystem_pthread.dylib        0x1812f3a8c _pthread_body + 154
7  libsystem_pthread.dylib        0x1812f1028 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x18120cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18120ce54 mach_msg + 72
2  CoreFoundation                 0x181644c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181642964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x18156cc50 CFRunLoopRunSpecific + 384
5  CFNetwork                      0x181cedc68 +[NSURLConnection(Loader) _resourceLoadLoop:] + 412
6  Foundation                     0x182063e4c __NSThread__start__ + 1000
7  libsystem_pthread.dylib        0x1812f3b28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1812f3a8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1812f1028 thread_start + 4

#4. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x181228344 __select + 8
1  CoreFoundation                 0x18164b1c8 __CFSocketManager + 648
2  libsystem_pthread.dylib        0x1812f3b28 _pthread_body + 156
3  libsystem_pthread.dylib        0x1812f3a8c _pthread_body + 154
4  libsystem_pthread.dylib        0x1812f1028 thread_start + 4

#5. AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x18120cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x18120ce54 mach_msg + 72
2  CoreFoundation                 0x181644c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x181642964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x18156cc50 CFRunLoopRunSpecific + 384
5  libAVFAudio.dylib              0x187ce59e0 GenericRunLoopThread::Entry(void*) + 164
6  libAVFAudio.dylib              0x187cba75c CAPThread::Entry(CAPThread*) + 84
7  libsystem_pthread.dylib        0x1812f3b28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1812f3a8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1812f1028 thread_start + 4

#6. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#7. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#8. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#9. Crashed: com.vluxe.starscream.websocket
0  libobjc.A.dylib                0x180d05b90 objc_msgSend + 16
1  CoreFoundation                 0x18163625c <redacted> + 56
2  CoreFoundation                 0x1815ddbc0 <redacted> + 192
3  CoreFoundation                 0x1816520a4 <redacted> + 24
4  libdispatch.dylib              0x1810d94bc <redacted> + 24
5  libdispatch.dylib              0x1810d947c <redacted> + 16
6  libdispatch.dylib              0x1810e54c0 <redacted> + 864
7  libdispatch.dylib              0x1810dcf80 <redacted> + 464
8  libdispatch.dylib              0x1810e7390 <redacted> + 728
9  libdispatch.dylib              0x1810e70b0 <redacted> + 112
10 libsystem_pthread.dylib        0x1812f1470 _pthread_wqthread + 1092
11 libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#11. queue2:src
0  libsystem_kernel.dylib         0x181227f24 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1812f2d20 _pthread_cond_wait + 704
2  x-AppStore               0x1008ebab4 g_cond_wait_until (gthread-posix.c:891)
3  x-AppStore               0x1008ec4f8 g_async_queue_pop_intern_unlocked (gasyncqueue.c:422)
4  x-AppStore               0x1008ec668 g_async_queue_timeout_pop (gasyncqueue.c:543)
5  x-AppStore               0x1008a1430 g_thread_pool_thread_proxy (gthreadpool.c:167)
6  x-AppStore               0x1008a4f60 g_thread_proxy (gthread.c:778)
7  libsystem_pthread.dylib        0x1812f3b28 _pthread_body + 156
8  libsystem_pthread.dylib        0x1812f3a8c _pthread_body + 154
9  libsystem_pthread.dylib        0x1812f1028 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#13. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x181228b48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812f1530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x1812f1020 start_wqthread + 4

**Comment by daltoniam** [comment]
Unfortunately this doesn't give us much to go off. It really could be anything crashing the application and the WebSocket object is causing the crash because it thinks the WebSocket object is valid and it isn't. I would check for race conditions to the WebSocket object as Starscream isn't "thread safe" and shouldn't be called from multiple threads. Also I would check and ensure the WebSocket isn't getting over released and a zombie as that could cause this too. I know those are pretty broad suggestions, but unfortunately we don't have much to go off. Best of luck!

**Comment by pendikov** [comment]
I have the same issue. It's causing the most crashes in my app. It crashed when I was debugging it and it stopped on usleep call. 
<img width="663" alt="websocket swift 2016-08-10 11-20-39" src="https://cloud.githubusercontent.com/assets/5001531/17542657/85185296-5eec-11e6-9b7a-9716c833a607.png">

**Comment by appoulsen** [comment]
i have same issue

**Comment by ndreisg** [comment]
same issue here:

```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0xdeadfa11
Termination Description: SPRINGBOARD, power down shortcut |  | ProcessVisibility: Foreground Obscured | ProcessState: Running
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001845afde8 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001845afc60 mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x0000000184af2e40 __CFRunLoopServiceMachPort + 196 (CFRunLoop.c:2613)
3   CoreFoundation                	0x0000000184af0908 __CFRunLoopRun + 1568 (CFRunLoop.c:2969)
4   CoreFoundation                	0x0000000184a10da8 CFRunLoopRunSpecific + 552 (CFRunLoop.c:3245)
5   GraphicsServices              	0x00000001869f6020 GSEventRunModal + 100 (GSEvent.c:2245)
6   UIKit                         	0x000000018ea30758 UIApplicationMain + 236 (UIApplication.m:3965)
7   Scan-IT                       	0x000000010215591c main + 56 (ViewControllerWebSocketDelegate.swift:12)
8   libdyld.dylib                 	0x00000001844a1fc0 start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x000000018476fb04 start_wqthread + 0

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001845afde8 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001845afc60 mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x0000000184af2e40 __CFRunLoopServiceMachPort + 196 (CFRunLoop.c:2613)
3   CoreFoundation                	0x0000000184af0908 __CFRunLoopRun + 1568 (CFRunLoop.c:2969)
4   CoreFoundation                	0x0000000184a10da8 CFRunLoopRunSpecific + 552 (CFRunLoop.c:3245)
5   Foundation                    	0x0000000185485674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304 (NSRunLoop.m:367)
6   Foundation                    	0x000000018548551c -[NSRunLoop(NSRunLoop) runUntilDate:] + 148 (NSRunLoop.m:411)
7   UIKit                         	0x000000018e715768 -[UIEventFetcher threadMain] + 136 (UIEventFetcher.m:437)
8   Foundation                    	0x0000000185595efc __NSThread__start__ + 1040 (NSThread.m:1181)
9   libsystem_pthread.dylib       	0x0000000184771220 _pthread_body + 272 (pthread.c:740)
10  libsystem_pthread.dylib       	0x0000000184771110 _pthread_start + 292 (pthread.c:799)
11  libsystem_pthread.dylib       	0x000000018476fb10 thread_start + 4

Thread 3 name:
Thread 3:
0   libsystem_kernel.dylib        	0x00000001845afde8 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001845afc60 mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x0000000184af2e40 __CFRunLoopServiceMachPort + 196 (CFRunLoop.c:2613)
3   CoreFoundation                	0x0000000184af0908 __CFRunLoopRun + 1568 (CFRunLoop.c:2969)
4   CoreFoundation                	0x0000000184a10da8 CFRunLoopRunSpecific + 552 (CFRunLoop.c:3245)
5   CoreFoundation                	0x0000000184b02074 _legacyStreamRunLoop_workThread + 268 (CFStream.c:1779)
6   libsystem_pthread.dylib       	0x0000000184771220 _pthread_body + 272 (pthread.c:740)
7   libsystem_pthread.dylib       	0x0000000184771110 _pthread_start + 292 (pthread.c:799)
8   libsystem_pthread.dylib       	0x000000018476fb10 thread_start + 4

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001845afde8 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001845afc60 mach_msg + 72 (mach_msg.c:103)
2   CoreFoundation                	0x0000000184af2e40 __CFRunLoopServiceMachPort + 196 (CFRunLoop.c:2613)
3   CoreFoundation                	0x0000000184af0908 __CFRunLoopRun + 1568 (CFRunLoop.c:2969)
4   CoreFoundation                	0x0000000184a10da8 CFRunLoopRunSpecific + 552 (CFRunLoop.c:3245)
5   CFNetwork                     	0x000000018531e6e0 -[__CoreSchedulingSetRunnable runForever] + 220 (CoreSchedulingSet.mm:1365)
6   Foundation                    	0x0000000185595efc __NSThread__start__ + 1040 (NSThread.m:1181)
7   libsystem_pthread.dylib       	0x0000000184771220 _pthread_body + 272 (pthread.c:740)
8   libsystem_pthread.dylib       	0x0000000184771110 _pthread_start + 292 (pthread.c:799)
9   libsystem_pthread.dylib       	0x000000018476fb10 thread_start + 4

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001845d152c __select + 8
1   CoreFoundation                	0x0000000184afb378 __CFSocketManager + 644 (CFSocket.c:2241)
2   libsystem_pthread.dylib       	0x0000000184771220 _pthread_body + 272 (pthread.c:740)
3   libsystem_pthread.dylib       	0x0000000184771110 _pthread_start + 292 (pthread.c:799)
4   libsystem_pthread.dylib       	0x000000018476fb10 thread_start + 4

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib        	0x00000001845d1604 __semwait_signal + 8
1   libsystem_c.dylib             	0x00000001844ea12c nanosleep + 212 (nanosleep.c:104)
2   libsystem_c.dylib             	0x00000001844ea04c usleep + 64 (usleep.c:52)
3   Starscream                    	0x00000001022b6610 closure #1 in FoundationStream.connect(url:port:timeout:ssl:completion:) + 96 (WebSocket.swift:214)
4   Starscream                    	0x00000001022b59b4 thunk for @escaping @callee_guaranteed () -> () + 36 (WebSocket.swift:0)
5   libdispatch.dylib             	0x000000018443caa0 _dispatch_call_block_and_release + 24 (init.c:994)
6   libdispatch.dylib             	0x000000018443ca60 _dispatch_client_callout + 16 (object.m:507)
7   libdispatch.dylib             	0x000000018447b1d4 _dispatch_queue_serial_drain$VARIANT$armv81 + 568 (inline_internal.h:2500)
8   libdispatch.dylib             	0x000000018447baf8 _dispatch_queue_invoke$VARIANT$armv81 + 328 (queue.c:5290)
9   libdispatch.dylib             	0x000000018447c49c _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 332 (queue.c:5908)
10  libdispatch.dylib             	0x000000018448446c _dispatch_workloop_worker_thread$VARIANT$armv81 + 612 (source.c:2529)
11  libsystem_pthread.dylib       	0x000000018476fe70 _pthread_wqthread + 860 (pthread.c:2218)
12  libsystem_pthread.dylib       	0x000000018476fb08 start_wqthread + 4

Thread 7:
0   libsystem_pthread.dylib       	0x000000018476fb04 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x000000018476fb04 start_wqthread + 0
```
