### ISSUE TITLE
Implement ability adding custom headers in handshake request

### ISSUE THREAD

**Issue by makhmutov** [daltoniam/Starscream#226]
App should have ability to add customer headers. Also will be great if Starscream will have supporting `Cookie` header. Should I open another issue for this?

**Comment by daltoniam** [comment]
This already exist in Starscream. See:

https://github.com/daltoniam/Starscream#custom-headers

Cookies are simply apart of an HTTP header. Example here:
https://gist.github.com/daltoniam/eb82f5600439aef4a050
