### ISSUE TITLE
Swift 2.3 support

### ISSUE THREAD

**Issue by cpinski** [daltoniam/Starscream#228]
Will there be a branch that supports swift 2.3 only? As of now there is a swift 3 branch but it seems as though the syntax is changing so rapidly that it may be beneficial for consumers of this library to have a swift 2.3 option.

**Comment by daltoniam** [comment]
I haven't done any work on a Swift 2.3 branch, but I could see one being created if there was need for it. Pull Requests and feedback are welcome if this would be beneficial.

**Comment by cpinski** [comment]
I am working on a project that could use a swift 2.3 branch. I actually have a PR ready to go for full swift 2.3 support but I need a swift2.3 branch created. Could you please add that?

**Comment by cpinski** [comment]
@daltoniam

**Comment by daltoniam** [comment]
Done and done. Thanks!

https://github.com/daltoniam/Starscream/tree/swift-23

**Comment by cpinski** [comment]
Thanks! New PR has been put up https://github.com/daltoniam/Starscream/pull/230
