### ISSUE TITLE
Support of custom close codes and access to close message payload

### ISSUE THREAD

**Issue by serieuxchat** [daltoniam/Starscream#229]
I was wondering whether it would be possible to support the following:
- Ability to specify a custom code when closing the web socket (currently the disconnect method always sends CloseCode.Normal.rawValue)
- Ability to get the payload of the close message that is sent by the remote end.
  (Currently the private method processTCPHandshake only passes the received HTTP code to doDisconnect and the eventual callback, but there is no way to get the payload that came with the close message).

(The RFC refers to the possible custom body of the Close message in https://tools.ietf.org/html/rfc6455#section-5.5.1)

**Comment by daltoniam** [comment]
- I figure this could be added, would just have to a small change to the disconnect method to support different codes (maybe do a default parameter or something).
- This is supported right now here: https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L619. Are you wanting to get the HTTP payload back on a failed upgrade request from `processTCPHandshake`?

**Comment by serieuxchat** [comment]
(1) Would be really great if it's supported.
(2) Wow, that awesome! I guess, the reason string (UTF8 encoded data from section 5.5.1) would be enough for our purposes. I will give it a try asap.

**Comment by daltoniam** [comment]
This was added in the 2.0.0 release (Swift 3 support)!

**Comment by serieuxchat** [comment]
I was wondering whether it would be possible to have those in Swift 2.3 code as well?

**Comment by commjoen** [comment]
+1 for the swift 2.3 code as we are using this in our project :).
