### ISSUE TITLE
Re-using socket after seeing NSPOSIXErrorDomain, code: 57.

### ISSUE THREAD

**Issue by hifall** [daltoniam/Starscream#231]
We are using Socket.IO swift client lib: https://github.com/socketio/socket.io-client-swift, which uses Starscream as a module for websockets. And we found some issue which could be related to Starscream while using the Socket.IO swift client lib, and the project owner suggested me to ask the question here.

In the following scenario, a socket.io-client-swift integrated app creates an extra socket upon seeing an NSPOSIXErrorDomain error:

1 start the app, then open a stream to connect to the socket.io server, and a socket is created. Let's call this socket A;
2 the app goes to background for 1 minute. This time span is long enough for me to reproduce this issue. Your mileage might vary;
3 bring the app to foreground again;
4 now the OS finds that the stream is idle long enough, and calls the NSStreamDelegate's stream method with NSPOSIXErrorDomain error, code 57, and message "The operation couldn’t be completed. Socket is not connected";
5 the stream method calls disconnectStream, which in turn calls SocketIOClient.tryReconnectWithReason, which calls connect() to create another socket on the server. Let's call this socket B;
6 now we have 2 sockets on the server, A and B, created by the same app. But socket A will soon be detected by the server to be dead, since the stream has been disconnected, and no heartbeat is sent to the server anymore. Socket A will be removed by the server, while socket B will be the active socket responsible for signalling for the app.
7 each time this background/foreground business happens, an extra socket is created. If one repeats this process multiple times, which is quite typical for an average app user, multiple extra sockets are created.

Now my question is: is it possible to keep using socket A in such a scenario? That would save creating another socket. I have tested mobile Safari, and it did NOT seem that it created an extra socket on the server, after being idle long enough so that the original socket was disconnected. So it seems to me that mobile Safari's behaviour is better with regard to socket use.

Thanks!

**Comment by daltoniam** [comment]
Thanks for the clear explanation. This is a inevitable issue with the way iOS backgrounds apps. The socket can't be "saved" and will always create a new connection. This makes sense from Apple's side as you won't want every app on your phone maintaining a network connection when you weren't using it (even though it adds a bit more complexity for the app developers). I would suspect the different between your app and mobile Safari is mobile Safari has the ability to "run in the background" in some regards. You can configure your app to do this as well using the background modes and the VOIP flag `https://github.com/daltoniam/Starscream#self-signed-ssl-and-voip`. This however needs to fall into Apple's guidelines of usages for the background modes. I ran into this same problem with one of my own apps and we ended up configuring our WebSocket server to ping every 90 and kill connections aggressively, but multiple connections from one client is inevitable. I hope that helps clear things up and best of luck.

**Comment by hifall** [comment]
Got it. Thanks for your kind reply!
