### ISSUE TITLE
Pong data is missing

### ISSUE THREAD

**Issue by nonameplum** [daltoniam/Starscream#232]
Hi,

I wonder why *Starscream* doesn't handle data that may be included in pong message sent from web socket. According to the web socket's specs:
https://tools.ietf.org/html/rfc6455#section-5.5.2

**Comment by acmacalister** [comment]
Thanks for including the RFC reference. I'm not sure what you mean? Starscream responses with a Pong to any Ping data, which according to the spec, should be the same data as the Ping. Are you seeing something different?

**Comment by nonameplum** [comment]
`onPong`callback and delegate doesn't have data passed in it as in `onText` or `onData` and i.e.
But in my opinion as RFC reference is saying that pong may have data so `Starscream` should pass it as optional parameter.

**Comment by daltoniam** [comment]
I added this to the Swift 3 branch (2.0.0).
