### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by AdamMak** [daltoniam/Starscream#236]
Hey

I downloaded the Swift 3.0 branch however I am getting over 23 Swift Compiler errors. Will this branch be updated soon? Really like this framework and would like to continue using this in my project

Thanks

Adam

**Comment by nuclearace** [comment]
This should be addressed when #235 is merged.

**Comment by AdamMak** [comment]
Ah cool, thanks for the info!

**Comment by daltoniam** [comment]
#235 has been merged!
