### ISSUE TITLE
question - how to wait for websocket connection

### ISSUE THREAD

**Issue by leoschweizer** [daltoniam/Starscream#241]
I'm trying to write a test case which requires to send data over a websocket to a server in the same executable. The problem seems to be that the `connect` method of Starscream is asynchronous, thus code like the following
```
socket = WebSocket(...)
socket.connect()
socket.writeData(...)
```
results in `writeData` being called before the connection is actually established.

Any suggestions on how I can do that?

**Comment by nonameplum** [comment]
I wrote pull request exactly to deal with this problem. https://github.com/daltoniam/Starscream/pull/238

**Comment by acmacalister** [comment]
you can use either the delegate or closure methods to wait for the socket connection as seen in the docs:

```swift

socket = WebSocket(url: NSURL(string: "ws://localhost:8080/")!)
socket.delegate = self
socket.connect()
socket.onConnect = { //closure API
    print("websocket is connected")
}

// or delegate method
func websocketDidConnect(socket: WebSocket) {
    print("websocket is connected")
}
```

**Comment by nonameplum** [comment]
But `onConnect` will be triggered always no matter from where `connect` was triggered. My pull request is adding callback closure to the `connect` method that is in relation with this call. This closure will not be called when another `connect` from different place will be triggered.
