### ISSUE TITLE
Cannot connect to mac terminal using netcat

### ISSUE THREAD

**Issue by vineethvijayan** [daltoniam/Starscream#244]
I am trying to connect to mac using nc with below command

`nc -l 10.201.50.11 8000`

I have tried your simple test application and it seems to get connected (terminal output below)

```
GET / HTTP/1.1
Host: 10.201.50.11:8000
Origin: ws://10.201.50.11:8000/
Sec-WebSocket-Key: dm1vYXdjZHBsanR4ZXVtcw==
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Version: 13
```

but no delegate methods are being called or `socket.writeString("hello there!")` doesn't work.

Am I doing anything wrong? 

I am using the SimpleTest application provided by you guys.

**Comment by acmacalister** [comment]
You need to be running a WebSocket server. Netcat just listens for arbitrary TCP and UDP connections, which won't work. The README in the SimpleTest app has an example to run the provided test WebSocket server. 

https://github.com/daltoniam/Starscream/blob/master/examples/SimpleTest/README.md

**Comment by vineethvijayan** [comment]
Ohh I see, thanks @acmacalister
