### ISSUE TITLE
enhancement - docker container server side sample

### ISSUE THREAD

**Issue by johndpope** [daltoniam/Starscream#246]
looks like this will fit my needs 
https://github.com/dataferret/docker-websocket-echo

consider it maybe helpful to document getting starscream with something like this
https://github.com/dataferret/docker-websocket-echo
and adding to readme

If I have time I'll take a look.

**Comment by daltoniam** [comment]
Ah a docker thing might be cool. We do have the SimpleTest app that uses a local ruby server and the simulator, but if someone went through the trouble of setting up a docker example in the README that would be nice 😄. I will close this issue out and if someone gets some time to do this we will update the README. Thanks!
