### ISSUE TITLE
Swift 2.3 Cocoapods Release

### ISSUE THREAD

**Issue by dcdspace** [daltoniam/Starscream#249]
Any expected release date of the Swift 2.3 branch to Cocoapods? iOS 10 comes out Monday so older versions are now deprecated...thanks

**Comment by daltoniam** [comment]
I will probably do all my open source stuff this weekend. I will do both 2.3 and 3 at the same time and update all the package manager and such then.

**Comment by julien-c** [comment]
Any news on this? Am waiting on this to publish my app to the Appstore so it would be very cool (I'm on Swift 2.3). Looks like at least 11 other people are anxiously waiting for this 😄 

Let me know if I can help in any way!

**Comment by dcdspace** [comment]
For now what I did is to set the pod source to the repo using the 2.3 branch and that worked. 

--
Dylan Diamond

**Comment by julien-c** [comment]
Cool. That's what I intended to try as a fallback. Cheers

**Comment by daltoniam** [comment]
Swift 2.3 and 3 released! 1.1.4 for 2.3 in CocoaPods and 2.0 for Swift 3.

**Comment by julien-c** [comment]
@daltoniam Thanks. Looks like the logging is much, much verbose though (see attached screenshot). Any idea why?

![capture d ecran 2016-09-18 a 18 25 38](https://cloud.githubusercontent.com/assets/326577/18619539/517c51e4-7dcd-11e6-88e0-f269ab217712.png)

**Comment by julien-c** [comment]
Ooops, nevermind: http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs
