### ISSUE TITLE
swift 3.0 branch Can not be used in Xcode 8 beta6, there are a lot of error

### ISSUE THREAD

**Issue by jh235** [daltoniam/Starscream#250]
I downloaded the latest 3.0 branch, but can no longer use under Xcode 8 beta6

**Comment by nmccann** [comment]
Have you tried it with the Xcode 8 GM? I haven't encountered any errors with the `swift3` branch and the GM.

If you continue getting errors with the GM, could you list some of them here?

**Comment by jh235** [comment]
Xcode 8 GM is OK, thinks! @nmccann
