### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by brightsider** [daltoniam/Starscream#257]
https://github.com/socketio/socket.io-client-swift/pull/515#issuecomment-249829170
Can you make update for this issue?

**Comment by daltoniam** [comment]
Can you provide anymore information than just a screenshot? I'm not sure how to reproduce this behavior without some more info. Thanks!

Also to have it for reference.

![](https://cloud.githubusercontent.com/assets/4996231/18663280/810068ba-7f26-11e6-8b92-5a27f06deaaf.png)

**Comment by brightsider** [comment]
I don't understand why it's crashed, but pull helps me.
Why make as to AnyObject, then to SecTrust, if can only as SecTrust? This helps me :)

**Comment by nuclearace** [comment]
@daltoniam His fix for this was https://github.com/socketio/socket.io-client-swift/pull/515/files, I said he should reopen the PR here.

**Comment by daltoniam** [comment]
2.0.1 with this fixed released!
