### ISSUE TITLE
there have any plan to support like "Websocket API similar to socket.io"?

### ISSUE THREAD

**Issue by arden** [daltoniam/Starscream#262]
there have any plan to support like "Websocket API similar to socket.io"?

like
https://github.com/kataras/go-websocket
https://github.com/kataras/iris

this way is simplifies the message parsing.

**Comment by nuclearace** [comment]
Why not just use: https://github.com/socketio/socket.io-client-swift. It uses this library.

**Comment by arden** [comment]
because https://github.com/socketio/socket.io-client-swift only support socket.io, not websocket.

**Comment by nuclearace** [comment]
Right. But this is just a WebSocket client, it doesn't make sense to do anything more than relay what it receives back. WebSockets make it easy to write event-driven frameworks, which is what socket.io is.

**Comment by daltoniam** [comment]
@nuclearace is right (and thank you).The WebSocket library you are referencing is implementing its own "framework" and not the standard WebSocket RFC. This library is designed to provide the base WebSocket RFC and any message implementation is left to the user or another library (like socket.io).
