### ISSUE TITLE
Xcode detects errors on this library at build time.

### ISSUE THREAD

**Issue by alexxsanchezm** [daltoniam/Starscream#263]
I add this lib to my app project, but at build time xcode shows up a tons of error in 2 files, one is SSLSecurity.swift and WebSocket.swift. This error didn't happened before
<img width="1413" alt="screen shot 2016-10-05 at 10 02 39 pm" src="https://cloud.githubusercontent.com/assets/3522488/19139195/0184f898-8b48-11e6-82fb-839fcae9cbb2.png">

<img width="344" alt="screen shot 2016-10-05 at 10 02 59 pm" src="https://cloud.githubusercontent.com/assets/3522488/19139180/dd0b9620-8b47-11e6-9bab-e956b1dd2981.png">

Maybe there is something  out of place on the project settings or pod file

**Comment by gunjotSinghMansa** [comment]
How to fix this?
