### ISSUE TITLE
Errors trying to download using Swift Package Manager

### ISSUE THREAD

**Issue by MarcusSmith** [daltoniam/Starscream#264]
When trying to do a swift build with Starscream in my Package dependencies I'm seeing this error:

```
error: the package has an unsupported layout, unexpected source file(s) found: .../Packages/Starscream-2.0.0/Tests/StarscreamTests.swift
fix: move the file(s) inside a module
```

**Comment by daltoniam** [comment]
Hrm, not sure. I'll have to checkout the package manager again, haven't touched it since Swift 2.X. 

@nuclearace maybe I am misremember, but aren't you a Mac/Swift Package Manager user? I'll look into it to, just didn't know if you had any ideas off hand.

**Comment by nuclearace** [comment]
Yeah I saw this when working on my new Discord library. Seemed to happen on the latest preview release of swift and the pm. Didn't make much sense to me deleting the test folder and rebuilding is a workaround

**Comment by nuclearace** [comment]
I think you need to move the file in Tests into its own folder. Like `Tests/StarscreamTests/*.swift`

**Comment by daltoniam** [comment]
#277 should have fixed this (in master now).

**Comment by abrain** [comment]
Thanks for resolving this. It seems Swift Package Manager still picks tag 2.0.1, so the error continues to exist until a new release.

**Comment by daltoniam** [comment]
`2.0.2` released.
