### ISSUE TITLE
obtain negotiated subprotocol after connect

### ISSUE THREAD

**Issue by eliburke** [daltoniam/Starscream#270]
I'm trying to use a WAMP library that uses ws / Starscream. I can set multiple protocols on the web socket (wamp.2.json, wamp.2.msgpack) but there is no way I can find to retrieve the negotiated value after the connection succeeds, which means I can't set the socket mode to text / binary as needed. 

I see back in issue #6 that there was briefly an optional parameter on the WebSocketDelegate `+    optional func websocketProtocolValue() -> String` but it was removed in a subsequent commit.

I'm nearly certain everything is working correctly with the underlying code, because I can trace through `validateResponse` and see in the http headers that `Sec-WebSocket-Protocol` (headerWSProtocolName) is set to the selected protocol. 

Would you be willing to have a copy of the session's initial HTTP Headers saved in the WebSocket object, or added to the `websocketDidConnect()` or another new delegate method? I'm happy to submit a PR if you tell me how you'd prefer to see it implemented (though... the change is small enough it may not be worth the extra back and forth! 😄 )

**Comment by daltoniam** [comment]
Thanks for explanation! The `websocketProtocolValue()`  got removed in favor of just overriding/setting custom headers:

https://github.com/daltoniam/Starscream#custom-headers

I could see the value in returning the initial HTTP Headers, hadn't got a request for that. Would the HTTP headers be included in the 101 upgrade response?
