### ISSUE TITLE
Establishing new connections connections causes app to crash over time

### ISSUE THREAD

**Issue by darrenhaken** [daltoniam/Starscream#272]
We're having an issue which causes the application to crash after we've connected several times (say 50+) which causes the application to crash.

We are wondering if it's something to do with using WSS due to seeing this commit:
https://github.com/daltoniam/Starscream/commit/20285cce972762929a497abf616b1a460b499f32

Here is a link to the crash:
https://gist.github.com/darrenhaken/7a9c2adc772de12e9cd50a1ba725fb92

**Comment by darrenhaken** [comment]
To add to this we're creating different Websocket instances as we switch between pointing to different providers.

**Comment by mchaffee1** [comment]
There's a sample project which (sometimes) demonstrates this crash here: https://github.com/mchaffee1/StarscreamCrash

**Comment by koke** [comment]
I just hit what I believe is the same crash. What I think happens:

- `pingOnce` gets called twice in a very short time
- The first time, it sees that `socket.isConnected` is `false` and it connects the socket
- `WebSocket.connect` creates the request, and sets up the input and output streams. Once that's done it sets `isConnecting = false`
- The second `pingOnce` arrives, the socket isn't `connected` yet, but it's also not connecting, so it connects again, replacing the input/output streams
- ...
- The socket gets deallocated, the streams delegates are set to nil for the current streams, but not for those created by the first `connect()`
- The old input stream receives some data and forwards it to a deallocated delegate.
- Crash

I was surprised to see `isConnecting = false` before being connected, but maybe there's a reason for it. In any case, whenever `inputStream`/`outputStream` are replaced, their delegates should be set to `nil`.
