### ISSUE TITLE
Xcode detects errors on this library at build time.

### ISSUE THREAD

**Issue by gunjotSinghMansa** [daltoniam/Starscream#273]
I am getting same issue as in #263. What to do?

**Comment by daltoniam** [comment]
This is because you are either using an old version of Xcode which doesn't support Swift 3 or you are using Swift 2.3 for your project and using version 2.0.0 instead of the 1.1.4 version for swift 2.3 project.

**Comment by gunjotSinghMansa** [comment]
Very thanks for your reply!  

Actually, I was following the pod installation instructions, which mentioned to use release 1.13 for swift 3.0 (which i later realized to be old). Updating it to latest released resolved it.
