### ISSUE TITLE
How to use Starscream in background mode ?

### ISSUE THREAD

**Issue by moto0000** [daltoniam/Starscream#278]
?

**Comment by acmacalister** [comment]
I assume what you mean from "background mode" you mean running the WebSocket in the VOIP service. As the README says you just need to enable the property:

```swift
//set this if you are planning on using the socket in a VOIP background setting (using the background VOIP service).
socket.voipEnabled = true
```

**Comment by moto0000** [comment]
Hi,
I'm mean run WebSocket in background task without VOIP service.

**Comment by acmacalister** [comment]
You can't just run things in the background without the VOIP service or such. Apps get suspended when backgrounded. You can read more about the background states in Apple's Docs here.

https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

**Comment by moto0000** [comment]
Hi,
Do you know how to configure VoIP on iOS 9 and above ?
I need send local notification to user when app is backgrounded.
