### ISSUE TITLE
Invalid http upgrade

### ISSUE THREAD

**Issue by mithunsree** [daltoniam/Starscream#280]
Hi,

I am new to IOS Development, While implementing a web socket for my app i got an error as invalid http upgrade. It is happening when i send message to the remote backend/Server, it is working in localhost. If i change the request type to https/wss it shows CFNetwork SSLHandshake failed (-9847). Eagerly waiting for the reply

**Comment by acmacalister** [comment]
Invalid HTTP Upgrade is a response from the Web Server when trying to upgrade to a WebSocket connection. Sounds like there is a network configuration between your WebSocket client and server, hence it working fine on localhost. I would start by looking there. The SSL issue is being caused either by the network configuration issue just like the standard HTTP or ATS. 

https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by mithunsree** [comment]
Thank you for your Reply,
I added the following keys to my info.plist but still it is not working. Showing the same error as before

<key>NSAppTransportSecurity</key>
<dict>
  
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>

**Comment by acmacalister** [comment]
Then it probably is a network configuration issue. I would start by doing some network troubleshooting and see what is going on there (check WebSocket server setup, your load balancer or proxy if you have one, or maybe run a packet capture). Doesn't sound like this is an issue with Starscream though and there is not anything I can do to help to narrow it down as it seems specific to your configuration.
