### ISSUE TITLE
Swift Package Manager: project has unsupported layout

### ISSUE THREAD

**Issue by 4np** [daltoniam/Starscream#281]
The project layout is incompatible with the Swift Package Manager.

According to #264 this should have been solved by #277, however the version still needs to be bumped to 2.0.2 as the patch got merged to Master and is [not in 2.0.1](https://github.com/daltoniam/Starscream/compare/2.0.1...master). @daltoniam, can you please create a new 2.0.2 Release?

### Steps to Reproduce

```
myUser ~ $ mkdir test
myUser ~ $ cd test
myUser ~/test $ printf "import PackageDescription\n\nlet package = Package(\n\tname: \"Test\",\n\ttargets: [],\n\tdependencies: [\n\t\t.Package(url: \"https://github.com/daltoniam/Starscream.git\", majorVersion: 2)\n\t]\n)" > Package.swift
myUser ~/test $ swift build
error: the package has an unsupported layout, unexpected source file(s) found: /path/to/test/Packages/Starscream-2.0.1/Tests/StarscreamTests.swift
fix: move the file(s) inside a module
myUser ~/test $ 
```

### Swift version

```
myUser ~/test $ swift --version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
myUser ~/test $ swift package --version
Apple Swift Package Manager - Swift 3.0.1 (swiftpm-11504)
myUser ~/test $ 
```

_ps. For reference purposes, the same issue existed in [SwiftyJson](https://github.com/SwiftyJSON/SwiftyJSON/issues/709) and got fixed by [moving the tests](https://github.com/SwiftyJSON/SwiftyJSON/pull/707)._

**Comment by hug33k** [comment]
@4np Could you check if my PR [https://github.com/daltoniam/Starscream/pull/282] is fixing your problem?
I got the same and now it is working for me.

**Comment by daltoniam** [comment]
`2.0.2` released that resolved this. Also see #264.

**Comment by 4np** [comment]
Confirmed, thanks 👍
