### ISSUE TITLE
Can i send json on websocket

### ISSUE THREAD

**Issue by mithunsree** [daltoniam/Starscream#283]
i need to send a json string over websocket to get correct response from server. now i created the json and when i try to send it with  "socket.write(string: json)" and "socket.write(data: json)" it shows JSON has no member data/string. I am using SwiftyJson to create json.

**Comment by acmacalister** [comment]
Yes you can send JSON, binary or any encoding you want over a WebSocket. I assume this is an issue with your implementation, but without a code example of your issue, there isn't much help we can provide.

**Comment by marinbenc** [comment]
You can use JSONSerialization to serialize an object into binary JSON data.

`func send(_ value: Any, onSuccess: @escaping ()-> Void) {

		guard JSONSerialization.isValidJSONObject(value) else {
			print("[WEBSOCKET] Value is not a valid JSON object.\n \(value)")
			return
		}

		do {
			let data = try JSONSerialization.data(withJSONObject: value, options: [])
			socket.write(data: data) {
				onSuccess()
			}
		} catch let error {
			print("[WEBSOCKET] Error serializing JSON:\n\(error)")
		}
	}
`

**Comment by vlori2k** [comment]
Is there possible to send "complete" json objects over websocket? 

For instance: `{"userID" : "tim@hotmail.com", "device" : "01"}`

My issue is that json objects are sent through websockets with ' ' inside the json object instead of " "   :/ 


my code snippet:


```
    func connectUserToMachine(){
        let user = userData.init()
           print(user)
​
           let jsonEncoder = JSONEncoder()
           let jsonData = try! jsonEncoder.encode(user)
           let json = String(data: jsonData, encoding: .utf8)
​
           print(json)  //prints: {"userID" : "tim@hotmail.com", "device" : "01"}
           self.socket?.write(string: json!)  // sends it like: {'userID' : 'tim@hotmail.com', 'device' : '01'}
          
    }
```
