### ISSUE TITLE
Linux support will be very helpful.

### ISSUE THREAD

**Issue by JayZhao** [daltoniam/Starscream#285]
Since swift is going server side, a swift websocket server on Linux will be very needed.

**Comment by acmacalister** [comment]
Thanks for the feature request. We are going to keep an eye on the Swift Server API Workgroup and see if Starscream fits in that equation at all.

https://swift.org/server-apis/

Going to close this out for now and has the server apis develop we will create an issue for more discussion then.

**Comment by pixelspark** [comment]
How are your current thoughts on this, @acmacalister? 

Would really like to have Starscream on Linux as WebSocket client (a WebSocket server is already available through Kitura-WebSocket but a WebSocket client is currently missing, and the server WG has not yet produced anything usable at this point as far as I know).

**Comment by Dev1an** [comment]
Any progress updates?
