### ISSUE TITLE
access from wi-fi ipv6

### ISSUE THREAD

**Issue by salvatore100** [daltoniam/Starscream#286]
you can access my server that has ipv4
from a wifi network ipv6 ?.

Apple Review Reject the application because it uses for app testing a wi-fi network and ipv6
socket = WebSocket (url: URL (string: "myIpPlublic_ipv4")!)

does not work

**Comment by acmacalister** [comment]
I'm not sure what you are trying to ask here. The WebSocket initializer takes an `NSURL` a Foundation type from Apple. It doesn't care if it is IPV4, IPV6 or a hostname. I would guess your app is getting rejected as Apple doesn't want you to use hard set IPV4 addresses. I suggest switching over to a hostname, as it has several benefits. Short version is, this doesn't sound like a Starscream issue and more of an issue with trying to submit an app with a hard set IPV4 address.
