### ISSUE TITLE
Help needed - I get Error Domain=WebSocket Code=200 "Invalid HTTP upgrade"

### ISSUE THREAD

**Issue by antwerpenR** [daltoniam/Starscream#290]
I am trying to use the Meetup.com websocket interface.   Description [here](https://www.meetup.com/meetup_api/docs/stream/2/photos/#websockets)

Very simple code:
`  let socket = WebSocket(url: URL(string: "ws://stream.meetup.com/2/photos")!, protocols: [])
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    socket.delegate = self
    socket.connect()
  }`

The `websocketDidDisconnect` delegate method is the only one to be called:
`websocketDidDisconnect Optional(Error Domain=WebSocket Code=200 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})`

I guess I am doing something wrong but no idea what and the previous issues with this error do not give much help...

**Comment by acmacalister** [comment]
Remove the empty protocols array (why is it blank in the first place?). The server isn't going to upgrade the connection if the protocols are empty. So:

`let socket = WebSocket(url: URL(string: "ws://stream.meetup.com/2/photos")!, protocols: [])`

becomes:

`let socket = WebSocket(url: URL(string: "ws://stream.meetup.com/2/photos")!)`

Tried on my end and it works fine after that modification.

**Comment by antwerpenR** [comment]
Perfect - thanks and sorry for for my lack of understanding.
