### ISSUE TITLE
Latency workaround?

### ISSUE THREAD

**Issue by siberian1967** [daltoniam/Starscream#291]
I 💙 StarScream, thanks!

Our issue is that isConnected returns true but in high latency scenarios (in my testing, latency greater then 475ms or so) commands that are sent get lost during this time window.

Anything under 475ms everything works great.
Anything above this somewhat arbitrary  threshold gets lost.

If we wait until that time expires and then send the command it goes through fine.

Is there some other indicator that indicates not just a tcp connection but that the server is actually ready to receive data?

We have some other workarounds in place but I wanted to make sure I wasn't missing something or seeing an actual bug.

**Comment by siberian1967** [comment]
Damn, was a problem in our server. Starscream RUlez

**Comment by acmacalister** [comment]
Glad you got it figured out! Appreciate the ❤️ for Starscream. 😄
