### ISSUE TITLE
Make a release 2.0.3 ?

### ISSUE THREAD

**Issue by euskadi31** [daltoniam/Starscream#299]
Can you make a release?

Thx

**Comment by qadirsuh** [comment]
please make a new release ASAP. Thanks

**Comment by daltoniam** [comment]
Finally got around to this. 2.0.3 has been released!

**Comment by qadirsuh** [comment]
Got problem

`Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Starscream (~> 2.0.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Starscream (~> 2.0.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
`

**Comment by qadirsuh** [comment]
Updated to 2.0.3 via pod update. still experiencing the same issue `Invalid HTTP upgrades`

**Comment by qadirsuh** [comment]
Actually fixed. was issue with our auth process. Thanks anyways
