### ISSUE TITLE
Library not loaded:

### ISSUE THREAD

**Issue by veluloganathan** [daltoniam/Starscream#303]
It was working fine but suddenly i got this, i tried to resolve with all the possible ways. i couldn't fix it. Help me

```
dyld: Library not loaded: @rpath/Starscream.framework/Versions/A/Starscream
  Referenced from: /Users/velu/Library/Developer/Xcode/DerivedData/...............
  Reason: image not found
```

**Comment by acmacalister** [comment]
This happens when you are running your app on a real device and the framework is not being copied over to the app bundle. See this in the README on how to solve.

https://github.com/daltoniam/Starscream#add-copy-frameworks-phase

**Comment by veluloganathan** [comment]
Hi, there was a cache problem. I have deleted all the cache related to 'Starscream'.

**Comment by tiwariammit** [comment]
@acmacalister 
I didn't find solution on README, can you please point me out?
