### ISSUE TITLE
Unable to use Pod on Xcode 8.2.1

### ISSUE THREAD

**Issue by thatjuan** [daltoniam/Starscream#305]
I have this on my Podfile

`pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'master'`

But I'm getting this on Xcode 8.2.1:

![screenshot 2017-01-26 00 47 51](https://cloud.githubusercontent.com/assets/389677/22325028/2cd90c16-e361-11e6-97d4-740dc1077390.png)

Is there anything I'm missing? I've also tried the `swift3` branch but that seems to be even older.

**Comment by daltoniam** [comment]
I'm not sure what you are seeing. Starscream works fine on Xcode 8.2.1 (I'm not using CocoaPods though). Maybe try upgrading to 2.0.3 that just got released and see if that resolves the build error?
