### ISSUE TITLE
Invalid HTTP upgrade (Duplicate)

### ISSUE THREAD

**Issue by qadirsuh** [daltoniam/Starscream#307]
As per @Elethier, the changes to fix "invalid HTTP upgrade" aren't in 2.0.2, they're just on master. I recommend you replace this line in your Podfile:

`pod 'Starscream', '2.0.2'`
with this:

`pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :commit => '60b27a4388bcb1b8b170c645dd19142cfa674f59'`

This will let you use the pre-release version. But use this version with caution; it's better to use a release tag when you can.

I have changed my pod as you suggested above. I am still experiencing the same error "Invalid HTTP upgrade" :(

- Starscream (from https://github.com/daltoniam/Starscream.git, commit 60b27a4388bcb1b8b170c645dd19142cfa674f59)
pod.lock file now showing like below.

```
EXTERNAL SOURCES:
  Starscream:
    :commit: 60b27a4388bcb1b8b170c645dd19142cfa674f59
    :git: https://github.com/daltoniam/Starscream.git

CHECKOUT OPTIONS:
  Starscream:
    :commit: 60b27a4388bcb1b8b170c645dd19142cfa674f59
    :git: https://github.com/daltoniam/Starscream.git
did I miss any thing still?
```

**Comment by daltoniam** [comment]
2.0.3 is released!

**Comment by qadirsuh** [comment]
Updated to 2.0.3 via pod update. still experiencing the same issue "Invalid HTTP upgrades"

**Comment by qadirsuh** [comment]
Actually fixed. issue was with our auth process. Thanks anyways
