### ISSUE TITLE
IOS10 voipEnabled = true not work

### ISSUE THREAD

**Issue by hai00jiao** [daltoniam/Starscream#309]
when my app enter background , the socket connection is paused, after the app enter foreground again, the request data arrive together.
<key>UIBackgroundModes</key>
	<array>
		<string>voip</string>
		<string>audio</string>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>

**Comment by alphatroya** [comment]
Confirm, iOS 9 devices receive data normally, but iOS10 data receiving paused after going background. `socket.voipEnabled` enabled, background modes too.

There is any temporary workaround for this?

**Comment by alphatroya** [comment]
Fix it by launch background task in `applicationDidEnterBackground` method

**Comment by nitrag** [comment]
I don't think @alphatroya suggestion works, does it?

**Comment by Laptopmini** [comment]
FYI, using VOiP Background mode goes against Apple TOS/Guidelines. It is a misuse of background modes, which is grounds for rejection from the AppStore.

**Comment by daltoniam** [comment]
Yeah I don't know why iOS 9 -> 10 caused this to stop working. That being said, @Laptopmini is right in general use cases. This was added for a very specific case of in house apps and someone using a WebSocket in a VOIP setup. I will try looking into this as time permits and PRs are welcomed.

**Comment by nitrag** [comment]
I've recently had an in-depth conversation with Apple DTS on this. 

Simply, you have to use PushKit/APNS. The "Legacy VOIP API" as they call it (which would hand the socket over to the system to wake up your app if communication arrived) was deprecated in iOS 9 and removed in iOS 10. As such, there's no way to keep a socket _connected_ while in the background and that flag no longer has any effect as OP described. 

You _can_ buy yourself ~3 min by launching a background task on `applicationDidEnterBackground` but that's all you get and it cannot be called again without the app entering the foreground (by the user).

@daltoniam nothing to look into I'm afraid, you should plan to pull the functionality.

**Comment by daltoniam** [comment]
@nitrag nice write up and thank you for that info! I'll do that next version (and update the documentation accordingly).

**Comment by sahara108** [comment]
If the app is woken up by the push notification, the socket will be closed after around 40 seconds with this error `Socket being disconnect with error Optional(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1})`. In my solutions, I will force the socket to re-connect when there is another push after socket being closed.

**Comment by johnnynanjiang** [comment]
Hi @daltoniam one scenario I discovered is that
1. websocket is connected in foreground, ping/pong going on
2. websocket goes into background, ping/pong is paused
3. websocket comes back to foreground, ping/pong continues for a short time
4. websocket gets disconnected with error nil

Not sure if 4. is expected or not, can you please advise? Thanks.
