### ISSUE TITLE
SignalR support

### ISSUE THREAD

**Issue by lehovsepyan** [daltoniam/Starscream#314]
Will this client work with signalR on the back-end side?

**Comment by acmacalister** [comment]
I have never used signalR, so I can't say. From the quick search I did, it can use WebSockets as a transport, so Starscream could help you get started build a SignalR iOS library if there isn't one already. I would suggest searching Github and seeing if there is already a SignalR library to use or using Starscream to write your own.

**Comment by jlubeck** [comment]
Hey @lehovsepyan did you end up trying this out? My server team is about to start using SingalR and I was wondering if I will be able to use this or not.
