### ISSUE TITLE
Crash on WebSocket.cleanupStream()

### ISSUE THREAD

**Issue by prcela** [daltoniam/Starscream#318]
I am posting crash stack with one error that rarely appears when app is trying to reconnect to web socket.
The line 448 in WebSocket.swift:
            stream.close()
![screen shot 2017-03-10 at 08 23 23](https://cloud.githubusercontent.com/assets/457998/23786107/5cceb7b4-056b-11e7-9215-421bd6fb5e54.png)

The problem starts to appear when we switched to swift3.

**Comment by acmacalister** [comment]
Thanks for the report, but like all the screenshots of backtraces, this gives use absolutely nothing to work off. If you have steps to reproduce or a code sample to show the issue I would be happy to take a look.
