### ISSUE TITLE
Codes 1 and 2 not defined as contants

### ISSUE THREAD

**Issue by SnitramDev** [daltoniam/Starscream#319]
Hi,

Is there a specific reason for the codes 1 and 2 not being defined as constants? Code 1 for invalid SSL certificate and code 2 for timed out.

```
let error = errorWithDetail("Invalid SSL certificate", code: 1)
self?.doDisconnect(self?.errorWithDetail("write wait timed out", code: 2))
```
I don't like to use ==1 or ==2 in my code within the webSocketDidDisconnect function, since it makes the logic a bit harder to understand.

Perhaps we could define these codes in the CloseCode enum?

By the way, this library is super awesome! Thank you for all the hard work!

**Comment by morganzellers** [comment]
I would like to work on this if need be!

**Comment by acmacalister** [comment]
Not really, I think it is just a carry over from older code. An enum is a good idea. Thanks. Glad you enjoy it! @morganzellers I'm fine if you want to work on it. Should be a fairly easy change.
