### ISSUE TITLE
Usage of enabledSSLCipherSuites is unclear (to me)

### ISSUE THREAD

**Issue by winsmith** [daltoniam/Starscream#321]
I'm trying to connect to a HTTPS-based Websocket server, using 

    let socket = WebSocket(url: URL(string: "wss://example.com/etc/etc/")!)
    socket.connect()

This fails however, in Websocket.swift:341

    if let cipherSuites = self.enabledSSLCipherSuites

Here, `self.enabledSSLCipherSuites` is `nil`, so execution returns without an error message. Is this the intended behaviour? If not, I could create a PR that prints out some kind of error message or throws an exception.

I can't find relevant docs for how to use `enabledSSLCipherSuites`, I haven't seen it in the example code, and the property is not used anywhere else that I can see. Could you maybe give a short example on how to use this, or how I can make my connection work?

**Comment by winsmith** [comment]
Here is what I did to fix this problem: I used ssllabs.com to check my Websocket server's supported cipher suites. The most preferred of those were `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` and `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. Since these correspond to Cocoa's defines of SSLCipherSuite objects, this code works for me:

    socket.enabledSSLCipherSuites = [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]

If this is the preferred way to set `enabledSSLCipherSuites`, I'll gladly write a PR that adds a few lines of docs about this.

**Comment by daltoniam** [comment]
You are correct, that is the intended implementation or how to setup the SSLCipherSuites. A PR would be greatly appreciated. This feature never got documented as it was added in a PR for a specific use case and then forgotten about 😄. Thanks!

**Comment by winsmith** [comment]
On it!
