### ISSUE TITLE
Receive big size binary cause following small size binary combine together 

### ISSUE THREAD

**Issue by atjoneswang** [daltoniam/Starscream#322]
Hi, 
I use protobuf  pack data to binary, if my binary only have string will be good.
if i send one big size binary contain video and then follow closely some  string binary, will cause all data combine together. how can I solve this situation?

**Comment by acmacalister** [comment]
There is not enough info here to give you an answer. Starscream doesn't combine message frames, so it probably an implementation issue of how you are formatting or parsing your data.

**Comment by atjoneswang** [comment]
here is my code
every receive data pass value to  process function. i use google protobuf, ex: when first data size over 1M bytes and following some small messages send per ms, i find the recive data size  combine.
```
func websocketDidReceiveData(socket: WebSocket, data: Data) {
        processSocketData(data: data)
    }
func processSocketData(data: Data) {
        let msgdata = try! MsgPacket.parseFrom(data: data)
        
        if UserInfoModel.shared.email != msgdata.from {
            handleMessageData(msgdata: msgdata)
        } else {
            realmHelper.updateMessageSendStatus(cliendid: msgdata.clienmsgid, status: true)
        }
    }
```

**Comment by daltoniam** [comment]
Thank you for the code, but this still doesn't give us anything actionable to help with. WebSockets by default don't interleave messages. @acmacalister is correct in recommending looking at the implementation of your formatting or parsing. It might be your server sends the protobuf payload in multiple WebSocket messages, but from what we have here, it doesn't sound like an issue with the library.
