### ISSUE TITLE
How to access http upgrade response body

### ISSUE THREAD

**Issue by xuxiangyang** [daltoniam/Starscream#325]
Hi，I use StarScream to connect to websocket server, ws server responded a 403 code and json data in http response body. How could I access the http body?

Thx

**Comment by acmacalister** [comment]
403 is an HTTP status for the request being forbidden. Starscream isn't design for handling HTTP requests. It expects the connection to be upgrade to a WebSocket, otherwise it returns an error that you can get from the disconnect delegate method. You need to fix whatever is going on with you getting a forbidden error when making the initial HTTP connection.

**Comment by xuxiangyang** [comment]
Hi, this issue is not about than I do not know why I can not connect to websocket and get a 403 response. I could connect to websocket, but I need to process the case that server many not forbid client to connection and carry some message with the 403 response in body.  why I can not access the message wtih StarScream? 

even status code is 403, this response body many be different。sometimes server wants to tell client  that client has no permmison to access, sometimes server wants to tell client that client it was forbidden for a while. client need to tell user the different message. How could I process this case?

Thx

**Comment by daltoniam** [comment]
Starscream doesn't process HTTP messages other than the 101 upgrade request. It doesn't have a way handle different HTTP response codes as anything that isn't the 101 upgrade request is just seen as a bad upgrade request. All that being said, you can see the response status code in the error return from the disconnect:

https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L520

Other than the status code, It isn't designed to process the entire HTTP response as there could be many different response types and Starscream isn't a full HTTP client. I understand the desire to show a message to the user, but I don't think the extra code bloat to the library is worth the specific use case.
