### ISSUE TITLE
websocket is disconnected: Invalid HTTP upgrade

### ISSUE THREAD

**Issue by MynaBay** [daltoniam/Starscream#327]
I'm trying to use Starscream on AppleTV. 

        socket = WebSocket(url: URL(string: url)!)
        socket?.delegate = self
        socket?.connect()

My url is valid "wss://hooq.com/blablabla"    (replacing the blablabla part)

My delegate is sometimes called with the error "websocket is disconnected: Invalid HTTP upgrade", and other times nothing is called. Not connected or disconnected. 

Any thoughts as to what might be wrong?

**Comment by dbismut** [comment]
Same thing here (on iPhone though). I tried https://www.websocket.org/echo.html and everything seems to be working ok with the url.

**Comment by dbismut** [comment]
Just so you know, I've tried https://github.com/tidwall/SwiftWebSocket and I did manage to connect to the server that failed with Starscream. Starscream doesn't set a user agent header by default so I tried adding it, but that didn't make it work.

**Comment by MynaBay** [comment]
Thanks for your help on this. Using the suggested SwiftWebSocket seemed to work for me.


On April 6, 2017 at 9:40:21 AM, David (notifications@github.com) wrote:

Same thing here (on iPhone though). I tried https://www.websocket.org/echo.html and everything seems to be working ok with the url.

**Comment by muchprogrammer** [comment]
Not sure if outdated, but I noticed that using Starscream with `wss://` forced 'host' header to be site.com:443, while it had to be just site.com. So I had to set it manually `socket.headers["host"] = site.com` - that fixed the issue for me

**Comment by MynaBay** [comment]
Thanks.


On April 20, 2017 at 6:25:26 PM, muchprogrammer (notifications@github.com) wrote:

Not sure if outdated, but I noticed that using Starscream with wss:// forced 'host' header to be site.com:443, while it had to be just site.com. So I had to set it manually socket.headers["host"] = site.com - that fixed the issue for me

**Comment by daltoniam** [comment]
Hi all, not sure what you are seeing here. I have been able to successfully connect with the default Starscream configuration in the past to multiple WebSocket servers over both secure and non secure connections. That being said, some WebSocket servers might have a specific host name requirement or user agent requirement that isn't apart of the RFC. This of course makes it impossible for Starscream to handle all cases requirement by different servers, but as you have all found, you can easily set your own headers as needed by your WebSocket server to connect. If anyone finds anything specific, feel free to open a issue or PR.
