### ISSUE TITLE
Crash when calling CFReadStreamSetDispatchQueue

### ISSUE THREAD

**Issue by JayZhao** [daltoniam/Starscream#328]
Here's the crash log:
http://crashes.to/s/3d624667ce6

pod 'Starscream'
It's v2.0.4

<img width="1045" alt="screen shot 2017-04-17 at 17 37 01" src="https://cloud.githubusercontent.com/assets/2278174/25085403/88a9a898-2394-11e7-89a3-063827f3ee5e.png">

**Comment by MaxAdamyan** [comment]
+1

**Comment by daltoniam** [comment]
Thanks for the link, but that doesn't give us anything actionable. The crash being a the set Dispatch Queue just tells us something runtime related crash when attempting do something to the socket. The call is also coming on the `cleanupStream` portion of the code, so it is rather unlikely it is the library doing something wrong. I would recommend looking at race condition within your code as that is what normally leads to issues like this. Starscream isn't thread safe, so one must take care on the calls to it.
