### ISSUE TITLE
[V2.0.4] Crashes with SSL Pinning

### ISSUE THREAD

**Issue by remybourgoin** [daltoniam/Starscream#329]
Hi,

Since the last version, and particularly since the fix on the SSL Pinning (https://github.com/daltoniam/Starscream/commit/dbeb1190b8dcbff4f0b797f9e9d9b9b864d1f0d6), I experience a couple of crashes on my app, in production (App Store).

<img width="1126" alt="capture d ecran 2017-04-18 a 11 15 01" src="https://cloud.githubusercontent.com/assets/349614/25146324/51b992f0-2428-11e7-8c50-2a6864f66c25.png">

### The issue
The line that causes the problem is this one (and especially the `as!` 😺):
https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L398

It means that in this case, the kCFStreamPropertySSLPeerTrust is null.

### Other libs
I've looked at other implementations of SSL Pinning on other libraries, and they are all doing the pinning at the old location (`open func stream(_ aStream: Stream, handle eventCode: Stream.Event)`).

- https://github.com/facebook/SocketRocket/blob/master/SocketRocket/SRWebSocket.m#L1399
- https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPWebSocket.m#L1420
- ...

And more important, they check if this variable is not-null.

### Solution (or not !)
We could easily secure this code and avoid the crash, by changing it to the following one, but I'm not really sure that the SSL Pinning would be done anymore.

```
if let sec = s.security,
    !s.certValidated,
    let trust = outStream.property(forKey: kCFStreamPropertySSLPeerTrust as Stream.PropertyKey) as? SecTrust {
```

### Questions
- In your opinion, why the kCFStreamPropertySSLPeerTrust would be null at this precise moment?
- What decision lead you to moving this code from `open func stream(_ aStream: Stream, handle eventCode: Stream.Event)`?

**Comment by daltoniam** [comment]
Hi @remybourgoin. Thanks for the quality write up. I haven't see that issue before, normally a trust comes along with a secure stream, but I guess it could be possible to fall into that block of code connecting to a non secure stream and having a valid security object set. I agree that state should be handled and will be updated accordingly.

The decision that lead to the moving of the code from the `func stream` was actually a report of an SSL pinning vulnerability [here](https://github.com/daltoniam/Starscream/blob/master/CHANGELOG.md#204). Basically they found in their SSL pinning tests that they could bypass the checking in certain cases. The moving of the code fixed this vulnerability according to their reports and testing.

**Comment by giullo** [comment]
I opened https://github.com/daltoniam/Starscream/pull/349 to fix the issue

**Comment by daltoniam** [comment]
`2.1.0` release with #349 fix. Thanks!
