### ISSUE TITLE
Resonse from server is c[1007,“null”]

### ISSUE THREAD

**Issue by ashishpandita** [daltoniam/Starscream#330]
I am writing a string to sockets its delegate call back always returns c[1007,“null”] 
After that sockets gets disconnect I am printing  error message 
Optional("Error Domain=WebSocket Code=1007 \"\" UserInfo={NSLocalizedDescription=}"

here are the call backs 
 func websocketDidConnect(socket: WebSocket) {
       
        print("websocket is connected \(socket.description)")
        if (socket.isConnected) {
            
      
            
        }
        
    }
    
    func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        print("websocket is disconnected: \(String(describing: error?.description))")
        
    }
    
     func websocketDidReceiveData(socket: WebSocket, data: Data) {
        print("websocketDidReceiveData \(data)")
    }
    
     func websocketDidReceiveMessage(socket: WebSocket, text: String) {
         print("websocketDidReceiveMessage \(text)")
    }
  

// This is how I write on a button action 
  let myjson = "{ \"Param1\": \"Value\", \"Param2\": \"value2\", \"Param3\": \"value3\"}"
                        
                        socket?.write(string: myjson, completion: {
                           
                        })

Need help?

**Comment by daltoniam** [comment]
Thanks for the code, but I think this is an issue with your server. I can't say for certain what you are seeing, but I think the 1007 error code is a encoding error. I would look why your server is rejecting your messages since the response of `c[1007,“null”]` doesn't have anything to do with the Starscream or the WebSocket protocol.
