### ISSUE TITLE
Staying connected (or reconnecting) for background processes 

### ISSUE THREAD

**Issue by casparwylie** [daltoniam/Starscream#332]
My system involves accessing network data when the app is in background. After a while trying to work out the problem, it turns out the socket connection drops once a user enters background. I've been struggling to find a successful work around. Is there anything in Starscream that would help?

**Comment by rmvz3** [comment]
Same here. I'm updating an app that used to work without problems in background but now it stop sending "keep alive" messages when the app goes boackground. Any workaround for this?

**Comment by daltoniam** [comment]
The standard app lifecycle will cause the socket connection drop when entering the background. Nothing "official" can be done to prevent that. In the past people use to abuse the VOIP background mode to allow this (see #309 for more details), but Apple frowned on this as it isn't the intend use case. As that issue notes, this restriction is now strictly enforced in iOS 10. The recommend course of action is to have a server that does all the processing and wakes the app up with push notifications with the new data you need.
