### ISSUE TITLE
Does not check the Upgrade response `Sec-WebSocket-Accept`

### ISSUE THREAD

**Issue by hishnash** [daltoniam/Starscream#334]
https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L581-L583

This should be validated as being equal:

```
SHA1(Sec_WebSocket_Key_Value + '258EAFA5-E914-47DA-95CA-C5AB0DC85B11')
```
The reason for this is to ensure that the web socket is not behind a caching layer.
see https://tools.ietf.org/html/rfc6455 page 24

**Comment by daltoniam** [comment]
Would you look at that. Can't believe I missed that. Thanks for the link. Certainly something that should be addressed. Thanks!
