### ISSUE TITLE
Stream disconnects after phone is locked & unlocked again.

### ISSUE THREAD

**Issue by ndreisg** [daltoniam/Starscream#336]
Hi!

My socket is automatically disconnected when i lock my phone & unlock it again.
I get following Error: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}

Can I avoid this somehow?

Thanks

**Comment by ndreisg** [comment]
Can Error Code 57 occur in other cases too?
Because I solved it like this:

```
func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
    if error?.code == 57 {
        socket.connect() // reconnect if disconnected because of phone lock
    }
}
```

**Comment by daltoniam** [comment]
Code 57 can probably happen under more cases than locking or unlocking your phone. That being said, you have the right idea of reconnecting. Your app can get closed when locking it, which is apart of standard iOS app lifecycle behavior. Based on the nature of how the iOS app lifecycle of backgrounding and foregrounding apps, you will need to reconnect under these circumstances and it isn't anything Starscream handles directly.

**Comment by rolandleth** [comment]
Hey, @daltoniam!

Sorry to open such an old issue, but I'm having problem with this as well.

Taking the app into background works, the connection is kept alive. Only locking the screen disconnects the socket and the delegate method is only called after unlocking the phone, so that's not quite helpful in my case.

Is there any way to actually keep the connection open while the screen is locked?

Thank you,
Roland

**Comment by ndreisg** [comment]
Hi @rolandleth 

By default Apple does not permit having connections opened in the Background.
You can probably try using one of the Background modes described here: https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

Although I'm afraid that a constantly opened WebSocket connection in the Background probably won't pass the review.

**Comment by rolandleth** [comment]
Hey!

Thanks for the swift answer and the suggestion. 

Oh, well, I’ll do with the 2–3 minute limit, then, since none of those use cases really apply.

Have a great day!
