### ISSUE TITLE
Swift Client <> Java Backend messages aren't being received by Java

### ISSUE THREAD

**Issue by willwang888** [daltoniam/Starscream#340]
Hi,

I'm currently using Starscream for a Swift client, Java Backend application that is currently deployed on **Heroku**, and uses web sockets between Swift code and Java code to send and receive messages back and forth. However, when I run the whole app locally @ localhost:8080, everything works perfectly and all messages are sent correctly. 

When I deployed it on heroku, the connection "handshake" is made (I made sure to check on both ends), but when my Swift client sends a message to the Java backend:

socket.write(data: jsonData as Data) **where "jsonData" is a json that has been converted to bytes**

— the Java "onMessage()" function in my backend does not get fired at all. What's weird is that it works when it's run locally but not anymore when I try and run it on heroku.

My swift socket is defined like this: 
**var socket = WebSocket(url: URL(string: "wss://myapp.herokuapp.com/ws")!)** (tried ws:// as well and still doesn't work)

My Java server endpoint is: **@ServerEndpoint(value = "/ws")**

I get an "Idle Connection" error message after a while and the websocket automatically disconnects. Does anyone know what the issue is? Thanks!

**Comment by hishnash** [comment]
This sounds like part of your connection on Hiroko does not support http upgrades. 

you are using `wss` so your endpoint is secure behind ssl, are you resolving the `ssl` as part fo the java server is that resolved in a layer before the server? 

when testing localy are you using a secure conection?

**Comment by willwang888** [comment]
I tried with "ws" as well, but it still didn't work. I'm not getting any errors at all, just blank and nothing is going through.

**Comment by hishnash** [comment]
does the WS connect? the `websocketDidConnect` method on your delegate does it get called?

**Comment by AkiraTaki** [comment]
Just to share my experience, I had designed a Java backend server and iOS client using StarScream to communicate with it- which runs without issues. (Both ws and wss works well. )
