### ISSUE TITLE
Swift Client and Ruby server by Faye socket

### ISSUE THREAD

**Issue by manhcuong27** [daltoniam/Starscream#342]
Hello,

I'm using Starcream in my swift project, my server is Ruby and is using Faye socket. I got message socket connected in my app and I define this socket right in the home controller, the socket variable is define as a property. But after a while I got disconnected message with error = nil . I try to broadcast from the server but seem like my device does not get it. 

Is Starcream compatible with Ruby faye ?

Thanks.

**Comment by daltoniam** [comment]
Starscream should be compatible with any WebSocket server that implements the standard 6455 RFC for the WebSocket protocol. That being said, I haven't used Faye with Starscream personally and I don't know if Faye is just a generic WebSocket server or has some kind of extensions add to it. As far as seeing a disconnect, I don't know why that would happen without more information, but this probably isn't an issue with Starscream. Best of luck.
