### ISSUE TITLE
Invalid HTTP Upgrade with SpringBoot Stomp as a backend

### ISSUE THREAD

**Issue by milanovici** [daltoniam/Starscream#343]
I have an issue using Starscream library in combination with SpringBoot Websockets (using Stomp) as a backend. Every time i get this error : 

> error Error Domain=WebSocket Code=200 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade}

Chat with web and android client work, only problem is with ios client. Anyone has an idea ?

**Comment by annguyen-iosdev** [comment]
Im facing to same issue. any updates about this one ?

**Comment by daltoniam** [comment]
STOMP builds off the WebSocket, so you will need to add some extra code to make this work. I think someone build a STOMP library off Starscream at some point, I'd search around GitHub for it.

**Comment by RushOT** [comment]
@milanovici Sorry to bother you, could you find any lib to work with stomp over websocket. I'm using Spring as a backend. And wandering do they my clients can use it.
