### ISSUE TITLE
Sending images to server

### ISSUE THREAD

**Issue by casparwylie** [daltoniam/Starscream#345]
What is the recommended way of doing this? Assuming I have UIImage, do I convert it to matrix and send via the data method?

**Comment by daltoniam** [comment]
I don't know of a recommend way of sending images over a WebSocket (or if that is recommended at all), but yes you will need to convert the `UIImage` to a `Data` as you would have to do with any generic socket (TCP, HTTP, etc). See `UIImagePNGRepresentation` (there is a JPEG one too) for more info.
