### ISSUE TITLE
Can not connect to socket

### ISSUE THREAD

**Issue by zzheads** [daltoniam/Starscream#348]
Have server at http://188.120.235.97:8082/, trying to connect WebSocket using your library, but can not... Using Fiddler - there is no any GET requests when I call socket.connect()... Why?

**Comment by daltoniam** [comment]
I'm sorry, but there is no information here for me to help with. I'd recommend try updating the example app with your URL to start the debugging process as it is probably not an issue with Starscream but rather a usage or configuration issue. Best of luck.
