### ISSUE TITLE
Configurable websocket initial connection timeout

### ISSUE THREAD

**Issue by admeister** [daltoniam/Starscream#350]
Can the timeout for the web socket to be established be configurable? Due to lack of web proxy support on our corporate network it takes some time for this to fail.

**Comment by daltoniam** [comment]
It can be. Not sure why it isn't in the README (I could have swore it was at some point...). 

See here:
https://github.com/daltoniam/Starscream/blob/master/Source/WebSocket.swift#L178

Basically just set the `socket.timeout = 20` or whatever you need.
