### ISSUE TITLE
No such module 'zlib' 

### ISSUE THREAD

**Issue by drmarkpowell** [daltoniam/Starscream#351]
Using Cocoapods, pointing directly to tagged release 2.1.0 on github, building Starscream library fails to resolve the zlib library link dependency.

XCode build error message:
.../Starscream/Source/Compression.swift:30:8: No such module 'zlib'

Podfile dependency in my project:
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :tag => '2.1.0'

**Comment by drmarkpowell** [comment]
Hey dude,
I hacked around your Podspec file until I got this version to run. Here it what worked for me (really just the last two lines I needed to add to fix the include and modulemap paths)

Pod::Spec.new do |s|
  s.name         = "Starscream"
  s.version      = "2.1.0"
  s.summary      = "A conforming WebSocket RFC 6455 client library in Swift for iOS and OSX."
  s.homepage     = "https://github.com/daltoniam/Starscream"
  s.license      = 'Apache License, Version 2.0'
  s.author       = {'Dalton Cherry' => 'http://daltoniam.com', 'Austin Cherry' => 'http://austincherry.me'}
  s.source       = { :git => 'https://github.com/daltoniam/Starscream.git',  :tag => "#{s.version}"}
  s.social_media_url = 'http://twitter.com/daltoniam'
  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.10'
  s.tvos.deployment_target = '9.0'
  s.source_files = 'Source/*.swift'
  s.requires_arc = 'true'
  s.libraries    = 'z'
  s.preserve_paths = 'zlib/**/*'
  s.pod_target_xcconfig = {
    'SWIFT_INCLUDE_PATHS' => '$(PODS_ROOT)/Starscream/zlib'
  }
end

**Comment by daltoniam** [comment]
Ah yes, I hadn't deployed it yet as you probably noticed 😕. I had some trouble getting CocoaPods and the SPM to work together, but sorted out now. Thanks for sharing the updated Podspec, that help a lot in figured this out. 2.1.0 is properly pushed to the trunk now!
