### ISSUE TITLE
SSL certificate with socket

### ISSUE THREAD

**Issue by AdamMak** [daltoniam/Starscream#352]
I have an SSL certificate I am trying to use with my socket. I got the CRT file, converted it to DER, added it to my project and tried adding it to my socket. Below is my code you can see it being added

`var socket = WebSocket(url: URL(string: "wss://192.168.1.143:6223")!, protocols: [])`

```
  override func viewDidLoad() {
        super.viewDidLoad()
        do
        {
            let urlPath     = Bundle.main.path(forResource: "my_cert", ofType: "der")
            let url         = NSURL.fileURL(withPath: urlPath!)
            let certificateData = try Data(contentsOf: url)
            
            let certificate: SecCertificate =
                SecCertificateCreateWithData(kCFAllocatorDefault, certificateData as CFData)!

            var trust: SecTrust?
            let policy = SecPolicyCreateBasicX509()
            let status = SecTrustCreateWithCertificates(certificate, policy, &trust)
            if status == errSecSuccess {
                let key = SecTrustCopyPublicKey(trust!)!;
                let ssl =  SSLCert(key: key)
                socket.security = SSLSecurity(certs: [ssl], usePublicKeys: true)
                socket.delegate = self
                socket.connect()
            }

        }catch let error as NSError
        {
            print(error)
        }
    }
```
However I am getting this error

> CFNetwork SSLHandshake failed (-9807)
> websocket is disconnected: The operation couldn’t be completed. (OSStatus error -9807.)

The only way I can get it working is by calling this line of code

`socket.disableSSLCertValidation = true`

Any ideas why this is working. I know the certificate is valid, my Android colleague has added it to this project and passed it into his socket and is working fine for him. Any ideas on what I am doing wrong?

Thanks in advance

**Comment by daltoniam** [comment]
Thank you for the code and write up, but unfortunately there isn't much I can do to assist. The error is a fairly generic SSL error and SSL pinning is difficult to troubleshoot without access to the server, certificates, environment, etc. Setting the `disableSSLCertValidation` to true makes sense because that disables SSL checking completely thus bypassing the pinning.

**Comment by noahkamara** [comment]
Was `socket.disableSSLCertValidation` deprecated? It doesn't seem to work anymore

**Comment by jbarros35** [comment]
Holy shit

disableSSLCertValidation

**Comment by noahkamara** [comment]
Don’t freak 😂 I use star scream only for the local web socket of a mod for Kerbel Space Program, which doesn’t provide a certificate
