### ISSUE TITLE
Building fails for 2.1.0 as a framework target dependency

### ISSUE THREAD

**Issue by onevcat** [daltoniam/Starscream#354]
Hi, I am using Starscream as a dependency of a framework like this:

The dependency path is something like this:
MyApp --> MyFramework --> Starscream

MyApp contains a Cartfile depends to MyFramework, and MyFramework contains a Cartfile for Starscream.

Starscream 2.1.0 fails the build of `MyFramework` when I running `carthage update` under MyApp folder. It says:

```
import Starscream // <- missing required module 'zlib'
```

So it seems that the Zlib module is not visible now when Starscream used as a framework dependency. Maybe it would be better to add zlib as a carthage dependency instead of just defining the module file?

**Comment by eliburke** [comment]
I've run into this problem as well. Is there a fix that doesn't involve downgrading to 2.0.x?

**Comment by daltoniam** [comment]
Ah yeah I forgot about Carthage support needing the new dependencies for compression. I personally don't use Carthage, what would need to be done besides adding a Cartfile? I'm also open to PRs 😄.

**Comment by daltoniam** [comment]
I checked in a Cartfile with the latest 3.0.0 release. I don't know if it works, but 🤞.

**Comment by daltoniam** [comment]
I'm going to close this one out based on what has been reported in #389 and the release of 3.0.1. If that doesn't fix it, please reopen the the issue (and PR welcomed too).
