### ISSUE TITLE
Masked pong closes connection

### ISSUE THREAD

**Issue by anisimovsergey** [daltoniam/Starscream#356]
One of the libraries I'm using in my project for creating a WebSockets server generates a pong to my ping request (from Starscream client) which contains a mask. Overall the TCP payload looks like this in hex: "8a 80 00 00 00 00"

Starscream client receives the packet and processes the first two bytes ignoring the fact that the packet has a mask and leaving fragment 00 00 00 00 in fragBuffer. On the next cycle the parser starts from the begging of the fragment buffer and disconnects from the server with message:
"continue frame before a binary or text frame" because isFin == 0 and receivedOpcode == 0.

Looking at the RFC I couldn't understand whether a masked pong is a valid case or not.

**Comment by daltoniam** [comment]
I've never heard or seen a masked pong before. Starscream does pass all of the Autobahn tests which doesn't include masked pongs. That being said, I'm not saying it can't happen or a WebSocket server won't send a packet like that, but I'm not sure how to test or add support for that. A PR is welcomed if you can track down what is happening.

**Comment by anisimovsergey** [comment]
Yes, I agree it's not clear whether it's a valid case or not. I guess, for fixing this properly, the Authobahn test suite should be extended covering this case too. But I'm still not sure if it's a valid case or not. From my perspective, it's not entirely valid because the ping I'm sending doesn't contain any data to mask, but anyway it can be handled without failing since it's not a protocol violation either. 
I'll try to think how to introduce a fix with minimal intervention and create a PR.

**Comment by daltoniam** [comment]
Sounds good! Thanks. I agree. I tend to lead toward invalid case due to the RFC saying: 
(5.1 data framing, p26)
```
...a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).
...
A server MUST NOT mask any frames that it sends to
   the client
```

**Comment by anisimovsergey** [comment]
You are absolutely right! How I missed it? From the same paragraph it becomes pretty clear that client should close the connection upon receiving a masked frame. I started thinking that the current implementation is correct, maybe the error handling can be a bit better with some proper detection of incoming masked frames. But I guess this particular issue can be closed.
