### ISSUE TITLE
When processing a HTTP header, there is an off-by-one bug that results in parsing error.

### ISSUE THREAD

**Issue by dinghaoz** [daltoniam/Starscream#358]
if the header is 
"HTTP/1.1 440 Client Error (440)\r\n\r\n{"api:statuscode": 105, "api:message": "Invalid session. Please re-login."}" 
the `validateResponse()` returns 200, but 440 expected

```
for i in 0..<bufferLen {
    if buffer[i] == CRLFBytes[k] {
        k += 1
        if k == 3 {
            totalSize = i + 1
            break
        }
    } else {
        k = 0
    }
}
```

` if k == 3` should be ` if k == 4`

**Comment by daltoniam** [comment]
See #359.
