### ISSUE TITLE
Crash on WebSocket.swift line 453

### ISSUE THREAD

**Issue by superlin** [daltoniam/Starscream#360]
#11. Crashed: com.vluxe.starscream.websocket
0  CoreFoundation                 0x18151f404 CFHash + 352
1  CoreFoundation                 0x18151beec CFBasicHashFindBucket + 164
2  CoreFoundation                 0x18151bdf4 CFDictionaryGetValue + 164
3  CoreFoundation                 0x1815922d8 _CFStreamUnscheduleFromRunLoop + 184
4  CoreFoundation                 0x181602120 _CFStreamSetDispatchQueue + 168
5  Starscream                     0x102042958 WebSocket.cleanupStream() -> () (WebSocket.swift:453)
6  Starscream                     0x10204b758 specialized WebSocket.stream(Stream, handle : Stream.Event) -> () (WebSocket.swift)
7  Starscream                     0x1020428cc @objc WebSocket.stream(Stream, handle : Stream.Event) -> () (WebSocket.swift)
8  CoreFoundation                 0x18159201c _signalEventSync + 212
9  CoreFoundation                 0x1816025c4 ___signalEventQueue_block_invoke + 24
10 libdispatch.dylib              0x1804fe9e0 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1804fe9a0 _dispatch_client_callout + 16
12 libdispatch.dylib              0x18050cad4 _dispatch_queue_serial_drain + 928
13 libdispatch.dylib              0x1805022cc _dispatch_queue_invoke + 884
14 libdispatch.dylib              0x18050cfa8 _dispatch_queue_override_invoke + 344
15 libdispatch.dylib              0x18050ea50 _dispatch_root_queue_drain + 540
16 libdispatch.dylib              0x18050e7d0 _dispatch_worker_thread3 + 124
17 libsystem_pthread.dylib        0x180707100 _pthread_wqthread + 1096
18 libsystem_pthread.dylib        0x180706cac start_wqthread + 4

**Comment by daltoniam** [comment]
This is just a part of a backtraces and doesn't really give us anything to go off. It could really be a lot of things causing the crash outside of a problem with Starscream (race conditions, etc). We need either steps to reproduce or a sample app for us to look at. If you are able to get that for us, feel free to open a new issue and we can take a look.
