### ISSUE TITLE
SSL validation only passes with Configuration Profile

### ISSUE THREAD

**Issue by vhart** [daltoniam/Starscream#362]
I have a root certificate which is used to pass SSL Validation when opening a web socket connection. If the certificate is manually installed (say by dragging it to the simulator, opening in a browser, email) the web socket is able to connect. But if I add the `der` file to the keychain and add it as an iOS Trust Anchor, the connection continuously fails with a `OSS -9807` (invalid certificate chain) error. I've also called `SecTrustEvaluate` using the cert and it comes back `trusted`. Any idea why this is happening? Also, how does the socket get the cert data when it is installed by creating a configuration profile?

**Comment by daltoniam** [comment]
Hrm, If I understand the question right, the certs are pulled from the app bundle. A configuration profile would have to push the certificate into the app bundle for the app to be able to access it. For the first question, there has to be code to pull the certificate out of the keychain that is then passed into Starscream. Starscream doesn't read directly from the keychain for SSL pinning.
