### ISSUE TITLE
Crash on WebSocket.swift line 534

### ISSUE THREAD

**Issue by ImanovTamerlan** [daltoniam/Starscream#363]
Crashed: com.vluxe.starscream.websocket
0 Starscream 0x89a218 WebSocket.processInputStream() -> () (WebSocket.swift:534)
1 Starscream 0x89a050 WebSocket.processInputStream() -> () (WebSocket.swift)
2 Starscream 0x899e18 @objc WebSocket.stream(Stream, handle : Stream.Event) -> () (WebSocket.swift)
3 CoreFoundation 0x1c82dc15 _signalEventSync + 154
4 CoreFoundation 0x1c88a85f ___signalEventQueue_block_invoke + 12
5 libdispatch.dylib 0x1bf91797 _dispatch_call_block_and_release + 10
6 libdispatch.dylib 0x1bf9e59d _dispatch_queue_serial_drain + 854
7 libdispatch.dylib 0x1bf94b71 _dispatch_queue_invoke + 886
8 libdispatch.dylib 0x1bf9ea1f _dispatch_queue_override_invoke + 282
9 libdispatch.dylib 0x1bfa01b5 _dispatch_root_queue_drain + 326
10 libdispatch.dylib 0x1bfa000f _dispatch_worker_thread3 + 106
11 libsystem_pthread.dylib 0x1c14687d _pthread_wqthread + 1040
12 libsystem_pthread.dylib 0x1c14645c start_wqthread + 8

**Comment by daltoniam** [comment]
This is just a part of a backtraces and doesn't really give us anything to go off. It could really be a lot of things causing the crash outside of a problem with Starscream (race conditions, etc). We need either steps to reproduce or a sample app for us to look at. If you are able to get that for us, feel free to open a new issue and we can take a look.
