### ISSUE TITLE
Compile issue on Xcode9b5

### ISSUE THREAD

**Issue by ys1382** [daltoniam/Starscream#366]
Xcode 9 beta 5 Swift 4 now complains if you put (Void) as the function deceleration parameter list. In WebSocket.swift, you have:

    public var onConnect: ((Void) -> Void)?
    public var onPong: ((Void) -> Void)?

This triggers a warning, as well as errors below in the same file, where those two functions are called. The warnings and error go away if you remove the "Void" like so:

    public var onConnect: (() -> Void)?
    public var onPong: (() -> Void)?

**Comment by nuclearace** [comment]
This should already be fixed.

**Comment by daltoniam** [comment]
I also didn't see any issues with the latest code and swift4/Xcode beta 5. I created a `swift4` branch anyway to upgrade the project files for any beta testing.
