### ISSUE TITLE
Crash in WebSocket.processInputStream()

### ISSUE THREAD

**Issue by kilyukhin** [daltoniam/Starscream#367]
Hi,

The problem reported in issue #363 happens in my released app. Looks like there is a concurrency issue inside the library code.

`WebSocket.processInputStream` is called from `WebSocket.stream` delegate in a background thread. While the function is being executed, a client code may call `WebSocket.disconnect` in main queue. So it could happen that between `WebSocket.processInputStream` start and `let length = inputStream!.read(buffer, maxLength: BUFFER_MAX)` line `inputStream` becomes `nil` and `inputStream!` unwrapping crashes.
Client code has no access to `WebSocket.stream` thread and hence has no way to avoid this issue from happening.

Does it make sense to dispatch `WebSocket.stream` body execution to main queue?

**Comment by rastersize** [comment]
I’m seeing this issue as well and came to the same conclusion as @kilyukhin. There also seems to be a similar race condition for `cleanupStream()` where the `stream.close()` call results in a crash due to `CFHash(_:)` being given `NULL`.

**Comment by daltoniam** [comment]
`2.1.1` has been released with a fix for this!

**Comment by rastersize** [comment]
Thank you @daltoniam!

**Comment by superlin** [comment]
Still happend in my app with iOS 11.0.3
