### ISSUE TITLE
Possibility to increase BUFFER_MAX size

### ISSUE THREAD

**Issue by SnitramDev** [daltoniam/Starscream#368]
Hi,

Currently, the BUFFER_MAX is a constant set to 4096. Is it possible for this value to be changed?

Thanks!

**Comment by daltoniam** [comment]
Currently there isn't a way to change it. What is the reason for the request? The BUFFER_MAX is really only used to say how big of a chunk of data to read at once which usually isn't a problem since it will keep reading until it gets all the data.
