### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by JayZhao** [daltoniam/Starscream#370]
Turn on Xcode thread sanitizer and run on simulator(it has more CPU cores than an iPhone).
You'll see this error:

<img width="445" alt="screen shot 2017-08-18 at 18 21 47" src="https://user-images.githubusercontent.com/2278174/29455118-802a84ee-8442-11e7-8bc8-a80010af3801.png">

**Comment by daltoniam** [comment]
`2.1.1` has been released with a fix for this!
