### ISSUE TITLE
Live video support

### ISSUE THREAD

**Issue by nicpro85** [daltoniam/Starscream#371]
Could this allow websocket to be used to access a live stream of lets say h265 video and be eventually passed to an AVPlayer? I dont know where to ask the question.

**Comment by acmacalister** [comment]
See #116. WebSockets probably aren't the best choice for video streaming. You might use them to figure out the connection info, then use HLS for the actual streaming.

**Comment by nicpro85** [comment]
Yeah i was dubious about it but who knows... look at this

https://medium.com/@daspinola/video-stream-with-node-js-and-html5-320b3191a6b6

**Comment by acmacalister** [comment]
Streams in Node are just wrappers around regular socket connections. WebSockets != sockets. You could do this in iOS using the NSStream API to do the similar streaming, but luckily iOS has `AVPlayer` that can do all the heavy lifting for you.

```swift
let url = URL(string: "http://awesome.com/video.mp4")
let playerViewController = AVPlayerViewController()
playerViewController.player = AVPlayer(url: url)
self.present(playerViewController, animated: true)
playerViewController.player?.play()
```

**Comment by saroar** [comment]
may be you can check this https://github.com/tidwall/SwiftWebSocket @nicolasbigot
