### ISSUE TITLE
Crashes caused by so many wakeups

### ISSUE THREAD

**Issue by MhdHejazi** [daltoniam/Starscream#373]
I noticed many crashes in my app with the type "CPU Usage". This is the reason from one of them:

> Event:           wakeups
Wakeups:         45022 wakeups over the last 8 seconds (5959 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Duration:        7.56s
Steps:           3

After checking, the problem seems to be caused by the following code:
```swift
private func initStreamsWithData(_ data: Data, _ port: Int) {
    ...
    var out = timeout /*5*/ * 1_000_000 // wait 5 seconds before giving up
    let operation = BlockOperation()
    operation.addExecutionBlock { [weak self, weak operation] in
        guard let sOperation = operation else { return }
        while !outStream.hasSpaceAvailable && !sOperation.isCancelled {
            usleep(100) // wait until the socket is ready
            guard !sOperation.isCancelled else { return }
            out -= 100
            if out < 0 {
                WebSocket.sharedWorkQueue.async {
                    self?.cleanupStream()
                }
                let errCode = InternalErrorCode.writeTimeoutError.rawValue
                self?.doDisconnect(self?.errorWithDetail("write wait timed out", code: errCode))
                return
            } else if outStream.streamError != nil {
                return // disconnectStream will be called.
            }
        }
        ...
        outStream.write(bytes, maxLength: data.count)
    }
    writeQueue.addOperation(operation)
}
```

As you can see, if the stream isn't ready, the code tries to sleep for 100 microsecond before checking again, and repeats that for **50,000** times in around **5 seconds**. This intensive use of `usleep()` causes the system to stop the app.

Isn't there any better way to check if the stream is ready without polling every 100 microsecond?

**Comment by acmacalister** [comment]
Yeah, this code was added to create a "timeout" for the Stream. Without it, you basically have to wait for whatever the system defines for it to give up on the connection. You could change the timeout value to something smaller. If that doesn't do the trick, the only other potential change I could see making would be to add code to ignore timeouts altogether or up the sleep wait.
