### ISSUE TITLE
when deinit happens in another thread, It may crash?

### ISSUE THREAD

**Issue by luoqisheng** [daltoniam/Starscream#376]
hi,I have an question,detail in https://github.com/socketio/socket.io-client-swift/issues/792.  the delegate callback `open func stream(_ aStream: Stream, handle eventCode: Stream.Event) ` called in the com.vluxe.starscream.websocket queue, It may lead to crash ? if the socket object deinit happens in another thread?

**Comment by acmacalister** [comment]
I'm not totally sure what you are asking. Starscream isn't thread safe by default. That means you need to take care when writing potentially racy code to use the appropriate locking techniques.  A picture of a backtrace in other issue doesn't provide any information for us to go off. If you have steps to reproduce or a code example that would be helpful.

**Comment by luoqisheng** [comment]
thanks for your reply!

**Comment by luoqisheng** [comment]
hi,  when the websocket object released, the `deinit` called the `cleanupStream`.should the `cleanupStream` must be called in workQueue in order to wait the steam callback finish its work?

**Comment by daltoniam** [comment]
No, because deinit means that object is getting deallocated so you can't push the cleanup work to another queue when the object is just about to get deallocated. The work might not be finished, but that can't be helped because the object is getting deallocated and would be the expected behavior.

**Comment by luoqisheng** [comment]
if object was deallocated and works in the stream's callback has not finished, then any access to the object's property in the callback would be unexpected,can it leads to crash?

**Comment by luoqisheng** [comment]
// is this be ok?
   deinit {
        mutex.lock()
        readyToWrite = false
        mutex.unlock()
        // wait sharedWorkQueue to finish works in callback and cleanup
        WebSocket.sharedWorkQueue.sync {
            cleanupStream()
        }
        writeQueue.cancelAllOperations()
    }
