### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by khodzhamberdiyev** [daltoniam/Starscream#380]
There is a crash with the reference to [answer](https://github.com/daltoniam/Starscream/issues/51#issuecomment-73528079) when suddenly _websocketDidDisconnect_ is called. And a lot of _write binary data_ and _websocketDidReceiveData_ functions are called at that moment.

1. Thread 0. Crash point.
<img width="351" alt="starscream crash when auto reconnect" src="https://user-images.githubusercontent.com/11474016/30530733-b7188374-9c62-11e7-8b00-c6bc1fb66890.png">

2. Thread 0. Trace.
<img width="526" alt="starscream crash when auto reconnect" src="https://user-images.githubusercontent.com/11474016/30531327-fa1e51ae-9c66-11e7-90e3-14e18264489b.png">

3. Thread 0. Trace.
<img width="451" alt="starscream crash when auto reconnect" src="https://user-images.githubusercontent.com/11474016/30533715-3df079e0-9c74-11e7-9172-97221cce7c91.png">

4. Thread 0. Trace.
<img width="891" alt="starscream crash when auto reconnect" src="https://user-images.githubusercontent.com/11474016/30531369-4f53cd98-9c67-11e7-8b3d-241b6bef7039.png">

**Comment by acmacalister** [comment]
Starscream isn't thread safe. You need to take care when writing any potentially racy code and make sure you are using the proper lock techniques to prevent race condition and crashes. Part of a picture of Starscream code in your Xcode debugger doesn't provide anything useful that we can go off to help you. If you have a sample application that demos this problem or steps to reproduce the issue that would be helpful.
