### ISSUE TITLE
Release version with Swift 4 support

### ISSUE THREAD

**Issue by fassko** [daltoniam/Starscream#383]
Could you please release update with Swift 4 support? Thanks!

**Comment by nmazzon** [comment]
or to change swift version to 3.2

**Comment by fassko** [comment]
For me is that I'm making a cocoapod library which I want to update to Swift 4 and use new fancy Codable protocol. :P

**Comment by acmacalister** [comment]
We are working Swift 4 support right now. We are doing a couple of refactoring things to make things a little nicer. We should have the update out shortly.

**Comment by daltoniam** [comment]
Version 3.0.0 has been released with Swift 4 support!

**Comment by fassko** [comment]
Thanks @daltoniam ! ;)
