### ISSUE TITLE
Xcode 9 Carthage Fails to Build Error 65

### ISSUE THREAD

**Issue by LondonAtlas** [daltoniam/Starscream#389]
From terminal:
/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/Starscream/Starscream.xcodeproj -scheme Starscream -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Starscream/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/.../Carthage/Checkouts/Starscream)

From the Carthage log:
/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/Starscream/Starscream.xcodeproj -scheme Starscream -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Starscream/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/.../Carthage/Checkouts/Starscream)User defaults from command line:
    IDEDerivedDataPathOverride = /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Starscream/3.0.0

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos11.0

=== BUILD TARGET Starscream OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies
No architectures to compile for (ARCHS=armv7 arm64, VALID_ARCHS=i386 x86_64 armv7s).

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

N.B.
All "..." in the paths are local directories that won't mean anything to anyone but my system.

**Comment by LondonAtlas** [comment]
Starscream 2.1.1 seems to work though.

**Comment by ChristRm** [comment]
If you link to last commit in master branch it builds ok. Like me in Cartfile:

> github "daltoniam/Starscream" "dc4891680469c29cd13008946db5c096511824c7"

I think new version of lib should be created.

**Comment by daltoniam** [comment]
Thanks for the update. Version 3.0.1 has been released.

**Comment by appskottage** [comment]
Still getting the same error with 3.0.1
