### ISSUE TITLE
Carthage Error code 65 on v3.0.1

### ISSUE THREAD

**Issue by LondonAtlas** [daltoniam/Starscream#391]
Sorry but still having issues when building via Carthage. I have also tried after manually clearing derived data.

Terminal log:
*** Building scheme "Starscream" in Starscream.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/Starscream/Starscream.xcodeproj -scheme Starscream -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/Starscream/3.0.1 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/.../Carthage/Checkouts/Starscream)

Carthage log:
=== BUILD TARGET Starscream OF PROJECT Starscream WITH CONFIGURATION Release ===

Check dependencies
No architectures to compile for (ARCHS=armv7k, VALID_ARCHS=x86_64 i386 arm64 armv7s armv7).

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by daltoniam** [comment]
I personally don't use Carthage, but based on that error, I just tried adding `armv7k` to the framework as a valid architecture. Try using master and let me know if that works. If it does, I'll do a new release.

**Comment by LondonAtlas** [comment]
Yes that worked 😄 

Thank you for maintaining this project and thank you for responding so quickly to these issues!

**Comment by daltoniam** [comment]
Version 3.0.2 has been released with the fix.
