### ISSUE TITLE
Opportunity to parse with custom protocol

### ISSUE THREAD

**Issue by wowlocal** [daltoniam/Starscream#393]
Can you implement possibility for delegate parse binary data with my custom protocol. It will be look like low level-parser dependency injection.

**Comment by acmacalister** [comment]
Can you provide a little more detail on what you are trying to accomplish? If you want to control parsing the stream,`WSStream` is a provided as a protocol for custom stream parsing. Otherwise you can just read the data out of the `websocketDidReceiveData` callback...

**Comment by wowlocal** [comment]
I read all your code, function write(data: Data) of WSStream get parsed data, parse occurs in private func dequeueWrite(_ data: Data, code: OpCode, writeCompletion: (() -> ())? = nil) for write and private func processOneRawMessage(inBuffer buffer: UnsafeBufferPointer<UInt8>) -> UnsafeBufferPointer<UInt8>  for read

**Comment by wowlocal** [comment]
I wrote some hard code for my custom data transfer protocol, but it bad when i forced to delete pieces of code and paste mine

**Comment by acmacalister** [comment]
Right. The main parsing logic is intended for the WebSocket protocol. It sounds like you might be doing something else? Not sure it makes a lot of sense to use this library if you aren't using WebSockets. This isn't a general purpose socket library.
