### ISSUE TITLE
Can't seem to connect to Poloniex WSS API?

### ISSUE THREAD

**Issue by johnalanwoods** [daltoniam/Starscream#397]
Is there something I'm missing, or doing wrong here?

This is how I'm preparing the socket.

		self.socket = WebSocket(url: URL(string: "wss://api.poloniex.com")!, protocols: ["ticker"])

I get a disconnect delegate call with the error:

(Error Domain=WebSocket Code=400 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade}

Maybe an issue on the Poloniex end? Their API looks like I'm using it correctly:
https://m.poloniex.com/support/api/

Anyone been successful using Starscream and Poloniex?

**Comment by johnalanwoods** [comment]
FWIW its working with Autobahn

**Comment by acmacalister** [comment]
Looks like Poloniex is using WAMP, which is built on top of the WebSocket protocol. You might need to use WAMP specific library, such as https://github.com/iscriptology/swamp or implement some custom logic to support WAMP (maybe it has additional required headers for auth or something along those lines).
