### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by HamedGh** [daltoniam/Starscream#398]
After connecting and write some data, I get this error message in `websocketDidDisconnect` method:

> Decompression failed: Error Domain=WebSocket Code=2 \"(null)\

why?

**Comment by acmacalister** [comment]
Sounds like it is failing to decompress the data. Are you sure the WebSocket server is setup to use gzip compression?

**Comment by HamedGh** [comment]
I don't get your point, Why it should setup to use gzip compression?

I use version 
`pod 'Starscream', '~> 2.0.3'`
and work well, but after I upgrade to the new version I encounter that problem.I just change the way I should I add header

**Comment by H-Ghadirian** [comment]
Is there anybody to help me?  I can not send data!

**Comment by acmacalister** [comment]
It sounds like you have gzip compression enabled. Try and disable it. 

```swift
socket.enableCompression = false
```

**Comment by H-Ghadirian** [comment]
TanX, It works for me 👍
