### ISSUE TITLE
Sending large image and data stream at the same time

### ISSUE THREAD

**Issue by robreuss** [daltoniam/Starscream#403]
I have a socket open through which I'm sending a real-time stream of motion data.  When I try to send an image through the same socket, it blocks the flow of motion data completely.  Before I launch into adding a second socket for large data elements, could you confirm that I'm on the right path?  Do WebSockets block in this way?  Thanks for a great framework!

**Comment by robreuss** [comment]
I went ahead and implemented two sockets, one for large and one for small data frames.  I'm not sure, but I believe it is partially solving the problem because the stream of small data does not get blocked during image transfer.  However, I believe it is when the transfer is complete or thereabouts I get a disconnect with error message "masked and rsv data is not currently supported".  Note that if I am not running the stream of small data the image transfers fine.  Any thoughts?

**Comment by daltoniam** [comment]
Hi @robreuss, yep two sockets would be the right course of action. The WebSocket protocol be default doesn't support interleaving messages, so an large image transfer would block sending any other data until that complete message was sent. 

https://tools.ietf.org/html/rfc6455#section-5.4

```
The fragments of one message MUST NOT be interleaved between the
fragments of another message unless an extension has been
negotiated that can interpret the interleaving.
```

The second question on the disconnect, I'm not sure why that would happen without more information. That error can normally crop up if the buffer or message frame is malformed (or the client is really sending unsupported masked data).

**Comment by robreuss** [comment]
Thanks @daltoniam!  My implementation for the image transfer using two sockets is working as hoped.  I'll keep trying to track down the other issue.
