### ISSUE TITLE
iOS app crash in release version when we use starscream library for connect to web socket

### ISSUE THREAD

**Issue by elahekhani** [daltoniam/Starscream#414]
we develop an iOS application in Xcode. we need to connect to server via web socket. we use starscream library. In debug mode everything is good, but in release mode on iPhone app crash after some minutes.

we add websocketdelegate in all viewControllers and receive text in all of them.

Do you have any idea?

**Comment by AdamMak** [comment]
You should get the .dSYM file so you can symbolicate the crash log. If you can get those logs symbolicated and post the logs here, will give us a better idea of what went wrong

**Comment by elahekhani** [comment]
thanks AdamMak.
I get log and understand my bug is in image processing codes.
