### ISSUE TITLE
Cannot disconnect before upgrading to websocket protocol

### ISSUE THREAD

**Issue by dragosnicolae** [daltoniam/Starscream#417]
Hi!

In my application, I need to implement some timeout logic when connecting to the server. The problem is that calling **disconnect** before the HTTP response is received will not work because of a guard, *isConnected*, which is set only after the HTTP response is received. Thus, closing the TCP socket in case of a timeout is impossible.

**Comment by daltoniam** [comment]
I'm not exactly sure what your timeout logic looks like, but any reason you couldn't just check on `onConnect` and `onDisconnect` and update a variable that it is ready and not to disconnect? The `isConnected` is rather simple in its usage and just notifies the socket is communicating with the server or not connected at all. 

Also it is a bit of a simple implementation, but Starscream does include timeout logic:

https://github.com/daltoniam/Starscream#custom-headers

Lastly, you can force a disconnect in Starscream which might be helpful in your timeout logic:

https://github.com/daltoniam/Starscream/blob/master/Sources/WebSocket.swift#L483
