### ISSUE TITLE
WebSocket server support

### ISSUE THREAD

**Issue by szuwest** [daltoniam/Starscream#428]
can you add webSocket server support ?
There are few projects That supports webSocket server

**Comment by daltoniam** [comment]
This has been asked a few times before and I felt it was outside the scope of the project. Also to your point, there are a few WebSocket servers already out there so I don't want to add to the project bloat and maintenance overhead if it is just a "nice to have". All that being said, I'll leave this issue open for discussion and reference.

**Comment by fassko** [comment]
@szuwest you should look into https://github.com/vapor/websocket or using whole vapor solution. More info https://docs.vapor.codes/3.0/websocket/overview/

I will close this issue.
