### ISSUE TITLE
Missing argument for parameter #1 in call: s.OnPong() in websocket.swift

### ISSUE THREAD

**Issue by leoskingsley** [daltoniam/Starscream#430]
In the WebSocket.swift file, lines 464 and 658 error saying 
![screen shot 2017-11-26 at 2 48 23 pm](https://user-images.githubusercontent.com/30047431/33241089-df2736e4-d2b8-11e7-95ed-f3d010c7f006.png)

Changing this to include `Void` errors saying that it expected no arguments. This is on the latest Xcode and swift, and the module was installed from CocoaPods

**Comment by daltoniam** [comment]
I think this might be because there was a change at some point for `OnPong` that made it return data instead of just void. It should look like:

``swift
socket.onPong = { data in
    //do stuff
}
```
The example above should work with the latest version (3.0.3).
