### ISSUE TITLE
Xcode 9 failed to compile

### ISSUE THREAD

**Issue by Zeaa** [daltoniam/Starscream#431]
https://github.com/daltoniam/Starscream/blob/8f2af31bd3e87246d302d92d00b75b8ab6e9b512/Starscream.podspec#L16

 Xcode putput:

`The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
 `

Starscream.podspec lack of `'SWIFT_VERSION' => '4.0'`

```ruby
 s.pod_target_xcconfig = {
      'SWIFT_VERSION' => '4.0'
      'SWIFT_INCLUDE_PATHS' => '$(PODS_ROOT)/Starscream/zlib'
  }
```

**Comment by Zeaa** [comment]
[Update]

**Comment by daltoniam** [comment]
Version 3.0.3 has just been released that addresses this!
