### ISSUE TITLE
"characters is deprecated" warning

### ISSUE THREAD

**Issue by olgadanylova** [daltoniam/Starscream#432]
Hi guys!
There are several warnings in the WebSocket.swift class: 

> 'characters' is deprecated: Please use String or Substring directly

Could you please fix them?
Also there is an annoying issue everytime I install Starscream, it is already described [here](https://github.com/daltoniam/Starscream/issues/431).

Regards, Olga

**Comment by daltoniam** [comment]
Version 3.0.3 has just been released with a resolution!
