### ISSUE TITLE
timeout is not working

### ISSUE THREAD

**Issue by cnliusen** [daltoniam/Starscream#439]
I set the connection timeout using the following code. The `timeout` seems have not effect.
```swift
var request = URLRequest(url: url)
        request.timeoutInterval = 5
```

I looked at the library code and found [this part](https://github.com/daltoniam/Starscream/blob/6cb1c474e09b0a3aa60bcdc7553b570336d6a61a/Sources/WebSocket.swift#L660). It seems the stream is not actually disconnected.
```swift
stream.connect(url: url, port: port, timeout: timeout, ssl: settings, completion: { [weak self] (error) in
            guard let s = self else {return}
            if error != nil {
                //do disconnect
                return
            }
          ...
```

**Comment by daltoniam** [comment]
Great catch! This has been fixed in `3.0.4`! Thanks!
