### ISSUE TITLE
Your Install Instructions Don't Work

### ISSUE THREAD

**Issue by deusprogrammer** [daltoniam/Starscream#44]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/mmain/Library/Developer/Xcode/DerivedData/GoddamnIt-ckykmwrqrfjsapewtbzpncynxuuq/Build/Products/Debug/StarscreamOSX.framework/Versions/A/StarscreamOSX
  Reason: image not found

**Comment by deusprogrammer** [comment]
Am I perhaps just doing it wrong?  Does it not work for a command line app?  Does it have to be a Cocoa app?

**Comment by acmacalister** [comment]
I think it should work fine for command line apps.I would guess that error is from not having the framework being copied to your app bundle/binary. 

per the Swift framework norm, you can add a framework to the project like so:

In Xcode, navigate to the target configuration window by clicking on the blue project icon, and selecting the application target under the "Targets" heading in the sidebar. In the tab bar at the top of that window, open the "Build Phases" panel. Expand the "Link Binary with Libraries" group, and add Starscream.framework. Click on the + button at the top left of the panel and select "New Copy Files Phase". Rename this new phase to "Copy Frameworks", set the "Destination" to "Frameworks", and add Starscream.framework.

Also see #12 and #21

**Comment by deusprogrammer** [comment]
Thanks =).  I am new to Swift.  So excuse my inexperience.  I have it
working now.  Thanks again for such a wonderful API.

**Comment by acmacalister** [comment]
Awesome. Glad it worked for you. I'm going to update the README with the instructions above to remove any ambiguity.
