### ISSUE TITLE
only get messages back

### ISSUE THREAD

**Issue by NowyQuei** [daltoniam/Starscream#447]
hi

it looks like i get only msgs...
it doesnt detect pings or other things like data.
it shows me all answers as text.

any idea?

**Comment by daltoniam** [comment]
I don't know what you mean. I'd need more information to be able to assist, but by default the library handles responding to pings for you. Data shows up as outline in this method:
https://github.com/daltoniam/Starscream#websocketdidreceivedata

Also custom ping/pong control is found here:

https://github.com/daltoniam/Starscream#write-a-pong-frame
