### ISSUE TITLE
Library not found error

### ISSUE THREAD

**Issue by azamsharp** [daltoniam/Starscream#449]
I followed your instructions and I am still getting the same error. I am running a OS X terminal application. 
<img width="1096" alt="screen shot 2017-12-27 at 12 19 58 pm" src="https://user-images.githubusercontent.com/16604/34389645-7e24d2a6-eb00-11e7-97af-4876055a11a5.png">

**Comment by azamsharp** [comment]
<img width="869" alt="screen shot 2017-12-27 at 12 24 48 pm" src="https://user-images.githubusercontent.com/16604/34389739-0e474a58-eb01-11e7-8673-bb9d0ddfc457.png">

**Comment by daltoniam** [comment]
The error in the screenshot appears to be a different error than what you get when a framework is not found in an MacOS application. I use those instructions for all of my projects and it works as expected. That looks more like an issue with maybe conflicting dependencies? Anyway, I tested it out again with a  fresh MacOS app and it worked as expected. I'd maybe check you aren't trying to import Starscream through CocoaPods and directly import it?

**Comment by azamsharp** [comment]
Should I be using Cocoapods or not for importing the starsscream framework into my terminal iOS app

**Comment by azamsharp** [comment]
Can you make a video or something from SCRATCH showing how to add the framework to a terminal console app in iOS? This will benefit a lot of people. The instructions you gave are very confusing and results in different error as I have pasted in my original question.
