### ISSUE TITLE
Invalid http upgrade

### ISSUE THREAD

**Issue by RickSlot** [daltoniam/Starscream#45]
Hi,
I'm trying to connect to a socket but I get the following error:
```objective-c
websocket did disconnectError Domain=Websocket Code=1 "Invalid HTTP upgrade" UserInfo=0x7f83a8d11800 {NSLocalizedDescription=Invalid HTTP upgrade}
```

I try to connect using the following code:
```objective-c
var socket = WebSocket(url: NSURL(scheme: "http", host: "localhost:8080", path: "/socket")!)
socket.delegate = self
socket.connect()
```

Any idea what the problem is or what causes this error?
Thanks in advance!

**Comment by RickSlot** [comment]
Never mind, the error was due to a server error!

**Comment by daltoniam** [comment]
Awesome. Glad to hear you got it sorted out.

**Comment by shawnmitchell** [comment]
Rick, can you comment on the nature of the server error, I'm seeing the same thing. Thanks in advance.

**Comment by Struki84** [comment]
I have the same error, the error messaged doesn't really explain much, and google is prity thin about it, so any information is welcome.

**Comment by ShGup** [comment]
@RickSlot  
Hi Rick, 
I am also facing the same error. Could you tell us what was the issue you faced at server.

**Comment by ShGup** [comment]
Nevermind. I figured out I was not passing Auth headers in the request needed by the server. That did it
