### ISSUE TITLE
ERROR: 404 Invalid HTTP upgrade

### ISSUE THREAD

**Issue by Meniny** [daltoniam/Starscream#450]
I'm using this library, but I just can't connect to the server (`ws://*******.***.mobi/ws`)

```swift
import Starscream
```

```swift
private var socket: WebSocket?
```

```swift
let url = URL(string: host)!
var request = URLRequest(url: url)
request.timeoutInterval = 30
//request.httpMethod = "POST"
        
if let token = ...,
    let regionCode = Locale.current.regionCode,
    let languageCode = Locale.current.languageCode {
    request.setValue(token, forHTTPHeaderField: "APPINFO")

    request.setValue(regionCode + ", " + languageCode, forHTTPHeaderField: "Accept-Language")
    request.setValue("http://com.****.mm.websocket", forHTTPHeaderField: "origin")
}
        
self.socket = WebSocket(request: request)
self.socket?.delegate = self
```

then:

```swift
self.socket?.connect()
```

this is the error info:

```swift
// websocketDidDisconnect(socket:error:)
- "Optional(Error Domain=WebSocket Code=404 \"Invalid HTTP upgrade\" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})"
```

in the function `private func validateResponse(_ buffer: UnsafePointer<UInt8>, bufferLen: Int) -> Int`  at `WebSocket.swift: 847`:

```swift
Printing description of str:
"HTTP/1.1 404 Not Found\r\nServer: openresty/1.11.2.4\r\nDate: Tue, 09 Jan 2018 07:00:44 GMT\r\nContent-Type: text/plain\r\nContent-Length: 18\r\nConnection: keep-alive\r\n\r\n"
```

**Comment by daltoniam** [comment]
This is an issue with how you have your server setup or how you are connecting to it. 404 is the HTTP response for not find a resource, which means the /ws you are connecting to is not a WebSocket server resource or it is configured to reject the connection for some reason. I'd check over your environment, but this probably isn't an issue with Starscream as that looks like the right behavior for the information provided.

**Comment by Meniny** [comment]
@daltoniam thank you, you are right.
