### ISSUE TITLE
Advice on dealing with the Swift 4 "Simultaneous Access" error

### ISSUE THREAD

**Issue by astoeckley** [daltoniam/Starscream#451]
Because socket messages arrive asynchronously and sometimes simultaneously, I'm getting crashes because messages are simultaneously modifying and reading the same data in my app -- this is a new thing in Swift 4.

Starscream has a delegate method `websocketDidReceiveData` that is the only method where incoming data arrives; I wrapped the contents of its body in `DispatchQueue.main.async { ... }` with the hope that this would queue up processing on the main thread and avoid this problem, but doesn't make a difference.

Do you have advice on how to handle this sort of thing with async socket messages?

**Comment by daltoniam** [comment]
Hm, not sure what to say about this. All of the delegate methods by default dispatch to the main queue, so you shouldn't have an issue with access on the delegate methods (write and connect calls should be done in a thread safe matter though). Maybe you should try adding all your received data and the calls to update that same to an OperationQueue and process it as to avoid the race conditions you are experiencing?

**Comment by waruss321** [comment]
Is there a way to make star scream work with Completion handlers?
