### ISSUE TITLE
Connect error callback

### ISSUE THREAD

**Issue by sacOO7** [daltoniam/Starscream#453]
If I am trying to connect to wrong url or if server is down for the url, it should generate connect error callback. It will be really helpful if you can add this functionality. Thank you 👍

**Comment by daltoniam** [comment]
It does do this. You might be see an issue with the timeout that has been fixed in version 3.0.4. Upgrading to that should fix the issue, but Starscream is using the NSStream API which does report connection failures.

**Comment by jbarros35** [comment]
How to do that?
