### ISSUE TITLE
Didn't call callbackQueue.async

### ISSUE THREAD

**Issue by seQVAER** [daltoniam/Starscream#456]
<img width="959" alt="2018-01-22 14 52 43" src="https://user-images.githubusercontent.com/17088535/35221746-f623a77c-ff83-11e7-9673-574e29e98f2d.png">

Please check image, we use Parse and Sashido. It is working fine but some times if low connection internet we lost observer. 
We found out that problem on screen. 
Callback called but line 1168 didn't call, it just go to 1172.

Do you have any suggestions how we can fix it?

Thanks a lot

**Comment by acmacalister** [comment]
There isn't much to go off here, but since that is an async call, that block is getting scheduled to run on the callback queue and it will continue execution. That is a fundamental of how parallel ("multithreaded") code works. If your delegates aren't getting called for some reason, you need to check to sure either queue isn't being over taxed or something isn't falling out of scope.

**Comment by viralplatipuss** [comment]
I know this is closed, but wanted to share my solution in case it helps anyone else:

I was using Starscream inside Vapor (swift webserver).

Vapor blocks the main thread to keep the server alive, so the block will never be executed.

Try chaining the callbackQueue:

`socket.callbackQueue = DispatchQueue(label: "websocket")`

Worked for me. Just don't forget your callbacks will now be running on a different thread!

**Comment by kingkangyu** [comment]
> I know this is closed, but wanted to share my solution in case it helps anyone else:
> 
> I was using Starscream inside Vapor (swift webserver).
> 
> Vapor blocks the main thread to keep the server alive, so the block will never be executed.
> 
> Try changing the callbackQueue:
> 
> `socket.callbackQueue = DispatchQueue(label: "websocket")`
> 
> Worked for me. Just don't forget your callbacks will now be running on a different thread!

thank u ,it helps me a lot

**Comment by viralplatipuss** [comment]
@kingkangyu - by the way, if you are using Starscream in Vapor, be aware that it will not run on linux. Only on Mac.

I ended up switching to using Vapor's own websocket library, which will then work on both Linux servers and MacOS: https://github.com/vapor/websocket-kit
