### ISSUE TITLE
Feedback: Don't change error handling between minor patch versions

### ISSUE THREAD

**Issue by kharmabum** [daltoniam/Starscream#457]
Between 3.0.2 and 3.0.4 you adjusted how error handling behaves in this library:

- 3.0.2 // `NSError` based // https://github.com/daltoniam/Starscream/blob/3.0.2/Sources/WebSocket.swift#L248
- 3.0.4 // `WSError` based // https://github.com/daltoniam/Starscream/blob/3.0.4/Sources/WebSocket.swift#L54

Maybe I was doing error handling inappropriately but in my view this was a very significant API change and ought to have been incorporated in a major release. 

If you could demonstrate how one would access the error code between these versions without rewriting code I would be very interested/appreciative.

**Comment by kharmabum** [comment]
I appreciate the fact that this was documented in the CHANGELOG.md. It should have inspected more carefully before updating.

**Comment by acmacalister** [comment]
In general you are right. It didn't previously work in all edge cases, so since it sort of a bug fix, we did just a patch. Sorry if it caused some headaches for you. We are using Swift enums for errors, which I think should be a lot nicer.
