### ISSUE TITLE
"Invalid HTTP Upgrade"

### ISSUE THREAD

**Issue by mvoccola** [daltoniam/Starscream#459]
I am Parse / ParseLiveQuery and started receiving the following error yesterday. Parse LiveQueries do not seem to be functioning properly.

`ParseLiveQuery: WebSocket did disconnect with error: Optional(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 200))`

Unfortunately, I don't have a terribly extensive background working with this type of framework, so any help is appreciated. The project is a Swift 4 project with Parse Server hosted on Back4App. I have tried switching from Parse Server 2.6.5 to 2.7.1 with no solution.

**Comment by acmacalister** [comment]
ParseLiveQuery uses it's own protocol on top of WebSockets. In fact, they appear to use Starscream under the hood. I would suggest using their library.

https://github.com/parse-community/ParseLiveQuery-iOS-OSX
