### ISSUE TITLE
Change naming 

### ISSUE THREAD

**Issue by jethmalani** [daltoniam/Starscream#460]
Would you ever consider changing the declaration of `Websocket` to a different name? It is a very common name and it conflicts with other pods. I am having issues when using it in the same project as https://github.com/pusher/pusher-websocket-swift

**Comment by acmacalister** [comment]
Not really. Pusher uses Starscream under the hood, so if you need to use both for some reason, I couldn't see why you couldn't just call the class directly from pusher's library.
