### ISSUE TITLE
Multipath interactive mode: websockets doesn't work with Wi-Fi without internet connection

### ISSUE THREAD

**Issue by iSevenDays** [daltoniam/Starscream#464]
Websockets doesn't work when iPhone has both WiFi and 3G enabled and connected, but WiFi router has no internet connection.
Steps to reproduce
1. Enable 3G
2. Enable Wi-Fi
3. Connect to router Wi-Fi with stable internet connection
4. Open any test application with Starscream
5. Get the internet cable out of Wi-Fi router
6. See websocket is disconnected and never reconnects

Usual standard REST requests that use .intereactive multipath mode works fine.

I found that your issue may be related to usage of c sockets, but seems you don't use POSIX sockets.
https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/CommonPitfalls/CommonPitfalls.html

Is there any way I can switch my connection from Wi-Fi without internet connection to 3G with a good internet connection?
Ideally, it should be done automatically.

Thanks

**Comment by iSevenDays** [comment]
NSURLSessionStreamTask uses URLSession, a session can use .intereactive multipath mode

**Comment by acmacalister** [comment]
This sounds like a reachability issue, which has already been discussed on #401. You will need to implement Apple's Reachability APIs and handle whatever your app's reconnection logic when that happens.
