### ISSUE TITLE
objc_msgSend Crash

### ISSUE THREAD

**Issue by SanjithKanagavel** [daltoniam/Starscream#468]
We are using **Socket.IO-Client-Swift** in our app. 

We are facing some weird crash in the following code in WebSocket.swift in **StarscreamSocketIO** framework.

##  **Crash Details 1:** 

```
private var canDispatch: Bool {
        readyToWriteMutex.lock() -> Crashing here
        let canWork = readyToWrite
        readyToWriteMutex.unlock()
        return canWork
}
```

**Version of frameworks :** 
  - Socket.IO-Client-Swift (11.1.3):
    - StarscreamSocketIO (~> 8.0.5)
  - StarscreamSocketIO (8.0.7)

**Crashed on : iPhone 7 (Model 1660, 1778, 1779, 1780) iOS 11.2.5 (15D60)**

<img width="1136" alt="screen shot 2018-02-20 at 12 08 03 pm" src="https://user-images.githubusercontent.com/9746842/36410458-19c2a664-1637-11e8-9327-ae0ccce9aba2.png">

##  **Crash** Details 2:

```
Exception name: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
1 libobjc.A.dylib objc_msgSend + 110448
2 StarscreamSocketIO 4308633324 + 132844
3 StarscreamSocketIO 4308576512 + 76032 
4 CoreFoundation _signalEventSync + 498320
5 CoreFoundation ___signalEventQueue_block_invoke + 962332
6 libdispatch.dylib _dispatch_call_block_and_release + 4600
7 libdispatch.dylib _dispatch_client_callout + 4536
8 libdispatch.dylib _dispatch_queue_serial_drain + 62424
9 libdispatch.dylib _dispatch_queue_invoke + 18848
10 libdispatch.dylib _dispatch_queue_override_invoke + 63700
11 libdispatch.dylib _dispatch_root_queue_drain + 70472
12 libdispatch.dylib _dispatch_worker_thread3 + 69800
13 libsystem_pthread.dylib _pthread_wqthread + 4764
```

We couldn't try to reproduce it. Please suggest some steps so to avoid this crash in future.

**Comment by acmacalister** [comment]
As with the other issues that have screenshots and parts of a backtrace, this doesn't really give us anything to go off. There are numerous things that could could cause a crash like this. My suggestion  would start by reviewing if you have an potentially racy code in your app, as Starscream is not thread safe.
