### ISSUE TITLE
Tried everything and nothing is working for a Console App for Mac

### ISSUE THREAD

**Issue by azamsharp** [daltoniam/Starscream#470]
The instructions are either incomplete or wrong. This library cannot be used in a Mac Command Line Tool. Here is the error I am getting: 

<img width="788" alt="screen shot 2018-02-20 at 9 00 51 pm" src="https://user-images.githubusercontent.com/16604/36461056-37c5b9ae-1681-11e8-9318-3db4cdffb4eb.png">

Can you make a video or something that uses the framework with the macOS Command Line Tool.

**Comment by acmacalister** [comment]
Those instructions are for regular apps, which are app bundles. MacOS command line apps, don't have app bundles, so those instructions wouldn't work. I would suggest looking over an article like this one below on how to set frameworks up for command line app.

https://www.swiftbysundell.com/posts/building-a-command-line-tool-using-the-swift-package-manager

This isn't an issue specifically an issue with Starscream, but how you configure frameworks with a command line app. You might also consider just copying the source if versioning isn't an issue.
