### ISSUE TITLE
WebSocket with Proxy wss

### ISSUE THREAD

**Issue by DorkisIT** [daltoniam/Starscream#475]
Hi, I have a problem with websoket behind proxy. 
I try do it 

```
            var request = URLRequest(url: url);
            request.timeoutInterval = 5;
            
            let stream = FoundationStream();
            stream.enableSOCKSProxy = true;
            
            socket = WebSocket(request: request, stream: stream);
            socket.enabledSSLCipherSuites = [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,     TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256];
            socket.delegate = self;
```

on connect method receive this error 

Printing description of error:
Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}

Thanks very much.

**Comment by acmacalister** [comment]
This doesn't give us much to go off. Are you sure it is a socks proxy? Maybe try and run a packet capture to debug what is going on here. Other than the basic socks proxy stuff, Starscream still has an outstanding PR for more robust proxy support.
