### ISSUE TITLE
pid 359 (EShop) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled

### ISSUE THREAD

**Issue by 350541732** [daltoniam/Starscream#477]
pid 359 (EShop) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
how to fix this warnning

**Comment by acmacalister** [comment]
Sounds like you have an issue in your MacOS not having properly configured sandbox entitlements. This isn't a Starscream issue. You can read about App sandbox here:

https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html#//apple_ref/doc/uid/TP40011183-CH1-SW1
