### ISSUE TITLE
Socket disconnected when send any data or string

### ISSUE THREAD

**Issue by MuhammadAhmedBaig** [daltoniam/Starscream#478]
hey,
I have face a problem, i successfully connected to socket but when i try to send any data, or string to socket it immediately disconnects, and return me this error.
 

> WSError
>   - type : Starscream.ErrorType.protocolError
>   - message : ""
>   - code : 1000

**Comment by acmacalister** [comment]
Code 1000 is a normal closure error. The first thing to verify is that you are retaining your socket object so it isn't falling out of scope. The second is to verify that the WebSocket server is sending proper WebSocket framing for messages.
