### ISSUE TITLE
websocketDidWriteError not used

### ISSUE THREAD

**Issue by nicolasbigot** [daltoniam/Starscream#48]
It seems that the delegate method `websocketDidWriteError` isn't used (nor called) across the whole `WebSocket.swift` implementation. 
To avoid confusion and missing features, it should be removed from the `WebSocketDelegate` protocol declaration. 
Another option would be to mark it as `optional` (since it is currently mandatory to be implemented in delegate object but never called) but this wouldn't solve the 'missing feature' issue.
What do you think?

**Comment by daltoniam** [comment]
I agree and vote we just remove it. It appears to be something that was carried over from jetfire and got replace by the `disconnect` delegate method at some point. Thanks for pointing it out.
