### ISSUE TITLE
How to send Mattermost authentication headers to check whether the socket is connected successfully using Starscream library?

### ISSUE THREAD

**Issue by machoasif** [daltoniam/Starscream#483]
I need to check whether the socket connection established successfully. In order to verify that how to send the following mattermost authentication header over the connection?

> { "seq": 1, "action": "authentication_challenge", "data": { "token": "mattermosttokengoeshere" } }

How can I verify that the socket is connected successfully in my project.

**Comment by machoasif** [comment]
@daltoniam please suggest me an answer

**Comment by daltoniam** [comment]
I'm sorry, but I'm not sure what you are asking. See the docs if you want to send custom headers:
https://github.com/daltoniam/Starscream#custom-headers

By the look of that, you just need to send some JSON over a WebSocket. For that, you need to just create a JSON String and send it via the `write` method.
https://github.com/daltoniam/Starscream#write-a-string-frame

Also looked at closed issues. This has been asked before: #283
