### ISSUE TITLE
Can you please give an example of an optional completion header?

### ISSUE THREAD

**Issue by Jeremy-Kotai** [daltoniam/Starscream#485]
I can't seem to get the optional completion header to work for:

open func write(string: String, completion: (() -> ())? = default)

I need to be able to receive a response from the websocket.

**Comment by daltoniam** [comment]
That completion closure is just for when a write finishes sending. You can see the server response here:

https://github.com/daltoniam/Starscream#websocketdidreceivemessage
https://github.com/daltoniam/Starscream#websocketdidreceivedata
https://github.com/daltoniam/Starscream/tree/master/examples/SimpleTest
