### ISSUE TITLE
No shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by admeister** [daltoniam/Starscream#486]
Trying to install Starscream v3.0.4 with Carthage and getting the following errors:

```
*** Skipped building common-crypto-spm due to the error:
Dependency "common-crypto-spm" has no shared framework schemes for any of the platforms: iOS

*** Skipped building zlib-spm due to the error:
Dependency "zlib-spm" has no shared framework schemes for any of the platforms: iOS
```

Xcode project still seems to build ok though once Carthage has finished.

**Comment by Bersaelor** [comment]
Same warning here. It then proceeds to work locally but it still fails when run on remote build systems.

**Comment by rckoenes** [comment]
Are you using `Socket.io-client-swift`? It seems that updating to "v13.1.2" stying on "v13.1.1" does not seem to give the error.

**Comment by hayashikun** [comment]
I've failed to install. I think this is because Carthage 0.29.0.
I downgraded to Carthage 0.28.0 and so I could build.

**Comment by Bersaelor** [comment]
@rckoenes Nah, we're using https://github.com/davidstump/SwiftPhoenixClient which depends on `StarScream`.

What worked for us was the following:
After every `carthage update` we delete the `SSCZLib` and `SSCommonCrypto` modulemap entries in
`./Carthage/Checkouts/SwiftPhoenixClient/Example/Pods/Starscream/zlib`.

Also we added `$(SRCROOT)/Carthage/Checkouts/Starscream/zlib/` under `Swift Compiler - Search Paths` -> `Import Paths` in the Project Build Settings.
