### ISSUE TITLE
It is possible to inspect Starscream traffic with Charles Proxy

### ISSUE THREAD

**Issue by CRoig** [daltoniam/Starscream#487]
I am trying to the debug Starscream socket connection with Charles Proxy but I can't find the transactions. There is any extra configuration needed to expose the traffic.

**Comment by daltoniam** [comment]
There shouldn't be anything else that needs to be done. Charles is a proxy and should sit in between and capture all of the traffic on the socket. I'm not sure if Charles decodes the WebSocket frames or not, but it should see the traffic regardless if it reads it or not. Also I found this:

https://stackoverflow.com/questions/33090087/how-to-inspect-websocket-traffic-with-charlesproxy-for-ios-simulator-devices

**Comment by dai-cb** [comment]
I am having the same issue. @CRoig did you solve this?

**Comment by RobertGummesson** [comment]
Same here. :(

**Comment by Ricardo1980** [comment]
Use Wireshark

**Comment by srgevipr** [comment]
> Use Wireshark

Wireshark doesn't give you any information since it encrypted channel (https, wss). As for me the  question is: "Do Starscream use System Proxy settings?"

**Comment by gsabran** [comment]
I'm able to use Charles Proxy correctly with Starcream
