### ISSUE TITLE
Normal closure status code returned as .protocolError type

### ISSUE THREAD

**Issue by jensgrud** [daltoniam/Starscream#488]
In WebSocket.swift, lines 1009-1020 the normal closure with status code 1000 is potentially returned as an error with type .protocolError on disconnect - is this intentional/expected behavior?

**Comment by daltoniam** [comment]
That is a good point. It use to just return the code, but now it has a type. There should probably be a new type of "everything is ok" of that error codes since 1000 is normal with a connectionClose frame.

**Comment by acmacalister** [comment]
This should be addressed in #653. We now send a 1000 normal with a "closed" event as opposed to an error.
