### ISSUE TITLE
Question: Shouldn't websocketDidDisconnect be called if the remote device hosting the socketServer reboots?  

### ISSUE THREAD

**Issue by chadham** [daltoniam/Starscream#489]
Am creating a web socket to an ESP8266 MCU. Connection happens successfully, data is sent and received correctly, but when the MCU reboots, (and therefore the socket is killed from its end), the delegate didDisconnect method is not called. I've used TCP Sockets, and there its possible to know once a socket has been terminated at the other end so am assuming the same should work here, but am new to the world of web sockets so am not sure if this a gap in my understanding on an issue.

Would appreciate clarification on this. 

Thanks.

**Comment by daltoniam** [comment]
This was brought up in #401. It should do the disconnect delegate once the system realize the socket has been disconnect. The connection and disconnect works similar to a TCP socket (obviously built off of it). Basically the NSStream object never notifies the caller until later. The best way to handle this is with the reachability APIs.

See #401 for more info on all the detail about it.
