### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wentao** [daltoniam/Starscream#49]
I was looking at this library, and would like to suggest a few changes to the API.

First, I think it makes sense to add an API to let the user to choose which queue to dispatch_async the delegate methods. Right, it dispatches to the main thread. But sometimes, the networking might happen in the background entirely.

If that makes sense, I think the connect() method can be implemented in a way that it detects which queue (thread) it is executed, and by default to use that queue to dispatch delegate execution.

**Comment by daltoniam** [comment]
I could see the need for that. I would think the main queue it is on now is a good default, but being able to configure it could be useful in certain contexts. Could be something as simple as: 
```swift
var socket = WebSocket(url: NSURL(scheme: "ws", host: "localhost:8080", path: "/"))
socket.queue = myCustomQueue
//do other stuff....
```

**Comment by wentao** [comment]
Yes, having a property is helpful.

**Comment by daltoniam** [comment]
see #50
