### ISSUE TITLE
Is there any way to compare WebSocket and WebSocketClient?

### ISSUE THREAD

**Issue by alanywlee** [daltoniam/Starscream#490]
Dear Sir,

I have multiple websocket connections and all have different work. 
Therefore, error handling need to identify which socket is disconnected by remote.
In case of using delegate callback, parameter type is WebSocketClient but not WebSocket,
that make socket identification need a way to convert of make WebSocket and WebSocketClient to be compared.

Is there any way to compare WebSocket and WebSocketClient?

```
var m_ws:WebSocket?
func connect() {
        let socket = WebSocket(url: url!, protocols: [])
        socket.delegate = self
        m_ws = socket
}

func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        // confimred disconnected socket is specific connection
        if let ws = m_ws, ws == socket { // How to compare WebSocketClient and WebSocket?
            // do error handling
        }
    }
```

**Comment by daltoniam** [comment]
yeah, the WebSocket object isn't equatable. I would recommend to try casting and comparing the URLs or whatever you use to identify the different objects. Example:
```swift
guard let  ws = socket as? WebSocket else {return}
if let storedWS = m_ws, storedWS. currentURL == ws.currentURL { 
     // do error handling
}
```
