### ISSUE TITLE
Xcode 9.3 Carthage update fails

### ISSUE THREAD

**Issue by milanstevanovic** [daltoniam/Starscream#491]
Since updating to Xcode 9.3 (9E145) / Swift 4.1 (Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)) I am having a problem when trying to install Starscream through Carthage.

My Cartfile:
`github "daltoniam/Starscream"`

Upon running `carthage update --platform ios` this is what I get:
```
*** Fetching Starscream
*** Fetching common-crypto-spm
*** Fetching zlib-spm
*** Checking out zlib-spm at "1.1.0"
*** Checking out Starscream at "3.0.4"
*** Checking out common-crypto-spm at "1.1.0"
*** xcodebuild output can be found in /var/folders/77/v4xtnv9j7sxbvplzq1ln4yvc0000gn/T/carthage-xcodebuild.Ds6jru.log
*** Skipped building common-crypto-spm due to the error:
Dependency "common-crypto-spm" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/daltoniam/common-crypto-spm/issues/new
*** Skipped building zlib-spm due to the error:
Dependency "zlib-spm" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/daltoniam/zlib-spm/issues/new
*** Building scheme "Starscream" in Starscream.xcodeproj
```

**Comment by glennrfisher** [comment]
This seems to be fixed with the changes in #461. Any chance you could publish a release, @daltoniam, to make those changes easily accessible with Carthage?

### Workaround

In the meantime, you can update your Cartfile to point to the merge commit for those changes:

```
github "daltoniam/Starscream" "31f522155a4d6323cd1aaefb8dbc140ced7be1ca"
```

Or if you're willing to be a bit risky as new releases are published, you could point your Cartfile to the `master` branch:

```
github "daltoniam/Starscream" "master"
```

Either way should resolve the Carthage warnings:

```
Glenns-MacBook:swift-sdk glennrfisher$ carthage update --platform iOS
*** Checking out Starscream at "31f522155a4d6323cd1aaefb8dbc140ced7be1ca"
*** xcodebuild output can be found in /var/folders/ht/_1xwgf3s0ml1ghzg8tmzhly00000gn/T/carthage-xcodebuild.2nQsSm.log
*** Building scheme "Starscream" in Starscream.xcodeproj
Glenns-MacBook:swift-sdk glennrfisher$
```

**Comment by UnfairAdvantage** [comment]
This does resolve the warnings, but then it doesn't even checkout zlib-spm and common crypto, so it doesn't work...

**Comment by daltoniam** [comment]
Version 3.0.5 has been released. It has a Carthage fix #461.

**Comment by milanstevanovic** [comment]
@daltoniam Thanks for the speedy update! 👍

**Comment by glennrfisher** [comment]
Awesome, thanks @daltoniam!
