### ISSUE TITLE
WebSocket.swift warning

### ISSUE THREAD

**Issue by olgadanylova** [daltoniam/Starscream#494]
Hi guys,
I'm using Xcode 9.3, Swift 4. And this warning occurs in the WebSocket class (line 125):
> warning: 'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions

Regards, Olga

**Comment by daltoniam** [comment]
Version 3.0.5 has been released. It removed the `weak` and should fix this warning.
https://github.com/apple/swift-evolution/blob/master/proposals/0186-remove-ownership-keyword-support-in-protocols.md
