### ISSUE TITLE
Release changelog missing

### ISSUE THREAD

**Issue by ergunkocak** [daltoniam/Starscream#495]
Hello,

Release change log can be like : https://github.com/Alamofire/Alamofire/releases 
but it is like : https://github.com/daltoniam/Starscream/releases

**Comment by daltoniam** [comment]
👍. I haven't looked into what it would take to do that. PR is welcomed. You can also see all the changes in the CHANGELOG: https://github.com/daltoniam/Starscream/blob/master/CHANGELOG.md
