### ISSUE TITLE
Headers Causing Problems

### ISSUE THREAD

**Issue by Mahan3340** [daltoniam/Starscream#496]
Hi , when calling socket.connect() on server im getting this , its going as a get request its not pure websocket

```
GET / HTTP/1.1
Connection: Upgrade
Host: IP:6363
Origin: ws://IP:6363
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; server_max_window_bits=15
```
what may cause the problem ? how can i remove all headers ?

**Comment by yusufonderd** [comment]
I'm facing same issue.

**Comment by daltoniam** [comment]
You need the headers to connect to a WebSocket server. The main advantage of WebSocket is they use HTTP to "upgrade" the connection so it can work over the same port/system/server as HTTP. Are you trying to Starscream as a normal TCP/IP socket?

**Comment by acmacalister** [comment]
You have to have those headers to start a WebSocket connection as defined in RFC6455.
https://tools.ietf.org/html/rfc6455#section-1.3 
You can already set additional custom headers in Starscream. 

 If you are just wanting to write random data, you can use a plain TCP socket. There are numerous resources online for how to get started with that.
