### ISSUE TITLE
Asynchronous creation of `WebSocket`: Callbacks don't fire

### ISSUE THREAD

**Issue by bredfield** [daltoniam/Starscream#497]
The websocket functionality that I'm implementing requires pulling the URL from an authenticated endpoint. I'm struggling to come up with a pattern that enables the WebSocket object to remain in scope. Example:

```swift
class Example {
  var socket: WebSocket? = nil

  init() {
    AuthManager.getSocketURL() { [weak self] socketURL in 
      self?.socket = WebSocket(url: socketURL)
      self?.socket.onConnect = {
         // not called, socket falls out of scope
      }
      self?.socket.connect()
    }
  }
}
```

Is there a good pattern for keeping the WebSocket in scope whilst also avoiding retain cycles?

**Comment by marksiu** [comment]
Hi, @bredfield 
you can check this post for detail
https://stackoverflow.com/questions/45704034/starscream-swift-connecting-to-localhost-socket-does-nothing

when you create the var `socket`, it cannot be nil, it needs to put sth when you init that value.

**Comment by daltoniam** [comment]
Thanks @marksiu. Also see the example applications and the Swift manual on scope management. Starscream should behavior like any other object so any normal Swift memory pattern should work. 

From your example, you would need to keep the instance of the `Example` object in scope, else Starscream will fall out of scope then be disconnected. Hope that helps and best of luck!
