### ISSUE TITLE
Move disconnect functionality to background thread

### ISSUE THREAD

**Issue by rickydamelio** [daltoniam/Starscream#500]
It appears that disconnecting a socket runs on the main thread, but connections are made asynchronously? Is this intentional, and if so, why? It seems like a bit of a susceptibility to intentionally block this thread.

> Thread 0 name:  Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib        	0x00000001811340f0 __psynch_cvwait + 8
> 1   libsystem_pthread.dylib       	0x000000018124ef74 _pthread_cond_wait$VARIANT$armv81 + 624
> 2   Foundation                    	0x0000000181ff35b0 -[__NSOperationInternal _waitUntilFinished:] + 776
> 3   Foundation                    	0x0000000181f803b8 -[NSOperationQueue waitUntilAllOperationsAreFinished] + 252
> 4   Silverlake_iPhone             	0x0000000100fd30c0 WebSocket.disconnect(forceTimeout:closeCode:) + 3010752 (WebSocket.swift:212)
> 5   Silverlake_iPhone             	0x0000000100fe2808 WebsocketTransport.closeConnection() + 3074056 (WebsocketTransport.swift:42)

**Comment by fassko** [comment]
Hi @rickydamelio could you help us and come up with PR for this? Thanks!
