### ISSUE TITLE
How can i use in Fragmentation

### ISSUE THREAD

**Issue by wosxieez** [daltoniam/Starscream#505]
How can i use in Fragmentation（5.4），
i am not found any method in this case.

**Comment by daltoniam** [comment]
Starscream "fragments" messages by default when sending them. If the message happens to be large it will send it in chucks until the whole message is sent. If you want to have interleaved messages, that isn't apart of the base spec and would require extensions to be added.

**Comment by yuhanle** [comment]
> Starscream "fragments" messages by default when sending them. If the message happens to be large it will send it in chucks until the whole message is sent. If you want to have interleaved messages, that isn't apart of the base spec and would require extensions to be added.

How about receiving new response from server? Should I must use fragmentation? @daltoniam
