### ISSUE TITLE
EXC_BAD_ACCESS on objc_msgSend in _outputStreamCallbackFunc

### ISSUE THREAD

**Issue by ssokol** [daltoniam/Starscream#508]
I recently upgraded to 3.0.5 and have started getting an occasional crash in Starscream. It's possible but time consuming to reproduce: I have to let the app run for anywhere from several minutes to several hours before it occurs.

The error always occurs on the ```com.vluxe.starscream.websocket``` queue in ```libobjc.A.dylib`objc_msgSend:```, which appears to be called from ```CoreFoundation`_outputStreamCallbackFunc:```. Not much to go on. 

My app uses several sockets. I'm going to edit it to test one at a time and see if I can find a single entry. 

I've read elsewhere in the the issues for Starscream that you can't do much with the raw debugger output. If that's not the case - if it's useful to see the backtrace - please let me know and I can post it.

If anyone has seen this before or knows what I might be doing wrong, please let me know. 

Thanks!

Edited: had wrong version (4.1) listed. App is still Swift 3.

**Comment by luoqisheng** [comment]
same issue. In my case , the error occurs when `_inputStreamCallbackFunc`was called. It looks like the FoundationStream object became a wile pointer.  So whether FoundationStream.cleanup()  need to be called in FoundationStream.sharedWorkQueue.

**Comment by luoqisheng** [comment]
We have solved this problem by Calling cleanup() in sharedWorkQueue only. and set the handleQueue to a custom queue instead of mainqueue so that it would not hangs

**Comment by ssokol** [comment]
Finally getting back to this. @luoqisheng - do you happen to have a patch you could share?
