### ISSUE TITLE
doDisconnect does not call onDisconnect due to guard canDispatch else {return}

### ISSUE THREAD

**Issue by elmodos** [daltoniam/Starscream#509]
Environment: iOS 11, an instance of WebSocket with ```onDisconnect``` handler set.
```сonnect``` is called on main thread after small chain of async opertion started from ```appliction(didFinishLaunchingWithOptions:)```.

App functionality is made to try reconnect on disconnect and 50/50 of all app launches leads to onDisconnect not being called.

Debug shows that this guard check prevents it to be called:
```
File: WebSocket.swift
Method: doDisconnect(_ error: Error?)
Line: ~1287
Code: guard canDispatch else {return}
```

Var ```canDispatch``` depends on ```readyToWrite``` which is set to true in the end of 
```
initStreamsWithData(_ data: Data, _ port: Int)
``` 
and might not be true when ```completion``` is called **synchronuously** here: 
```
File: WebSocket.swift
Method: connect(url: URL, port: Int, timeout: TimeInterval, ssl: SSLSettings, completion: @escaping ((Error?) -> Void))
Line: ~197, ~200
Code: completion(WSError(type: .invalidSSLError, message: "Error setting ingoing cypher suites", code: Int(resIn)))
```

Thus it prevents app from handling failed connection and schedule delayed reconnect.

Possible solutions:
1. Call completion async.
2. Set ```self.readyToWrite = true``` before calling ```stream.connect()```.

**Comment by acmacalister** [comment]
This should be addressed in the refactor of #653
