### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by telenc** [daltoniam/Starscream#51]
Hello,

It is possible to automatically reconnect if the socket is disconnected ?

thk's

**Comment by daltoniam** [comment]
There isn't a property like `autoReconnect` per say, but it can be done by simply doing:

```swift
func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
socket.connect() //will reconnect on disconnect
}
```
This way you have control over when to reconnect, which is useful if you want to manually disconnect the socket or have another reason for the WebSocket to be disconnected.
