### ISSUE TITLE
Subscribe to a public channel

### ISSUE THREAD

**Issue by arkader** [daltoniam/Starscream#510]
Hello everyone,

I'm new to Starscream. 
I'm able to connect to a remote server without any issue, 
however, I would need to subscribe to a public channel. 

I don't see anything related to channel on the main documentation, 
could someone help me please?

ps: The backend is using:
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md

Thank you
--
Emal

**Comment by daltoniam** [comment]
The concept of channels aren't apart of the WebSocket RFC directly. I would recommend checking out [Socket.io]`https://github.com/socketio/socket.io-client-swift` or building your own channeling implementation over the top of WebSockets.
