### ISSUE TITLE
websocketDidDisconnect doesn't be called if [weak self] is nil

### ISSUE THREAD

**Issue by marksiu** [daltoniam/Starscream#512]
Testing version: `3.0.5` via pod install

Try to implement the `Starscream` as following, implement `WebSocketAdvancedDelegate`

```
class StarscreamViewController: UIViewController, WebSocketAdvancedDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        initWebSample()
    }
    
    func initWebSample() {
        
        let url: URL = URL(string: "wss://echo.websocket.org")!
        var request = URLRequest(url: url)
        request.timeoutInterval = 50

        let stream = FoundationStream()
        stream.enableSOCKSProxy = true

        let socket = WebSocket(request: request,            // problem in here, the var is not in class level
                           protocols: ["chat","superchat"],
                           stream: stream)
        socket.advancedDelegate = self
        socket.disableSSLCertValidation = true
        socket.enableCompression = false
        socket.connect()
        
    }
}
```

since the `socket` var is declared within `initWebSample`, `Starscream` should return `WSError.closeError`. However, `websocketDidDisconnect` doesn't be called.

The call sequence is
```
WebSocket.swift
line 488 - func connect() - [line 492] call createHTTPRequest()
line 569 - func createHTTPRequest() - [line 612] call initStreamsWithData(httpBody.data(using: .utf8)!, Int(port!))
line 634 - func initStreamsWithData() - [line 660] call stream.connect(url: url, port: port, timeout: timeout, ssl: settings, completion: {}
line 143 - func connect() - [line 223] return completion block with WSError.closeError to line 661 
```

Since the `[weak self]` already nil, it will only tigger return without anything, so no error will be returned to the delegate method.

attach the debugger call flow for reference.
<img width="1449" alt="screen shot 2018-05-09 at 11 25 03 am" src="https://user-images.githubusercontent.com/22641551/39794307-4207881a-537c-11e8-8f74-ea38a2baffc5.png">

**Comment by texuf** [comment]
Where do you expect the error to go if the websocket has been deallocated? You should be keeping a strong reference to the websocket instance from the calling code.
