### ISSUE TITLE
Propose to make the `WebSocket.write` operations cancellable

### ISSUE THREAD

**Issue by secretworry** [daltoniam/Starscream#513]
Hi,
I'd like to know why not make the write operation cancellable?
1. The write operation is implemented with `NSBlockOperation` and `OperationQueue`, so the writing requests are queued and cancellable
2. The actual writing block is implemented with cancellation-supported.
So just return the NSBlockOperation(or its superclass `NSOperation`) back to the invoker, will make the write operation cancellable.

My scenario is that when I was trying to wrap the `WebSocket` with RxSwift, which enables downstream to propagate disposing to upstream, I found the `WebSocket.write`, though cancellable,  prevents me from doing the cancellation.

I think its a good idea to let the invoker to make the decision.

**Comment by daltoniam** [comment]
I'm gonna close this out since the new 4.0.0 version remove the use of `OperationQueue` from the library (and it has been a long time). Any follow up question regrading that please open a new issue with the 4.0.0 changes. Thanks!
