### ISSUE TITLE
Code 400 : Invalid HTTP upgrade error

### ISSUE THREAD

**Issue by iOS-Development-iPC** [daltoniam/Starscream#514]
Hi,

I am running below code 

**let webSocket = WebSocket.init(url: URL(string: signallingUrl))
webSocket.connect()**

it gives below error while processHTTP function for connecting websocket and websocket disconnecting with error

**error code 400 : Invalid HTTP upgrade**

_Note : Same signallingUrl working with DotNet web app and websocket. So, signalling server and url is fine and it's a Xirsys singnalling host_

I am using Starscream latest version 3.0.5

Please checkout this issue and let me know.

**Comment by daltoniam** [comment]
There isn't enough here to help, but from what you are reporting your server is returning a HTTP 400 error. That means it is probably an issue with how you have your WebSocket server setup and isn't an issue with Starscream. I'd check your configuration of your server and see why it is returning a 400 error when the WebSocket on the client app attempts to connect.
