### ISSUE TITLE
Wrong  error._code for 403 error.

### ISSUE THREAD

**Issue by caravaneer404** [daltoniam/Starscream#515]
Hi guys. I face this problem after updating to swift 4 and latest Starscream. You replace `NSError?` with `Error?` in websocketDidDisconnect delegate and after this Xcode replace `error.code` on `error._code`. I have a code like this `error._code == 403` and it stop working, because for 403 `error._code` return 1

`▿ Optional<Error>
  ▿ some : WSError
    - type : Starscream.ErrorType.upgradeError
    - message : "Invalid HTTP upgrade"
    - code : 403
`

```
(lldb) po error._code
▿ Optional<Int>
  - some : 1

```

How to solve it?

**Comment by alexeichhorn** [comment]
Hi,
I found out that you can cast an Error into a WSError and get the code from that:
`(error as WSError).code`

I hope it will solve your problem.

**Comment by metisdev** [comment]
@caravaneer404 how did you solve the problem?
