### ISSUE TITLE
EXC_BAD_ACCESS when receiving large messages

### ISSUE THREAD

**Issue by cyphercommunications** [daltoniam/Starscream#52]
Starscream cannot process messages larger than 65536 characters.

Steps to reproduce:

1. Run nodejs ws server comprised of the following:

        var WebSocketServer = require('ws').Server,
            wss = new WebSocketServer({port: 8080 });

        wss.on('connection', function connection(ws) {
            ws.send(Array(65537).join('a'));
        });
        
2. Connect to server using Starscream
3. Crash should be triggered:
        
        EXC_BAD_ACCESS (code=EXC_ARM_DA_ALIGN, address={{ *address removed* }} )

**Comment by cyphercommunications** [comment]
Note, the above example functions as expected when sending the following message from the nodejs server
    Array(65537).join('a')

**Comment by cyphercommunications** [comment]
Thrown at line 464 of WebSocket.swift:

    if dataLength == 127 {
        let bytes = UnsafePointer<UInt64>((buffer+offset))
        dataLength = bytes[0].byteSwapped // <-- here
        offset += sizeof(UInt64)
	} else if dataLength == 126 {...

**Comment by daltoniam** [comment]
Interesting. The autobahn test suite runs through a large message test and Starscream passed last time I tested it. If you have it handy, what is the value of the `offset` variable? Also is `bytes` a valid pointer?

**Comment by cyphercommunications** [comment]
This may be speculation, but it appears to be related to iOS devices lacking a 64 bit processor, ie. anything prior to the iPhone 5S. I did not notice the crash on the iPhone 6, it was not until testing on an iPhone 5 with a Testflight build of an app, latest version of iOS for all.

offset: 2
buffer: 0x1562d968

Just another note, SocketRocket does not experience the same issue, messages > 2MB are delivered as expected.

**Comment by cyphercommunications** [comment]
and the EXC_BAD_ACCESS for that example was thrown when accessing 0x1562d96a

**Comment by daltoniam** [comment]
Alright thanks. Can you try one thing for me? Change out `byteSwapped` with `bigEndian` and see if that resolves the issue?

**Comment by cyphercommunications** [comment]
Can do, will try later today

**Comment by cyphercommunications** [comment]
No luck, unfortunately

![screenshot](https://cloud.githubusercontent.com/assets/10092236/6118272/cd899656-b070-11e4-88d1-cc3156dec95b.png)

**Comment by daltoniam** [comment]
well that is disappointing. I will try setting up my test WebSocket server for debugging and see what I can find. I am not totally certain on how the large packet size would be different versus the smaller sizes, but hopefully debugging will bring the answer.

**Comment by daltoniam** [comment]
I tested the latest code on an old iPad 2 and setup a test server (modified version of the ws-server.rb in the example folder) that sent back the same 65537 bytes. I wasn't able to reproduce the issue with the latest code. Is there any other information you can provide on how to possibly reproduce?

**Comment by cyphercommunications** [comment]
hmm, perhaps it's related to the node server's implementation (https://github.com/websockets/ws)

I will have to see if I can recreate the issue with the same ruby server you are testing with

**Comment by daltoniam** [comment]
Alright, yeah it might be. Here is the modified ruby code:

```ruby
require 'em-websocket'

EM.run {
  EM::WebSocket.run(:host => "0.0.0.0", :port => 8080) do |ws|
    ws.onopen { |handshake|
      puts "WebSocket connection open"
      puts "origin: #{handshake.origin}"
      puts "headers: #{handshake.headers}"

      ws.send "Hello Client, you connected to #{handshake.path}"
    }

    ws.onerror do |error|
      puts "[error] #{error}"
    end

    ws.onclose { puts "Connection closed" }

    ws.onmessage { |msg|
      puts "message from client: #{msg}"
      ws.send (0...65537).map { ('a'..'z').to_a[rand(26)] }.join
    }
  end
}
```

**Comment by daltoniam** [comment]
@cyphercommunications did you make any progress on this? Does it appear to be fixed with the latest code?

**Comment by cyphercommunications** [comment]
I will pull the latest and run the test case I have for it

**Comment by daltoniam** [comment]
Thanks, fingers crossed :smile:

**Comment by cyphercommunications** [comment]
looks good!
