### ISSUE TITLE
Stream is not disconnecting when `disconnect` is not called with any arguments

### ISSUE THREAD

**Issue by brian-dlee** [daltoniam/Starscream#526]
Looking at the `disconnect(forceTimeout, closeCode)` method, it doesn't look like it ever hits `disconnectStream(nil)` unless you supply a timeout to allow the disconnect to be asynchronous.

You can actually get the `default` condition to be met if you pass a non-positive number to `forceTimeout`. I'm assuming this is a bug. Should `disconnectStream` be called immediately when no `forceTimeout` is provided?

**Comment by brian-dlee** [comment]
If anyone else if being held up by this calling disconnect like this will work around the issue.

```swift
socket.disconnect(forceTimeout: -1, closeCode: CloseCode.normal.rawValue)
```

**Comment by brian-dlee** [comment]
I forked and went to perform the change for this, but it turns out this behavior is intentional per comments in the code. It looks like the WebSocket server is not honoring the close code in my case.

**Comment by daltoniam** [comment]
Addressed in PR above.
