### ISSUE TITLE
Physical iOS device 

### ISSUE THREAD

**Issue by weiFans** [daltoniam/Starscream#531]
**Specific error**
<img width="1033" alt="241321" src="https://user-images.githubusercontent.com/5456137/42924611-9419490e-8b5d-11e8-97ee-4d65f06a12b9.png">

**Build Phases**
<img width="904" alt="123123" src="https://user-images.githubusercontent.com/5456137/42924943-f10fed10-8b5e-11e8-8c92-611a46f613d0.png">

**Bitcode**
![b7d9e7f3-1e21-4e2c-931f-8d0e0805295e](https://user-images.githubusercontent.com/5456137/42924982-1a2c07e2-8b5f-11e8-8225-a157e98f1df6.png)

**Yes / No Will not work**

**What is the problem? thank you very much**

**Comment by daltoniam** [comment]
There isn't enough info to help here. You appear to have Starscream imported right, but you are showing that you are getting an error about bitcode. I'm not sure how your project settings are configured, but trying adjusting your bitcode settings and see if that fixes it.
