### ISSUE TITLE
charles traffic websocket not show

### ISSUE THREAD

**Issue by phpmaple** [daltoniam/Starscream#532]
#240  My Device is iOS11.3

**Comment by daltoniam** [comment]
Starscream doesn't have full proxy support yet (#202). Charles support isn't an issue with Starscream as you should just configure Charles to proxy all the connections on your device versus directly within Starscream.

**Comment by dai-cb** [comment]
@daltoniam any links / help on how to configure Charles properly? Have tried many variations, but sadly non work.
