### ISSUE TITLE
Why do I need full SSL certificate if I only want SPKI (Subject Public Key Info) pinning?

### ISSUE THREAD

**Issue by dannyhertz** [daltoniam/Starscream#533]
I am a bit of a security novice but I'd like to add SSL pinning to my Starscream implementation. Everything I've read suggests using SPKI and standard public key pinning at the least. I see there is an option for using public key pinning in the library but it needs a full cert for extracting it. Is there no way to simply provide that public key info without packagaing a full cert file (that will frequently expire) in the app bundle? 

Thanks for any help/wisdom!

**Comment by acmacalister** [comment]
The docs could definitely use love. We are working on some updates around the Networking and SSL Pinning currently, so stay tuned for those updates. In the meantime, you should be able to currently provide just the public key like so:

```swift
let publicKey = SecTrustCopyPublicKey(trust) // or wherever you obtain your SecKey from.
let cert = SSLCert(key: publicKey)
socket.security = SSLSecurity(certs: [cert], usePublicKeys: true)
```

**Comment by dannyhertz** [comment]
Ah wonderful. Thanks for the update!
