### ISSUE TITLE
Please version bump to 3.0.6

### ISSUE THREAD

**Issue by mgrant34** [daltoniam/Starscream#534]
This fix was recently merged in https://github.com/daltoniam/Starscream/pull/524

To access this fix in other dependencies, it would be awesome if you could release a minor version bump.

Thanks!

**Comment by daltoniam** [comment]
I know it has been a while, but this is coming soon!

**Comment by daltoniam** [comment]
There will be a 3.0.6 release and a 4.0.0 release for Xcode 10.

**Comment by fassko** [comment]
@mgrant34 version 3.0.6 released https://github.com/daltoniam/Starscream/releases/tag/3.0.6

Other stuff like @daltoniam already explain will be in 4.0.0 release.
