### ISSUE TITLE
Problem of sending text

### ISSUE THREAD

**Issue by KompoD** [daltoniam/Starscream#536]
Hello!
I successfully connected to WS server with ticket by link like `"ws://url/ws?ticket={ticket}"`.
But when I try to send text I don't receive any message in this delegate method 
`func websocketDidReceiveMessage(socket: WebSocketClient, text: String) {
        print("Received text: \(text)")
    }`
Can you help me?

**Comment by acmacalister** [comment]
You need to make sure the socket object is a property, so it doesn't fall out of scope. You can see this in the example code and docs here.

https://github.com/daltoniam/Starscream#example

**Comment by KompoD** [comment]
@acmacalister no, it was wrong model sent to the server.
But thanks for quick response! :)
