### ISSUE TITLE
How to use it with iOS 7?

### ISSUE THREAD

**Issue by vani2** [daltoniam/Starscream#54]
"embedded dylibs/frameworks are only supported on iOS 8.0 and later"
I think via source code directly? Please add update readme in that case.

**Comment by daltoniam** [comment]
You feel the docs are unclear? iOS 7 is source only support and to use it as a framework, you need iOS 8. Would a directly statement of "iOS 7 is source only" be ideal?

**Comment by vani2** [comment]
For iOS 7 I added as submodule, this is the best working solution.

**Comment by daltoniam** [comment]
:+1:
