### ISSUE TITLE
I do not receive events when I connect to the server

### ISSUE THREAD

**Issue by kimilpyoung** [daltoniam/Starscream#541]
hi, i have one issue

I connected to ws://ip:8188 but not called connect event
only called disconnect event with no err message

I dont know why this happens

 If you know why, please answer me.

thx..

**Comment by fassko** [comment]
@kimilpyoung Could you please share small example of this issue?

**Comment by thbaja** [comment]
It has been almost 8 months without an example. This issue should be closed.
