### ISSUE TITLE
Timed out waiting for the socket to be ready for a write

### ISSUE THREAD

**Issue by quanguyen** [daltoniam/Starscream#542]
Hi,

I websocket connect to my server with: `private let websocket = WebSocket(url: URL(string: "ws://<MY IP>:<MY PORT>")!)`

When the connection is disconnected, I retry it with the code below (`retry == true`):

```
func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        NSLog("ws disconnected: \(String(describing: error)) => retry: \(retry)")
        
        if retry {
            Timer.scheduledTimer(withTimeInterval: WSConstant.RECONNECT_INTERVAL, repeats: false, block: { [weak self] (_) in
                guard let strongSelf = self else { return }
                
                NSLog("reestablishing...")
                strongSelf.establish(retry: nil)
            })
        }
    }
```

But it raises this error:

`ws disconnected: Optional(Starscream.WSError(type: Starscream.ErrorType.writeTimeoutError, message: "Timed out waiting for the socket to be ready for a write", code: 0)) => retry: true`

Minimizing and maximizing app do not help (when my app is minimized, it disconnects from the server; and reconnects when it is maximized).

The connection is only restored when I kill the app and rerun.

What should I do to over come this`1writeTimeoutError`?

Thanks

**Comment by nyeu** [comment]
I have the same issue, did you manage to fix it @quanguyen ?

**Comment by deniskirillov** [comment]
+1, I have the same:(

**Comment by fassko** [comment]
> I have the same issue, did you manage to fix it @quanguyen ?
> 
> As a workaround I added a small delay to reconnect and seems to be working.

Hi @nyeu maybe you can help put with PR? Thanks!

**Comment by cnliusen** [comment]
Do you have multiple web socket connections?

**Comment by acmacalister** [comment]
I'm going to close this for now. If it comes up again in v4, we can reopen it.

**Comment by usama8981** [comment]
anybody gets solution?

**Comment by nyeu** [comment]
@usama8981 I made it work with this workaround:
> As a workaround I added a small delay to reconnect and seems to be working.
