### ISSUE TITLE
failed build as static framework

### ISSUE THREAD

**Issue by ichina** [daltoniam/Starscream#544]
i tried to build all carthage dependincies as static framework for reduce app launch time. the instruction for this [here](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md), but i got an error while build Starscream, its only one dependency, with error in my cartfile with above 20 deps

**Comment by fassko** [comment]
Hi @ichina can you please share precise commands you did and also what is the error? Thanks!

Also new version with zlib and CommonCrypto from system libs should improve the launch time.

**Comment by ichina** [comment]
found out it builds as static framework successfuly by carthage in modern way, which is available in carthage since 0.30.1 version. thanks
