### ISSUE TITLE
Support writing encodable objects to your current connection

### ISSUE THREAD

**Issue by Shanlon** [daltoniam/Starscream#545]
My backend uses django-channels where I needed to support writing JSON data. Currently, from what I saw this was only supported using strings/data/etc. I created a small helper function for sending Encodable objects to connected sockets. I think this might be helpful for the API to support.

```
extension WebSocket {
    /// Writes a encodable object over the current socket
    ///
    /// - Parameter encodable: The encodable object
    func write<T: Encodable>(encodable: T) {
        guard isConnected,
            let data = try? JSONEncoder(outputFormatting: .prettyPrinted).encode(encodable),
            let stringRepresentation = String(data: data, encoding: .utf8) else {
                return
        }
        
        write(string: stringRepresentation)
    }
}
```

**Comment by fassko** [comment]
Really good idea, I would like to use this as well.

Maybe chance for PR?

**Comment by mooshee** [comment]
I disagree that this needs to be part of the interface.  It already exposes a way to write a `String` or `Data`.  This piece of code assumes all of your Encodables use the default encoder options (mine don't).  It feels unnecessary.

**Comment by acmacalister** [comment]
extension seem like a fine solution to this and keeps the interface small (which is something we have always aimed for).
