### ISSUE TITLE
Type 'SignalClient' does not conform to protocol 'WebSocketDelegate'

### ISSUE THREAD

**Issue by Ivan411** [daltoniam/Starscream#548]
I have some problems - in SignalClient file
"Type 'SignalClient' does not conform to protocol 'WebSocketDelegate'"
http://joxi.ru/BA0Leg0HJw1zXA
Xcode want to add only
func websocketDidReceiveData(socket: WebSocketClient, data: Data)
But all protocol methods are implemented.
Can you help me please?

**Comment by thbaja** [comment]
Click on the button (red with white in the middle) and get some more details, and perhaps an automatic fix.

**Comment by ginppian** [comment]
my same case, I give in the fix button and a few moments later xcode sends me the same message again

**Comment by neilyoung** [comment]
Don't call it "WebSocketClient". This seem to clash with some Starscream stuff. Call it SocketClient and good
