### ISSUE TITLE
Question about validation logic

### ISSUE THREAD

**Issue by mbrandonw** [daltoniam/Starscream#549]
Looking at the source I found this:

https://github.com/daltoniam/Starscream/blob/70fd033db6d1d0300f900bd05fd05c1246eb721d/Sources/SSLSecurity.swift#L177-L188

and I'm curious why all of the certificates from the server are required to match one of the certificates provided. I was under the impression that it is sufficient for at least one of the certificates to match.

Is this logic correct?

Thanks!

**Comment by eliburke** [comment]
@mbrandonw The original behavior was to require the entire chain to be trusted. Like you, I am under the impression that only one cert needs to match. #412 added a boolean to control the behavior. If you set validateEntireChain=false, it will short circuit out of that loop. If any cert is trusted it will pass. (it's not super clear but a

**Comment by mbrandonw** [comment]
oh wow, that's it! I saw that option but didn't look further into it. Thanks for the help!

**Comment by eliburke** [comment]
I should add-- I left the existing behavior as default in the PR so that current Starscream users wouldn't suddenly have a change in their security model. I do think it should be the default behavior in a future major release such as 4.0 hint hint @daltoniam 😄
