### ISSUE TITLE
Socket overhead producing too much power consumption.

### ISSUE THREAD

**Issue by papley** [daltoniam/Starscream#550]
Any thoughts how we can keep an open socket and reduce power consumption?

First image shows socket ping every 3 seconds or so. No significant socket traffic.
![image](https://user-images.githubusercontent.com/1513087/44811782-825dbb80-aba3-11e8-84f2-969a4142c3fa.png)
Second image shows power consumption of app with socket open.
![image](https://user-images.githubusercontent.com/1513087/44811804-90abd780-aba3-11e8-9f6c-e71eaf472d9e.png)
Third image shows power consumption of app with socket disabled.
![image](https://user-images.githubusercontent.com/1513087/44811837-a02b2080-aba3-11e8-9c86-ba8baea7842c.png)

**Comment by papley** [comment]
As far as I can tell the vast majority of my application power consumption is a result of just having a socket open with no traffic except pings inherent to the socket implementation.

**Comment by flagoworld** [comment]
I have been using this library for some time now and I now believe that Xcode is very aggressive with its "energy impact" figures. I have noticed no significant battery drain when keeping the socket open for extended periods of time in practice. I believe apple is giving you this "data" mainly as a hint to make sure you are not doing any unnecessary processing over extended periods of time. I would take it as hyperbole, verify you aren't doing anything silly, and be on your merry way.

But I mean, that's just my 2¢ on this and I am sure there are much more informed people.

**Comment by tiwariammit** [comment]
Hey guys!
 How did you done https://github.com/daltoniam/Starscream/issues/671 task??

**Comment by mmdock** [comment]
Starscream 3.1.0 and I am seeing a lot of power consumption as well.  Not just me, but i have a number of users complaining about the chat portion of my company's app because of how quickly their battery dies when in chat.  This is mostly on SE and older phones (iOS 10 - iOS 13).

**Comment by siempay** [comment]
Having the same issue here, the energy impact is always *Height* even without doing anything.
