### ISSUE TITLE
Multiple connection communication issue

### ISSUE THREAD

**Issue by akiroz** [daltoniam/Starscream#551]
When there are 2 connections and one of them is connecting, the other connection cannot send / receive any data.

I suspect it has something to do with the `sharedWorkQueue` here but I'm not sure...
https://github.com/daltoniam/Starscream/blob/70fd033db6d1d0300f900bd05fd05c1246eb721d/Sources/WebSocket.swift#L137

**Comment by fassko** [comment]
Do you have any working example of this issue?

**Comment by akiroz** [comment]
I'll try to produce a minimal working project for this issue ASAP but I solved the problem in my production app by providing a custom queue: https://github.com/akiroz/Starscream/commit/be7c8bdcca4d62fe3c6febaf4958654f611d402d

**Comment by fassko** [comment]
@akiroz maybe here chance for PR?

**Comment by acmacalister** [comment]
Should be resolved in #653
