### ISSUE TITLE
Xcode 10, Apple Watch (arm64_32) minimum deployment

### ISSUE THREAD

**Issue by jordimele** [daltoniam/Starscream#552]
`This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`

You have to set the deployment target for all watchOS targets (although it says iOS) to 3.0 or higher..

By upload to App Store Connect we have one error to minimumOS deployment.

**Comment by fassko** [comment]
It's also tricky with watchOS because Network.framework isn't supported there. https://developer.apple.com/documentation/network
Most likely need to do some backwards compatibility there.

**Comment by jordimele** [comment]
The problem is in the definition of the podspec file, which is configured `s.watchos.deployment_target = '2.0'`

**Comment by fassko** [comment]
So it's too low version? I'm confused atm.

**Comment by jordimele** [comment]
In version 3.0.5 this is configured s.watchos.deployment_target = '2.0'.
I understand that in the xcode-10 development branch, watchOS will not be supported, eliminating the line from the podspec.
If this is correct, do we know what foresight is there?

**Comment by fassko** [comment]
Yeah, 2.0 is quite old. Maybe do a PR with this before xcode-10 changes are being merged?

**Comment by KeimyPlaza** [comment]
Maybe this error is only for Xcode10 but this library must be to supported Xcode 9.X

You can change the podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '3.0'
    end
  end
end
```
Reference: https://forums.developer.apple.com/thread/108408

**Comment by fassko** [comment]
Apple is fixing this bug itself. Meanwhile please use @KeimyPlaza solution.

https://forums.developer.apple.com/thread/108408
