### ISSUE TITLE
xcode 10 & Swift 4.2 Version

### ISSUE THREAD

**Issue by ergunkocak** [daltoniam/Starscream#557]
Fisrt of all thanks for great library. 

Will there be a new version for xcode 10 and swift 4.2? 

I see a branch named xcode 10. Will it be merged as a new version?

Best

**Comment by fassko** [comment]
I believe it's coming. Biggest issue is backwards compatibility as with Swift 4.2 we can use Network.framework. Just it doesn't support watchOS.

More info about it here: #521

**Comment by darecki** [comment]
can it be closed now?

**Comment by fassko** [comment]
@darecki Implementing Network.framework is still in works. But I guess this can be closed.
