### ISSUE TITLE
Set a timeout

### ISSUE THREAD

**Issue by ch4vi** [daltoniam/Starscream#56]
Sometimes a certain timeout for connection attempts is needed. Having a function to set the timeout of websocket be a good functionality.

**Comment by daltoniam** [comment]
I could see that in specific cases. To be clear, the timeout would just be used on connecting to a server? `NSStream` doesn't have a timeout property that I am aware of, but Pull Requests are welcomed.

**Comment by daltoniam** [comment]
I tested different connection possibilities that would make a timeout useful. Configs test where:

- Host doesn't exist
- Host isn't a WebSocket server
- Host is down. 
- Host is working properly

In all cases the socket responded in less than a second stating it could not connect. Is there a specific test case that would show the usefulness of the timeout?

**Comment by goki88** [comment]
Maybe I have a test case that would show a usefulness of a timeout. In my application I have this code below. I send a string to the Server and wait for response. The response time from the server is always variable. Therefore I implement a do while statement and wait until text is not nil. Otherwise I would work with an empty String.

           queue.addOperationWithBlock() {
                // do something in the background
                self.logData="{\"username\":\"\(username)\",\"password\":\"\(password)\"}"
                self.socket.writeString(self.logData)
                
                do {
                    //do nothing, wait for response
                } while (self.text=="")
                
                self.response=self.text //websocketDelegate method didReceiveMessage
                println("Login \(self.response!)")
                
                NSOperationQueue.mainQueue().addOperationWithBlock() {
                    // when done, update your UI and/or model on the main queue
                   if self.text == "true" {
                             //do something
                   }
                 }
              }

**Comment by daltoniam** [comment]
@goki88 thanks for the example. This would be something app specific, not something that we would want to implement in Starscream. For the use case above, I would use a `NSDate` or/and maybe a `NSTimer` to watch the wait time. It could be something like the timer fires every 1 or 2 seconds to see if the 10 seconds have elapsed then do the connection failure logic.

**Comment by ch4vi** [comment]
in my case it is for synchronous requests (with a loading label), 10 seconds is not long enough or sometimes too. Right now I'm using a timer, it was just an idea to a cleaner code.

**Comment by daltoniam** [comment]
Alright cool. I think the timer is going to be the best solution at this point. I am certainly open to Pull Requests, so please do open one if a cleaner solution that fits inside the library presents itself.
