### ISSUE TITLE
macOS - The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -72000.)

### ISSUE THREAD

**Issue by perpeer** [daltoniam/Starscream#561]
Hi,

I'm getting this error in macOS application. Do you have any idea for solution ?

![screen shot 2018-09-30 at 23 04 54](https://user-images.githubusercontent.com/6865708/46262097-49e43100-c505-11e8-8a6d-ee6f8821620c.png)

I tested this framework with iOS project and working very well. 

macOS Deployment Target: 10.10 to 10.14 (tested)
I installed framework with carthage package manager

**Comment by acmacalister** [comment]
It appears to have failed to make a TCP connection. That is all we can discern from that error.
