### ISSUE TITLE
Crash in FoundationStream.cleanup()

### ISSUE THREAD

**Issue by jincc** [daltoniam/Starscream#566]
When I was using socket.io.swift, a crash occurred, and the final stack was located in starscream. I suspect it might be a concurrency issue, and I can give good suggestions when I am in trouble.
<pre><code>
0   libobjc.A.dylib                 objc_msgSend + 16
specialized _VariantDictionaryBuffer.nativeUpdateValue(_:forKey:) (in Starscream) (<compiler-generated>:0)
WebSocket.WSResponse.__deallocating_deinit (in Starscream) (WebSocket.swift:0)
closure #2 in WebSocket.processResponse(_:) (in Starscream) (<compiler-generated>:0)
FoundationStream.cleanup() (in Starscream) (WebSocket.swift:249)
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
-[NSBlockOperation main] + 72
</code></pre>

**Comment by fassko** [comment]
Hi @jincc !

Do you have any example app? That could help a ton to pinpoint this issue. Thanks!

**Comment by jincc** [comment]
I am re-opening and closing the socket when switching between the front and the back. Is this related?
<pre><code>
- (void)didEnterBackground:(NSNotification *)_{
    if (self.status >= MTBLBCenterStatusConnecting) {
        [self close];
    }
}

- (void)didBecomeActive:(NSNotification *)_{
    if (self.status <= MTBLBCenterStatusDisconnected) {
        [self connect];
    }
}
</code></pre>

**Comment by jincc** [comment]
@fassko

**Comment by fassko** [comment]
Try to connect again only if you disconnect from the socket. I think there can be a race condition.
