### ISSUE TITLE
Callback to get reponseHeaders

### ISSUE THREAD

**Issue by vonox7** [daltoniam/Starscream#567]
When processing the HTTP response, I'd like to get the response headers that are processed in `validateResponse()`. In those headers, I have IDs that are generated by my loadbalancer to simplify debugging.
Please add a callback to handle this headers.

**Comment by fassko** [comment]
Hi @vonox7 !

Thank you for the feedback, maybe you can help out with PR for this? :)

**Comment by vonox7** [comment]
Already on it, I'll keep the same style is the recently made onPong PR.

**Comment by vonox7** [comment]
@fassko could you take a look at https://github.com/daltoniam/Starscream/pull/570 ?
Thanks!
