### ISSUE TITLE
set timeout if nothing receives within 10 sec

### ISSUE THREAD

**Issue by goki88** [daltoniam/Starscream#57]
Hi,

first of all I have to say nice framework.
I would like to know if I can set a timeout which shows me an error message. E.g. I send a string via websocket and wait for response. If nothing receives within 10 seconds I would like to show a message "Connection failed." or "Server unreachable". Can you help me at this point :D?

Thanks and best regards

**Comment by daltoniam** [comment]
Thanks. I may be misunderstanding your intend use case, but that doesn't sound like something you would use a WebSocket for. A WebSocket is meant to be persistent connection. Once you are connected to the WebSocket server it does a ping/pong to keep the connection alive. If you successfully make the connection to the server, writing a message shouldn't be an issue.

**Comment by goki88** [comment]
Thanks for your answer :D... This means I have to set a timeout for the connection. The variable "isConnected" has to be "true" within 10 seconds. Otherwise throw a timeout exception. Can you help me to implement this in your framework :S...

**Comment by daltoniam** [comment]
This seems to be similar to #56. I still think this would be outside the scope of a how a WebSocket works. I assume you have a WebSocket server that is up and running? It should report back in the `websocketDidDisconnect` almost immediately if it was unable to connect or gets disconnected for any reason. Basically you would connect as the example project shows, and when the `websocketDidDisconnect ` is trigger, print your message of "Connection failed"
