### ISSUE TITLE
How to listen the change of a string ?

### ISSUE THREAD

**Issue by FLGiOS** [daltoniam/Starscream#574]
How to listen the change of a string ?

like the method of socket.io 👍 
        [_client on:@"/topic/menu/apptop/8837" callback:^(NSArray* data, SocketAckEmitter* ack) {
     
        }];

**Comment by fassko** [comment]
@FLGiOS Can you please explain what did you mean with that? I'm a bit confused. Thanks!

**Comment by FLGiOS** [comment]
how to subscribe messages?

like this:

connect   "wss://www.9con.pru:8080/topcenter"

[client subscribeTo:@"/topic/menu/apptop/8837" headers:nil messageHandler:^(STOMPMessage *message) {
            NSLog(@"body = %@",message.body);
        }];

**Comment by fassko** [comment]
For Objective-C there is also it's counterpart https://github.com/acmacalister/jetfire

But where did you get this code from?
You need to instantiate Websocket with full URL like

```
let websocket = WebSocket(url: URL(string:"wss://www.9con.pru:8080/topcenter/topic/menu/apptop/8837")!)
socket.delegate = self
socket.connect()
```

If you want to set headers, please check https://github.com/daltoniam/Starscream#custom-headers
