### ISSUE TITLE
No such module 'CommonCrypto'

### ISSUE THREAD

**Issue by lkxiluo** [daltoniam/Starscream#575]
Use Cocoapods some error tips "No such module 'CommonCrypto'".
How to solve it

**Comment by fassko** [comment]
Hi @lkxiluo can you please explain more about the issue?

**Comment by manusaxena** [comment]
Error is coming in websocket.swift file

**Comment by Pro2005** [comment]
Thx a lot. Adding "pod 'Starscream', '<= 3.0.5'" solves my problem

**Comment by fassko** [comment]
I went to compromise to use system zlib and CommonCrypto instead of from modulemap.

**Comment by ResulticksInc** [comment]
Hi, I am facing same problem. But here I am using pod 'Socket.IO-Client-Swift', '~> 13.2.0' this has starscream 3.0.0 depndencies. When I update my pod with socket.io-client-swift version 13.2.0 by default this downloads the latest version of Starscream (3.0.6).  Kindly help me to fix this issue.

**Comment by Pro2005** [comment]
> Hi, I am facing same problem. But here I am using pod 'Socket.IO-Client-Swift', '~> 13.2.0' this has starscream 3.0.0 depndencies. When I update my pod with socket.io-client-swift version 13.2.0 by default this downloads the latest version of Starscream (3.0.6). Kindly help me to fix this issue. My xcode version is 9.4.1

Just add "pod 'Starscream', '<= 3.0.5'" to your podfile

**Comment by ResulticksInc** [comment]
Thank you Pro 2005. It fixed my issue. (y)

**Comment by bdtian** [comment]
i face the same problem, it fixed my issue using "pod 'Starscream', '<= 3.0.5'" works, my xcode is 9.4.1 and 'Socket.IO-Client-Swift', '~> 13.2.0'
thx
