### ISSUE TITLE
one connection for all app pages

### ISSUE THREAD

**Issue by sadeghrz** [daltoniam/Starscream#578]
hi guys
i'm new in IOS
can i have a something like Service in android to connect my websocket client in that and send event to all listeners in any page or i must have separate connection in any single page?

**Comment by fassko** [comment]
Unfortunately we don't have any Android support for this.

**Comment by sadeghrz** [comment]
oh sorry.
i just want to explain a example.
i mean something like android service in IOS for run code whole the app.
