### ISSUE TITLE
one connection for all app pages

### ISSUE THREAD

**Issue by sadeghrz** [daltoniam/Starscream#579]
hi guys
i'm new in IOS
can i have a something like android service in IOS to connect my websocket client in that and send event to all listeners in any page or i must have separate connection in any single page?

**Comment by ollitapa** [comment]
Maybe check out https://github.com/ReactiveCocoa/ReactiveSwift/#readme

**Comment by sadeghrz** [comment]
it's Third-party library, i think swift have a native solution because it's very important. it's not a idea to create and connect new connection in each page of app. is it?

**Comment by fassko** [comment]
Like @ollitapa mentioned you can set up one socket connection and then redirect events using RxSwift or ReactiveSwift. At least I'm doing similar stuff in Swift. You can open multiple sockets, but then it can be hard to manage that.

And please don't open new issues. Reopen old one and comment there. Thanks!

**Comment by ollitapa** [comment]
You can also make your own observer-listener stuff. Check out https://www.swiftbysundell.com/posts/observers-in-swift-part-2
