### ISSUE TITLE
is there something like didPingRecieve or onPing?

### ISSUE THREAD

**Issue by sadeghrz** [daltoniam/Starscream#585]
some times connection is not really stable and it broke silently without calling onDisconnect.
my solution is i save last ping that send from server to my client and if client didn't receive ping for a while i call reconnect method.
so how can i implement didPingRecieve in my client?

**Comment by thbaja** [comment]
Seems like this is answered in #194.

You could also send a ping to your server yourself, and then use the `websocketDidReceivePong` delegate in combination with a timeout for how long you are willing to wait.

See: https://github.com/daltoniam/Starscream#optional-websocketdidreceivepong-required-protocol-websocketpongdelegate

**Comment by fassko** [comment]
I will close this as it's answered.
