### ISSUE TITLE
Version 3.0.6 breaks Xcode 9 compatibility

### ISSUE THREAD

**Issue by AnthonyOliveri** [daltoniam/Starscream#587]
Starscream 3.0.6 [removed custom module maps](https://github.com/daltoniam/Starscream/commit/dceb95c4ea822829a44d6915a446e5205f1c62a0) for CommonCrypto in favor of importing directly from native Swift. The `CommonCrypto` module is only available as of Xcode 10, so building Starscream in Xcode 9 fails due to this module missing. 

Any framework that depends on Starscream will no longer be able to maintain compatibility with any Xcode versions besides Xcode 10 unless the Starscream dependency is hard-coded to 3.0.5, precluding any future updates.

**Comment by fassko** [comment]
Please use 3.0.5 version.

**Comment by mkistler** [comment]
[Semver](https://semver.org/) requires that any changes made in a minor or patch version to be backward compatible.
