### ISSUE TITLE
How to provide a close reason when disconnecting?

### ISSUE THREAD

**Issue by musa-almatri** [daltoniam/Starscream#589]
Currently we can disconnect from the WebSocket using

`disconnect(forceTimeout: TimeInterval? = nil, closeCode: UInt16 = CloseCode.normal.rawValue)`

How can I provide a custom close reason (String)?

**Comment by fassko** [comment]
Can you please explain more what kind of information and when would you provide? Right now there is just close code.

**Comment by musa-almatri** [comment]
I have an app that supposed to send a reason when close the session. This behavior exists in many libraries.
here is an example from **Java-WebSocket** (see line 434)

[Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket/blob/89418985308acfa964186a77b1eab8e6c21b9825/src/main/java/org/java_websocket/WebSocketImpl.java)

The user can close the session by setting the code and reason for the close frame

**Comment by fassko** [comment]
@musa-almatri Thanks for clearing this out. Maybe you could help out with PR?

**Comment by fassko** [comment]
I will be more than happy to merge it in.

**Comment by thbaja** [comment]
This issue should be closed.
