### ISSUE TITLE
Potential writeQueue race with sharedWorkQueue

### ISSUE THREAD

**Issue by yxztj** [daltoniam/Starscream#594]
Per my understanding(please correct me if I'm wrong), outputStream could be accessed on:
1. Any thread that is trying to call cleanupStream() to release it, which could be in disconnectStream and deinit.
2. writeQueue: for writing data

So if we are releasing outputStream(could be on any thread) and happens to be writing outStream(on writeQueue) at the same time, then there would be a race condition?

We are seeing intermittent crashes(Starscream 3.0.5) as mentioned in https://github.com/daltoniam/Starscream/issues/588, looks like memory corruption by threading issue.

**Comment by fassko** [comment]
Hi @yxztj can you show some of the issues you're having? Thanks!

**Comment by yxztj** [comment]
<img width="687" alt="screen shot 2018-11-02 at 10 51 33 am" src="https://user-images.githubusercontent.com/3334458/48326126-bb6dde00-e672-11e8-98d3-abc6198de098.png">

It's because the FoundationStream object is set as delegate of the CFReadStream/CFWriteStream on FoundationStream.sharedWorkQueue, the system would try to call the delegate functions on that queue. But meanwhile you could be releasing the WebSocket/FoundationStream on any thread(probably due to reconnect), a memory corruption is very likely to occur. @fassko

**Comment by fassko** [comment]
@yxztj Maybe you can help out with a PR? Thanks!
