### ISSUE TITLE
Can the Starscream iOS app be the server not the client?

### ISSUE THREAD

**Issue by dumbledad** [daltoniam/Starscream#595]
I'm trying to build an iOS app that serves up frames from the camera over a web socket. Starscream seems to be the library of choice for web sockets on iOS. Starscream examples start with a line like this one:

    socket = WebSocket(url: URL(string: "ws://localhost:8080/")!)

I.e. they assume that we are opening a connection to a server, and after that we can send and receive data over the web socket. What I need is the other way around, I will be serving the data over a web socket and a client will connect to me so that I can send the data over a web socket. 

Is that possible using Starscream? How?

**Comment by fassko** [comment]
@dumbledad you can look into https://github.com/apple/swift-nio-transport-services

Starscream has only client capabilities.
