### ISSUE TITLE
Channel support?

### ISSUE THREAD

**Issue by shawnmitchell** [daltoniam/Starscream#60]
WebSockets should support sending data on channels, no?

**Comment by shawnmitchell** [comment]
Ah, it seems I'm confusing WebSockets with Socket.io. Would be nice to have support for that.

**Comment by acmacalister** [comment]
I'm sure what you mean by "channels", but if I understand what you are asking correctly, the WebSockets RFC spec does not include anything about channels in the sense like Socket.io supported channels. That being said, it is doablel to build channels on top of the WebSocket protocol.

**Comment by acmacalister** [comment]
The goal of Starscream is just to provide a RFC 6455 complaint WebSocket library. You could use it to build a Socket.IO library or channel based system off. Here is a library that uses Starscream to create a Socket.IO library.

https://github.com/shuoli84/SocketIOCocoa

**Comment by shawnmitchell** [comment]
Thanks!
