### ISSUE TITLE
EXC_BREAKPOINT - closure #1 in WebSocket.processTCPHandshake(_:bufferLen:)

### ISSUE THREAD

**Issue by LuisMDeveloper** [daltoniam/Starscream#600]
I am having this crash in an application that does an intensive use of sockets, I can't reproduce the issue yet, all I can see is that something goes wrong the handshake, network issues maybe?
<img width="1122" alt="screen shot 2018-11-16 at 12 28 50 pm" src="https://user-images.githubusercontent.com/2772114/48642652-1c632200-e9a3-11e8-9d7e-a5f61335c723.png">

**Comment by acmacalister** [comment]
I would lean toward this being racy writing to socket. Starscream is not thread safe, so you have to take care to ensure you aren't writing racy code that can cause a crash.
