### ISSUE TITLE
Crash recorded in crashlytics - globalinit_33_E91840E7069A0D2D302D042308E9D928_func3

### ISSUE THREAD

**Issue by carlchungrekki** [daltoniam/Starscream#601]
I am having this crash recorded in crashlytics. Is there anyone getting the same ?

#12. Crashed: com.vluxe.starscream.websocket
0  libobjc.A.dylib                0x191c31430 objc_retain + 16
1  Starscream                     0x10501f484 globalinit_33_E91840E7069A0D2D302D042308E9D928_func3 + 6116
2  CoreFoundation                 0x1929eb030 _signalEventSync + 216
3  CoreFoundation                 0x1929eb090 ___signalEventQueue_block_invoke + 24
4  libdispatch.dylib              0x1924816c8 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x192482484 _dispatch_client_callout + 16
6  libdispatch.dylib              0x192429be0 _dispatch_lane_serial_drain$VARIANT$mp + 592
7  libdispatch.dylib              0x19242a728 _dispatch_lane_invoke$VARIANT$mp + 432
8  libdispatch.dylib              0x192432ec8 _dispatch_workloop_worker_thread + 600
9  libsystem_pthread.dylib        0x1926640dc _pthread_wqthread + 312
10 libsystem_pthread.dylib        0x192666cec start_wqthread + 4

The crash insight says this:
The stack trace indicates that heap corruption may have caused your app to crash. Memory corruption can occur pretty easily from freeing a dangling pointer, a thread race, or bad pointer arithmetic. The important thing to keep in mind is that the resulting crash may happen long after the initial corruption. As a result, the stack trace for this crash might not provide any clues to the location of the bug in your code. However, you can still fix memory issues with tools from Apple. For speedy resolution of memory corruption issues, we recommend regularly auditing your app with Xcode’s memory debugging facilities: Visual Memory Debugger, Zombies Instrument, Address Sanitizer, Thread Sanitizer and malloc diagnostics.

**Comment by acmacalister** [comment]
Starscream is not thread safe, so you have to take care to ensure you aren't writing racy code that can cause a crash. Please provide either steps to reproduce or a sample app for us to assist with this issue.
