### ISSUE TITLE
Send ping,  received pong but websocketDidDisconnect callback function revoked right away

### ISSUE THREAD

**Issue by HayTran94** [daltoniam/Starscream#602]
Version: 3.0.6
Platform iOS 10.

When I ping to another connected socket by: 

`self.socket.write(ping: Data())`

after that, `websocketDidReceivePong()` callback revoked, but `websocketDidDisconnect()` callback also revoked right away with error: `Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "continue frame before a binary or text frame", code: 1002)`.

If my ping frame not properly or anything else? I am looking forward hearing from you. Many thanks.

**Comment by acmacalister** [comment]
Starscream handles the ping/pong mechanism for you, so generally you don't need to send it yourself. the error is an underlining WebSocket protocol, presumably from writing the data incorrectly.
