### ISSUE TITLE
Unix Domain Sockets

### ISSUE THREAD

**Issue by vhmth** [daltoniam/Starscream#605]
I've created a websocket server that runs over a local Unix Domain Socket. I was wondering how I might get Starscream to connect over this socket (e.g. `/var/run/example.sock`)?

**Comment by acmacalister** [comment]
Starscream isn't a generic socket library. I'm not sure it really makes sense to use WebSocket over a local unix (especially for mobile), but this doesn't sound like the library you are looking for. Most unix sockets are used as IPC for processes on local machines and don't need the framing overhead of a protocol like WebSockets.

**Comment by vhmth** [comment]
Totally get that Starscream isn't a generic socket library (and respect that), but running websocket (and http servers) over unix pipes is very standard in commercial applications that don't want to bind to ports for security reasons.

I'm actually using Starscream in a Mac desktop application to communicate with a node.js (Electron) layer that spins it up. Essentially, the built Swift binary accesses some OSX APIs and takes commands from the Electron (UI) layer.

I'm using websockets here because their interface is *much* friendlier than listening to raw bytes and parsing ([example](https://github.com/IBM-Swift/BlueSocket#complete-example)).

**Comment by acmacalister** [comment]
ah, sorry for the assumption on this. I agree on the unix socket usage, I think the main issue is underlying API `CFStreamCreatePairWithSocketToHost` is design for TCP/IP only. Meaning we would need to implement a unix socket support of `WSStream` for this use case to work. That is something we can look into as we move over to the Network.framework.

**Comment by thbaja** [comment]
I think that it's a bit out of scope for this library, and since the OP went for another solution perhaps this issue could be closed for now.
