### ISSUE TITLE
xcode-10 branch and NetworkStream

### ISSUE THREAD

**Issue by bukira** [daltoniam/Starscream#606]
I can't seem to get this branch with NetworkStream in to work with "wss" it only works with "ws"
I have tried echo.websocket.org which works perfectly fine with FoundationStream.

Is wss supported yet?

**Comment by bukira** [comment]
I see you haven't implemented yet

 public func isValidSSLCertificate() -> Bool {
        return false //TODO: SSL pinning for the network framework
    }

any plans to complete this ?

**Comment by bukira** [comment]
can it return true until you do the SSL pinning? as I don't need SSL pinning but I do need SSL

**Comment by fassko** [comment]
There are plans, but can't give any ETA atm. Current master should work fine with Xcode10.

**Comment by bukira** [comment]
@fassko It doesnt because you return false to isValidSSLCertificate so it fails every time,

I have to modify the code to return true which means I can no longer use Carthage to pull down builds

**Comment by fassko** [comment]
@bukira I understand about xcode-10 branch. Please use master. Xcode-10 is in development phase.

**Comment by bukira** [comment]
error: pathspec 'Xcode-10' did not match any file(s) known to git.

**Comment by bukira** [comment]
but master branch doesnt support Network.framework?

**Comment by fassko** [comment]
It does not currently. Are you having any big issues with that?

Network.framework is only iOS 12+, macOS 10.14+, tvOS 12+ and it has no watchOS support.

**Comment by bukira** [comment]
I don't need watch support as I dont use web sockets in the watch I use alamofire, 
Your xcode-10 branch has great backward compatibility, so with a simple @available I can support ios12 and ios10/11

My issue is that you set isValidSSLCertificate to false, so it always fails on wss, which is for me the natural and best way to connect to a WebSocket, we have our own valid cert so we dont need SSL Pinning so I dont have a need for isValidSSLCertificate to be anything but true,

However to get this working I have to use Carthage to get Xcode-10 branch and then change the source code to "true" and recompile and copy into my Carthage folder, OR I could fork your project to my own but seems a bit OTT for just 1 word change

I understand its development and you dont garuntee any issues, but you have done a great job and it works perfectly so far as long as the cert check is true, I also understand you have no etc on SSL pinning as you have lottos other stuff to do, but to me it seems that returning true would suit everyone.

**Comment by fassko** [comment]
I understand that you don't need it, but removing watchOS support is a breaking change for this library.

**Comment by bukira** [comment]
@fassko ok im kind of lost, im not saying remove watchOS and anything, all I'm saying is that on the xcode-10 branch that you already have (which I think is great and well done), change "false" to "true" in isValidSSLCertificate.

I can't see that that change will break anything, but allow SSL WSS to work

**Comment by fassko** [comment]
How you could help please add a PR to xcode-10 branch and I will merge it.

**Comment by bukira** [comment]
ok ,hopefully I've done that now :-)
