### ISSUE TITLE
Feature Request: Global debug toggling

### ISSUE THREAD

**Issue by mgcrea** [daltoniam/Starscream#608]
I'm currently working to reverse engineer an home automation app with [.ipa code injection](https://medium.com/@kennethpoon/how-to-perform-ios-code-injection-on-ipa-files-1ba91d9438db). The app does use Startscream for the websocket communication I'm trying to inspect.

I've quickly looked at the code but did not found a global way to enable debug of messages. Is it something that can be done? Is it something that could be added?

Thanks!

**Comment by fassko** [comment]
Hi @mgcrea currently there is nothing like that built in.

As I understand you don't have full control of the app and can't change the code?

**Comment by mgcrea** [comment]
Thanks for the reply, indeed, I can't change the code, only sideload some. Somehow it looks like it is possible to override/hook core methods (like what @depoon is doing with its framework [NetworkInterceptor](https://github.com/depoon/NetworkInterceptor)) with [open override](https://github.com/depoon/NetworkInterceptor/blob/master/NetworkInterceptor/Source/URLProtocol/NetworkRedirectUrlProtocol.swift#L29) calls.

But not sure if it is achievable on an already loaded framework hence the question about a global logging that would have been quite useful in my case...!

Thanks!

**Comment by fassko** [comment]
I honestly think that such feature can be a security issue. I understand it can be used while developing but when it has been bundled into app it can do harm. This is the reason why Apple is sandboxing apps and doing other security related things.

Sadly I can't help you.

You could use Wireshark or try to build a man in the middle solution. But I have no concrete recipe how to do it.
