### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by jfdream** [daltoniam/Starscream#613]
2019-01-22 14:40:07.071567+0800 NewWebsocket[16706:1555156] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=16706
2019-01-22 14:40:07.071641+0800 NewWebsocket[16706:1555156] SecTaskCopyDebugDescription: NewWebsocket[16706]/0#-1 LF=0

**Comment by fassko** [comment]
@jfdream Could you please provide more information? An example would help.

**Comment by jfdream** [comment]
OK，Thank you for your reply. (I'm using swift 4.2,Starscream 3.0.6 )

[NewWebsocket.zip](https://github.com/daltoniam/Starscream/files/2782144/NewWebsocket.zip)

**Comment by thbaja** [comment]
If this is still relevant, I think you would have better luck of getting an answer if you provide a small code example right here in the thread. Alternatively a fork or a PR, so we don't have to download zip file.
If it's not relevant anymore the close the issue.

**Comment by thbaja** [comment]
I think this issue should be closed for now. Can be re-opened if a sample is provided.
