### ISSUE TITLE
websocket connected success but it's isConnect property is false

### ISSUE THREAD

**Issue by smalldu** [daltoniam/Starscream#619]
It rarely happened and hard to reproduce . I just happened once and user feedback once . so could you find the reason and fix it, thanks.

**Comment by fassko** [comment]
Without any example it's impossible to reproduce and fix.

**Comment by smalldu** [comment]
> Without any example it's impossible to reproduce and fix.

I debug in `websocketDidConnect` method and isConnect is false . but just once.

**Comment by fassko** [comment]
If you can make a simple example app that could help.
