### ISSUE TITLE
error:  invalidFrameLength when sending Data

### ISSUE THREAD

**Issue by wildthink** [daltoniam/Starscream#621]
I'm getting `error:  invalidFrameLength` on the server when trying to send a Data block from the client.
The Data is an encoded image of 33443 bytes.
Any ideas where I could look?
Thanks

**Comment by wildthink** [comment]
This is remedied by a setting on the server. Was wondering if there was an automatic way to tell Starscream to segment a large payload.

**Comment by fassko** [comment]
@wildthink Thank you for following up to this issue.

There is no such feature for Starscream. We're keeping it simple.
