### ISSUE TITLE
Force new connection on websocket

### ISSUE THREAD

**Issue by vinh869163** [daltoniam/Starscream#622]
Could Starscream have option for "Force new connection"?. Thank you

**Comment by fassko** [comment]
@vinh869163 Could you please explain more?

**Comment by vinh869163** [comment]
@fassko we want when create a socket, it can always using full handshake  in TLS 1.2. As i test with your source it always use abbreviated handshake when reconnect. Do you have this option to force new connection with full handshake in TLS 1.2

**Comment by acmacalister** [comment]
We use the underlying Apple APIs to handle the TLS session for connections. I'm not aware of any exposed API to control this, but if you find one, PRs are welcomed.
