### ISSUE TITLE
Need to have functionality to set NSStreamNetworkServiceType to work with QoS

### ISSUE THREAD

**Issue by katsumiy** [daltoniam/Starscream#624]
Cisco infrastructure + iOS 10 have functionality to distinguish service type by NSStreamNetworkServiceType for QoS. For details, please see https://developer.cisco.com/site/fast-lane

So we need to have functionality to set NSStreamNetworkServiceType by application in Starscream.

**Comment by fassko** [comment]
@katsumiy Maybe you can help with PR for this specific issue? Thanks!

**Comment by bukira** [comment]
I would be interested in this also

**Comment by acmacalister** [comment]
With #653 you can handle this with the init of FoundationStream that you can now customize. We also added support for `Network.framework` which also has support for this.
