### ISSUE TITLE
extension data

### ISSUE THREAD

**Issue by wildthink** [daltoniam/Starscream#625]

**Comment by wildthink** [comment]
It would be helpful to have support for Extension Data. Perhaps some parameters based on the protocols.

**Comment by fassko** [comment]
@wildthink Could you please explain more what do you mean with this?

Maybe a help with PR? :)

**Comment by wildthink** [comment]
Sorry about that.

>    The base framing protocol defines a frame type with an opcode, a
   payload length, and designated locations for "Extension data" and
   "Application data", which together define the "Payload data".
   Certain bits and opcodes are reserved for future expansion of the
   protocol.

https://tools.ietf.org/html/rfc6455

This is reflected in the Swift NIO [WebSocketFrame](https://apple.github.io/swift-nio/docs/current/NIOWebSocket/Structs/WebSocketFrame.html.l)

>  Payload data:  (x+y) bytes

      The "Payload data" is defined as "Extension data" concatenated
      with "Application data".

As I understand it the extension data prepends the main application data and its size has to be "agreed upon" by the sender and recipient. I imagine that such information could delivered in the initial request header as are WebSocket Protocols. The advantage  would be that this makes it easier for the applications to define their own supplemental header to the overall payload.

**Comment by thbaja** [comment]
Is this something you actually need?

It seems it hasn't been requested before so it might be more of a special case. Perhaps close this issue for now, since it's not a priority given the lack of use cases and requests.

But I'm sure a PR would be most welcome!
