### ISSUE TITLE
handle ping (or pingdelegate)

### ISSUE THREAD

**Issue by tolgatanriverdi** [daltoniam/Starscream#629]
Starscream framework returns a delegate such as pong delegate but as far as I see, there is no pingdelegate
So in the client side I'm not able to see if ping message is received to starscream(In our application receiving pings connected with our application's algorithms)

So my question is , are there any method to inform us when the starscream received ping (I just wanted to be informed, it doesnt matter if starscream automaticaly sends pong),
or If I want to add such a method in starscream's code where should I check if the starscream receives ping message

**Comment by fassko** [comment]
@tolgatanriverdi 

There is `WebSocketPongDelegate` which has method `websocketDidReceivePong` and one of the parameters is `data: Data?` That contains data what came back from the server.

**Comment by thbaja** [comment]
@tolgatanriverdi if you need a delegate for when receiving a ping it should be fairly easy to implement and a PR would probably be appreciated.

You could imitate the implementation of the ```websocketDidReceivePong``` delegate (protocols etc.) and then place it inside here: https://github.com/daltoniam/Starscream/blob/07e09a8ab355df832f2c457e6dd13519662af618/Sources/Starscream/WebSocket.swift#L1168
