### ISSUE TITLE
Calling write() /w explicit control over the code param (.textFrame or .binaryFrame)

### ISSUE THREAD

**Issue by eliburke** [daltoniam/Starscream#632]
This is maybe a minor nitpick, but I believe it is a common scenario. 
We send JSON over a web socket as text (WAMP) and it goes through a round of unnecessary conversions to and from String form because the Starscream API sends all Data as binary and all Strings as text. 

1. convert Dictionary to JSON produces Data
    let data = try JSONSerialization.data(withJSONObject: json, options: [])
2. convert Data to String (in order to send using . textFrame)
    **let string = String(data: data, encoding: String.Encoding.utf8)** 
3. write the data to the socket
    self.socket.write(string: outgoingStr)
4. WebSocket.swift immediately converts back to Data
    dequeueWrite(**string.data(using: String.Encoding.utf8)!**, code: .textFrame, writeCompletion: completion)

I would like to skip the two conversions in bold, but it does not seem possible. I can't fix it with an extension because dequeueWrite() is private. Is there a reason for this restriction?

**Comment by fassko** [comment]
Hi @eliburke,

I can't speak from library creators. But I think reason to make it private is to express as little as possible when using this library. Only essential things.

What I have done is I did create an extension for specific things you mentioned to send JSON.

Other than that maybe a PR with sending objects which conform to Codable might sound nice, but I would rather keep this library as simple as possible.

**Comment by eliburke** [comment]
@fassko I understand (and agree with) the importance of keeping things simple. But that can be accomplished in many ways. For example, a default parameter such as `socket.write(data: Data, binary: Bool = true)`

How were you able to create an extension that sends JSON without additional format conversions? Would you mind posting your code?

**Comment by mooshee** [comment]
I agree with @eliburke.  This isn't about extending the interface, but rather, not doing unnecessary work with the existing interface by surfacing a lower-level method.

**Comment by fassko** [comment]
@eliburke I'm basically doing what you posted in first comment. It can be an overhead but as I'm reusing that again it's fine.

If you or @mooshee could come up with PR for that I would be more than happy to review it. I think that sending objects which conform to Codable would be a nice touch. :)

**Comment by daltoniam** [comment]
Agreed, so I added this into 4.0.0 😄. A new method of `write(stringData: Data)` to handle this case.

https://github.com/daltoniam/Starscream/blob/master/Sources/Starscream/WebSocket.swift#L156

Any issues or questions, feel free to reopen this issue. Thanks!
