### ISSUE TITLE
How can I use StarScream framework as a fat library inside my project

### ISSUE THREAD

**Issue by erhnby** [daltoniam/Starscream#633]
Hi everyone,

What is the way to compile StarScream framework to be able to support also simulator, Can you help on this?

**Comment by fassko** [comment]
Hi @erhnby could you explain more what is the issue? Right now I'm a bit confused.

**Comment by erhnby** [comment]
Hi @fassko what I am trying to say is I need a StarScream framework which contains both device and simulator architectures (arm7, arm64, i386, x86_64).To achieve this how should I build the project? Is there any build script for that?

**Comment by fassko** [comment]
If you use cocoapods or Carthage it should work with existing version.

What is your build process/flow?

**Comment by erhnby** [comment]
I am not using Cocoapods or Carthage, I'm going to use the StarScream inside of my iOS framework project.

**Comment by fassko** [comment]
I would recommend then using Carthage to bring it in your framework. Easier to keep up to date.

Other than that currently Starscream is platform agnostic so you can implement it in Simulator project.
