### ISSUE TITLE
Scanning network for connection

### ISSUE THREAD

**Issue by AngCosmin** [daltoniam/Starscream#634]
Hello!

I created a websocket server using Python. 

I want to make my application to scan the network and find the server IP. Without manually hardcoding it.

Do you have any solution to this? Thanks.

**Comment by thbaja** [comment]
IP is not enough, you also need to find the port. It seems quite odd and is completely irrelevant for this library.
I suggest closing this issue.

**Comment by fassko** [comment]
@AngCosmin like @thbaja mentioned this is out of the scope for this library. If you make it make it open source as it sounds useful for other folks.
