### ISSUE TITLE
Cannot build 3.1.0 Xcode 10.1

### ISSUE THREAD

**Issue by natebirkholz** [daltoniam/Starscream#637]
I updated cocoa pods using `pod update` and got Starscream version 3.1.0. Upon building my project, I get the following error for the Starscream module: "The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor."

I see that the latest seems to have 5.0 set as the Swift version. I was able to specify version 3.0.6 for the version of Starscream and continue to build my project.

**Comment by fassko** [comment]
Yes, I updated readme that for Xcode 10.1 you need to use 3.0.6
