### ISSUE TITLE
xCode 10.2 + Carthage update = build error

### ISSUE THREAD

**Issue by Yelles** [daltoniam/Starscream#638]
Hi,

I'm trying to build by `carthage update --platform ios` and it failed : Task failed with exit code 65:

`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Starscream iOS')`

I think there is references to SWIFT_VERSION '3.0', xCode 10.2 support only 4.x min.

**Comment by fassko** [comment]
Please use 3.0.6 version. I put info about Swift version support in readme as well. Cheers.

**Comment by Yelles** [comment]
Hi, I still get this error with the version 3.1.0

error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Starscream iOS')
