### ISSUE TITLE
Question how to disconnect from AppDelegate

### ISSUE THREAD

**Issue by sk1tt1sh** [daltoniam/Starscream#64]
How do I disconnect the websocket from appdelegate when the app goes into background or closes. 

In my main view controller I have a Disconnect method that gets called when a button is tapped, so then I call like this:
```swift
var rootViewController = self.window!.rootViewController
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        var setViewController = mainStoryboard.instantiateViewControllerWithIdentifier("Main") as ViewController
        
        setViewController.DisconnectSocket(self)
```

And it looks like its trying to disconnect but the server shows the connection still open, and indeed if I go back into the app it still is connected.

**Comment by daltoniam** [comment]
All you need to do is call the `disconnect` method when the app is closing, usually in the `willEnterBackground` method of your AppDelegate.

https://github.com/daltoniam/Starscream#disconnect

**Comment by sk1tt1sh** [comment]
Thanks... I'm having trouble getting the correct instance from the AppDelegate though. I'm basically using the example app. I've been using google searches but I am not quite nailing the terms down I think. Any suggestions?

**Comment by daltoniam** [comment]
I would suggest either creating a singleton object to keep the WebSocket object in or put the WebSocket object as a property of the AppDelegate and reference it from the rest of the app through the AppDelegate.

**Comment by sk1tt1sh** [comment]
Thanks! Is Apple ok with doing the appdelegate property way?

**Comment by daltoniam** [comment]
I can't speak for Apple :smile:, but I would always recommend scoping a variable as locally as possible. In the case of WebSocket through out an app, normally it has to stick around for the life time of an app, so an app delegate variable or singleton would fit the bill. It really depends on your needs of your app and what works for your app.
