### ISSUE TITLE
(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 500))

### ISSUE THREAD

**Issue by cxxcapf** [daltoniam/Starscream#646]
Please tell me how to deal with this error

`socket.disableSSLCertValidation = true`
it doesn't work.˜!

I use wss links

**Comment by cxxcapf** [comment]
There is no user-agent in the request header, Intercepted by server˜!
囧

**Comment by metisdev** [comment]
So? how did you fix it? :)
