### ISSUE TITLE
Support for Socket IO

### ISSUE THREAD

**Issue by Abhishek9634** [daltoniam/Starscream#648]
Unable to connect with Socket IO. Always show 'web socket disconnected'

**Comment by nuclearace** [comment]
Starscream is just a web socket client, try https://github.com/socketio/socket.io-client-swift for socketio

**Comment by Abhishek9634** [comment]
@nuclearace : So what's the diff ?

**Comment by nuclearace** [comment]
@Abhishek9634 socket.io is just a framework that _can_ use WebSockets as a transport mechanism. Socket.io has its own protocol that a stand-alone WebSocket client won't, and in fact shouldn't, understand.

That library -- which I will disclose is one that I created and maintain -- is made for connecting to servers that implement the socket.io protocol. And the library does in-fact use this one for its WebSocket functionality.

**Comment by thbaja** [comment]
Great answer!
Let's close this issue.
