### ISSUE TITLE
Is it possible to intercept requests?

### ISSUE THREAD

**Issue by Ricardo1980** [daltoniam/Starscream#654]
Hello,

Can I intercept request?

Something like RequestAdapter and RequestRetrier used to, for example, add a JWT token and send another request if required while stopping the current one.
https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests

Basically, I am using a library called Nabto in order to access IOT devices outside my home. This library creates a TCP tunnel and then I have to redirect all the network requests to that tunnel (using 127.0.0.1 and a local port, instead of a remote port).

Can I intercept Starscream requests to add the tunnel creation there? Or there is no way and I have to manage that outside Starscream?

Thanks a lot for suggestions.

**Comment by fassko** [comment]
This kind of feature is not supported by this library. We're keeping it as simple as possible. So I guess you need to manage that outside Starscream.
