### ISSUE TITLE
Swift Compiler Warnings

### ISSUE THREAD

**Issue by adrian-niculescu** [daltoniam/Starscream#657]
Using Xcode Version 10.2 (10E125) I get the following warnings in a Swift 5 project:
![Screenshot 2019-05-10 at 10 51 47](https://user-images.githubusercontent.com/15037449/57511365-c9df3e80-7311-11e9-9cc7-b008176cd043.png)

Also thank you for this great library!

**Comment by acmacalister** [comment]
We rolled the Swift update in the v4 refactor of #653. Check it out.
