### ISSUE TITLE
Change socket URL

### ISSUE THREAD

**Issue by lindseyvastola** [daltoniam/Starscream#658]
I need to change my socket's url in certain cases and I don't see a way to do it.
I am establishing the variable with : 
var socket = WebSocket(url: URL(string: "First")!, protocols: ["chat", "superchat"])
socket.delegate = self
socket.voipEnabled = true
socket.disableSSLCertValidation = false

The socket is disconnected when I try to change the url and I try to change the url using the line below but the url doesn't change. If I try to change via socket.url, I am told that it is a read only value
socket = WebSocket(url: URL(string: "Second")!, protocols: ["chat", "superchat"])

**Comment by texuf** [comment]
Are you repeating all 4 lines or just the constructor? This code should work...

    socket = WebSocket(url: URL(string: "Second")!, protocols: ["chat", "superchat"])
    socket.delegate = self
    socket.voipEnabled = true
    socket.disableSSLCertValidation = false

**Comment by lindseyvastola** [comment]
Setting the delegate again when it switched was the answer for me, thanks. I was just setting the socket variable when it change.

**Comment by texuf** [comment]
You weren't setting a variable, you were creating a new instance of a class. You can read up on classes and how they behave here https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html. 

You should also be able to close this issue.
