### ISSUE TITLE
Does Starscream work with WAMP v1?

### ISSUE THREAD

**Issue by Luke47** [daltoniam/Starscream#66]
First of all, good work!

WAMP v2 seems to be supported, but is there also the possibility to use this with WAMP v1? Thank you! :)

**Comment by daltoniam** [comment]
Thanks! The library isn't specifically designed to support WAMP, but from my quick check, it appears both the V1 and V2 protocols use websockets. I would assume another library could be built using Starscream to support both WAMP V1 and V2.

 http://wamp.ws/spec/wamp1/
