### ISSUE TITLE
Retry logic built-in? [Question]

### ISSUE THREAD

**Issue by whoyawn** [daltoniam/Starscream#660]
If I'm trying to connect to the socket and it fails, is there built-in logic or do I have to write that myself?

**Comment by fassko** [comment]
@whoyawn Can you please share your example? From your information it's hard to understand what is the issue.

**Comment by whoyawn** [comment]
Let's say I call webSocket.connect() in my logic, if the server connection doesn't exist (connectivity issues, I'm offline), but then exists later (back online), does the socket automatically try to ping the server again after a certain amount of time? Or would I have to write my own backoff algorithm?

**Comment by acmacalister** [comment]
You would need to write this yourself. The only "retry" logic that exist is standard reconnection of a TCP socket.
