### ISSUE TITLE
Cocoapod support for swift 5 

### ISSUE THREAD

**Issue by lindseyvastola** [daltoniam/Starscream#664]
When will the cocoapod project be updated to support swift 5? https://cocoapods.org/pods/Starscream

**Comment by acmacalister** [comment]
It has been updated in #653, which we are planning releasing very soon.

**Comment by nonpensavo** [comment]
> It has been updated in #653, which we are planning releasing very soon.

Sorry if bothering you, any approximate dates?~

**Comment by tiwariammit** [comment]
Hey guys!
 How did you done https://github.com/daltoniam/Starscream/issues/671 task??

**Comment by daltoniam** [comment]
Version 4.0.0 released!
