### ISSUE TITLE
URLSessionWebSocketTask

### ISSUE THREAD

**Issue by kielgillard** [daltoniam/Starscream#666]
Is this something you could use for improving the reliability of sockets on iOS?

[URLSessionWebSocketTask](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask) was introduced in iOS 13. I'm guessing it's mentioned in either [Part 1](https://developer.apple.com/videos/play/wwdc2019/712/) or [Part 2](https://developer.apple.com/videos/play/wwdc2019/713) of Advances in Networking.

**Comment by acmacalister** [comment]
Discussing this on #653

**Comment by fassko** [comment]
And it's only for latest beta.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kielgillard** [comment]
Thanks!
