### ISSUE TITLE
Support iOS 13 native websockets

### ISSUE THREAD

**Issue by julien-c** [daltoniam/Starscream#667]
Opening a thread about this big iOS 13 announcement – native websocket!

It's exposed both as a high-level (and very clean) URLSession task (https://developer.apple.com/documentation/foundation/urlsessionwebsockettask), and as lower-level protocol in Network.framework (https://developer.apple.com/documentation/network/nwprotocolwebsocket)

<img width="1783" alt="Capture d’écran 2019-06-12 à 21 18 53" src="https://user-images.githubusercontent.com/326577/59396736-188c5800-8d58-11e9-8e49-3e6fabca63cd.png">

What do you guys think? Should Starscream defer to the native framework on iOS 13?

**Comment by fassko** [comment]
Right now it is supported only for beta. Some discussion about this topic is here https://github.com/daltoniam/Starscream/pull/653
