### ISSUE TITLE
Unable To subscribe channel.

### ISSUE THREAD

**Issue by tiwariammit** [daltoniam/Starscream#671]
First, I set up the socket instance as
    private let socket = WebSocket(url: URL(string: Urls.socketChatBaseUrl)!)
where I am using url to connect  server and it  successfully called the delegate method 

  ```
  func websocketDidConnect(socket: WebSocketClient) {

}
```

after that I am try to subscribe to the chat channel as:

  ```
  func websocketDidConnect(socket: WebSocketClient) {
        print("websocket is connected")

        let type = "/user/47/queue/specific-user"
        self.socket.write(string: type) {
            print("Observer Activated")
        }
    }
```

success completion of write method printed out "Observer Activated".
But actually it shows wrong that it is not connected.
And If it connected then Observer message is come on 
 

`>  func websocketDidReceiveData(socket: WebSocketClient, data: Data)
`       
method?

And another part of my question is For  **How do I send the message to server**:

Here what I done is:-

```
func sendMessage(_ message : String){
    
    var jsonObject = [String: String]()
    jsonObject["from"] = "47"
    jsonObject["to"] = "1"
    jsonObject["message"] = message
        
    let type = "/app/chat/buyer"
    let data = [type:jsonObject] as [String : AnyObject]
    let valid = JSONSerialization.isValidJSONObject(data)
    if valid {
        do {
            let jsonData = try JSONSerialization.data(withJSONObject: data, options: JSONSerialization.WritingOptions()) as Data
            
            if let jsonString = NSString(data: jsonData as Data, encoding: String.Encoding.utf8.rawValue) as String? {
                print("json string = \(jsonString)")
                
                socket.write(string: jsonString) {
                    print("Message send to server")
                }
            }
        } catch _ {
            print ("JSON Failure")
        }
    }
}
```

But unable to send the message to the server. Here, if I unable to send message to server then why **print("Message send to server")** print out?

Please help me.

**Comment by fassko** [comment]
Hi @tiwariammit 

Please don't spam in other issues which are not related.

Do you get any error. Because with a quick glimpse this code should work.

**Comment by tiwariammit** [comment]
@fassko I am not spamming other issue comment section. I just request help from other. My issue is base part of this library and I think all you guys solved this problem. I am just sharing my issue to other in order to get help. 
Nope, I am stuck on this issue.

**Comment by fassko** [comment]
Can you share code sample because from information provided it should work. Who is maintaining websocket server?

**Comment by tiwariammit** [comment]
I have uploaded sample project on https://github.com/tiwariammit/SampleChat .Please find the attachment. Websocket server is maintained by my friend.

**Comment by daltoniam** [comment]
I don't think this is an issue with Starscream as it works fine with several web socket servers and conforms to the Websocket RFC. I don't see an issue at first glance with the code in the project, but it might be an issue with expectations, as Starscream and WebSockets don't do anything channel related (that is another protocol layered on top of them, like Socket.io).  You can also try upgrading to the latest 4.0.0 version and see if that resolves it. If you still have issues please report back and reopen this issue. Thanks!
