### ISSUE TITLE
Ping/Pong

### ISSUE THREAD

**Issue by Abreu0101** [daltoniam/Starscream#673]
Hello guys,

These are more general question, rather than issue (sorry not sure if this is the correct space, but reading other issues here get more confused).

1) **Should the client manually send ping to server ("to keep connection alive")?** Asking because in some issues was mentioned that is handled by StarScream [Suggest automatic ping](https://github.com/daltoniam/Starscream/issues/602) but in another issue is mentioned that should send ping [(Suggest manual ping)](https://github.com/daltoniam/Starscream/issues/649)
```
.....
// Called when the socket is connected (delegate)
func startPingTimer() {
        stopPingTimer()
        pingTimer = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { [weak self] _ in
            self?.sendPing()
        }
}
.....
```

2) **Is it there a suitable interval for ping? (I think that 2.0 seconds could cause a lot of overhead like in my example above)**

3) **In case the ping is send by Starscream, at what interval?**

4) **If the application move to background should continue the ping to the server or should stop it? (i have voip background mode)**

**Comment by avitruk** [comment]
Hi, 

1. It depends on how you ws-server configured. If your server sends general ping frames to the client, so Starscream will automatically respond with pong frames. If your ws-server configured to listen to ping frames sent by the client and answer with pong, so you need manually handle ping writes.

2. Again, it depends on your server settings. I think It should be at least twice often than your ws-server timeout. E.g. if the server has a timeout 10 seconds, so client should send ping frame every 5 seconds. It should cover all cases with network delay (ping to server) etc. Also, your timeout settings may depends on use-cases. E.g. how fast you need to know, that the client disconnected? We send ping every 30 secs and we didn't face any issues.

3. Correct me if I am wrong, but as I know, Starscream doesn't send ping automatically. He can only respond with pong frame in automatic mode. 

4. I don't know what you trying to achieve. But in our case, we force disconnect WS when application moved to the background. After application moved in active state we have a mechanism to obtain possible missed events. Also, you can check connection handling and communication protocols in other large applications. Personally, I like how it's done in [discord](https://discordapp.com/developers/docs/topics/gateway#resuming).
