### ISSUE TITLE
[Swift 5] Frequent crashes using version 3.1.0

### ISSUE THREAD

**Issue by gdombiak** [daltoniam/Starscream#674]
Hi,

I'm using Starscream v3.1.0 in the also [open source OctoPod app](https://github.com/gdombiak/OctoPod) and I noticed a high spike in crashes in the app since I updated to v3.1.0. Previous versions were not seeing these frequent crashes. Below you can find the stack traces of the 2 most frequent type of crashes.

![Screen Shot 2019-07-09 at 7 47 02 PM](https://user-images.githubusercontent.com/1791267/60936736-f9afb180-a282-11e9-958c-a288ad48ab03.png)

![Screen Shot 2019-07-09 at 7 49 49 PM](https://user-images.githubusercontent.com/1791267/60936771-1fd55180-a283-11e9-89f3-cd6304d1aa80.png)

Users are using latest iOS version. 

Here is the [source code that uses Starscream](https://github.com/gdombiak/OctoPod/blob/master/OctoPod/OctoPrint/WebSocketClient.swift) in case that helps.

Let me know if you need other info. Of course, I never saw this error locally or know how to reproduce it. You know how it goes... ;)

Thanks,
Gaston

**Comment by gdombiak** [comment]
Here you can see crashes since the app went live one year ago. The spike correlates to the upgrade to v3.1.0.

![Screen Shot 2019-07-09 at 7 58 52 PM](https://user-images.githubusercontent.com/1791267/60937041-008af400-a284-11e9-8486-7af0a64d793d.png)

**Comment by gdombiak** [comment]
I will soon release a new version of OctoPod so have to make a decision to keep using 3.10 or roll back the upgrade. Any help with this ticket is appreciated. :D

**Comment by daltoniam** [comment]
Thanks for the report. Not sure how to debug this without any reproduction steps, but I did refactor the whole codebase in 4.0.0. I suggest upgrading to that when you can and if you find any issues related to that please reopen this issue. Thanks!

**Comment by gdombiak** [comment]
Hi @daltoniam,

Thanks for your reply. After more research that took me into memory management in Swift with concurrency the problem no longer happens. Sharing changes I made in case this helps others:

Issue: https://github.com/gdombiak/OctoPod/issues/217
Commit 1: https://github.com/gdombiak/OctoPod/commit/1f9014e57e16014e4771eca45fb38b2b23ebb936
Commit 2: https://github.com/gdombiak/OctoPod/commit/977984167cc2d9adfff793348bcd0c7ab89c24bc

App crashes are back to normal after those 2 commits. Let me know once you have an Alpha of 4.0.0 and I will update OctoPod and test things with the new version and report back findings/experience.

Thanks,
Gaston
