### ISSUE TITLE
[CRASH]  WebSocket.swift

### ISSUE THREAD

**Issue by bfallon** [daltoniam/Starscream#675]
Version 3.0.6

We are receiving a fatal crash in WebSocket.swift line 151 via Crashlytics

The following are being forced unwrapped:

```
        inputStream = readStream!.takeRetainedValue()
        outputStream = writeStream!.takeRetainedValue()
```

I am now safely unwrapping these items and everything appears to be working as expected.

```
        inputStream = readStream?.takeRetainedValue()
        outputStream = writeStream?.takeRetainedValue()
```

**Comment by vonox7** [comment]
Possibly related to https://github.com/daltoniam/Starscream/pull/651

**Comment by daltoniam** [comment]
The stream code has been refactor for version 4.0.0 which should help with issues like this. If you are still seeing a similar crash please reopen this issue. Thanks!
