### ISSUE TITLE
Not able to connect to a web socket

### ISSUE THREAD

**Issue by anjali40** [daltoniam/Starscream#679]
I'm using "Swifter" as my local HTTP Server. I'm using "Starscream" for WebSockets.

Unfortunately getting websocket is disconnected: Optional("The operation couldn’t be completed. (Starscream.WSError error 1.)")) when i'm trying to connect.

I tried accessing localhost from browser and it looks like Http Server is working fine.
Below is the code that I'm working on:

`import UIKit
import Starscream

class ViewController: UIViewController, WebSocketDelegate {

    @IBOutlet weak var button: UIButton!
    
    var simpleServer = SimpleServer()
    var socket = WebSocket(url: URL(string: "ws://127.0.0.1:3000/")!)

    
    override func viewDidLoad() {
        super.viewDidLoad()
        //simpleServer.startServer()
        
        socket.delegate = self
        socket.connect()
    }
    
    func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        print("websocket is disconnected: \(String(error?.localizedDescription ?? "")))")
    }
    
    func websocketDidReceiveMessage(socket: WebSocketClient, text: String) {
        print("got some text: \(text)")
    }
    
    func websocketDidReceiveData(socket: WebSocketClient, data: Data) {
        print("got some data: \(data.count)")
    }
    
    func websocketDidConnect(socket: WebSocketClient) {
        print("websocket is connected")
    }
    
    @IBAction func buttonClicked(_ sender: Any) {
        print("button clicked")
        print(socket.isConnected)
        socket.write(string: "Hi Server!")
    }
}
`

`import Foundation
import Swifter

class SimpleServer{
    
    let server: HttpServer = HttpServer()
    
    init(){
        self.startServer()
    }
    
    public func startServer(){
        do {
            server["/hello"] = { .ok(.htmlBody("You asked for bhuvesh \($0)"))  }
            try server.start(3000)
        }
        catch{
            print("Server could not be started")
        }
    }
    
}`

**Comment by noahkamara** [comment]
I was also going crazy searching for a solution that is in fact very simple :D

You just have to disable SSL Certificate verification by adding `websocket.disableSSLCertValidation = true` to the `viewDidLoad()` method.
If this is set to false Starscream will try to verify the certificate from the server which in your (and my) case is probably not provided
