### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by jannomeister** [daltoniam/Starscream#680]
`error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')`

**Comment by MichaelNeas** [comment]
@jannomeister are you still seeing this? If you're using cocoapods try `pod update`

**Comment by fassko** [comment]
Or try to install newest cocoapods:

`[sudo] gem install cocoapods`
