### ISSUE TITLE
[Crash] sslTrust (WebSocket.swift:275)

### ISSUE THREAD

**Issue by decazuk** [daltoniam/Starscream#684]
On version 3.1.0
Here's the strac trace via bugly

0 libobjc.A.dylib | objc_retain + 16
1 Starscream | sslTrust (WebSocket.swift:275)
2 Starscream | sslTrust (<compiler-generated>:0)
3 Starscream | _$s10Starscream9WebSocketC19initStreamsWithData33_E91840E7069A0D2D302D042308E9D928LLyy10Foundation0G0V_SitFys5Error_pSgcfU_yycfU_ (WebSocket.swift:688)
4 Starscream | _$sIeg_IeyB_TR (<compiler-generated>:0)
5 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
6 Foundation | -[NSBlockOperation main] + 72
7 Foundation | -[__NSOperationInternal _start:] + 848
8 Foundation | ___NSOQSchedule_f + 404
9 libdispatch.dylib | __dispatch_client_callout + 16
10 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$armv81 + 416
11 libdispatch.dylib | __dispatch_async_redirect_invoke$VARIANT$armv81 + 596
12 libdispatch.dylib | __dispatch_root_queue_drain + 592
13 libdispatch.dylib | __dispatch_worker_thread3 + 112
14 libsystem_pthread.dylib | _pthread_wqthread + 1176

**Comment by daltoniam** [comment]
unfortunately this doesn't give us much to help debug with. It could be a lot of things with a generic error like this. I'd recommend upgrading to 4.0.0 since that is the latest and refactor how SSL logic is handled.
