### ISSUE TITLE
Maximum concurrent sendings

### ISSUE THREAD

**Issue by Lucky1st** [daltoniam/Starscream#686]
I wrote my own queue for sending operations for granting successful sending from async queues of my app. Do I still have to use it or Starscream Framework does it himself?

**Comment by daltoniam** [comment]
Not completely sure what you are asking, but Starscream allows custom async queues for callbacks. It handles on the framing and logic in an async matter as well, so shouldn't need to put the write and connect logic on their own queues necessarily.
