### ISSUE TITLE
Using this with the Fleck Websocket Server C#

### ISSUE THREAD

**Issue by jshafer817** [daltoniam/Starscream#689]
Anyone had starscream and fleck to play nice? I am just trying to send a string from starscream to fleck. Tried settings subprotocol negotiation, etc. No dice. I can send a message from another websocket library for swift, but.. it uses a TON of memory.

**Comment by daltoniam** [comment]
I haven't personally used Fleck, but I'd try upgrading to 4.0.0 as it refactor a lot of the connection logic. Starscream is RFC compliant though, so it should work with any WebSocket server that is also compliant.
