### ISSUE TITLE
Please upgrade pod install

### ISSUE THREAD

**Issue by szuniverse** [daltoniam/Starscream#70]
Hi.
Thanks the swift 1.2 upgrade works fine, but please upgrade the cocoapods installation also because it still install the 0.9.2 version. Thanks. Great work!

**Comment by daltoniam** [comment]
Thanks. I pushed an update yesterday, try running `pod update` and see if that pulls the 0.9.3 version.

**Comment by szuniverse** [comment]
Okey. Now works fine :) Thanks!
