### ISSUE TITLE
Why is Starscream not working anymore on real Apple Watch (WatchOS 6)?

### ISSUE THREAD

**Issue by JackieNBee** [daltoniam/Starscream#701]
Hi guys!

First I want to thank you for developing Starscream, it's such a good library and it helped me a lot in my projects. 
But recently I run into a problem :(

I updated my Apple Watch to WatchOS 6, my iPhone to iOS 13.1, Xcode to 11.1. MacOS still 10.14.6.

I've created an Independent Apple Watch project where I test the communication between the Watch and a WebSocket server using Starscream: ws://echo.websocket.org/

It **works perfectly on the Simulator** but on **real Apple Watch** when I try to connect to the server I **got these errors**:

    2019-10-08 18:57:53.064887+0200 BackgroundWebSocketOnlyWatch WatchKit Extension[251:31011] [] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection

    2019-10-08 18:57:53.068928+0200 BackgroundWebSocketOnlyWatch WatchKit Extension[251:31011] TCP Conn 0x16d8d5f0 Failed : error 0:50 [50]

    websocket is disconnected: Optional("The operation couldn’t be completed. Network is down")

I'll show you the code of my app:

**InterfaceController.swift**

    import WatchKit
    import Foundation
    import Starscream

    class InterfaceController: WKInterfaceController, WebSocketDelegate {
    
    let socket = WebSocket(url: URL(string: "ws://echo.websocket.org/")!)
    
    @IBOutlet var label: WKInterfaceLabel!
    
    /**************************************************************************************************/
    
    override func awake(withContext context: Any?) {
        super.awake(withContext: context)
        
        socket.delegate = self
    }
    
    override func willActivate() {
        // This method is called when watch view controller is about to be visible to user
        super.willActivate()
    }
    
    override func didDeactivate() {
        // This method is called when watch view controller is no longer visible
        super.didDeactivate()
    }
    
    /************************************************************************************************/
    
    @IBAction func connectButtonPressed() {
        
        socket.connect()
    }
    
    @IBAction func sendButtonPressed() {
        
        socket.write(string: "Hi!")
    }
    
    @IBAction func disconnectButtonPressed() {
        
        socket.disconnect()
    }
    
    /******************************************************************************************/
    
    func websocketDidConnect(socket: WebSocketClient) {
        print("websocket is connected")
        label.setText("Connected")
    }
    func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        print("websocket is disconnected: \(error?.localizedDescription)")
        label.setText("Disconnected")
    }
    func websocketDidReceiveMessage(socket: WebSocketClient, text: String) {
        print("got some text: \(text)")
        label.setText("Received: \(text)")
        createVibration()
        
    }
    func websocketDidReceiveData(socket: WebSocketClient, data: Data) {
        print("got some data: \(data.count)")
    }
    /******************************************************************************************/
    
    // Creates vibration
    func createVibration() {
        
        WKInterfaceDevice.current().play(.notification)
        print("Vibration created")
    }
}

I tried using **Starscream** with **iOS 13.1** and it **works perfectly both on Simulator and real iPhone**.

Is this a **bug** of WatchOS 6 or is Starscream that needs an update?

Thanks in advance! :)

**Comment by Rexios80** [comment]
Getting the exact same error here

**Comment by atirit** [comment]
I am as well.

**Comment by atirit** [comment]
As a stopgap I've decided to use [`URLSessionWebSocketTask`](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask).

Note that even on previous versions of watchOS, Starscream only worked in the Simulator. This is because in watchOS < 6, streaming APIs such as `NSStream` are disabled on the device but not in the Simulator (which is stupid). However, those APIs have been re-enabled in watchOS 6, so I'm unsure what exactly is preventing Starscream from working.

**Comment by atirit** [comment]
Upon looking through the library, there are still a lot of instances of

    #if os(watchOS) //watchOS us unfortunately is missing the kCFStream properties to make this work
    #else
        ...
    #endif
I suspect that may be part of the problem.

**Comment by daltoniam** [comment]
Version 4.0.1 added support for URLSessionWebSocketTask APIs in version 4.0.1 which was released today!
