### ISSUE TITLE
Version 3.1.0 Info.plist set to 3.0.5

### ISSUE THREAD

**Issue by dessmith** [daltoniam/Starscream#703]
The Info.plist in version / tag 3.1.0 is set to 

Version 3.1.0 [Info.plist](https://github.com/daltoniam/Starscream/blob/3.1.0/Sources/Info.plist) set to 3.0.5

```
	<key>CFBundleShortVersionString</key>
	<string>3.0.5</string>
```

This caused me a few hours of head scratching when dealing I was updating multiple framework dependancies and wondering why Carthage kept getting 3.0.5 of Starscream.

Please fix in a future release, thanks.

**Comment by fassko** [comment]
Hey @dessmith could you help out with a PR? I will merge it. Thanks!

**Comment by dessmith** [comment]
@fassko Sure I can set the version to 3.1.0 would you move the git tag to fix, or would it be a new version?

**Comment by fassko** [comment]
Let's make it as a patch version 3.1.1 Thanks!

**Comment by fassko** [comment]
Thanks @dessmith! Version got updated.
