### ISSUE TITLE
websocketDidReceiveData func call again 

### ISSUE THREAD

**Issue by TuralVeli** [daltoniam/Starscream#705]
![Screen Shot 2019-10-15 at 15 46 11](https://user-images.githubusercontent.com/46748438/66829578-b7260100-ef64-11e9-8ac3-32baf18f364f.png)
this is my problem

**Comment by daltoniam** [comment]
See the example projects on how to properly implement the delegate. For example:

https://github.com/daltoniam/Starscream/blob/master/examples/SimpleTest/SimpleTest/ViewController.swift
