### ISSUE TITLE
WebSocket.write(data: ) is not writing to the socket server. 

### ISSUE THREAD

**Issue by MaruthiBasava** [daltoniam/Starscream#707]
Tested by adding a completion handler to see if it's being called, but unfortunately, it is not. I swapped out to another library to check if my socket server might have been the issue, but the other swift socket library worked fine; however, I would like to stick to using Starscream.

**Comment by daltoniam** [comment]
This is probably a byproduct of the old 3.X.X codebase. I will close this out and if it is still a problem, please open a new issue with steps on how to reproduce. Thanks!
