### ISSUE TITLE
I get an error "No such module SSCZLib"  when i use .xcframework bundle  in my project ，what can i do to deal it

### ISSUE THREAD

**Issue by chenxiaopao** [daltoniam/Starscream#710]
![截屏2019-10-24下午3 07 43](https://user-images.githubusercontent.com/28309377/67461506-1627fc00-f670-11e9-9209-bff4cec9cdd0.png)

**Comment by daltoniam** [comment]
This should be resolved in 4.0.0 as it no longer has a dependency on these libraries.
