### ISSUE TITLE
Write empty data will give an error

### ISSUE THREAD

**Issue by 954788** [daltoniam/Starscream#714]
Hello, my server needs to receive null data to disconnect the link. When I send empty data, this error occurs, how can I solve it?

` 
let data = Data.init() 
self.websocket?.write(data: data)
`

`Starscream was compiled with optimization - stepping may behave oddly; variables may not be available.
/Users/Fatm/Library/Developer/Xcode/DerivedData/VoiceBook-dctiihmtfqcadwbprkkjcalevtuw/Build/Products/Debug-iphoneos/VoiceBook.app/Frameworks/Starscream.framework/Starscream: Cannot load Swift type information; failed to initialize ClangImporter: error: virtual filesystem overlay file '/Users/Fatm/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/Starscream/3.1.0/Build/Intermediates.noindex/ArchiveIntermediates/Starscream/IntermediateBuildFilesPath/Starscream.build/Release-iphoneos/Starscream.build/all-product-headers.yaml' not found`

**Comment by daltoniam** [comment]
I'm not sure that error is related to the issue. That error is a build error and won't affect runtime issues like data not being written. Also I'd suggest upgrading to version 4.0.0 as it refactor had connection processing is handled. If the issue still persist after upgrading feel free to reopen this issue. Thanks!
