### ISSUE TITLE
starscream 3.1.1 version: Invalid argument when connecting to WebSocket

### ISSUE THREAD

**Issue by sreevidyaJ** [daltoniam/Starscream#717]
Hi Team,

I get invalid argument error when connecting to WebSocket.
Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}

code:
var request = URLRequest(url: URL(string: “< wss socket url>")!)
        request.setValue("x-webkit-deflate-frame", forHTTPHeaderField: "Sec-WebSocket-Extensions")
        let stream = FoundationStream()
        stream.enableSOCKSProxy = true;
        socket = WebSocket(request: request, stream: stream)

I have checked the server logs, and below is the log details.

WebSocket session established. 
2019-11-28 08:43:45.057 ERROR 1 --- [nio-8042-exec-8] o.s.w.s.s.s.DefaultHandshakeHandler : Handshake failed due to invalid Upgrade header: null

I have debugged through Xcode and saw that request has upgrade header. 

Can anyone please help me

Thanks,
Sreevidya

**Comment by daltoniam** [comment]
The sever is rejecting the connection because the upgrade HTTP header isn't correct. Try setting that header to what the server expects and that should hopefully resolve the error. Best of luck!

https://github.com/daltoniam/Starscream#custom-headers-protocols-and-timeout
