### ISSUE TITLE
Warning 'couldn't find pc file' when using SwiftPM

### ISSUE THREAD

**Issue by nkristek** [daltoniam/Starscream#719]
When importing Starscream version 3.1.1 (currently latest) using SwiftPM I get the warning `couldn't find pc file`. I tried version 3.1.1 and master branch, when using 3.1.0, the warning does not appear.

## Steps to reproduce
- create new iOS project (File > New > Project > iOS > Single View App)
- add SwiftPM dependency (File > Swift Packages > Add Package Dependency...), select either exact version 3.1.1 or branch master
- build

**Comment by patburns** [comment]
Also have this warning. It's because of this issue in swift-nio-zlib-support:

https://github.com/apple/swift-nio-zlib-support/issues/3

Of which starscream currently depends on.

**Comment by patburns** [comment]
I commented in the other two threads. I don't have the context on why streamscreeam uses swift-nio-zli-support, but you can "silence" this warning by installing pkg-config on the device that you are compiling on:

`brew install pkg-config`

This really isn't a fix but a workaround. Maybe it should be considered adding this to the documentation for this project? Or maybe evaluated how swift-nio-zli-support is being used?

**Comment by nkristek** [comment]
Thank you for that workaround

**Comment by yspreen** [comment]
Two and a half months later and it's still an issue... Do I really have to add this to the common issues page of our project? Or is there a proper fix?

**Comment by yspreen** [comment]
Since 3.1.0 does not have this issue, is there any crucial functionality missing from the latest version>

**Comment by nkristek** [comment]
This issue seems to come from swift-nio. Thus I will close this issue, thanks!
