### ISSUE TITLE
Bug: UInt64 maybe negativ

### ISSUE THREAD

**Issue by szuniverse** [daltoniam/Starscream#72]
Hi.

Very often get a runtime error on the latest version.

This is around the 500. row:
var len = dataLength
if dataLength > UInt64(bufferLen) {
    len = UInt64(bufferLen-offset) // runtime error position
}

the bufferLen value is 8, and the offset value is 10. I dont know how it happens but it will be negativ..
Unfortunately I didnt implement the server so I cannot check it. maybe it would be a good way to handle this case in this library.

**Comment by daltoniam** [comment]
Yeah a `UInt64` should never be negative as it is unsigned. I'm not sure how the bufferLen could be 8 and the offset be 10. That would equal -2 which certainly would crash an unsigned number. The code you are referencing means the webSocket frame (packet) doesn't have a full `UInt64` value to read the length of the data. Can you verify what the size of `dataLength`? There isn't an easy way to handle this in the library as a webSocket packet should always all of it's framing information.

**Comment by daltoniam** [comment]
@szuniverse where you able to verify with the size of `dataLength` was or track down any more information?

**Comment by szuniverse** [comment]
Unfortunately in the last few weeks I couldn't working on my project. So I will write more details If I will have enough time

**Comment by daltoniam** [comment]
OK sounds good. I will go ahead and close this issue out until then. Just reopen it when you are ready.

**Comment by wispur** [comment]
@daltoniam 
Hello~
We are facing the same issue, in our case the dataLength is 126, which means we should have 2 more byte following to read, however the bufferLen is only 3 (offset being 4).
We suspect we would need to create a temporary  WSResponse in order to postpone the processing just like if we lack normal data even though this is a rare case.

**Comment by daltoniam** [comment]
@wispur thanks for the report. If you get any details on a consistent way to reproduce this, let me know and I will look into it.

**Comment by wispur** [comment]
@daltoniam Thanks for the reply too! I am also trying to reproduce this issue reliably, so far this issue just pops randomly when I do not expect it to happen :(

**Comment by szuniverse** [comment]
Hi. Last past days I tried to reproduce this bug on a consistent way but I cant.. 
But this bug is crashes the app, so if there any solution to doesnt crash the app, maybe receive an error message or something like this, but worst thing when the app crashed...

**Comment by daltoniam** [comment]
If I knew what was causing the crash, I would just fix it :smile:. It isn't something that can just be handled and not crash, we have to track down a cause and hopefully a fix. My working theory is that a huge packet is coming through, but is fragmented just right, so we can't read the expect length of the packet. I am going to try adding that protection logic and see if it resolves the issue. I will try to do that in the next few days, but no promises as it has been a busy last few weeks.

**Comment by daltoniam** [comment]
@szuniverse try adding this at line 499 (right below the dataLength checkers):

```swift
if bufferLen < offset {
    fragBuffer = NSData(bytes: buffer, length: bufferLen)
    return
}
```

Also here is a screenshot for reference:
![screen shot 2015-07-06 at 10 34 06 am](https://cloud.githubusercontent.com/assets/905059/8528822/96e88198-23ca-11e5-814f-45281be9379a.png)

**Comment by szuniverse** [comment]
Okey. thanks a lot! I will "test" it, I hope the crash will dissapear without side effect :)
Will you add these lines to the official version later?

**Comment by daltoniam** [comment]
Yes I will, hoping it works :smile: . Let me know if it fixes and I will add it into the official release.

**Comment by szuniverse** [comment]
Well, It works fine. The runtime crash has been resolved, but give me one week to test it. I will write you soon.

**Comment by daltoniam** [comment]
Great to hear. If all goes well, we can run it threw the autobahn tests again and cut a new version!

**Comment by szuniverse** [comment]
Okey. I tested it on this weekend and everything works fine. The crash has been resolved :)
I think its time to make autobahn tests again and cut a new version!

**Comment by daltoniam** [comment]
Awesome! I will try and run the test some time this week and cut the new version.

**Comment by szuniverse** [comment]
Hi! Do you merged this bug fix to the master?

**Comment by daltoniam** [comment]
I did, master should have all the fixes. Haven't create the new tag yet, was finishing the final touches on an autobahn test/example before creating the 0.9.4 tag.

**Comment by szuniverse** [comment]
Awesome! :)
