### ISSUE TITLE
No notification when timeout.

### ISSUE THREAD

**Issue by JorgenTeckro** [daltoniam/Starscream#725]
I'm getting no notification when the socket loses connection.
This can be from either server side or the internal socket. I'm using the boilerplate stuff for now.

```
 // MARK:- Websocket
  
  func connectSocket() {
    var request = URLRequest(url: URL(string: webSocketURL)!)
    request.addValue(NetworkManager.shared.accessToken, forHTTPHeaderField: "AccessToken")
    request.addValue(NetworkManager.shared.idToken, forHTTPHeaderField: "IdToken")
    request.timeoutInterval = 10000
    socket = WebSocket(request: request)
    socket?.delegate = self
    socket?.connect()
  }

  func didReceive(event: WebSocketEvent, client: WebSocket) {
    switch event {
      case .connected(let headers):
        isConnected = true
        print("websocket is connected: \(headers)")
      case .disconnected(let reason, let code):
        isConnected = false
        print("websocket is disconnected: \(reason) with code: \(code)")
      case .text(let string):
        print("Received text: \(string)")
      case .binary(let data):
        print("Received data: \(data.count)")
      case .ping(_):
        break
      case .pong(_):
        break
      case .viablityChanged(_):
        break
      case .reconnectSuggested(_):
        break
      case .cancelled:
        isConnected = false
      case .error(let error):
        isConnected = false
        handleError(error)
    }
  }
  
  func handleError(_ error: Error?) {
    if let e = error as? WSError {
      print("websocket encountered an error: \(e.message)")
    } else if let e = error {
      print("websocket encountered an error: \(e.localizedDescription)")
    } else {
      print("websocket encountered an error")
    }
  }
```
  
I was expecting something to come in on the event, specially from the server when it does timeout. That way I can get it to connect again.

Thankful for any help.

**Comment by my-mo** [comment]
Same here. I am using version `3.1.1`. I was expecting to get some kind of error reported if the connection is suddenly closed. Ie running on the simulator and during transmission of data switching off the wifi (to rudimentary simulate a connection being lost). I get no error at all.

Thank you.

**Comment by JorgenTeckro** [comment]
Looking at the repo, the WebsocketEvent has very few cases in the enum.

**Comment by fassko** [comment]
I can tell that CFNetwork has some issues with sockets at some point when connection is dropped. I have tested and seen myself. Unfortunately I don't have a solution other than sending and receiving PING-PONG's.

**Comment by JorgenTeckro** [comment]
Hi,

Thanks for looking into this.
The problem is actually in the enum for the response.
I found a solution to the problem by using SwiftWebSocket instead.

Best regards

[signature_1603670256]
Jörgen Andreasson
Senior iOS Developer
e: jorgen.andreasson@teckro.com<mailto:jorgen.andreasson@teckro.com>
m. +353 86 770 7086
w. www.teckro.com

Follow us:
[signature_63354329]<https://linkedin.com/company/teckro/>[signature_1748975659]<https://www.facebook.com/teckroofficial/>[signature_1908014282]<https://twitter.com/teckroofficial>[signature_1247791527]<https://instagram.com/teckroofficial/>[signature_1655354313]<https://www.youtube.com/channel/UCFU2XOzcBvpUyLQ-nggI4Dw/>

**Comment by fukemy** [comment]
thanks i will try to using swiftwebsocket
