### ISSUE TITLE
WebSocket instantly disconnect on iOS 10 using Starscream 4.0.0

### ISSUE THREAD

**Issue by p-rob** [daltoniam/Starscream#728]
Starscream: 4.0.0
iOS: 10.3.4
Devices: iPhone 5 (MD299F/A) - iPad pro (9.7 inches; simulator) 

When connecting to a secure web-socket (wss:// or https://) the framework instantly send a `.cancelled` event coming from `FoundationTransport.stream(_ aStream: Stream, handle eventCode: Stream.Event)` `.endEncountered` event.

After further investigation, it looks like `FoundationTransport.getSecurityData()` always return nil.

**Comment by martinpristas** [comment]
Same here
