### ISSUE TITLE
Fatal error: Index out of range

### ISSUE THREAD

**Issue by Tayphoon** [daltoniam/Starscream#730]
Framer crashed when try read server packet
 
![Screenshot 2020-01-24 at 15 54 54](https://user-images.githubusercontent.com/1618506/73070666-f21fc500-3ec1-11ea-876e-5d2c6f0863ea.png)

**Comment by fassko** [comment]
Can you tell what do you get from server? Can you reproduce and debug this?

**Comment by JimmyKongM800** [comment]
This happens when receiving disconnect event from server.

`var offset = 2
    
        if isControlFrame && payloadLen > 125 {
            return .failed(WSError(type: .protocolError, message: "payload length is longer than allowed for a control frame", code: CloseCode.protocolError.rawValue))
        }
        
        var dataLength = UInt64(payloadLen)
        var closeCode = CloseCode.normal.rawValue
        if opcode == .connectionClose {
            if payloadLen == 1 {
                closeCode = CloseCode.protocolError.rawValue
                dataLength = 0
            } else if payloadLen > 1 {
                let size = MemoryLayout<UInt16>.size
                closeCode = pointer.readUint16(offset: offset)
                offset += size
                dataLength -= UInt64(size)
                if closeCode < 1000 || (closeCode > 1003 && closeCode < 1007) || (closeCode > 1013 && closeCode < 3000) {
                    closeCode = CloseCode.protocolError.rawValue
                }
            }
        }`

Sometimes, payloadLen > 1, pointer.count == 2, offset == 2.
