### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by dsngeu** [daltoniam/Starscream#731]
when I try to connect socket I got the following error 
-9858: Optional(handshake failed))
but when I use other socket library it works fine.

**Comment by cbhaiji** [comment]
I am also getting the same error.

**Comment by fassko** [comment]
I have feeling that this is related to https://github.com/daltoniam/Starscream/issues/726

**Comment by tapz** [comment]
#726 fixed the problem.

**Comment by daltoniam** [comment]
4.0.1 was released that I think should resolve this issue. If not, please open an issue with detailed report/example code. Thanks!
