### ISSUE TITLE
Any guidance on SSL pinning

### ISSUE THREAD

**Issue by yghaile** [daltoniam/Starscream#732]
I know your documentation says "TODO: Update docs on how to load certificates and public keys into an app bundle, use the builtin pinner and TrustKit."  I searched around, but could not find any good examples.  I'm working in Swift, but anything would be helpful.

I'm currently using TrustKit with IOS's URLSession, but when using it there, I just override the delegate function.  I don't see that here for Starscream.  I'm quite lost and any guidance would be much appreciated.

**Comment by yghaile** [comment]
Am I suppose to create a custom FoundationSecurity class, then override the evaluateTrust method?

**Comment by igorkulman** [comment]
I see that `WebSocket` has a `security` property when I can assign my own implementation of `Starscream.SSLTrustValidator`. I looked into that protocol and it has just one method `isValid(_ trust: SecTrust, domain: String?) -> Bool`.

This method looks like a match for `Trustkit`s `TSKPinningValidator.evaluateTrust(serverTrust: SecTrust, forHostname: String)`. 

Is this the way to got with `Trustkit`? I tried taking this route but there are a few things not clear to me

```
final class TrustkitSSLTrustValidator: Starscream.SSLTrustValidator {
    func isValid(_ trust: SecTrust, domain: String?) -> Bool {
        guard let domain = domain else {
            // can this even happen? is it really a fail?
            return false
        }

        let pinningValidator = TrustKit.sharedInstance().pinningValidator
        let result = pinningValidator.evaluateTrust(serverTrust: trust, forHostname: domain)
        switch result {
        case .shouldAllowConnection:
           return true
        case .shouldBlockConnection:
           return false
        case .domainNotPinned:
          // should this perform a default cert chain validation? or is this done by Starscream before even calling this method?
        }
    }
}
```

**Comment by jerbob92** [comment]
@igorkulman coincidentally I'm also working on integrating TrustKit with Starscream, however, I'm doing it in NativeScript (TypeScript), so I'm not sure my code would help you, so I'm just describing to you how I did it:

1. Create an instance of [FoundationSecurity](https://github.com/daltoniam/Starscream/blob/master/Sources/Security/FoundationSecurity.swift#L40), we will use it for when pinning succeeded or when no pinning was done for the domain, so we can still do the default SSL checks.
2. Create your own class that implements the [CertificatePinning](https://github.com/daltoniam/Starscream/blob/master/Sources/Security/Security.swift#L37) protocol with the `evaluateTrust` func
3. In your evaluateTrust func, add the following:
```
let pinningValidator = TrustKit.sharedInstance().pinningValidator
let result = pinningValidator.evaluateTrust(serverTrust: trust, forHostname: domain)

// Do default behaviour/FoundationSecurity checks when not pinned or allowed.
if result == .domainNotPinned || result == .shouldAllowConnection {
  foundationSecurityInstance.evaluateTrust(trust, domain, completion);
  return
}

// Should block connection.
// @todo: Create a new error here, something that says that certificate pinning failed
completion(.failed(error));
```
This code is obviously not tested, I don't have access to OSX right now, but something like this should work.
Hope it helps!

**Comment by igorkulman** [comment]
> @igorkulman coincidentally I'm also working on integrating TrustKit with Starscream, however, I'm doing it in NativeScript (TypeScript), so I'm not sure my code would help you, so I'm just describing to you how I did it:
> 
>     1. Create an instance of [FoundationSecurity](https://github.com/daltoniam/Starscream/blob/master/Sources/Security/FoundationSecurity.swift#L40), we will use it for when pinning succeeded or when no pinning was done for the domain, so we can still do the default SSL checks.
> 
>     2. Create your own class that implements the [CertificatePinning](https://github.com/daltoniam/Starscream/blob/master/Sources/Security/Security.swift#L37) protocol with the `evaluateTrust` func
> 
>     3. In your evaluateTrust func, add the following:
> 
> 
> ```
> let pinningValidator = TrustKit.sharedInstance().pinningValidator
> let result = pinningValidator.evaluateTrust(serverTrust: trust, forHostname: domain)
> 
> // Do default behaviour/FoundationSecurity checks when not pinned or allowed.
> if result == .domainNotPinned || result == .shouldAllowConnection {
>   foundationSecurityInstance.evaluateTrust(trust, domain, completion);
>   return
> }
> 
> // Should block connection.
> // @todo: Create a new error here, something that says that certificate pinning failed
> completion(.failed(error));
> ```
> 
> This code is obviously not tested, I don't have access to OSX right now, but something like this should work.
> Hope it helps!

That is basically my code posted above just without answering the questions. You asume that when domain is not pinned it OK, which I am not sure about, it can be an expired cert, or cert with invalid chain and it is not known if it gets validated or ignored .

**Comment by jerbob92** [comment]
@igorkulman Sounds like you didn't really read what I said. 
I did answer those questions. When pinning is OK or domain is not pinned, we call FoundationSecurity to do the other SSL checks, like invalid certs. You can compare this to `PerformDefaultHandling` in `NSURLSession`.

**Comment by daltoniam** [comment]
Thanks @jerbob92!
