### ISSUE TITLE
Responding to StarScream connection error codes

### ISSUE THREAD

**Issue by alexandermcpherson** [daltoniam/Starscream#733]
I am using version `3.1.1` and we are trying to respond to connection error codes. I see in an example we cast an `error` as `WSError` so that we can respond based on a code but from testing I can see that we dont get back a `WSError` when a connection error does occur.

Example it never seems to hit the WSError block and give us just an error with a message and no code.

```public func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
        if let error = error as? WSError {
            if error.code != CloseCode.normal.rawValue {
                delegate?.didReceiveResponse(errorCode: error.code, errorMessage: error.message)
                onErrorReceived?(error.code, error.message)
            } else {
                delegate?.didDisconnect()
                onConnected?(false)
            }
        } else if let error = error { // We seem to get this... If I turn on airplane mode during a connection I would expect a WSError not an Error with a code to indicate the network has been lost?
            delegate?.didReceiveResponse(errorCode: nil, errorMessage: error.localizedDescription)
            onErrorReceived?(nil, error.localizedDescription)
        } else {
            delegate?.didDisconnect()
            onConnected?(false)
        }
    }

**Comment by fassko** [comment]
Do you have any idea what is server giving back?

**Comment by my-mo** [comment]
Well the server doesn't and wont give anything back if I cut the connection with using Airplane mode for example. Trying to simulate the server either going away or the connection cutting to get 2 different errors to respond accordingly to.

**Comment by my-mo** [comment]
Solved if you cast the error as NSError as below you will get a code you can switch on

```else if let error = error as NSError? {
            print("\(error.code)")
        }```
