### ISSUE TITLE
Error "notAnUpgrade(403)" when trying to connect.

### ISSUE THREAD

**Issue by f6qpQNBA3p** [daltoniam/Starscream#736]
Hello
I try to connect to an app server that use Kurento Media Server but I get this error : "notAnUpgrade(403)"

I am able to connect using Java-WebSocket from TooTallNate, also using SocketRocket.
The url looks like this : "wss://123.123.123.123:8443/groupcall"

Can someone help me please ?

**Comment by f6qpQNBA3p** [comment]
I will try again tomorrow using the same headers from this link : https://doc-kurento.readthedocs.io/en/6.13.0/user/installation.html#check-your-installation

I will tell you the result

**Comment by f6qpQNBA3p** [comment]
I still have the same error :(

**Comment by f6qpQNBA3p** [comment]
I am now connecting using URLSessionWebSocketTask, I leave the issue open in case it can help.

**Comment by ergunkocak** [comment]
Sample code would be more helpful ;)

**Comment by daltoniam** [comment]
@ergunkocak agreed 😄. I would suggest upgrading to 4.0.1. A 403 HTTP response code is pretty generic and could be a lot of things, so I can't help troubleshoot without more details. Also 4.0.1 is now using URLSessionWebSocketTask under the hood when possible.
