### ISSUE TITLE
-9808: Optional(bad certificate format)

### ISSUE THREAD

**Issue by SparklingAir** [daltoniam/Starscream#738]
Hello! I updated the library from version 3 to version 4, and I got this error:
-9808: Optional(bad certificate format)

The socket does not connect at all :(

**Comment by my-mo** [comment]
Yeah I've not managed to get V4 working at all. V3 is working but its got a few issues. Namely its error handling is a bit of a pain.

**Comment by Mohamed-Afsar** [comment]
@SparklingAir Did you manage to fix it?. Facing the same issue.

**Comment by viki1024** [comment]
> Yeah I've not managed to get V4 working at all. V3 is working but its got a few issues. Namely its error handling is a bit of a pain. Other than that its a great library.

+1

**Comment by daltoniam** [comment]
Sorry I can't help without more context. Try upgrading to 4.0.1 as it address a few bugs from the 4.0.0 release. If that doesn't work, please open a detail report so we can help track down the issue.
