### ISSUE TITLE
dyld: Symbol not found:

### ISSUE THREAD

**Issue by alikazim** [daltoniam/Starscream#74]
updated the starscream in my project and getting this error.

dyld: Symbol not found: __TWPSSSs8Hashable
  Referenced from: /private/var/mobile/Containers/Bundle/Application/9F09CA1E-A5B7-400E-84BF-82ED8C410341/jamesAppV2.app/Frameworks/Starscream.framework/Starscream
  Expected in: /private/var/mobile/Containers/Bundle/Application/9F09CA1E-A5B7-400E-84BF-82ED8C410341/jamesAppV2.app/Frameworks/libswiftCore.dylib
 in /private/var/mobile/Containers/Bundle/Application/9F09CA1E-A5B7-400E-84BF-82ED8C410341/jamesAppV2.app/Frameworks/Starscream.framework/Starscream
(lldb) 

and crashed

Can you please tell me the way how to add starScream Library in my project using swift 1.2

**Comment by szuniverse** [comment]
the easiest way with pod install
https://cocoapods.org/

**Comment by daltoniam** [comment]
I have used both cocoapods and manual install of the framework without issue. I assume your are trying to deploy this to a real device. You have to add the framework to the copy phase so it will be available to your app. You need to follow:
https://github.com/daltoniam/Starscream#add-copy-frameworks-phase

Might also want to clean your build folder. Hold `Option` while the Product menu is open in Xcode, which will change Clean to Clean Build Folder. Select the Clean Build Folder.
