### ISSUE TITLE
Can't connect to WebSocket with compression.

### ISSUE THREAD

**Issue by svmakarov** [daltoniam/Starscream#743]
Hello, we trying to connect to WebSocket with compression and get error.

In documentation we can find property enableCompression of WebSocket class but there is no such property in last version of Starscream.

We understand that we should init WebSocket class with compressionHandler parameter to enable compression, is it right?
let socket = WebSocket(request: urlRequest, compressionHandler: WSCompression())

But if we init WebSocket with compressionHandler then we receive error "not valid UTF-8 data" after connected event. Looks like we can successfully connect but get error when server send us first message.

Compression on web socket server works correctly, we can successfully  work with it in browser with JavaScript, for example. We use Boost Beast to manage WebSocket on server.

Do you have any ideas why we can get "not valid UTF-8 data" error? And how we can fix it?

**Comment by svmakarov** [comment]
Looks like we have discover the problem. Situation is following:
1. Starscream send to the server request with following headers
permessage-deflate; client_max_window_bits; server_max_window_bits=15
2. Server (Boost.Beast) response with following headers
permessage-deflate;
The response do not contains server_max_window_bits header and Starscream in such case do not make decompression. Decompressor creates in WSCompression only when server send server_max_window_bits header.

For our case we have found workaround and Boost.Beast send server_max_window_bits header now (we decrease default value from 15 to 14 in Boost.Beast) and it works for us now.

May be more correct behaviour for Starscream is create Compressor and Decompressor if permessage-deflate header exists, but I'm not sure.

**Comment by daltoniam** [comment]
Yeah I'm not sure why it won't return that header as it is in the RFC:
https://tools.ietf.org/html/rfc7692#section-7

Honestly I haven't looked at the compression code in a while and I would need to comb through it and the boost code to figure out which side wasn't implemented to the RFC standards. 

Anyway, I'm glad you where able to track down the problem and thank you for the detailed follow up.
