### ISSUE TITLE
disableSSLCertValidation Not anymore compiling

### ISSUE THREAD

**Issue by jbarros35** [daltoniam/Starscream#745]
Hi,

I have to test local signed certificates, I was reading old threads on how to achieve that and found disableSSLCertValidation but this attribute is not available anymore...

I'm version 4.0.0

**Comment by jbarros35** [comment]
Downgraded for previous version 3.0.0 if its the expected thing not supporting this for 4.0 please let us know and close it for good.
Thank you

**Comment by daltoniam** [comment]
It is still there, just a different pattern to allow more customization. I added an example to the documentation with the 4.0.1 release: 
https://github.com/daltoniam/Starscream#ssl-pinning
