### ISSUE TITLE
Invalid HTTP upgrade, code: 429

### ISSUE THREAD

**Issue by MrShiY** [daltoniam/Starscream#747]
error log - Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 429)

Starscream version is 3.0.5, my customer encountered this error frequently when connecting to Websocket, could you give some suggestions?

**Comment by daltoniam** [comment]
I don't know without more context, but it appears your server is rate limiting the requests (hence the 429 response code). This isn't a Starscream issue but something specific to your environment.
