### ISSUE TITLE
Support certificate pinning

### ISSUE THREAD

**Issue by chickenlittle** [daltoniam/Starscream#75]
Can Starscream support certificate pinning similar to that of AFNetworking? This is how do it in their API.
   let securityPolicy = AFSecurityPolicy(pinningMode: AFSSLPinningMode.Certificate)
    let certificatePath = NSBundle.mainBundle().pathForResource("pinned-certificate", ofType: "cer")!
    let certificateData = NSData(contentsOfFile: certificatePath)!
    securityPolicy.pinnedCertificates = [certificateData];
    securityPolicy.validatesCertificateChain = false
    self.securityPolicy = securityPolicy

**Comment by daltoniam** [comment]
I would like to see SSL pinning added to Starscream. I personally haven't had the time to research and implement a solution yet, so Pull Requests are welcomed.

**Comment by daltoniam** [comment]
I checked a SSL pinning option into master. I don't have a easy way to test it right now, so feedback would be appreciated.

https://github.com/daltoniam/Starscream#ssl-pinning
