### ISSUE TITLE
Version 4.0.1 not pushed to CocoaPods repository

### ISSUE THREAD

**Issue by michalcichon** [daltoniam/Starscream#750]
Please push the newest changes to the CocoaPods repository. On [CocoaPods](https://cocoapods.org/pods/Starscream) there still is 4.0.0. There was quite a critical change where we evaluate trust based on the host (instead of absolute URL).

```
git tag 4.0.1
git push origin 4.0.1
pod spec lint
pod trunk push
```

**Comment by jerbob92** [comment]
Can someone please push 4.0.1? Certificate pinning won't work without this change. @daltoniam

**Comment by daltoniam** [comment]
Pushed! Should be live.
