### ISSUE TITLE
Errors "notAnUpgrade : 200" and ""masked and rsv data is not currently supported""

### ISSUE THREAD

**Issue by Shalena** [daltoniam/Starscream#751]
Hi)
I have a situation:
First time in func didReceive(event: WebSocketEvent, client: WebSocket) I have  "viablityChanged : true".
After that I am appearing in this function second time  and have "notAnUpgrade : 200"
3d time I have "masked and rsv data is not currently supported"
What is the reason of this errors? How can I handle the problem?
Thank you)

**Comment by Vlada31R** [comment]
Hi, I have the same problem, do you have any ideas?

**Comment by daltoniam** [comment]
Sorry, but I can't help without context. Based on the response it looks like you are getting an HTTP response instead of the 101 switching protocols response expected by a Websocket server. Make sure you are using a Websocket server and not just a HTTP server. Best of luck!

**Comment by Shalena** [comment]
Hi)
Thank you for the answer. In my case I found that I didn't send all the
necessary
 parameters for the backend, based on the VertX. So the problem was on my
side.
Best regards,
Olena Ostrozhynska



сб, 4 апр. 2020 г. в 22:37, Dalton <notifications@github.com>:

**Comment by Antol** [comment]
> Hi) Thank you for the answer. In my case I found that I didn't send all the necessary parameters for the backend, based on the VertX. So the problem was on my side.  

Can you please share what was the problem on your side? I think I have something similar and can't fix it
