### ISSUE TITLE
Starscream.TCPTransportError.invalidRequest

### ISSUE THREAD

**Issue by SharadExt** [daltoniam/Starscream#754]
I am using server-client based socket here. iPad will act as server and other payment device will be client in my app. 
In that I am using below request.
var request = URLRequest(url: URL(string: "192.168.1.101:8030")!)//https://localhost:8080
        request.timeoutInterval = 5
But I am getting Starscream.TCPTransportError.invalidRequest in didReceive method.
Can you please please help me

**Comment by daltoniam** [comment]
Sorry, I can help without more context. I'd recommend asking the question on StackOverflow. Also make sure you are using a web socket server on your iPad and not just a generic HTTP server. Best of luck!

**Comment by SharadExt** [comment]
Thanks daltoniam, How do we decided that we are using web socket server on iPad not just a generic HTTP server. Can you please help me to understand this.
