### ISSUE TITLE
Wired lifecycle events

### ISSUE THREAD

**Issue by alizx** [daltoniam/Starscream#76]
Hi 
first sorry for my bad english ;)
there are some situations that websocketDidDisconnect() get called but the value of the isConnected property is still true , and in some circumstances calling connect() method inside websocketDidDisconnect() block makes another websocket connection although the previous one is alive and receives messages.

**Comment by daltoniam** [comment]
Hmm, ok I have not seen that. Is there anyway to reproduce the issue?

**Comment by daltoniam** [comment]
I will roll this in the improvements on #81.
