### ISSUE TITLE
Unsafe Mutable Pointer Warning

### ISSUE THREAD

**Issue by pausanchezv** [daltoniam/Starscream#762]
Hello, after having updated my xcode to the latest version, I'm getting this warning. I'm using starscream in its version 4.0.0. The file is WSCompression.swift. I haven't found any fix on the internet for this. Could you help me please? This is the error:

Initialization of 'UnsafeMutablePointer<UInt8>' results in a dangling pointer

1. Implicit argument conversion from '[UInt8]' to 'UnsafeMutablePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'

2. Use the 'withUnsafeMutableBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope

Thank you so very much.

**Comment by tfonfara** [comment]
Duplicate of #758 😉

**Comment by rudyrichter** [comment]
This looks to be fixed in https://github.com/daltoniam/Starscream/pull/766

**Comment by daltoniam** [comment]
4.0.4 released!
