### ISSUE TITLE
enableCompression does not exist

### ISSUE THREAD

**Issue by IsaiahJTurner** [daltoniam/Starscream#779]
It used to, but it doesn't anymore. It's in the docs.

**Comment by KimiChiu** [comment]
Same problem here. Where is the property? There's no enableCompression in WebSocket nor WSCompression.

**Comment by daltoniam** [comment]
The docs should probably be better worded, but the example should how do accomplish compression support: https://github.com/daltoniam/Starscream#compression-extensions

just add:
```
let compression = WSCompression()
let socket = WebSocket(request: request, compressionHandler: compression) // add the compress object when creating a new Websocket
```

This was changed in 4.0.0 as it allows for custom compression implementations. I'll update the docs to make this clearer.
