### ISSUE TITLE
README Fix: Unwrapping nil in websocketDidDisconnect

### ISSUE THREAD

**Issue by AndrewZurn** [daltoniam/Starscream#78]
The README describes how one might use the websocketDidDisconnect required delegate method as:

websocketDidDisconnect
=========
websocketDidDisconnect is called as soon as the client is disconnected from the server.

<pre>
func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
    println("websocket is disconnected: \(error!.localizedDescription)")
}
</pre>

The issue with this, however, is that the value might be nil, in the case that the server doesn't send back an error(timeout/stale client is disconnected by server), force unwrapping the nil value will cause an exception, and crash the application.

Although this is just a minor fix, its probably worth the time just to take a second to update the documentation so new people like myself don't accidentally cause application crashes while using the library.

**Comment by daltoniam** [comment]
Good point, nice catch. Addressed #79.
