### ISSUE TITLE
How to disconnect websocket?

### ISSUE THREAD

**Issue by Mani-gloify** [daltoniam/Starscream#782]
I am able to connect to server with websocket and when I tried to disconnect I am calling socket.disConnect() method. but don't know websocket is disconnected or not? how to check connection status(connected or disconnected) when user came back from chat page.

**Comment by tfonfara** [comment]
You should get `.disconnected` callback within `didReceive` method. This works fine on iOS 12+, on iOS 11 I'm currently having issues (see https://github.com/daltoniam/Starscream/issues/783)

**Comment by aaksh-acto** [comment]
1. Add "WebSocketDelegate" to your chat view controller class  
 e.g. class ChatViewController: WebSocketDelegate{
}
    
Create var isSocketConnected = false 

 socket = WebSocket(request: request)
 socket.delegate = self
 socket.connect() // to connect 
socket.disconnect() 
// in the did receive method .cancelled case will be called instead of .disconnect 

2.   Implement the below function:

   func didReceive(event: WebSocketEvent, client: WebSocket) {
        switch event {
        case .connected(let headers):
             isSocketConnected = true
           // socket is connected
            print("websocket is connected: \(headers)")
             self.chatTextField.text = "websocket is connected"
        case .disconnected(let reason, let code):
            isSocketConnected = false
           //Socket is disconnected
            print("websocket is disconnected: \(reason) with code: \(code)")
        case .text(let responseString):
               print(responseString)
       case .binary(let data):
            print("Received data: \(data.count)")
        case .ping(_):
            break
        case .pong(_):
            break
        case .viabilityChanged(_):
            break
        case .reconnectSuggested(_):
            break
        case .cancelled:
            print("-------------------")
            print("Websocket is Cancelled")
            print("-------------------")
            isSocketConnected = false
        case .error(let error):
            isSocketConnected = false
            handleError(error)
            
        }
    }

**Comment by aaksh-acto** [comment]
> I am able to connect to server with websocket and when I tried to disconnect I am calling socket.disConnect() method. but don't know websocket is disconnected or not? how to check connection status(connected or disconnected) when user came back from chat page.

1. Add "WebSocketDelegate" to your chat view controller class
e.g. class ChatViewController: WebSocketDelegate{
}
Create var isSocketConnected = false

socket = WebSocket(request: request)
socket.delegate = self
socket.connect() // to connect
socket.disconnect()
// in the did receive method .cancelled case will be called instead of .disconnect

Implement the below function:
func didReceive(event: WebSocketEvent, client: WebSocket) {
switch event {
case .connected(let headers):
isSocketConnected = true
// socket is connected
print("websocket is connected: (headers)")
self.chatTextField.text = "websocket is connected"
case .disconnected(let reason, let code):
isSocketConnected = false
//Socket is disconnected
print("websocket is disconnected: (reason) with code: (code)")
case .text(let responseString):
print(responseString)
case .binary(let data):
print("Received data: (data.count)")
case .ping():
break
case .pong():
break
case .viabilityChanged():
break
case .reconnectSuggested():
break
case .cancelled:
print("-------------------")
print("Websocket is Cancelled")
print("-------------------")
isSocketConnected = false
case .error(let error):
isSocketConnected = false
handleError(error)

    }
}

**Comment by XueYoung** [comment]
the same problem, in .cancelled() and .disconnected() I could not receive any message about disconnect success or not ,but after some seconds I could receive message in .error() tell me time out.

**Comment by aaksh-acto** [comment]
> the same problem, in .cancelled() and .disconnected() I could not receive any message about disconnect success or not ,but after some seconds I could receive message in .error() tell me time out.

Can you share your code for more context? 

Also do you have some sort of authentication for your socket?

**Comment by XueYoung** [comment]
1，This problem just crash in iOS11 or eariler, devices is iPhone 7, but in iOS12 & 13 it is fine
2,  there is no authentication in my code
3, crash log(see #771)
import UIKit
import Starscream

@objc protocol TongSocketDelegate:NSObjectProtocol{
    @objc optional func webScoket(socket:TongSocket, didConnect headers:[String:String])
    @objc optional func webScoket(socket:TongSocket, didDisconnect errMsg:String,errCode:UInt16)
    @objc optional func webScoket(socket:TongSocket, didReceivedMessage message:String)
    @objc optional func webScoket(socket:TongSocket, didReceivedData data:Data)
}

class TongSocket: NSObject {

    var socket:WebSocket?
    var server:String?

    weak var delegate:TongSocketDelegate?

    func connectSever(url:String){
        var request = URLRequest.init(url: URL(string: url)!)
        request.timeoutInterval = 10
        socket = WebSocket.init(request: request)
        socket?.delegate = self
        start()
    }

    func sendMessage(msg:String){
        socket?.write(string: msg)
    }

    func start(){
        socket?.connect()
    }

    func close(){
        socket?.disconnect()
    }

}

extension TongSocket:WebSocketDelegate{
    func didReceive(event: WebSocketEvent, client: WebSocket) {
        switch event {
        case .connected(let headers):
            delegate?.webScoket?(socket: self, didConnect: headers)
        case .disconnected(let reason, let code):
            delegate?.webScoket?(socket: self, didDisconnect: reason, errCode:code)
        case .text(let string):
            delegate?.webScoket?(socket: self, didReceivedMessage: string)
        case .binary(let data):
            print("Received data: \(data.count)")
            delegate?.webScoket?(socket: self, didReceivedData: data)
        case .ping(_):
            break
        case .pong(_):
            break
        case .viabilityChanged(_):
            break
        case .reconnectSuggested(_):
            break
        case .cancelled:
            print("================================")
            "could not receive message in iOS 11 & earlier when i calling socket?.disconnect()"
            delegate?.webScoket?(socket: self, didDisconnect: "cancelled", errCode: 1001)
            socket?.delegate = nil
        case .error(_):
            delegate?.webScoket?(socket: self, didDisconnect: "error", errCode: 1002)
        }
    }
}

**Comment by XueYoung** [comment]
1，This problem just crash in iOS11 or eariler, devices is iPhone 7, but in iOS12 & 13 it is fine
2, there is no authentication in my code
3, crash log(see #771)

@objc protocol TongSocketDelegate:NSObjectProtocol{
    @objc optional func webScoket(socket:TongSocket, didConnect headers:[String:String])
    @objc optional func webScoket(socket:TongSocket, didDisconnect errMsg:String,errCode:UInt16)
    @objc optional func webScoket(socket:TongSocket, didReceivedMessage message:String)
    @objc optional func webScoket(socket:TongSocket, didReceivedData data:Data)
}

class TongSocket: NSObject {

    var socket:WebSocket?
    var server:String?

    weak var delegate:TongSocketDelegate?

    func connectSever(url:String){
        var request = URLRequest.init(url: URL(string: url)!)
        request.timeoutInterval = 10
        socket = WebSocket.init(request: request)
        socket?.delegate = self
        start()
    }

    func sendMessage(msg:String){
        socket?.write(string: msg)
    }

    func start(){
        socket?.connect()
    }

    func close(){
        socket?.disconnect()
    }

}

extension TongSocket:WebSocketDelegate{
    func didReceive(event: WebSocketEvent, client: WebSocket) {
        switch event {
        case .connected(let headers):
            delegate?.webScoket?(socket: self, didConnect: headers)
        case .disconnected(let reason, let code):
            delegate?.webScoket?(socket: self, didDisconnect: reason, errCode:code)
        case .text(let string):
            delegate?.webScoket?(socket: self, didReceivedMessage: string)
        case .binary(let data):
            print("Received data: \(data.count)")
            delegate?.webScoket?(socket: self, didReceivedData: data)
        case .ping(_):
            break
        case .pong(_):
            break
        case .viabilityChanged(_):
            break
        case .reconnectSuggested(_):
            break
        case .cancelled:
            print("================================")
            print("could not receive message in iOS 11 & earlier when i calling socket?.disconnect()")
            delegate?.webScoket?(socket: self, didDisconnect: "cancelled", errCode: 1001)
            socket?.delegate = nil
        case .error(_):
            delegate?.webScoket?(socket: self, didDisconnect: "error", errCode: 1002)
        }
    }
}

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
