### ISSUE TITLE
Swift Compiler warning 

### ISSUE THREAD

**Issue by aaksh-acto** [daltoniam/Starscream#785]
Xcode version 11.5 

Swift compile warning: 
File: WSCompression.swift - 

1. line: 150 ( strm.next_out = **UnsafeMutablePointer<UInt8>**(&buffer))
Initialization of 'UnsafeMutablePointer<UInt8>' results in a dangling pointer

2. line 212 (strm.next_out = **UnsafeMutablePointer<UInt8>(**&buffer))
warning: 
Initialization of 'UnsafeMutablePointer<UInt8>' results in a dangling pointer

**Comment by aleksie** [comment]
Facing same warnings.
