### ISSUE TITLE
Infinite loop in TCPTransport.swift : readLoop()

### ISSUE THREAD

**Issue by sdidla** [daltoniam/Starscream#786]
**Scenario:**
1. Simple WebSocket server running locally
2. Launch `SimpleTest.xcodeproj` to connect to `ws://localhost:8080`
3. Close the `NWConnection` on the server

**Result:**

On this [line](https://github.com/daltoniam/Starscream/blob/master/Sources/Transport/TCPTransport.swift#L141) : 

```swift
data = nil
error = nil
```

 thread `com.vluxe.starscream.networkstream (serial)` enters infinite loop eating up CPU. looking for one more frame even though `context.isFinal = true`

**Comment by horizon554** [comment]
facing same problem as you

**Comment by sdidla** [comment]
Replacing [line 144](https://github.com/daltoniam/Starscream/blob/master/Sources/Transport/TCPTransport.swift#L144) with:
```swift 
if data != nil || context?.isFinal == false {
    s.readLoop()
}
```
works for me. Is this a possible solution?

**Comment by horizon554** [comment]
Figured it out:
Close socket when your heartbeat not get response

**Comment by sdidla** [comment]
But you will still have the infinite loop (and high CPU usage) till the heartbeat timeout, right?

**Comment by fruitcoder** [comment]
I think this can be marked as fixed right @sdidla?

**Comment by sdidla** [comment]
✅
