### ISSUE TITLE
Masked and rsv data is not currently supported code 1002

### ISSUE THREAD

**Issue by rickrvo** [daltoniam/Starscream#791]
Hi, I was debugging normaly testing some parsing and now I'm getting this error on websocket.connect() I did a rollback on my minor changes and the error persists.

this is the log:
viabilityChanged
error Optional(Starscream.HTTPUpgradeError.notAnUpgrade(503))
error Optional(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002))

**Comment by rickrvo** [comment]
Today it was working again.. so it's something that the server replies. I'm consuming a exchange server, so I wouldn't have access to know what it was sending.

**Comment by hotwill07** [comment]
I have the same problem！ but it works when I use ip connect, not works for domain。

**Comment by hotwill07** [comment]
HTTP/1.0 503 Service Unavailable\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>

Optional(Starscream.HTTPUpgradeError.notAnUpgrade(503))
Optional(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002))

**Comment by hotwill07** [comment]
I solved this question！
First I use domain connect，not ip connect！
Reason：
WSEngine --> connectionChanged(state: ConnectionState)  -->  let wsReq = HTTPWSHeader.createUpgrade(request: request, supportsCompression: framer.supportsCompression(), secKeyValue: secKeyValue) --> HTTPWSHeader.createUpgrade -->  let hostValue = req.allHTTPHeaderFields?[HTTPWSHeader.hostName] ?? "\(parts.host):\(parts.port)"
        req.setValue(hostValue, forHTTPHeaderField: HTTPWSHeader.hostName)  
If we do not set Host，default value is  "\(parts.host):\(parts.port)", if we use domin connect, Host's value is like "ws://api.ws.cn:80".
The Host's value is like "ws://api.ws.cn" without port.
Hope usefully.

**Comment by shalyf** [comment]
I have the same problem, it happen when I use ip connect via lan.
It quickly received this error(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002)) when the websocket connected.

**Comment by eleazar0425** [comment]
Did you get to fix this?
