### ISSUE TITLE
Disconnect when returning to the foreground

### ISSUE THREAD

**Issue by xjimi** [daltoniam/Starscream#795]
Entering the background and returning to the foreground will disconnect, but it will not disconnect in version 3.1.1. Is there any way to stay connected?

Receive failed with error "Socket is not connected"
nw_read_request_report [C1] Receive failed with error "Socket is not connected"
websocket encountered an error: The operation couldn’t be completed. (Network.NWError error 0.)
Received data: cancelled

**Comment by commanderk33n** [comment]
facing the same Error, downgrading to 3.1.1 resolved the problem for me too

**Comment by AppleTTT** [comment]
face the same issue
Starscream version: 4.0.4
iOS 14.2
Xcode 12.2

**Comment by andreibudisan** [comment]
same issue here
Starscream version: 4.0.4
iOS 14.4
Xcode 12.4

**Comment by IrelDev** [comment]
same issue
Starscream version: 4.0.4
iOS 14.4
Xcode 12.4

**Comment by maxxy212** [comment]
Facing the same issue... please let us know if this is fixed in newer version. Thanks

**Comment by ccv-thuongbv** [comment]
Same issue. @xjimi Could you tell me how to fix this issue?
