### ISSUE TITLE
IOS webview websocket javasript

### ISSUE THREAD

**Issue by MaxESP** [daltoniam/Starscream#796]
Dear Sir, 

I have dev a androidstudio webview app ( HTML, JS,CSS) using websocket . and i wan to do the same on ios.

Library used for androidstudio is okhttp3.
Notice that iwant to keep my HTML JS structure 
for websocket transaction 

Do you think it's possible to do the same in a xcode project webview ?

var ipValue;
var connection;
ipValue = "ws://192.168.1.40:81/";
connection = new WebSocket(ipValue);
//console.log(text)
    console.log("IP value changed to:"+ipValue);
    connection.onopen = function () {
    connection.send('Websocket funcionando!' + new Date());
    //connection.send('ping');
    //await ws.send('2')
    //ws.send("Hello, Ardunio");
};
connection.onerror = function (error) {
    console.log('WebSocket Error ', error);
};
connection.onmessage = function (e) {
    console.log('Server: ', e.data);

var distancia = parseInt(e.data);

    var fermée= "la porte est fermée";
	var ouvert="la porte est ouverte";
	var input=document.querySelector('input[id="PORTE"]');

	if (distancia <25) {

	  input.value=ouvert;}

	  else if (distancia >25){

	  input.value=fermée;

		  };

	var value = parseInt(e.data);

	var fermée= "la porte est fermée";
    var ouverte="la porte est ouverte";
	var input=document.querySelector('input[id="VOLET"]');

	  if (value ==16080300) {

	  input.value=ouverte;}

	  else if (value ==16080789){

	  input.value=fermée;

		  };

};

    function OPEN() {
    var toSend = "1";
    connection.send(toSend);
};
    function CLOSE() {
    var toSend = "2";
    connection.send(toSend);
};
    function STOP() {
    var toSend = "3";
    connection.send(toSend);
};

   // ****************************************************  chambre1
      function ONC() {
          var toSend = "12";
          connection.send(toSend);
      };
   // ****************************************************  chambre1
      function OFFC() {
          var toSend = "13";
          connection.send(toSend);
      };

function ON() {
    var toSend = "11";
    connection.send(toSend);
};

**Comment by Reiszecke** [comment]
If that's really your question then yes that looks possible.

**Comment by daltoniam** [comment]
yes it is possible. You can send just about anything over the WebSocket connection. You appear to not being using Starscream but the native browser WebSocket APIs, since a Webview doesn't use Starscream. I recommend looking at the Javascript WebSocket APIs since that is what a web view will use.
