### ISSUE TITLE
Unable to compile on XCode12

### ISSUE THREAD

**Issue by varyP** [daltoniam/Starscream#805]
[Screenshot here](https://imgur.com/a/FY89bQi)

Starscream (4.0.3)
XCode12

Unable to compile.

### FoundationHTTPServerHandler.swift
//Type of expression is ambiguous without more context for `method != getVerb {`
```
if let method = CFHTTPMessageCopyRequestMethod(response)?.takeRetainedValue() {
            if method != getVerb { 
                delegate?.didReceive(event: .failure(HTTPUpgradeError.invalidData))
                return true
            }
        }
```

**Comment by ngingric** [comment]
Try replacing:
`method != getVerb`
with
`self.getVerb.isEqual(to: method as String)`

This worked for me!

**Comment by GoranLilja** [comment]
There is a PR by @amayers fixing this issue [here](https://github.com/daltoniam/Starscream/pull/799).

**Comment by ethancwb** [comment]
I've created a fork with the fix since the PR is not merged yet. If you are using cocoapods, then try:   
`pod 'Starscream', :git => 'https://github.com/ethancwb/Starscream.git', :branch => 'xcode-12-hotfix'
`
However, I highly suggest you to only apply the change on an experimental branch, not on your master. This is only a temporary workaround.

**Comment by amayers** [comment]
@ethancwb you didn't need to create a new fork to get the fix. You could have just pointed your pod at the repo/branch that my #799 is on.

**Comment by ethancwb** [comment]
@amayers Thanks for the response. Actually, after searching, I found that I just need to update the deploy target to above iOS 11.0. Then this issue is gone.

**Comment by 22Round** [comment]
I am testing my app with new SwiftUI, Swift Package Manager and Xcode 12 Beta and have same issue, please fix it!

**Comment by amayers** [comment]
> I am testing my app with new SwiftUI, Swift Package Manager and Xcode 12 Beta and have same issue, please fix it!

@22Round the fix has been merged to `master`, but a new version hasn't been released. So you could just point SPM to use `master` instead of a fixed version number, and everything should work.

**Comment by daltoniam** [comment]
4.0.4 released!
