### ISSUE TITLE
Strange behavior on socket.disconnect()

### ISSUE THREAD

**Issue by yoller** [daltoniam/Starscream#81]
Hi! I have a strange behavior on calling socket.disconnect()
when I disconnect websocketDidDisconnect is called three times! 

first one with this output error:
"Error Domain=Websocket Code=1000 "connection closed by server" UserInfo=0x17063b680 {NSLocalizedDescription=connection closed by server}"

second one with this error: 
"Error Domain=Websocket Code=1 "output stream error during write" UserInfo=0x17063b680 {NSLocalizedDescription=output stream error during write}"

and the third without error (error is nil)

could be a server side misconfiguration?

**Comment by daltoniam** [comment]
No, that is possible case and normal case. The first is the server doing a disconnect, the second is pending write operations being cancelled and the third is a disconnect from the NSStream on the client side. Basically this is normal and possible case as multiple parts of the stream can be disconnecting. I will look into improving this so it doesn't get called so many times.

**Comment by yoller** [comment]
Ok, I thought that disconnect, on didDisconnect, was a single state for the socket (just socket connected or socket disconnected) rather than having multiple parts of operations.
But your answer is clear, thank you!
