### ISSUE TITLE
How do I turn on loggin?

### ISSUE THREAD

**Issue by 15458434** [daltoniam/Starscream#818]
I'm attempting to make a websocket with Starscream. Is there a way to turn on more sophisticated logging than absolutely nothing? It would save me a lot of headache in ifguring out why Starscream won't connect.

**Comment by acmacalister** [comment]
Starscream doesn't take an opinion on logging about connections. You are free to implement those in any of the callback functions to get more information on the connection state. If you have a suggestion on additional methods for the protocol to help with this, happy to review and discuss.
