### ISSUE TITLE
websocketDidDisconnect has called in other thread

### ISSUE THREAD

**Issue by sakairyota** [daltoniam/Starscream#82]
Hi,
WebSocketDelegate.websocketDidDisconnect has called in other thread than main thread.
It has called from https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L710 .
Where websocketDidDisconnect is called, dispatch_async may be needed.

I'm using older version (I'm sorry but I couldn't identify the precise version), but the issue appears to be remained.

**Comment by daltoniam** [comment]
Ok good point. I will address it in the next version.

**Comment by daltoniam** [comment]
Fixed in the latest checkin to master. Thanks!

**Comment by sakairyota** [comment]
Thanks!
