### ISSUE TITLE
Are 4.0 - 4.0.4 public releases?

### ISSUE THREAD

**Issue by austintt** [daltoniam/Starscream#820]
The [Releases page](https://github.com/daltoniam/Starscream/releases) shows 3.1.1 as the “Latest Release”. Are versions 4.0 and greater considered dev or public releases?

**Comment by burkaslarry** [comment]
I would like to ask this question too

**Comment by cbiggin** [comment]
Curious about this too. I'm still on 3.1.1 because it's listed as the latest release.
