### ISSUE TITLE
Network.NWError 0

### ISSUE THREAD

**Issue by mark644873613** [daltoniam/Starscream#828]
After the successful connection, the error net.nwError 0 will be reported

**Comment by mmdock** [comment]
@mark644873613  anything more about this? I am also seeing this

**Comment by chinabrant** [comment]
So am I. Now i try to use FoundationTransport only.

**Comment by susslik** [comment]
Have a huge count of this error ar Crashlytics console: 
45k users got 1.5M errors during last week...

**Comment by gsm-miomni** [comment]
Any updates on this ? I am also seeing the same issue.

**Comment by ChrisGrant** [comment]
Did anyone ever resolve this issue? We're seeing the same thing.

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.

**Comment by JeryHuo** [comment]
Guys, close websocket when the app enters the background and open websocket when it returns to the foreground

**Comment by susslik** [comment]
Hi @JeryHuo - thanks for the suggestion, however that's exactly how we're doing this since the beginning. But despite this - the error appears.
