### ISSUE TITLE
Is possible to interrupt connection attempt?

### ISSUE THREAD

**Issue by yoller** [daltoniam/Starscream#83]
Is there a way to interrupt a socket.connect() call voluntarily? 
Example: I want to close the connection attempt if it doesn't respond within 10 seconds

I tried with socket.disconnect() but it has no effects

**Comment by daltoniam** [comment]
There isn't currently a timeout option, but NSStream is usually pretty quick to notify on connection failures. Is there a case where it is taking 10 seconds to connect?

**Comment by yoller** [comment]
Yes, in my experience when I try to reach my server and my server is not available socket.connect() call stay pending (nothing happened) until it reaches the timeout. Meanwhile I can do nothing and also socket.disconnect() has no effects. Even if the server back online during this time the socket connection wait till end of timeout.
Ok I can, and I'm doing it, manage reachability checking and status before try to connect the socket (better way to do it for sure) but thinking on this situation I was curious about the possibility of being able to stop the connection attempt in progress.

**Comment by daltoniam** [comment]
Ok cool, makes sense. Yeah NSStream doesn't have an easy way to do a timeout (not that it could not be worked around, just kinda of ugly). Sounds like you have good solution with using the reachability APIs.
