### ISSUE TITLE
xcode 12 issue

### ISSUE THREAD

**Issue by wwwshe** [daltoniam/Starscream#831]
starscream version : 4.03
xcode version : 12.0

<img width="273" alt="스크린샷 2020-09-21 오후 12 14 11" src="https://user-images.githubusercontent.com/10498849/93730571-322b7900-fc04-11ea-873a-5f676a612dcf.png">
<img width="755" alt="스크린샷 2020-09-21 오후 12 14 26" src="https://user-images.githubusercontent.com/10498849/93730577-35266980-fc04-11ea-9f5e-e64582ea5bdb.png">

**Comment by Zulqarnain-Mustafa** [comment]
I am also facing this issue, is there any solution?

**Comment by wwwshe** [comment]
Thank you
