### ISSUE TITLE
 Error: type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by DjuricMarija** [daltoniam/Starscream#835]
XCode: 12.0
Starscream: 4.0.0

Getting this error when try to build project:
<img width="862" alt="Screen Shot 2020-09-25 at 12 39 36 PM" src="https://user-images.githubusercontent.com/25622200/94257889-4802ac00-ff2c-11ea-8c06-9b640cbd5eb5.png">

**Comment by Vhora01** [comment]
I am getting the same issue

**Comment by StPov** [comment]
@Vhora01 @DjuricMarija https://github.com/daltoniam/Starscream/issues/837
it works - checked

**Comment by bogdan-razvan** [comment]
Having the same issue with the latest Starscream version.

**Comment by bealex** [comment]
Any news why is it happening or how to fix it?

**Comment by StPov** [comment]
@bealex  simply use version 4.0.4

**Comment by bealex** [comment]
@StPov Wow! I've updated like several minutes ago! New version already! Thanks! :-)
