### ISSUE TITLE
Optimize time

### ISSUE THREAD

**Issue by telenc** [daltoniam/Starscream#84]
Hello

i need to optimize the time of my request
i want to send a picture
My datalength is 442920
````
let bytes = UnsafeMutablePointer<UInt8>(data.bytes)
            let dataLength = data.length
            Logger.log("Data length = \(dataLength)")
            let frame = NSMutableData(capacity: dataLength + self.MaxFrameSize)
```

My server receives the image after four seconds !!! it's way too long for me

How I can optimize this?

Thank's

**Comment by daltoniam** [comment]
I am honestly not sure how to respond to this. There are a ton of variables that influence the speed of a file transfer. The code above doesn't really tell me anything about the file transfer, but either way, Starscream doesn't really affect that speed. It is just a websocket library that will send the bytes as fast as the stream will allow. I would recommend inspecting your network/app stack and see if you can find a bottleneck.

**Comment by telenc** [comment]
Ok, I understand ! thank's !
