### ISSUE TITLE
Feature: didReceivePong delegate method

### ISSUE THREAD

**Issue by thbaja** [daltoniam/Starscream#85]
Add a delegate for receiving a pong (after having sent a ping).
Eg.: `websocketDidReceivePong`

**Comment by daltoniam** [comment]
Just to be clear, you want a delegate method to notify when a pong is sent in response to a ping?

**Comment by thbaja** [comment]
Exactly :)
You already implemented a send ping method, so it would reasonable to be notified of the corresponding pong. This is already a feature of SocketRocket (not documented in the Readme, though) and is in the scope of Websocket functionality.

It can also be useful for measuring latency and it might be be a solution for #56 and #57 as well.

**Comment by daltoniam** [comment]
ok cool, should be a fairly simple add. Will try to get to it in the near future.

**Comment by thbaja** [comment]
I created a PR you can consider using: #88

**Comment by daltoniam** [comment]
#88 merged!
