### ISSUE TITLE
Source files accidentally deleted

### ISSUE THREAD

**Issue by lahoda** [daltoniam/Starscream#855]
I was checking out the project, but couldn't find several files. Upon investigation, it seems that merging pull request #653 (6b2742542cc89fe2f5b45e38d010efbf0a4e9b33) accidentally deleted multiple files, including SSLClientCertificate.swift and related functionality. Noticed this was mentioned by another user some time ago, but it was closed without resolution. What is the current status?

**Comment by acmacalister** [comment]
SSL pinning and such was moved out of the core library and can be provided through an external library. We will add examples on how to do this.
