### ISSUE TITLE
Reconnection will take long time

### ISSUE THREAD

**Issue by MrShiY** [daltoniam/Starscream#858]
For example, there are two network available, if I disable the connecting network, iPhone will connect to another network automatically some time later. Starscream returns only viabilityChanged(false) event, no other events, although the network was connected normally later. but the websocket doesn't work any more.  I tried to recreate socket object and reconnect, however, sometimes it will take a long time to connect successfully. (may be more than 1 minute).

Starscream version: 4.0.4

**Comment by cbiggin** [comment]
I don't believe that Websockets (and by extension Starscream) provide reconnection. You will have to roll that yourself using [Reachability.swift](https://github.com/ashleymills/Reachability.swift) or Apple's NWPath and monitor when the network changes and then reconnect.

[Socket.io](https://github.com/socketio/socket.io-client-swift) uses Starscream and reconnection is almost instantaneous.

**Comment by MrShiY** [comment]
For example. there are two WIFI network, I close the WIFI device my iPhone is connecting to(note: don't switch in iPhone，instead close the router), my iPhone will switch to another wifi a few seconds later, Reachability cannot monitor the change. the network reachable is still true. I tried to reconnect every few seconds， sometimes it will take a long time to reconnect successfully.

**Comment by sergeydi** [comment]
@MrShiY Could you please provide some code example of how you reconnect. I have the same issue, if I lost connection, socket don't reconnect.

**Comment by maniac-coder** [comment]
@MrShiY @sergeydi I am also facing the same issue. But a workaround/solution I am going to try is the ping failure mechanism. If I don't receive any data from the server for 1 min(configurable), I would disconnect the socket and reconnect. I hope this solves this problem.
