### ISSUE TITLE
Is this repo open for contributions?

### ISSUE THREAD

**Issue by nedimf** [daltoniam/Starscream#861]
I see PRs going back 7 months, that are not commented or reviewed. 
So is this project stale or it's in archive mode? @danielrhammond  
Edit: @daltoniam

**Comment by danielrhammond** [comment]
Not sure, my only relation to the project is contributing a small bug fix several years ago so not sure why you tagged me :)

**Comment by nedimf** [comment]
I'm sorry haha, I meant to tag @daltoniam.

**Comment by daltoniam** [comment]
This repo is still open for contributions, I just haven't had the time I would like to dedicate to this project. I typically go in sweep through everything every couple of months, but it has been a while. I'll try to go through and take a look at this in the next week or two.
