### ISSUE TITLE
NSGenericException after receiving some message

### ISSUE THREAD

**Issue by wispur** [daltoniam/Starscream#87]
Tested on iPhone 5s iOS7, this crash is not very common and appears randomly. I got 4 crashes in a day of work. Wonder if any of you have experience for this. Any help appreciated!

Crash happens inside the loop for function: **initStreamsWithData(data: NSData, _ port: Int)**:
```swfit
while(isRunLoop) {
            NSRunLoop.currentRunLoop().runMode(NSDefaultRunLoopMode, beforeDate: NSDate.distantFuture() as! NSDate)
        }
```
**The error message:**
2015-05-28 18:43:53.211 ProjectName[1086:c6b7] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x178257d00> was mutated while being enumerated.'
*** First throw call stack:
(0x182173100 0x18e67c1fc 0x182172b34 0x1851c2168 0x1851c2028 0x182133858 0x182130ae0 0x182130db4 0x182071dd0 0x182c0d2c4 0x10021a034 0x100218070 0x1002232f4 0x1001187a8 0x18ec54014 0x18ec53fd4 0x18ec5b2b8 0x18ec5b4fc 0x18ede96bc 0x18ede954c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by daltoniam** [comment]
Interesting. Starscream doesn't have any array mutations it does expect for the headers on `connect()`. Are you adding any custom headers or attempting to reconnect? I would lean toward this is another part of the code hitting that race condition and catching inside the runloop of Starscream since it doesn't exit. You might want to try adding the "catch all exceptions" breakpoint in xCode to get a bit more info on where it is crashing.

**Comment by wispur** [comment]
@daltoniam hi there~
I do not have any custom headers and unfortunately I am not too sure about the reconnect part as I did not keep any detail logs... My bad. However, you mentioned this could be a race condition by multiple reconnects (I think that's what you meant). I will try to look in that direction. Thanks!

**Comment by daltoniam** [comment]
@wispur did you ever resolve this issue? If not, the latest code in master might help.

**Comment by wispur** [comment]
@daltoniam Hello~ I avoided the problem by reducing concurrent connecting scenarios in my code. That worked since I have not crashed since then~
