### ISSUE TITLE
[54: Connection reset by peer]

### ISSUE THREAD

**Issue by vanjo2001** [daltoniam/Starscream#886]
Can you help me resolve my problem? After socket.connect I get message like this:
 nw_socket_get_input_frames [C1.1:3] recvmsg(fd 12, 1024 bytes) [54: Connection reset by peer]

**Comment by damirstuhec** [comment]
@vanjo2001 were you able to resolve this? I'm seeing the same log message, however not right after connect but rather after a long while.

**Comment by helinyu** [comment]
??? why? close? i have the same problem
