### ISSUE TITLE
Xcode 12.5 warning

### ISSUE THREAD

**Issue by alexander-larsson** [daltoniam/Starscream#889]
Since Xcode 12.5 you get this warning when building:

```
Package Loading
ignoring declared target(s) 'swift-nio-zlib-support' in the system package
```

There is an [issue](https://github.com/apple/swift-nio-zlib-support/issues/4) filed with the swift-nio-zlib-support where it turns out that it is basically a deprecated library.

So maybe it is time to replace that library? I mostly just want to get rid of the warning 🙂

**Comment by ddaddy** [comment]
Have you been able to build this for device? I get this error with Xcode 12.5

<img width="1304" alt="Screenshot 2021-06-08 at 11 47 51" src="https://user-images.githubusercontent.com/1425808/121172377-8a1c1580-c84f-11eb-8987-798ae351197d.png">

**Comment by Liuchunqi3240** [comment]
> Have you been able to build this for device? I get this error with Xcode 12.5
> 
> <img alt="Screenshot 2021-06-08 at 11 47 51" width="1304" src="https://user-images.githubusercontent.com/1425808/121172377-8a1c1580-c84f-11eb-8987-798ae351197d.png">

your xcode version must be xcode 13 beta2

**Comment by ddaddy** [comment]
Sorry yes, it is a 13.x issue. I've started a separate issue.
