### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by BeauNouvelle** [daltoniam/Starscream#892]
Has this project been abandoned?

Lots of PRs and issues open from many months back. Should we start looking at using something else?

**Comment by acmacalister** [comment]
Nope, not abandoned. Just not a lot of free time on the maintainers these days for reviewing PRs, responding to issues or questions.

**Comment by BeauNouvelle** [comment]
Would love to see some of these PRs merged in. A LOT of other packages rely on this one and they're starting to fall apart.

**Comment by rymotion** [comment]
opening this thread again. getting this error when attempting to build 

> Module compiled with Swift 5.0 cannot be imported by the Swift 5.3.2 compiler

**Comment by hubfresher** [comment]
> I am currently using Starscream directly for communicating with Janus servers but I am leaning strongly towards replacing it with Apple's Websockets. The only reason I haven't yet is because I also really heavily on SocketIO which is built on... wait for it... Starscream!

so 'Apple's Websockets' is what?

**Comment by dsrees** [comment]
@hubfresher [URLSessionWebSocketTask](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask) addded in iOS 13.
