### ISSUE TITLE
Minimum iOS version needs to increase

### ISSUE THREAD

**Issue by ddaddy** [daltoniam/Starscream#895]
This library fails to build for device (It builds for simulator fine) in Xcode 13 (BETA 1&2).
The error is:

> Failed to build module 'Network'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.20.4 clang-1300.0.21.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.20.104 clang-1300.0.21.1)'). Please select a toolchain which matches the SDK.

This error goes away when you set the minimum iOS version to 11.0

**Comment by rizwan95** [comment]
@daltoniam  @ddaddy   I have created a PR and submitted it as well. Here is the link -> https://github.com/daltoniam/Starscream/pull/897

Meanwhile if you want to use the library until the PR is accepted, you can do it by following the below given instructions.

Cocoapods - pod 'Starscream', '~> 4.0.0', :git => 'https://github.com/rizwan95/Starscream.git'

SPM - 

dependencies: [
    .Package(url: "https://github.com/rizwan95/Starscream.git", majorVersion: 4)
]

**Comment by sdc-78** [comment]
I don't understand the link between the error message and the minimum iOS version. Can someone explain to me?
Isn't that just an Xcode bug?

**Comment by ddaddy** [comment]
Yes it could be an Xcode bug, and I have filed a bug report with Apple (FB9296596)
If it gets fixed, great. If not, then the minimum iOS version will need to be increased.

**Comment by rizwan95** [comment]
According to Apple, it is not a bug, but it is a feature. Check this link https://github.com/SwiftKickMobile/SwiftMessages/issues/471#issuecomment-879971936 for more information about the issue.

**Comment by ddaddy** [comment]
Although it's a _feature_ to not allow the availability check, I'd say it's a bug that they have an availability check in the Network framework.

**Comment by ddaddy** [comment]
My bug report suggested this might be fixed in Beta 5, but it's not 🙄

**Comment by baveku** [comment]
> My bug report suggested this might be fixed in Beta 5, but it's not 🙄

Yes, I try but it's not, Do you have any idea to fix it?

**Comment by ddaddy** [comment]
Use a minimum iOS version of 11.0, or don't use Xcode 13 beta's.

**Comment by ddaddy** [comment]
This seems to be fixed in Xcode 13 Release Candidate :)

**Comment by baveku** [comment]
> This seems to be fixed in Xcode 13 Release Candidate :)

Really? 🤣🤣🤣🤣

**Comment by rizwan95** [comment]
> This seems to be fixed in Xcode 13 Release Candidate :)

😂😂 I can't believe it!

**Comment by ddaddy** [comment]
Yeh, they did tell me it was fixed in iOS 15 beta 6, but we never got a new Xcode after beta 5 to test it.

**Comment by baveku** [comment]
> Yeh, they did tell me it was fixed in iOS 15 beta 6, but we never got a new Xcode after beta 5 to test it.

confirmed, It's solved 👍
