### ISSUE TITLE
Update release to enable full SPM support

### ISSUE THREAD

**Issue by rathishubham7** [daltoniam/Starscream#898]
### Question
To fully support SPM, please tag the release (Latest release is 3.1.1). Currently when i fetch the master branch using `.package(url: "https://github.com/daltoniam/Starscream.git", .branch("master"))`, SPM fetched version 3 and not the latest version. Am i missing something ?

### Environment:
- OS/Version: general
- Starscream Version 4.0.4 
- Xcode version - 12.5

**Comment by bwees** [comment]
I was able to get v4 by adding the .master like you have stated and then going to file>swift packages>update to latest. (I am not In from of computer right now so the wording may not be exact)

**Comment by bwees** [comment]
You can also use .upToNextMajor(from: "4.0.0") to get the latest!

**Comment by rathishubham7** [comment]
Thanks for the help.
