### ISSUE TITLE
nw_protocol_get_quic_image_block_invoke dlopen libquic failed error when trying to connect

### ISSUE THREAD

**Issue by bwees** [daltoniam/Starscream#899]
### Describe the bug

When I run socket.connect(), I get the error of: `nw_protocol_get_quic_image_block_invoke dlopen libquic failed`

### Steps to Reproduce
Create a simple project on a standalone watch app and try to connect. 

### Expected behavior
A WebSocket is supposed to connect and send a connected event.

### Environment:
- OS/Version: [watchOS 7.2]
- Starscream Version [4.0.4]
- Xcode version [12.4]

### Additional context
I have heard that this is an Xcode problem but, I cannot upgrade any further due to being on an older mac.

**Comment by acmacalister** [comment]
I'm going to assume this was an Xcode or Network.framework issue as Starscream/websockets don't really have anything to do with quic. Going to close this out and happy to reopen if it is still happening.
