### ISSUE TITLE
Cocoapod crash when try to build with swift 5.5

### ISSUE THREAD

**Issue by lexin** [daltoniam/Starscream#905]
I just installed the Xcode 13 (beta 4). 
My current swift version in the system is Apple Swift version **5.5** (swiftlang-1300.0.27.6 clang-1300.0.27.2)

I try to call pod install and observe the issue 
`Prebuilding Starscream...
> Processing Starscream-Info.plist
> Copying Starscream-umbrella.h

[x] /Users/lexin/Downloads/Xcode-beta 4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/lib/swift/Network.swiftmodule/armv7-apple-ios.swiftinterface:1254:19: 'NWConnection' is only available in iOS 12.0 or newer

extension Network.NWConnection {
`

pod file contains platform :ios, '13.0'
deployment target in the project is '13.0'

**Comment by saroar** [comment]
it still have issue with swift 5.4 Xcode 13 beta 5

**Comment by sdc-78** [comment]
This is fixed in Xcode 13 RC and final.
See #895
