### ISSUE TITLE
Send failed with error "Socket is not connected"

### ISSUE THREAD

**Issue by luopan1990911** [daltoniam/Starscream#908]
### Describe the bug
> On a real IPhone, my app exits in the background and when it enters the foreground, it displays: Send failed with error "Socket is not connected"

### Steps to Reproduce
> Send failed with error "Socket is not connected"

### Expected behavior
> 

### Environment:
- OS/Version: [e.g. iOS/13.5.1]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 11.6]

**Comment by leotu** [comment]
Face the same problem (iOS14.7.1) :
 ... [connection] nw_write_request_report [C1] Send failed with error "Socket is not connected"

**Comment by hubfresher** [comment]
same problem, any suggestions?

**Comment by RyanLengChengdu** [comment]
just do this :
override func viewDidLoad() {
        super.viewDidLoad()
        NotificationCenter.default.addObserver(self,
            selector: #selector(appWillEnterForeground),
                                               name: UIApplication.willEnterForegroundNotification,
            object: nil)
        NotificationCenter.default.addObserver(self,
            selector: #selector(didEnterBackground),
                                               name: UIApplication.didEnterBackgroundNotification,
            object: nil)
}


    @objc func appWillEnterForeground(){
        WSManager.shared.establishConnection()
    }
    @objc func didEnterBackground(){
        WSManager.shared.closeConnection()
    }

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
