### ISSUE TITLE
Support for M1 Mac

### ISSUE THREAD

**Issue by KalpeshTalkar** [daltoniam/Starscream#909]
### Describe the bug
I am building a framework using Starscream as a dependency. The framework is built successfully and I am able to use it in the demo project.
But on M1 MacBook, I get the following error when building / running on simulator.
![Starscream error on M1 Mac](https://user-images.githubusercontent.com/14951672/129078952-7365016a-8d4c-46d7-976e-116a9f4f4e9c.png)

### Steps to Reproduce
> Build a framework, use Starscream as a dependency
> Generate the framework and integrate in a demo app
> Selected simulator target and run the project using M1 mac

### Expected behavior
> The project should work for simulators on M1 Macs also

### Environment:
- MacBook: M1 Mac running macOS Big Sur 11.4
- OS/Version: iOS 14.5
- Starscream Version: 4.0.4
- Xcode version: 12.5

**Comment by ppamorim** [comment]
I have the same issue, I will try to sort this out in a fork.

**Comment by gridNA** [comment]
same issue here, any news?

**Comment by tyiu** [comment]
Same issue on M2 Mac. Has anyone figured out a fix?

**Comment by nikitaame** [comment]
Any luck here?

**Comment by acmacalister** [comment]
4.0.5 release should build on m1/m2 now
