### ISSUE TITLE
 Project "Starscream.xcodeproj" has no shared schemes

### ISSUE THREAD

**Issue by siyangYao** [daltoniam/Starscream#91]
Project "Starscream.xcodeproj" has no shared schemes

I am using carthage update. but it shows this problem

**Comment by daltoniam** [comment]
I don't personally use Carthage and I am not sure why you are seeing that, but #40 added support. Looking at the schemes in xCode they are set to be shared:

![screen shot 2015-06-03 at 2 19 05 pm](https://cloud.githubusercontent.com/assets/905059/7971730/c8bf57c0-09fb-11e5-8c28-6b07d691cee4.png)

**Comment by ricardopereira** [comment]
@siyangYao Can you share the build log?

**Comment by siyangYao** [comment]
@ricardopereira I delete the carthage folder and re carthage update. The problem is solved. I do not know why there is that problem.
