### ISSUE TITLE
Replace SHA1 usages with SHA512

### ISSUE THREAD

**Issue by 1oo7** [daltoniam/Starscream#913]
### What do you want to happen?

Replace SHA1 usage with a more secure algorithm.

### What happens now?

https://github.com/daltoniam/Starscream/blob/df8d82047f6654d8e4b655d1b1525c64e1059d21/Sources/Security/FoundationSecurity.swift#L92-L99

SHA1 is insecure. Use something better.

### Demo Code
> Any demo code that may used to implement/use the desired feature. 

### Describe alternatives you've considered

I would recommend CC_SHA512

### Additional context

China, Russia, N. Korea, Iran...

**Comment by acmacalister** [comment]
https://datatracker.ietf.org/doc/html/rfc6455#section-10.8

RFC sets it as a SHA1
