### ISSUE TITLE
Highly battery usage?

### ISSUE THREAD

**Issue by JayachandraA** [daltoniam/Starscream#922]
### Question
> Why there is highly battery usage when working with this library? When I compare to other working threads , socket thread is highly consuming power and cpu usage. So, how can we handle this ?

### Environment:
- OS/Version: 12.4
- Starscream Version 4.0.4
- Xcode version 11.5

**Comment by hubfresher** [comment]
oooh，any idea?

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
