### ISSUE TITLE
Built Failed in Xcode13 beta5 with iOS 15 SDK

### ISSUE THREAD

**Issue by LiuJinzhu** [daltoniam/Starscream#924]
### Question
I met this error when I built this project with iOS15 SDK
"Failed to build module 'Network'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.29.1 clang-1300.0.28.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)'). Please select a toolchain which matches the SDK."

How can I resolve it ?
### Environment:
- OS/Version: [e.g. iOS/15]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 13.0-beta5]

**Comment by sdc-78** [comment]
This is fixed in Xcode 13 RC and final.
See #895
