### ISSUE TITLE
detect which socket ( with multi sockets)

### ISSUE THREAD

**Issue by fukemy** [daltoniam/Starscream#927]
### Question
> i have 2 socket that run in one class, this trigger same delegate, i want to detect what socket to implement each function. But i can not check if socket is firstSocket/secondSocket. like image below

![Ảnh chụp Màn hình 2021-10-11 lúc 01 33 39](https://user-images.githubusercontent.com/8202437/136708862-4edd5fff-c88c-452e-8241-49b4c02d9b9c.png)

here is the code to register socket:
```

    private let socket: WebSocket
    private var audioSocket: WebSocket?

init(url: URL) {
        var request = URLRequest(url: url)
        let protocols = ["janus-protocol"]
        request.setValue(protocols.joined(separator: ","), forHTTPHeaderField: "Sec-WebSocket-Protocol")
        socket = WebSocket(request: request)
        socket.delegate = self
        audioSocket = WebSocket(request: request)
        audioSocket?.delegate = self
    }
```

### Environment:
- OS/Version:15
- Starscream Version lasted
- Xcode version lasted

**Comment by mmdock** [comment]
Can't you just subclass the WebSocket type, add a convenience initialize that takes in a string and stores it (like MyWebSocket(label: "some generated identifier")) and then in the delegate cast back to your subclass and then get that identifier?
