### ISSUE TITLE
[WIP] Swift 2.0

### ISSUE THREAD

**Issue by ricardopereira** [daltoniam/Starscream#93]

**Comment by daltoniam** [comment]
#95

**Comment by vyshane** [comment]
@daltoniam could you make a CocoaPods release for Swift 2.0 compatibility?

**Comment by ricardopereira** [comment]
@vyshane You can do `pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'Swift-2.0'`

**Comment by vyshane** [comment]
@ricardopereira Ah, sweet! TIL.

**Comment by daltoniam** [comment]
@ricardopereira thank you much. @vyshane I most certainly will once Swift 2.0 goes full release. In the mean time @ricardopereira is the right approach until then.
