### ISSUE TITLE
Do you have plan to create a new tag?

### ISSUE THREAD

**Issue by buptwsg** [daltoniam/Starscream#931]
### Question
> A description of what you want to know.
Last tag 4.0.4 was created more than one year ago, there are many commits and pull requests after that. Do you have plan to create a new tag so that we can use latest code?

### Environment:
- OS/Version: [e.g. iOS/13.3]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 11.5]

**Comment by acmacalister** [comment]
Yes, 4.0.5 was released.
