### ISSUE TITLE
Security issue: use of a dangerous C functions

### ISSUE THREAD

**Issue by HenSafeUP** [daltoniam/Starscream#947]
Bug description:
Hello there, while testing the security of our iOS app, the Red Team observed that the iOS Starscream framework used a potentially dangerous function that could introduce a vulnerability if it is used incorrectly. Functions such as _memcpy and _strncpy were used, these could potentially lead to certain types of vulnerabilities.
https://scriptingxss.gitbook.io/embedded-appsec-best-practices/1_buffer_and_stack_overflow_protection

We’ll be happy if you could review this treats if possible,
Thanks 🙏

Environment:
- Starscream Latest iOS version
- Xcode

**Comment by acmacalister** [comment]
Starscream doesn't use any C calls like memcpy or strncpy directly. Those are implementation details from the higher CoreFoundation APIs that Starscream uses. If you feel there is a security issue with those, I would suggest reporting them to the Apple Radar/bug tracker so the Foundation team can review and patch it.
