### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ameter** [daltoniam/Starscream#951]
### What do you want to happen?

Any chance you could cut a release?  There have been a number of PRs merged to main that would be nice to make available via CocoaPods.  In particular, the recently merged PR to change the deprecated use of the `class` keyword to define a class-constrained protocols to `AnyObject` would clean up a lot of warnings in everyone's builds.

Thanks!

**Comment by acmacalister** [comment]
New release went out today. 4.0.5
