### ISSUE TITLE
memory leaks in Instruments in Starscream 4.0.4

### ISSUE THREAD

**Issue by lawmicha** [daltoniam/Starscream#954]
### Describe the bug
Hello, we received an issue in https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/90 regarding a memory leak. The referencing issue is a package that uses Starscream 4.0.4. The customer describes a memory leak when running Instruments. 

```
>    9 Starscream TCPTransport.connect(url:timeout:certificatePinning:) ../ios/Pods/Starscream/Sources/Transport/TCPTransport.swift:80
  10 Starscream protocol witness for Transport.connect(url:timeout:certificatePinning:) in conformance TCPTransport ../ios/Pods/<compiler-generated>:0
  11 Starscream WSEngine.start(request:) ../ios/Pods/Starscream/Sources/Engine/WSEngine.swift:67
  12 Starscream protocol witness for Engine.start(request:) in conformance WSEngine ../ios/Pods/<compiler-generated>:0
  13 Starscream WebSocket.connect() ../ios/Pods/Starscream/Sources/Starscream/WebSocket.swift:135
  14 AppSyncRealTimeClient closure #1 in StarscreamAdapter.connect(url:protocols:delegate:) ../ios/Pods/AppSyncRealTimeClient/AppSyncRealTimeClient/Websocket/Starscream/StarscreamAdapter.swift:47
  15 AppSyncRealTimeClient thunk for @escaping @callee_guaranteed () -> () ../ios/Pods/<compiler-generated>:0
```

I wanted to open this issue for your awareness as we gather more information. From a glance at the information provided, it looks like the problem is in **TCPTransport.swift:80**

### Steps to Reproduce
Will provide once we have more details from referencing issue (https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/90) or more information when we reproduce it ourselves.

### Expected behavior
No memory leaks

### Environment:
- OS/Version: [e.g. iOS/13.3]
- Starscream Version [e.g. 4.0.4]: 4.0.4
- Xcode version [e.g. 11.5]

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
