### ISSUE TITLE
Why is the framework named 'Starscream'? 

### ISSUE THREAD

**Issue by paulcanyon** [daltoniam/Starscream#956]
### Question
Why is it based on the decepticon, Starscream, from the Transformers comics / movies? 

### Environment:
- OS/Version: [e.g. iOS/13.3]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 11.5]

**Comment by acmacalister** [comment]
Because life is too short for lame library. Thought it was fun theme for the iOS libraries we created.
