### ISSUE TITLE
What's mean `Optional(-9808: Optional(错误的证书格式))` or `Optional(-9858: Optional(握手失败))`

### ISSUE THREAD

**Issue by Charlotte3240** [daltoniam/Starscream#958]
### Question
> A description of what you want to know.
Sometimes wss connect error , code same title .
-9808
-9858

The server certificate has not expired，it's work.
I feel confused. 
not always wrong.
retry is ok , but what' happen on ios ?

### Environment:
- OS/Version: Any possible
- Starscream Version 4.0.4
- Xcode version xc 13.4.1

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
