### ISSUE TITLE
xcframework won't build

### ISSUE THREAD

**Issue by johndpope** [daltoniam/Starscream#959]
### Describe the bug
> A clear and concise description of what the bug is.
creating xcframework fails
debug: evaluating manifest for 'supabase-swift' v. unknown
Error: Xcode project generation is not supported by Swift Package Manager for packages that reference system modules.These system modules were referenced: swift-nio-zlib-support

### Steps to Reproduce
```


brew install mint
mint install unsignedapps/swift-create-xcframework
swift create-xcframework --platform ios
```

### Expected behavior
create xcframework

### Environment:
ios / mac /xcode 13.4

### Additional context
> Add any other context about the problem here.
this PR fixes problem
https://github.com/daltoniam/Starscream/pull/844

**Comment by acmacalister** [comment]
Let's track this in #844.
