### ISSUE TITLE
websocket disconnect

### ISSUE THREAD

**Issue by siyangYao** [daltoniam/Starscream#96]
if websocket is disconnect with server, is the method "websocketDidDisconnect" called all the time or just call once?

**Comment by acmacalister** [comment]
That is a delegate method and is called when the WebSocket is disconnected. It is called whenever the client gets disconnected. It is only called on disconnect, so unless your connection to the WebSocket keeps dropping off, it would not generally called that often.

**Comment by daltoniam** [comment]
To co sign @acmacalister note, `websocketDidDisconnect ` wouldn't get called expect in the case of disconnections, but it can be called more than once for the same disconnect depending how the stream was disconnected (if it was wasn't a gracefully disconnection, etc). #81 has more info on this.

**Comment by siyangYao** [comment]
@acmacalister  @daltoniam  :+1:
