### ISSUE TITLE
masked and rsv data is not currently supported and Starscream.HTTPUpgradeError aws

### ISSUE THREAD

**Issue by SiddharthChopra** [daltoniam/Starscream#965]
Hi all, 

### Describe the bug
I was debugging while connecting to AWSConnect while doing that I'm getting this error on websocket.connect() and the error persists.

this is the log:
viabilityChanged
error Optional(Starscream.HTTPUpgradeError.notAnUpgrade(503))
error Optional(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002))

Referred this article for connection:
https://aws.amazon.com/blogs/contact-center/create-a-mobile-chat-solution-with-the-amazon-connect-mobile-sdk/

Tried this library also
https://github.com/jayesh15111988/SwiftWebSocket/tree/master

### Environment:
- OS/Version: [iOS/15.4]
- Starscream Version [4.0.4]
- Xcode version [13.3]

So, How to connect with this aws socket url in my ViewController. Any help will be appreciated.

**Comment by rromanchuk** [comment]
@SiddharthChopra can confirm i'm getting same error, but different context (kinesis video webrct).  Pinning to `3.0.0` works, but have no insights where the regression happened.

**Comment by SiddharthChopra** [comment]
@rromanchuk same error getting for 3.0.0 version refer below snap for more detail
<img width="844" alt="Screenshot 2022-11-07 at 3 56 49 PM" src="https://user-images.githubusercontent.com/8319595/200287704-1ba1fe0f-7b5a-4aaa-8639-f0264b057ab6.png">
also

**Comment by iOSUser25** [comment]
@SiddharthChopra  Hi, do you get any solution for this?
 I'm getting sort of same error - (Starscream.HTTPUpgradeError.notAnUpgrade(403)), so not able to connect with WebSocket.


Any help will be appreciated. Thank you.

**Comment by DioGnDev** [comment]
try to change ws:// to wss:// hope can help

**Comment by Fonta1n3** [comment]
Also getting the same issue. Seems to not be http v1.1 compatible...

**Comment by aijaz90** [comment]
please add this to your request and it will work fine :)
set "wamp" in header
 ```
ar request = URLRequest(url: URL(string: URL)!)

        request.setValue(["wamp"].joined(separator: ","), forHTTPHeaderField: "Sec-WebSocket-Protocol")
        socket = WebSocket(request: request)
      
        socket.delegate = self
        socket.connect()
```

**Comment by aijaz90** [comment]
ar request = URLRequest(url: URL(string: URL)!)

      ```
 request.setValue(["wamp"].joined(separator: ","), forHTTPHeaderField: "Sec-WebSocket-Protocol")
       socket = WebSocket(request: request)
     
       socket.delegate = self
       socket.connect()
```

**Comment by pablogeek** [comment]
that header didn't fix the issue. Does anyone has another idea?

**Comment by vanniktech** [comment]
@pablogeek have you found a solution for this?

**Comment by kuzomenskyi** [comment]
Not sure how it's completed, because this issue still persists in version 4.0.8
