### ISSUE TITLE
(Starscream.HTTPUpgradeError.notAnUpgrade(403))

### ISSUE THREAD

**Issue by iOSUser25** [daltoniam/Starscream#966]
Hi, 
   I am using WebRTC for video calling  and starscream for web socket connection. 
Websocket connection fails, issue is :
(Starscream.HTTPUpgradeError.notAnUpgrade(403))
and 
error Optional(POSIXErrorCode(rawValue: 54): Connection reset by peer)

### Environment:
- OS/Version: [e.g. iOS/15.6]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 14.0.1]

Earlier it was working fine. 
  If anyone facing same issue and have some solution for the same then please post it here. Thank you in advance!

**Comment by iOSUser25** [comment]
Hi, 
   Does anyone facing same issue? 
With the same WebSocket url if I use Native engine WebSocket connection, authorization is working fine and then it is getting disconnected automatically. Error is: Error Domain=kNWErrorDomainPOSIX Code=57 "Socket is not connected"

If I use WSEngine then WebSocket connection is always failed,  getting (Starscream.HTTPUpgradeError.notAnUpgrade(403)) error. 

I want to use WSEngine flow only, if anyone is facing same issue and resolved it, kindly update here. 

Any help will be appreciated. Thank you.

**Comment by iOSUser25** [comment]
Hi,
    I resolved this issue by commenting header "origin" only.

Thank you.

**Comment by LaoWangInNear** [comment]
hi,
how to resolve this issue, I can not understand, please Post your code
thank you
