### ISSUE TITLE
Starscream FoundationTransportError error 0

### ISSUE THREAD

**Issue by fahadjamal** [daltoniam/Starscream#967]
### Describe the bug
> Foundation Transport Error occur when i want to connect to the socket server for the Video Call. I have used the SSL Pining but still got the same error. I have provided the proper Session ID and the Server URL, but still did not got any Luck.

### Environment:
- OS/Version iOS/15.5
- Starscream Version 4.0.4
- Xcode version 13.4.1

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
