### ISSUE TITLE
No error delegate function when server sends empty data

### ISSUE THREAD

**Issue by saravanan6137** [daltoniam/Starscream#969]
open func stream(_ aStream: Stream, handle eventCode: Stream.Event) {
        if eventCode == .hasBytesAvailable {
            if aStream == inputStream {
                delegate?.newBytesInStream()
            }
        } else if eventCode == .errorOccurred {
            delegate?.streamDidError(error: aStream.streamError)
        } else if eventCode == .endEncountered {
            delegate?.streamDidError(error: nil)
        }
    }
}

The status remains at .isSpaceNeeded and not changing to hasBytesAvailable

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
