### ISSUE TITLE
Source code errors

### ISSUE THREAD

**Issue by vegancow** [daltoniam/Starscream#97]
I just installed Starscream with cocoapods and there are a lot of errors in the source files which makes Xcode complain a lot. Errors such as "can't invoke init with....", "expected ',' separator" and so on. Am I building it wrong or did someone goof something up?

Here's a paste with all the errors
http://pastebin.com/Gn2L56x3

**Comment by vegancow** [comment]
Edited the source code and got it to build at least, no clue if it will run as intended.

http://pastebin.com/Qm5q2aQp

**Comment by nuclearace** [comment]
What version of Xcode are you on? These sound like Swift version errors.

**Comment by vegancow** [comment]
Xcode 6.1.1

**Comment by daltoniam** [comment]
@nuclearace thanks for narrowing this down. xCode 6.3 is when swift 1.2 was released, which the last few releases of Starscream are targeted for. I would recommend installing the latest version xCode which should resolve the issue.
