### ISSUE TITLE
DoRead endless cycle

### ISSUE THREAD

**Issue by liangdahong** [daltoniam/Starscream#970]
- https://github.com/daltoniam/Starscream/commit/fedd77ba8e85ce0c73a5631917af6b3872e85578
This fix did not tag  4.0.4 😂，Is anyone using it ?

**Comment by RalfK92** [comment]
Yes we just encountered this bug today in an application.

**Comment by acmacalister** [comment]
Any steps to reproduce, sample projects, etc would be appreciated.
