### ISSUE TITLE
Does this framework maintainable in 2023?

### ISSUE THREAD

**Issue by alexanderkhitev** [daltoniam/Starscream#972]
Hello guys!

### Question
Does this framework maintainable in 2023?

**Comment by acmacalister** [comment]
Howdy. Yes, we are still maintaining it. Took a break for a while from the burnout, but starting back up.

**Comment by alexanderkhitev** [comment]
> Howdy. Yes, we are still maintaining it. Took a break for a while from the burnout, but starting back up.

Great news!
