### ISSUE TITLE
After update to 4.0.6 compile error WebSocketDelegate

### ISSUE THREAD

**Issue by AVDyadkovich** [daltoniam/Starscream#975]
### Describe the bug
After update from 4.0.4 to 4.0.6 using SPM, receive build time error that my class does not conform to protocol 'WebSocketDelegate'
however i conform to that protocol adding method to class in extension.  
What I got in extension: 
func didReceive(event: WebSocketEvent, client: WebSocket) {

What Xcode offer to add stubs: 
 func didReceive(event: Starscream.WebSocketEvent, client: Starscream.WebSocketClient) {

### Steps to Reproduce
Update Starscream from 4.0.4 to 4.0.6 from SPM, build and run.

### Expected behavior
No errors on build time when using func didReceive(event: WebSocketEvent, client: WebSocket) 

### Environment:
- OS/Version: iOS 16
- Starscream Version 4.0.6
- Xcode version 14.3.1 (14E300c)

### Additional context
I have returned to version 4.0.4 and there is no any troubles on it.

**Comment by acmacalister** [comment]
We probably should have bumped for a minor patch for the semv version, but the delegate changed with the addition of `peerClosed` to the protocol. This should be easily resolved by adding:

```swift
case .peerClosed:
        break
```

as seen in the README.

**Comment by AVDyadkovich** [comment]
Well, we have a default in switch, so this case, and any new one, should be worked out with default.

**Comment by AVDyadkovich** [comment]
just noticed, that you changed the signature from client: WebSocket to client: WebSocketClient
Sory for bothering you)
