### ISSUE TITLE
Embedding a Starscream dependent .xcframework into my own .xcframework with Cocoapod

### ISSUE THREAD

**Issue by invisibleBully** [daltoniam/Starscream#978]
### Question
> I am implementing a custom .xcframework "C". Within my custom framework, there's another .xcframework within which is "Starscream". I have specified the dependencies within my .podspec as well as the vendor frameworks. Now anytime I try to push to trunk, I get an error about Starscream having a deployment target set to 8 [I have tried to bump the target within the pods - didn't work]. Attached image.

How can I go about this  

### Environment:
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 14.3]
<img width="1571" alt="Screenshot 2023-08-29 at 5 32 47 PM" src="https://github.com/daltoniam/Starscream/assets/12860615/64f7732b-268a-4022-8637-478bc8a059b3">

**Comment by bertoraffo** [comment]
Hi, do you solve the issue?
