### ISSUE TITLE
Memory leak of stream objects

### ISSUE THREAD

**Issue by lyricsboy** [daltoniam/Starscream#98]
The socket stream pair is created in `WebSocket#initStreamsWithData` using `CFStreamCreatePairWithSocketToHost`, which sets the stream arguments to objects following the "create rule" (i.e. retained values).

The code subsequently calls `takeUnretainedValue()` on them which creates an unbalanced retain (memory leak).

Calling `takeRetainedValue()` instead is the correct approach. You can verify the leak (and the fix) using the Allocations Instrument to track allocations matching "stream" and explicitly disconnecting the socket.

**Comment by daltoniam** [comment]
Ah, very true. Totally forgot to change those, thank you for pointing that out. I will update that shortly.

**Comment by daltoniam** [comment]
Resolved in master. I will create a new tag and release shortly. Thanks again!

**Comment by daltoniam** [comment]
Tag `0.9.4` has been released with the fix.
