### ISSUE TITLE
Xcode 15 Trigger memory crash  Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by ChocolatesChen** [daltoniam/Starscream#980]
### Describe the bug
> A clear and concise description of what the bug is.
Crash caused by websocket initialization in Xcode 15
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### Steps to Reproduce
> Detailed steps to reproduce the problematic behavior:
webSocket = WebSocket(request: request)
webSocket?.delegate = self
webSocket?.connect()
Detailed point to file TCPTransport.swift line 58
Let options=NWProtocolTCP. Options()

### Expected behavior
> A clear and concise description of what you expected to happen.
Will not crash

### Environment:
- OS/Version: [e.g. iOS/15.7]
- Starscream Version [e.g. 4.0.4]
- Xcode version [e.g. 15]

### Additional context
> Add any other context about the problem here.

**Comment by hibernat** [comment]
I have the same issue.
`let options = NWProtocolTCP.Options()` in TCPTransport.swift causes crash

**Comment by yongshideweiyi** [comment]
I have the same problem, does anyone know how to solve it, thank you

Xcode Version 15.0 (15A240d)
iOS Version：[16.6.1]
Starscream Version [4.0.4]

**Comment by BestKai** [comment]
same problem
Xcode Version 15.0 (15A240d)
iOS Version：[15.7.5]
Starscream Version [4.0.4]

**Comment by vitkuzmenko** [comment]
Same problem
Xcode Version 15.0 (15A240d)
iOS Version：[12], [14].
Starscream Version [4.0.4]

iOS 17 works.

**Comment by Dygon89** [comment]
Same problem
Xcode Version 15.0 (15A240d)
iOS Version：[16.6.1].
Starscream Version [4.0.4], [4.0.6]

**Comment by Bylynka** [comment]
Same problem
Xcode Version 15.0 (15A240d)
iOS Version：[15.7.9]
Starscream Version [4.0.6]

**Comment by Bylynka** [comment]
> Same problem Xcode Version 15.0 (15A240d) iOS Version：[16.6.1]. Starscream Version [4.0.4], [4.0.6]
> 
> EDIT: Fix
> 
> I have fixed this issue by raising my minimum deployment target across the project from iOS 11.0 -> iOS 12.0 (only tested on device, not simulators)


It doesn't help for OS Version：[15.7.9]

**Comment by Gavin123** [comment]
I have the same issue.
let options = NWProtocolTCP.Options() in TCPTransport.swift causes crash
iOS Version: [iOS 16.4]
Starscream Version [4.0.4]
Xcode version [15.0 RC]

We have a large number of online users experiencing crashes and urgently need to resolve this issue

**Comment by GitHubZebra** [comment]
I have the same issue.
let options = NWProtocolTCP.Options() in TCPTransport.swift causes crash
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
iOS Version: [iOS 16.4]
Starscream Version [4.0.4]
Xcode version [15]

iOS 17 works, nothing else

**Comment by GitHubZebra** [comment]
> ### Describe the bug
> > A clear and concise description of what the bug is.
> > Crash caused by websocket initialization in Xcode 15
> > Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
> 
> ### Steps to Reproduce
> > Detailed steps to reproduce the problematic behavior:
> > webSocket = WebSocket(request: request)
> > webSocket?.delegate = self
> > webSocket?.connect()
> > Detailed point to file TCPTransport.swift line 58
> > Let options=NWProtocolTCP. Options()
> 
> ### Expected behavior
> > A clear and concise description of what you expected to happen.
> > Will not crash
> 
> ### Environment:
> * OS/Version: [e.g. iOS/15.7]
> * Starscream Version [e.g. 4.0.4]
> * Xcode version [e.g. 15]
> 
> ### Additional context
> > Add any other context about the problem here.

Excuse me, have you solved it

**Comment by killerdarkios** [comment]
I have the same issue.
When I run the app with xcode 15.0  and iOS(16.0.2),it crashes at  "let options = NWProtocolTCP.Options() " in TCPTransport.swift
When I run the app with xcode 14.2  and iOS(16.0.2) or iOS(17.0), it doesn't crash.
Maybe the xcode15.0 cause the crash?

**Comment by ChocolatesChen** [comment]
> > ### 描述错误
> > > 对错误内容的清晰简洁的描述。
> > > Xcode 15 线程 1 中 websocket 初始化导致的崩溃
> > > ：EXC_BAD_ACCESS（code=1，address=0x0）
> > 
> > 
> > ### 重现步骤
> > > 重现问题行为的详细步骤：
> > > webSocket = WebSocket(request: request) 
> > > webSocket?.delegate = self 
> > > webSocket?.connect()
> > > 详细指向文件 TCPTransport.swift 第 58 行
> > > Let options=NWProtocolTCP。选项（）
> > 
> > 
> > ### 预期行为
> > > 对您期望发生的情况的清晰简洁的描述。
> > > 不会崩溃
> > 
> > 
> > ### 环境：
> > 
> > * 操作系统/版本：[例如iOS/15.7]
> > * 红蜘蛛版本[例如4.0.4]
> > * Xcode 版本 [例如 15]
> > 
> > ### 额外的背景信息
> > > 在此处添加有关该问题的任何其他上下文。
> 
> 请问你解决了吗

Not yet. It will be packaged and launched through xcode 14. It needs to be fixed in xcode 15.

> > ### Describe the bug
> > > A clear and concise description of what the bug is.
> > > Crash caused by websocket initialization in Xcode 15
> > > Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
> > 
> > 
> > ### Steps to Reproduce
> > > Detailed steps to reproduce the problematic behavior:
> > > webSocket = WebSocket(request: request)
> > > webSocket?.delegate = self
> > > webSocket?.connect()
> > > Detailed point to file TCPTransport.swift line 58
> > > Let options=NWProtocolTCP. Options()
> > 
> > 
> > ### Expected behavior
> > > A clear and concise description of what you expected to happen.
> > > Will not crash
> > 
> > 
> > ### Environment:
> > 
> > * OS/Version: [e.g. iOS/15.7]
> > * Starscream Version [e.g. 4.0.4]
> > * Xcode version [e.g. 15]
> > 
> > ### Additional context
> > > Add any other context about the problem here.
> 
> Excuse me, have you solved it

Not yet. It will be packaged and launched through xcode 14. It needs to be fixed in xcode 15.

**Comment by zebraciam** [comment]
> I have the same issue. let options = NWProtocolTCP.Options() in TCPTransport.swift causes crash Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) iOS Version: [iOS 16.4] Starscream Version [4.0.4] Xcode version [15]
> 
> iOS 17 works, nothing else

The solution
Podfile:  
 post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    puts "#{target.name}"
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

**Comment by ChocolatesChen** [comment]
> > I have the same issue. let options = NWProtocolTCP.Options() in TCPTransport.swift causes crash Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) iOS Version: [iOS 16.4] Starscream Version [4.0.4] Xcode version [15]
> > iOS 17 works, nothing else
> 
> The solution Podfile: post_install do |installer_representation| installer_representation.pods_project.targets.each do |target| puts "#{target.name}" target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0' end end end

Yes, thank you for your help, it has been adopted. It turns out that Xcode 15 limits the minimum version of the sdk. Add IPHONEOS_DEPLOYMENT_TARGET to the podfile and set it to 12 or above and then pod install can solve the problem. Of course, the minimum os version of the project will also be 12.

**Comment by ChocolatesChen** [comment]
> I have the same issue. When I run the app with xcode 15.0 and iOS(16.0.2),it crashes at "let options = NWProtocolTCP.Options() " in TCPTransport.swift �When I run the app with xcode 14.2 and iOS(16.0.2) or iOS(17.0), it doesn't crash. Maybe the xcode15.0 cause the crash?

Maybe Xcode 15 limits the minimum version of the sdk. Add IPHONEOS_DEPLOYMENT_TARGET to the podfile and set it to 12 or above and then pod install. Of course, the minimum os version of the project will also be 12.
