### ISSUE TITLE
xcode version 15.0 (15A240d) crashes on phones younger than iOS17

### ISSUE THREAD

**Issue by ShaoAsher** [daltoniam/Starscream#983]
### Describe the bug

clash：
>let options = NWProtocolTCP.Options() 

Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by GoodbyeFox** [comment]
same issue

**Comment by ksv57rus** [comment]
I changed the deployment target version to iOS 13 (remove IPHONEOS_DEPLOYMENT_TARGET) and it's resolve the issue
<img width="809" alt="Снимок экрана 2023-10-04 в 08 46 30" src="https://github.com/daltoniam/Starscream/assets/637815/b3bb390a-8cb3-4e6f-8101-21a59170e2f1">

**Comment by adamsousa** [comment]
Make sure you're on version 4.0.6. That version increments the iOS target version from 9 to 12. 

NWProtocolTCP.Options requires iOS 12+ as a target when compiling in Xcode15

**Comment by ksv57rus** [comment]
> Make sure you're on version 4.0.6. That version increments the iOS target version from 9 to 12.
> 
> NWProtocolTCP.Options requires iOS 12+ as a target when compiling in Xcode15

podspec https://github.com/CocoaPods/Specs/blob/master/Specs/2/2/f/Starscream/4.0.6/Starscream.podspec.json

<img width="657" alt="Снимок экрана 2023-10-05 в 08 27 50" src="https://github.com/daltoniam/Starscream/assets/637815/5d90afbe-9201-4703-8980-6b75ad5f936a">

**Comment by no5ugar** [comment]
> > Make sure you're on version 4.0.6. That version increments the iOS target version from 9 to 12.
> > NWProtocolTCP.Options requires iOS 12+ as a target when compiling in Xcode15
> 
> podspec https://github.com/CocoaPods/Specs/blob/master/Specs/2/2/f/Starscream/4.0.6/Starscream.podspec.json
> 
> <img alt="Снимок экрана 2023-10-05 в 08 27 50" width="657" src="https://user-images.githubusercontent.com/637815/272789344-5d90afbe-9201-4703-8980-6b75ad5f936a.png">

still crash on version 4.0.6

ios version: 15.7.2
xcode version: 15.0

> let options = NWProtocolTCP.Options()

EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by Firstmsdong** [comment]
让选项 = NWProtocolTCP.Options()

线程 1：EXC_BAD_ACCESS（代码=1，地址=0x0）

这个问题怎么弄，项目现在已运行就闪退

**Comment by Firstmsdong** [comment]
> ### 描述错误
> 冲突：
> 
> > 让选项 = NWProtocolTCP.Options()
> 
> 线程 1：EXC_BAD_ACCESS（代码=1，地址=0x0）

解决了吗？求方案

**Comment by fousa** [comment]
We are using SPM, but it appears to be the same issue. Minimum deployment target is set to iOS 13.

**Comment by Charlotte3240** [comment]
I try fix it 



## first
```swift
    public convenience init(request: URLRequest, certPinner: CertificatePinning? = FoundationSecurity(), compressionHandler: CompressionHandler? = nil, useCustomEngine: Bool = true) {
        if #available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *), !useCustomEngine {
            self.init(request: request, engine: NativeEngine())
        } 
// don't use network transport engine
//        else if #available(macOS 10.14, iOS 12.0, watchOS 5.0, tvOS 12.0, *) {
//            self.init(request: request, engine: WSEngine(transport: TCPTransport(), certPinner: certPinner, compressionHandler: compressionHandler))
//        } 
        else {
            self.init(request: request, engine: WSEngine(transport: FoundationTransport(), certPinner: certPinner, compressionHandler: compressionHandler))
        }
    }
```


## last

```swift
// initial socket object with useCustomEngine: false
self.socket = WebSocket(request: request,useCustomEngine: false)
```

**Comment by song1404574145** [comment]
> 我将部署目标版本更改为 iOS 13（删除IPHONEOS_DEPLOYMENT_TARGET），它解决了这个问题 <img alt="Снимок экрана 2023-10-04 в 08 46 30" width="809" src="https://private-user-images.githubusercontent.com/637815/272474186-b3bb390a-8cb3-4e6f-8101-21a59170e2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzE0NDAsIm5iZiI6MTcwMTgzMTE0MCwicGF0aCI6Ii82Mzc4MTUvMjcyNDc0MTg2LWIzYmIzOTBhLThjYjMtNGU2Zi04MTAxLTIxYTU5MTcwZTJmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGMzZTk1OTk4ZmQyNWJjZjA4Y2FiMDU3NjY5MmI5Nzg2OWFkMDdjMzBhNDk0YTdlNTc3N2U1Nzc5OTA1YmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UXP43-gft984Fpz6dCWVGEpaDdzq-igvabZYrMYPniU"> <img alt="Снимок экрана 2023-10-04 в 09 04 30" width="689" src="https://private-user-images.githubusercontent.com/637815/272476891-ff6d2131-9271-4812-b44b-d10fa77c3403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzE0NDAsIm5iZiI6MTcwMTgzMTE0MCwicGF0aCI6Ii82Mzc4MTUvMjcyNDc2ODkxLWZmNmQyMTMxLTkyNzEtNDgxMi1iNDRiLWQxMGZhNzdjMzQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmVjYmM5OTM0MTQyZTNkZTFjNmNlMDcyMTE4Y2Q1YjM1NmNiODdiNDEzNDBiZjM0MjY2NmZkMGI3ZjBjZTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HVkU1b2jKhqAtdZeDZHhaSIX4Pxn2Qz-G8gGFrD1gO0">

But every time I re-use 'pod install', it goes back to the way it used to be.😂

**Comment by Charlotte3240** [comment]
> > 我将部署目标版本更改为 iOS 13（删除IPHONEOS_DEPLOYMENT_TARGET），它解决了这个问题 <img alt="Снимок экрана 2023-10-04 в 08 46 30" width="809" src="https://private-user-images.githubusercontent.com/637815/272474186-b3bb390a-8cb3-4e6f-8101-21a59170e2f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzE0NDAsIm5iZiI6MTcwMTgzMTE0MCwicGF0aCI6Ii82Mzc4MTUvMjcyNDc0MTg2LWIzYmIzOTBhLThjYjMtNGU2Zi04MTAxLTIxYTU5MTcwZTJmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGMzZTk1OTk4ZmQyNWJjZjA4Y2FiMDU3NjY5MmI5Nzg2OWFkMDdjMzBhNDk0YTdlNTc3N2U1Nzc5OTA1YmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UXP43-gft984Fpz6dCWVGEpaDdzq-igvabZYrMYPniU"> <img alt="Снимок экрана 2023-10-04 в 09 04 30" width="689" src="https://private-user-images.githubusercontent.com/637815/272476891-ff6d2131-9271-4812-b44b-d10fa77c3403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzE0NDAsIm5iZiI6MTcwMTgzMTE0MCwicGF0aCI6Ii82Mzc4MTUvMjcyNDc2ODkxLWZmNmQyMTMxLTkyNzEtNDgxMi1iNDRiLWQxMGZhNzdjMzQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjUyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmVjYmM5OTM0MTQyZTNkZTFjNmNlMDcyMTE4Y2Q1YjM1NmNiODdiNDEzNDBiZjM0MjY2NmZkMGI3ZjBjZTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HVkU1b2jKhqAtdZeDZHhaSIX4Pxn2Qz-G8gGFrD1gO0">
> 
> But every time I re-use 'pod install', it goes back to the way it used to be.😂

there pics not display , the link is private

if you change code in pods , you can get origin code when  you `pod install`.

because `pod install` will pull origin code , not you changed code
