### ISSUE TITLE
Calling `disconnect()` can trigger the `didDisconnect` callback multiple times

### ISSUE THREAD

**Issue by lyricsboy** [daltoniam/Starscream#99]
If you explicitly call `disconnect()` on `WebSocket`, you will receive 2-3 callbacks to the `didDisconnect` delegate method, each with different values for the `error` argument, depending on how soon you call it and what pending writes/reads may be in the queue.

I would expect only one call to `didDisconnect` for each attempt to `connect()`.

**Comment by daltoniam** [comment]
Agreed. A few people have reported this, but I think I have a plan to fix it this time :smile:. I am going to address it with the #98 check in here shortly.

**Comment by daltoniam** [comment]
Latest code in master should resolve this. Let me know if you see any discrepancies.

**Comment by daltoniam** [comment]
Tag `0.9.4` has been released with the fix.
